DAFoam: DAJacConDummy Class Reference
DAJacConDummy Class Reference
Public Member Functions
TypeName ("dummy")
DAJacConDummy (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAJacConDummy ()
virtual void initializeJacCon (const dictionary &options)
initialize the state Jacobian connectivity matrix
virtual void setupJacCon (const dictionary &options)
assign 1 to all non-zero elements for the Jacobian connecitivyt matrix
virtual void clear ()
clear members in parent and child objects
Public Member Functions inherited from DAJacCon
TypeName ("DAJacCon")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAJacCon, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAJacCon (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAJacCon ()
virtual void setupJacConPreallocation (const dictionary &options)
calculate the preallocation vector for initializing the JacCon mat, if necessary
label getNJacConColors () const
get the number of JacCon colors
virtual void preallocatedRdW (Mat dRMat, const label transposed) const
preallocate dRdW matrix using the preallocVec
void calcJacConColoring (const word postFix="")
compute graph coloring for Jacobian connectivity matrix
void readJacConColoring (const word postFix="")
read colors for JacCon
label coloringExists (const word postFix="") const
whether the coloring file exists
Vec getJacConColor () const
return DAJacCon::jacConColors_
void calcColoredColumns (const label colorI, Vec coloredColumn) const
calculate the colored column vector
virtual void setObjFuncVec (scalarList objFuncFaceValues, scalarList objFuncCellValues, Vec objFuncVec) const
assign values for the objective function vector based on the face and cell value lists
Additional Inherited Members
Static Public Member Functions inherited from DAJacCon
static autoPtr< DAJacCon > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Protected Member Functions inherited from DAJacCon
void initializeStateBoundaryCon ()
initialize state boundary connection
void calcNeiBFaceGlobalCompact (labelList &neiBFaceGlobalCompact)
calculate DAJacCon::neiBFaceGlobalCompact_
label getLocalCoupledBFaceIndex (const label localFaceI) const
given a local face index, return the local index of the coupled boundary face
void setupStateBoundaryCon (Mat *stateBoundaryCon)
calculate DAJacCon::stateBoundaryCon_
void setupStateBoundaryConID (Mat *stateBoundaryConID)
calculate DAJacCon::stateBoundaryConID_
void createConnectionMat (Mat *connectedStates)
allocate connectedState matrix
void addStateConnections (Mat connections, const label cellI, const label connectedLevelLocal, const wordList connectedStatesLocal, const List< List< word >> connectedStateInterProc, const label addFace)
a high-level function to add connected state column indices to the connectivity matrix
void setConnections (Mat conMat, const label idx) const
add value 1 for the colume idx to conMat
void setupJacobianConnections (Mat conMat, Mat connections, const label idxI)
assign values in connections to a specific row idxI in conMat
void combineStateBndCon (Mat *stateBoundaryCon, Mat *stateBoundaryConTmp)
combine stateBoundaryCon and stateBoundaryConTmp, this is to ensure including all connected states for parallel cases
void addConMatCell (Mat conMat, const label gRow, const label cellI, const word stateName, const scalar val)
add val to the gRow row in conMat, the column indice are the state (given by stateName) for a given cellI
void addConMatNeighbourCells (Mat conMat, const label gRow, const label cellI, const word stateName, const scalar val)
add val to gRow row in conMat, column indice are the neighbouring states (given by stateName) for a given cellI
void addConMatCellFaces (Mat conMat, const label gRow, const label cellI, const word stateName, const scalar val)
add val to gRow row in conMat, column indice are the faces (given by stateName) for a given cellI
void addBoundaryFaceConnections (Mat conMat, const label gRow, const label cellI, const labelList v, const List< List< word >> connectedStates, const label addFaces)
add the column index of the (iner-proc) connected states and faces to conMat, given a local face index
void clearDAJacConMembers ()
clear members in DAJacCon
void checkSpecialBCs ()
check if there is special boundary conditions that need special treatment in jacCon_
void setPIVVec (Vec iSPIV, const label idxI)
function used to add connectivity for pressureInletVelocity
label addPhi4PIV (const word stateName, const label idxI, const label comp=-1)
add connectivity phi for pressureInletVelocity
Protected Attributes inherited from DAJacCon
const word modelType_
the name of the jacCon matrix
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
DAColoring daColoring_
DAColoring object.
DAField daField_
DAField object.
HashTable< wordList > stateInfo_
the regState_ list from DAStateInfo object
Mat stateBoundaryCon_
matrix to store boundary connectivity levels for state Jacobians
Mat stateBoundaryConID_
matrix to store boundary connectivity ID for state Jacobians
labelList neiBFaceGlobalCompact_
neibough face global index for a given local boundary face
Mat jacCon_
Jacobian connectivity mat.
Vec jacConColors_
jacCon matrix colors
label nJacConColors_
number of jacCon colors
Vec isPIVBCState_
a vector to show whether a state is connected to a pressureInletVelocity boundary face (3 level max)
Detailed Description
Definition at line 29 of file DAJacConDummy.H.
Constructor & Destructor Documentation
DAJacConDummy()
DAJacConDummy (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 19 of file DAJacConDummy.C.
~DAJacConDummy()
virtual ~DAJacConDummy () inline virtual
Definition at line 48 of file DAJacConDummy.H.
References DAJacConDummy::clear(), DAJacConDummy::initializeJacCon(), and DAJacConDummy::setupJacCon().
Member Function Documentation
TypeName()
TypeName ("dummy")
initializeJacCon()
void initializeJacCon (const dictionary & options) virtual
initialize the state Jacobian connectivity matrix
Implements DAJacCon.
Definition at line 37 of file DAJacConDummy.C.
Referenced by DAJacConDummy::~DAJacConDummy().
setupJacCon()
void setupJacCon (const dictionary & options) virtual
assign 1 to all non-zero elements for the Jacobian connecitivyt matrix
Implements DAJacCon.
Definition at line 32 of file DAJacConDummy.C.
Referenced by DAJacConDummy::~DAJacConDummy().
clear()
void clear () virtual
clear members in parent and child objects
Implements DAJacCon.
Definition at line 42 of file DAJacConDummy.C.
Referenced by DAJacConDummy::~DAJacConDummy().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAJacCon/DAJacConDummy.H
dafoam/src/adjoint/DAJacCon/DAJacConDummy.C