DAFoam: DALaplacianFoam Class Reference
DALaplacianFoam Class Reference
Public Member Functions
TypeName ("DALaplacianFoam")
DALaplacianFoam (char *argsAll, PyObject *pyOptions)
virtual ~DALaplacianFoam ()
virtual void initSolver ()
initialize fields and variables
virtual label solvePrimal (const Vec xvVec, Vec wVec)
solve the primal equations
Public Member Functions inherited from DASolver
TypeName ("DASolver")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DASolver, dictionary,(char *argsAll, PyObject *pyOptions),(argsAll, pyOptions))
DASolver (char *argsAll, PyObject *pyOptions)
virtual ~DASolver ()
void setTimeInstanceField (const label instanceI)
assign primal variables based on the current time instance
scalar getTimeInstanceObjFunc (const label instanceI, const word objFuncName)
return the value of objective function at the given time instance and name
void setTimeInstanceVar (const word mode, Mat stateMat, Mat stateBCMat, Vec timeVec, Vec timeIdxVec)
assign the time instance mats to/from the lists in the OpenFOAM layer depending on the mode
void initOldTimes ()
initialize the oldTime for all state variables
void calcdRdWT (const Vec xvVec, const Vec wVec, const label isPC, Mat dRdWT)
compute dRdWT
void calcdRdWTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, Vec dRdWTPsi)
compute [dRdW]^T*Psi
void calcdFdW (const Vec xvVec, const Vec wVec, const word objFuncName, Vec dFdW)
compute dFdW
void createMLRKSP (const Mat jacMat, const Mat jacPCMat, KSP ksp)
create a multi-level, Richardson KSP object
label solveLinearEqn (const KSP ksp, const Vec rhsVec, Vec solVec)
solve the linear equation given a ksp and right-hand-side vector
void convertMPIVec2SeqVec (const Vec mpiVec, Vec seqVec)
convert the mpi vec to a seq vec
void updateOFField (const Vec wVec)
Update the OpenFOAM field values (including both internal and boundary fields) based on the state vector wVec.
void updateOFMesh (const Vec xvVec)
Update the OpenFoam mesh point coordinates based on the point vector xvVec.
void calcdRdBC (const Vec xvVec, const Vec wVec, const word designVarName, Mat dRdBC)
compute dRdBC
void calcdFdBC (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdBC)
compute dFdBC
void calcdRdBCTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdBCTPsi)
compute dRdBCAD
void calcdFdBCAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdBC)
compute dFdBCAD
void calcdRdAOA (const Vec xvVec, const Vec wVec, const word designVarName, Mat dRdAOA)
compute dRdAOA
void calcdFdAOA (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdAOA)
compute dFdAOA
void calcdRdAOATPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdAOATPsi)
compute dRdAOAAD
void calcdRdFFD (const Vec xvVec, const Vec wVec, const word designVarName, Mat dRdFFD)
compute dRdFFD
void calcdFdFFD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdFFD)
compute dFdFFD
void calcdRdACT (const Vec xvVec, const Vec wVec, const word designVarName, const word designVarType, Mat dRdACT)
compute dRdACT
void calcdFdACT (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, const word designVarType, Vec dFdACT)
compute dFdACT
void calcdRdFieldTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdFieldTPsi)
compute dRdField^T*Psi
void calcdFdFieldAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdField)
compute dFdField
void createMLRKSPMatrixFree (const Mat jacPCMat, KSP ksp)
create a multi-level, Richardson KSP object with matrix-free Jacobians
void calcdFdWAD (const Vec xvVec, const Vec wVec, const word objFuncName, Vec dFdW)
compute dFdW using AD
void calcdRdXvTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, Vec dRdXvTPsi)
compute dRdXv^T*Psi
void calcdForcedXvAD (const Vec xvVec, const Vec wVec, const Vec fBarVec, Vec dForcedXv)
compute dForcedXv
void calcdFdXvAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdXv)
compute dFdXv AD
void calcdRdActTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdActTPsi)
void calcdForcedWAD (const Vec xvVec, const Vec wVec, const Vec fBarVec, Vec dForcedW)
void calcdFdACTAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdACT)
compute dFdACT AD
void calcdRdWOldTPsiAD (const label oldTimeLevel, const Vec psi, Vec dRdWOldTPsi)
compute dRdWOld^T*Psi
void initializedRdWTMatrixFree (const Vec xvVec, const Vec wVec)
initialize matrix free dRdWT
void destroydRdWTMatrixFree ()
destroy the matrix free dRdWT
void registerStateVariableInput4AD (const label oldTimeLevel=0)
register all state variables as the input for reverse-mode AD
void registerFieldVariableInput4AD (const word fieldName, const word fieldType)
register field variables as the input for reverse-mode AD
void registerResidualOutput4AD ()
register all residuals as the output for reverse-mode AD
void registerForceOutput4AD (List< scalar > &fX, List< scalar > &fY, List< scalar > &fZ)
register all force as the ouptut for referse-mod AD
void assignVec2ResidualGradient (Vec vecX)
assign the reverse-mode AD input seeds from vecX to the residuals in OpenFOAM
void assignVec2ForceGradient (Vec fBarVec, List< scalar > &fX, List< scalar > &fY, List< scalar > &fZ)
assign the reverse-mode AD input seeds from fBarVec to the force vectors in OpenFOAM
void assignStateGradient2Vec (Vec vecY, const label oldTimeLevel=0)
set the reverse-mode AD derivatives from the state variables in OpenFOAM to vecY
void assignFieldGradient2Vec (const word fieldName, const word fieldType, Vec vecY)
set the reverse-mode AD derivatives from the field variables in OpenFOAM to vecY
void normalizeGradientVec (Vec vecY)
normalize the reverse-mode AD derivatives stored in vecY
void initializeGlobalADTape4dRdWT ()
initialize the CoDiPack reverse-mode AD global tape for computing dRdWT*psi
label loop (Time &runTime)
return whether to loop the primal solution, similar to runTime::loop() except we don't do file IO
label getGlobalXvIndex (const label idxPoint, const label idxCoord) const
basically, we call DAIndex::getGlobalXvIndex
void ofField2StateVec (Vec stateVec) const
set the state vector based on the latest fields in OpenFOAM
void stateVec2OFField (const Vec stateVec) const
assign the fields in OpenFOAM based on the state vector
void pointVec2OFMesh (const Vec xvVec) const
assign the points in fvMesh of OpenFOAM based on the point vector
void ofMesh2PointVec (Vec xvVec) const
assign the point vector based on the points in fvMesh of OpenFOAM
void resVec2OFResField (const Vec resVec) const
assign the OpenFOAM residual fields based on the resVec
void ofResField2ResVec (Vec resVec) const
assign the resVec based on OpenFOAM residual fields
void writeMatrixBinary (const Mat matIn, const word prefix)
write the matrix in binary format
void writeMatrixASCII (const Mat matIn, const word prefix)
write the matrix in ASCII format
void readMatrixBinary (Mat matIn, const word prefix)
read petsc matrix in binary format
void writeVectorASCII (const Vec vecIn, const word prefix)
write petsc vector in ascii format
void readVectorBinary (Vec vecIn, const word prefix)
read petsc vector in binary format
void writeVectorBinary (const Vec vecIn, const word prefix)
write petsc vector in binary format
label getNLocalAdjointStates () const
return the number of local adjoint states
label getNLocalAdjointBoundaryStates () const
return the number of local adjoint boundary states
label getNLocalCells () const
return the number of local cells
void setDAObjFuncList ()
initialize DASolver::daObjFuncPtrList_ one needs to call this before calling printAllObjFuncs
void printAllObjFuncs ()
calculate the values of all objective functions and print them to screen
label checkMesh () const
check the mesh quality and return meshOK
scalar getObjFuncValue (const word objFuncName)
return the value of the objective function
void getForces (Vec fX, Vec fY, Vec fZ, Vec pointList)
return the forces of the desired fluid-structure-interaction patches
void getForcesInfo (label &nPoints, List< word > &patchList)
return the number of points used for force calculation
void getForcesInternal (List< scalar > &fX, List< scalar > &fY, List< scalar > &fZ, List< label > &pointList, List< word > &patchList)
compute the forces of the desired fluid-structure-interation patches
void printAllOptions ()
print all DAOption
void calcPrimalResidualStatistics (const word mode, const label writeRes=0)
calculate the norms of all residuals and print to screen
void setdXvdFFDMat (const Mat dXvdFFDMat)
set the value for DASolver::dXvdFFDMat_
void setFFD2XvSeedVec (Vec vecIn)
set the value for DASolver::FFD2XvSeedVec_
void updateDAOption (PyObject *pyOptions)
update the allOptions_ dict in DAOption based on the pyOptions from pyDAFoam
scalar getPrevPrimalSolTime ()
get the solution time folder for previous primal solution
void setFieldValue4GlobalCellI (const word fieldName, const scalar val, const label globalCellI, const label compI=0)
set the field value
void updateBoundaryConditions (const word fieldName, const word fieldType)
update the boundary condition for a field
void syncDAOptionToActuatorDVs ()
synchronize the values in DAOption and actuatorDiskDVs_
const fvMesh & getMesh ()
const Time & getRunTime ()
return the runTime object
const DAOption & getDAOption ()
get DAOption object
const DAStateInfo & getDAStateInfo ()
get DAStateInfo object
const DAIndex & getDAIndex ()
get DAIndex object
const DAModel & getDAModel ()
get DAModel object
const DAResidual & getDAResidual ()
get DAResidual object
const DAField & getDAField ()
get DAField object
const DALinearEqn & getDALinearEqn ()
get DALinearEqn object
const DACheckMesh & getDACheckMesh ()
get DACheckMesh object
PetscScalar getForwardADDerivVal (const word objFuncName)
get forwardADDerivVal_
void setPrimalBoundaryConditions (const label printInfo=1)
update the primal state boundary condition based on the primalBC dict
void calcResidualVec (Vec resVec)
calculate the residual and assign it to the resVec vector
Protected Attributes
autoPtr< volScalarField > TPtr_
temperature field pointer
autoPtr< dimensionedScalar > DTPtr_
DT pointer.
word mode_ = "None"
unsteady mode
Protected Attributes inherited from DASolver
char * argsAll_
all the arguments
PyObject * pyOptions_
all options in DAFoam
autoPtr< argList > argsPtr_
args pointer
autoPtr< Time > runTimePtr_
runTime pointer
autoPtr< fvMesh > meshPtr_
fvMesh pointer
autoPtr< DAOption > daOptionPtr_
DAOption pointer.
autoPtr< DAModel > daModelPtr_
DAModel pointer.
autoPtr< DAIndex > daIndexPtr_
DAIndex pointer.
autoPtr< DAField > daFieldPtr_
DAField pointer.
UPtrList< DAObjFunc > daObjFuncPtrList_
a list of DAObjFunc pointers
autoPtr< DACheckMesh > daCheckMeshPtr_
DACheckMesh object pointer.
autoPtr< DALinearEqn > daLinearEqnPtr_
DALinearEqn pointer.
autoPtr< DAResidual > daResidualPtr_
DAResidual pointer.
autoPtr< DAStateInfo > daStateInfoPtr_
DAStateInfo pointer.
HashTable< wordList > stateInfo_
the stateInfo_ list from DAStateInfo object
wordList objFuncNames4Adj_
the list of objective function names that requires adjoint solution
dictionary psiVecDict_
the dictionary of adjoint vector (psi) values for all objectives
dictionary totalDerivDict_
the dictionary that stores the total derivatives reduced from processors
autoPtr< OFstream > objFuncAvgHistFilePtr_
pointer to the objective function file used in unsteady primal solvers
label nItersObjFuncAvg_ = -9999
number of iterations since the start of objFunc averaging
scalarList avgObjFuncValues_
the averaged objective function values used in unsteady flow
Mat dRdWTPC_
the preconditioner matrix for the adjoint linear equation solution
label nSolveAdjointCalls_ = 0
how many times the DASolver::solveAdjoint function is called
Mat dXvdFFDMat_
the matrix that stores the partials dXv/dFFD computed from the idwarp and pygeo in the pyDAFoam.py
Vec FFD2XvSeedVec_
the vector that stores the AD seeds that propagate from FFD to Xv and will be used in forward mode AD
HashTable< PetscScalar > forwardADDerivVal_
the derivative value computed by the forward mode primal solution.
scalar primalMinRes_ = 1e10
the maximal residual for primal solution
scalar prevPrimalSolTime_ = -1e10
the solution time for the previous primal solution
Mat dRdWTMF_
matrix-free dRdWT matrix used in GMRES solution
label globalADTape4dRdWTInitialized = 0
a flag in dRdWTMatVecMultFunction to determine if the global tap is initialized
List< List< scalar > > stateAllInstances_
state variable list for all instances (unsteady)
List< List< scalar > > stateBoundaryAllInstances_
state boundary variable list for all instances (unsteady)
List< dictionary > objFuncsAllInstances_
objective function for all instances (unsteady)
List< scalar > runTimeAllInstances_
the runtime value for all instances (unsteady)
List< label > runTimeIndexAllInstances_
the runtime index for all instances (unsteady)
label nTimeInstances_ = -9999
number of time instances for hybird adjoint (unsteady)
scalar periodicity_ = 0.0
periodicity of oscillating flow variables (unsteady)
Additional Inherited Members
Static Public Member Functions inherited from DASolver
static autoPtr< DASolver > New (char *argsAll, PyObject *pyOptions)
static PetscErrorCode dRdWTMatVecMultFunction (Mat dRdWT, Vec vecX, Vec vecY)
matrix free matrix-vector product function to compute vecY=dRdWT*vecX
Protected Member Functions inherited from DASolver
template<class classType >
void primalResidualControl (const SolverPerformance< classType > &solverP, const label printToScreen, const label printInterval, const word varName)
setup maximal residual control and print the residual as needed
label isPrintTime (const Time &runTime, const label printInterval) const
label checkResidualTol ()
check whether the min residual in primal satisfy the prescribed tolerance
void reduceStateResConLevel (const dictionary &maxResConLv4JacPCMat, HashTable< List< List< word >>> &stateResConInfo) const
reduce the connectivity level for Jacobian connectivity mat
void writeAssociatedFields ()
write associated fields such as relative velocity
void saveTimeInstanceFieldHybrid (label &timeInstanceI)
save primal variable to time instance list for hybrid adjoint (unsteady)
void saveTimeInstanceFieldTimeAccurate (label &timeInstanceI)
save primal variable to time instance list for time accurate adjoint (unsteady)
Detailed Description
Definition at line 47 of file DALaplacianFoam.H.
Constructor & Destructor Documentation
DALaplacianFoam()
DALaplacianFoam (char * argsAll, PyObject * pyOptions)
Definition at line 41 of file DALaplacianFoam.C.
~DALaplacianFoam()
virtual ~DALaplacianFoam () inline virtual
Definition at line 73 of file DALaplacianFoam.H.
Member Function Documentation
TypeName()
TypeName ("DALaplacianFoam")
initSolver()
void initSolver () virtual
initialize fields and variables
Implements DASolver.
Definition at line 51 of file DALaplacianFoam.C.
References DASolver::daCheckMeshPtr_, DASolver::daIndexPtr_, DASolver::daLinearEqnPtr_, DASolver::daOptionPtr_, mesh, DASolver::meshPtr_, DALaplacianFoam::mode_, DASolver::nTimeInstances_, DASolver::objFuncsAllInstances_, DASolver::periodicity_, runTime, DASolver::runTimeAllInstances_, DASolver::runTimeIndexAllInstances_, DASolver::runTimePtr_, DASolver::setDAObjFuncList(), DASolver::stateAllInstances_, and DASolver::stateBoundaryAllInstances_.
solvePrimal()
label solvePrimal (const Vec xvVec, Vec wVec) virtual
solve the primal equations
Implements DASolver.
Definition at line 126 of file DALaplacianFoam.C.
References DASolver::calcPrimalResidualStatistics(), DASolver::checkMesh(), DASolver::daOptionPtr_, DT, DASolver::isPrintTime(), DASolver::loop(), mesh, DALaplacianFoam::mode_, DASolver::ofField2StateVec(), DASolver::pointVec2OFMesh(), DASolver::primalMinRes_, primalResidualControl< scalar >(), DASolver::printAllObjFuncs(), runTime, DASolver::saveTimeInstanceFieldHybrid(), DASolver::saveTimeInstanceFieldTimeAccurate(), solverT, T, and TEqn().
Member Data Documentation
TPtr_
autoPtr<volScalarField> TPtr_ protected
temperature field pointer
Definition at line 54 of file DALaplacianFoam.H.
DTPtr_
autoPtr<dimensionedScalar> DTPtr_ protected
DT pointer.
Definition at line 57 of file DALaplacianFoam.H.
mode_
word mode_ = "None" protected
unsteady mode
Definition at line 60 of file DALaplacianFoam.H.
Referenced by DALaplacianFoam::initSolver(), and DALaplacianFoam::solvePrimal().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DASolver/DALaplacianFoam/DALaplacianFoam.H
dafoam/src/adjoint/DASolver/DALaplacianFoam/DALaplacianFoam.C