DAFoam: tractionDisplacementFvPatchVectorField Class Reference
tractionDisplacementFvPatchVectorField Class Reference
Public Member Functions
TypeName ("tractionDisplacement")
tractionDisplacementFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &)
tractionDisplacementFvPatchVectorField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField &)
virtual tmp< fvPatchVectorField > clone () const
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual const vectorField & traction () const
virtual vectorField & traction ()
virtual const scalarField & pressure () const
virtual scalarField & pressure ()
virtual void autoMap (const fvPatchFieldMapper &)
virtual void rmap (const fvPatchVectorField &, const labelList &)
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Definition at line 27 of file tractionDisplacementFvPatchVectorField.H.
Constructor & Destructor Documentation
tractionDisplacementFvPatchVectorField() [1/5]
tractionDisplacementFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 20 of file tractionDisplacementFvPatchVectorField.C.
Referenced by tractionDisplacementFvPatchVectorField::clone(), and tractionDisplacementFvPatchVectorField::tractionDisplacementFvPatchVectorField().
tractionDisplacementFvPatchVectorField() [2/5]
tractionDisplacementFvPatchVectorField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 44 of file tractionDisplacementFvPatchVectorField.C.
References tractionDisplacementFvPatchVectorField::tractionDisplacementFvPatchVectorField().
tractionDisplacementFvPatchVectorField() [3/5]
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField & tdpvf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 32 of file tractionDisplacementFvPatchVectorField.C.
References tractionDisplacementFvPatchVectorField::tractionDisplacementFvPatchVectorField().
tractionDisplacementFvPatchVectorField() [4/5]
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField & tdpvf)
Definition at line 57 of file tractionDisplacementFvPatchVectorField.C.
References tractionDisplacementFvPatchVectorField::tractionDisplacementFvPatchVectorField().
tractionDisplacementFvPatchVectorField() [5/5]
tractionDisplacementFvPatchVectorField (const tractionDisplacementFvPatchVectorField & tdpvf, const DimensionedField< vector, volMesh > & iF)
Definition at line 66 of file tractionDisplacementFvPatchVectorField.C.
Member Function Documentation
TypeName()
TypeName ("tractionDisplacement")
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Definition at line 66 of file tractionDisplacementFvPatchVectorField.H.
References tractionDisplacementFvPatchVectorField::tractionDisplacementFvPatchVectorField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 78 of file tractionDisplacementFvPatchVectorField.H.
References tractionDisplacementFvPatchVectorField::tractionDisplacementFvPatchVectorField().
traction() [1/2]
virtual const vectorField& traction () const inline virtual
Definition at line 89 of file tractionDisplacementFvPatchVectorField.H.
traction() [2/2]
virtual vectorField& traction () inline virtual
Definition at line 94 of file tractionDisplacementFvPatchVectorField.H.
pressure() [1/2]
virtual const scalarField& pressure () const inline virtual
Definition at line 99 of file tractionDisplacementFvPatchVectorField.H.
pressure() [2/2]
virtual scalarField& pressure () inline virtual
Definition at line 104 of file tractionDisplacementFvPatchVectorField.H.
References tractionDisplacementFvPatchVectorField::autoMap(), tractionDisplacementFvPatchVectorField::rmap(), tractionDisplacementFvPatchVectorField::updateCoeffs(), and tractionDisplacementFvPatchVectorField::write().
autoMap()
void autoMap (const fvPatchFieldMapper & m) virtual
Definition at line 77 of file tractionDisplacementFvPatchVectorField.C.
Referenced by tractionDisplacementFvPatchVectorField::pressure().
rmap()
void rmap (const fvPatchVectorField & ptf, const labelList & addr) virtual
Definition at line 85 of file tractionDisplacementFvPatchVectorField.C.
Referenced by tractionDisplacementFvPatchVectorField::pressure().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 98 of file tractionDisplacementFvPatchVectorField.C.
References gradD, lambda, mu, and rho.
Referenced by tractionDisplacementFvPatchVectorField::pressure().
write()
void write (Ostream & os) const virtual
Definition at line 146 of file tractionDisplacementFvPatchVectorField.C.
References Foam::makePatchTypeField().
Referenced by tractionDisplacementFvPatchVectorField::pressure().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/boundaryConditions/tractionDisplacement/tractionDisplacementFvPatchVectorField.H
dafoam/src/adjoint/boundaryConditions/tractionDisplacement/tractionDisplacementFvPatchVectorField.C