DAFoam: dummyTurbulenceModel< BasicTurbulenceModel > Class Template Reference
dummyTurbulenceModel< BasicTurbulenceModel > Class Template Reference
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("dummy")
dummyTurbulenceModel (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~dummyTurbulenceModel ()
virtual bool read ()
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
Protected Member Functions
virtual void correctNut ()
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::dummyTurbulenceModel< BasicTurbulenceModel >
Definition at line 29 of file dummyTurbulenceModel.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 42 of file dummyTurbulenceModel.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 43 of file dummyTurbulenceModel.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 44 of file dummyTurbulenceModel.H.
Constructor & Destructor Documentation
dummyTurbulenceModel()
dummyTurbulenceModel (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 30 of file dummyTurbulenceModel.C.
~dummyTurbulenceModel()
virtual ~dummyTurbulenceModel () inline virtual
Definition at line 63 of file dummyTurbulenceModel.H.
References dummyTurbulenceModel< BasicTurbulenceModel >::correct(), dummyTurbulenceModel< BasicTurbulenceModel >::epsilon(), dummyTurbulenceModel< BasicTurbulenceModel >::k(), and dummyTurbulenceModel< BasicTurbulenceModel >::read().
Member Function Documentation
correctNut()
void correctNut () protected virtual
Definition at line 23 of file dummyTurbulenceModel.C.
TypeName()
TypeName ("dummy")
read()
bool read () virtual
Definition at line 63 of file dummyTurbulenceModel.C.
Referenced by dummyTurbulenceModel< BasicTurbulenceModel >::~dummyTurbulenceModel().
k()
tmp< volScalarField > k () const virtual
Definition at line 70 of file dummyTurbulenceModel.C.
Referenced by dummyTurbulenceModel< BasicTurbulenceModel >::~dummyTurbulenceModel().
epsilon()
tmp< volScalarField > epsilon () const virtual
Definition at line 76 of file dummyTurbulenceModel.C.
Referenced by dummyTurbulenceModel< BasicTurbulenceModel >::~dummyTurbulenceModel().
correct()
void correct () virtual
Definition at line 82 of file dummyTurbulenceModel.C.
Referenced by dummyTurbulenceModel< BasicTurbulenceModel >::~dummyTurbulenceModel().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/models/dummyTurbulenceModel/dummyTurbulenceModel.H
dafoam/src/adjoint/models/dummyTurbulenceModel/dummyTurbulenceModel.C