DAFoam: ColoringSolid Class Reference
ColoringSolid Class Reference
Public Member Functions
ColoringSolid (char *argsAll, PyObject *pyOptions)
Construct from components.
virtual ~ColoringSolid ()
Destructor.
void run ()
run
Detailed Description
Definition at line 36 of file ColoringSolid.H.
Constructor & Destructor Documentation
ColoringSolid()
ColoringSolid (char * argsAll, PyObject * pyOptions)
Construct from components.
Definition at line 16 of file ColoringSolid.C.
~ColoringSolid()
~ColoringSolid () virtual
Destructor.
Definition at line 27 of file ColoringSolid.C.
Member Function Documentation
run()
void run ()
run
Definition at line 31 of file ColoringSolid.C.
References allOptions, daIndex(), daModel(), daOption(), mesh, DAStateInfo::New(), DAResidual::New(), DAObjFunc::New(), DAJacCon::New(), and solverName.
The documentation for this class was generated from the following files:
dafoam/src/utilities/pyColoringSolid/ColoringSolid.H
dafoam/src/utilities/pyColoringSolid/ColoringSolid.C