DAFoam: DAObjFuncForce Class Reference
DAObjFuncForce Class Reference
Public Member Functions
TypeName ("force")
DAObjFuncForce (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict)
virtual ~DAObjFuncForce ()
virtual void calcObjFunc (const labelList &objFuncFaceSources, const labelList &objFuncCellSources, scalarList &objFuncFaceValues, scalarList &objFuncCellValues, scalar &objFuncValue)
calculate the value of objective function
Public Member Functions inherited from DAObjFunc
TypeName ("DAObjFunc")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAObjFunc, dictionary,(const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict),(mesh, daOption, daModel, daIndex, daResidual, objFuncName, objFuncPart, objFuncDict))
DAObjFunc (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict)
virtual ~DAObjFunc ()
void clear ()
clear up members
void calcObjFuncSources (labelList &faceSources, labelList &cellSources)
calculate DAObjFunc::objFuncFaceSources_ and DAObjFunc::objFuncCellSources_
scalar getObjFuncValue ()
calcluate the value of objective function
scalar masterFunction (const dictionary &options, const Vec xvVec, const Vec wVec)
the master function to compute objective function given the state and point vectors
word getObjFuncName ()
return the name of objective function
word getObjFuncPart ()
return the part of objective function
word getObjFuncType ()
return the part of objective function
const labelList & getObjFuncFaceSources () const
return DAObjFunc::objFuncFaceSources_
const labelList & getObjFuncCellSources () const
return DAObjFunc::objFuncCellSources_
const scalarList & getObjFuncFaceValues () const
return DAObjFunc::objFuncFaceValues_
const scalarList & getObjFuncCellValues () const
return DAObjFunc::objFuncCellValues_
const List< List< word > > & getObjFuncConInfo () const
return DAObjFunc::objFuncConInfo_
Protected Member Functions
void updateForceDir (vector &forceDir)
dynamically adjust the force direction
Protected Attributes
vector forceDir_
the direction of the force
word dirMode_
if dynamically adjusting the angle what mode to use
word inoutPatch_
the patch name from the alpha design variable dict
label flowAxisIndex_
flowAxisIndex_ for the alpha design variable with tan(U_normal/U_flow)
label normalAxisIndex_
normalAxisIndex_ for the alpha design variable with tan(U_normal/U_flow)
const DATurbulenceModel & daTurb_
DATurbulenceModel object.
Protected Attributes inherited from DAObjFunc
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
const DAResidual & daResidual_
DAResidual object.
word objFuncName_
the name of the objective function
word objFuncPart_
the part of the objective function
word objFuncType_
the type of the objective function
const dictionary & objFuncDict_
dictionary containing the information for the objective function
DAField daField_
DAField object.
labelList objFuncFaceSources_
a sorted list of all face sources for the objective function
labelList objFuncCellSources_
a sorted list of all cell sources for the objective function
scalarList objFuncFaceValues_
value of the obj function on the discrete faces
scalarList objFuncCellValues_
value of the obj function in the discrete cells
scalar scale_
scale of the objective function
scalar objFuncValue_
the value of the objective function
List< List< word > > objFuncConInfo_
the connectivity information for the objective function
Additional Inherited Members
Static Public Member Functions inherited from DAObjFunc
static autoPtr< DAObjFunc > New (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict)
Detailed Description
Definition at line 26 of file DAObjFuncForce.H.
Constructor & Destructor Documentation
DAObjFuncForce (const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex, const DAResidual & daResidual, const word objFuncName, const word objFuncPart, const dictionary & objFuncDict)
Definition at line 19 of file DAObjFuncForce.C.
References DAModel::correctModelStates(), DAObjFunc::daOption_, DAObjFuncForce::dirMode_, DAObjFuncForce::flowAxisIndex_, DAObjFuncForce::forceDir_, DAOption::getAllOptions(), DAObjFuncForce::inoutPatch_, DAObjFunc::mesh_, DAObjFuncForce::normalAxisIndex_, DAObjFunc::objFuncConInfo_, DAObjFunc::objFuncDict_, DAObjFunc::objFuncType_, and DAObjFunc::scale_.
virtual ~DAObjFuncForce () inline virtual
Definition at line 68 of file DAObjFuncForce.H.
Member Function Documentation
void updateForceDir (vector & forceDir) protected
dynamically adjust the force direction
Definition at line 189 of file DAObjFuncForce.C.
References DAObjFuncForce::dirMode_, DAObjFuncForce::flowAxisIndex_, DAObjFuncForce::inoutPatch_, DAObjFunc::mesh_, DAObjFuncForce::normalAxisIndex_, Foam::reduce(), and U.
Referenced by DAObjFuncForce::calcObjFunc().
TypeName ("force")
void calcObjFunc (const labelList & objFuncFaceSources, const labelList & objFuncCellSources, scalarList & objFuncFaceValues, scalarList & objFuncCellValues, scalar & objFuncValue) virtual
calculate the value of objective function
Implements DAObjFunc.
Definition at line 116 of file DAObjFuncForce.C.
References DAIndex::bFaceFaceI, DAIndex::bFacePatchI, DAObjFunc::daIndex_, DAObjFuncForce::daTurb_, DATurbulenceModel::devRhoReff(), DAObjFuncForce::dirMode_, Foam::forAll(), DAObjFuncForce::forceDir_, DAObjFunc::mesh_, DAIndex::nLocalInternalFaces, p, Foam::reduce(), DAObjFunc::scale_, and DAObjFuncForce::updateForceDir().
Member Data Documentation
vector forceDir_ protected
the direction of the force
Definition at line 32 of file DAObjFuncForce.H.
Referenced by DAObjFuncForce::calcObjFunc(), and DAObjFuncForce::DAObjFuncForce().
word dirMode_ protected
if dynamically adjusting the angle what mode to use
Definition at line 35 of file DAObjFuncForce.H.
Referenced by DAObjFuncForce::calcObjFunc(), DAObjFuncForce::DAObjFuncForce(), and DAObjFuncForce::updateForceDir().
word inoutPatch_ protected
the patch name from the alpha design variable dict
Definition at line 38 of file DAObjFuncForce.H.
Referenced by DAObjFuncForce::DAObjFuncForce(), and DAObjFuncForce::updateForceDir().
label flowAxisIndex_ protected
flowAxisIndex_ for the alpha design variable with tan(U_normal/U_flow)
Definition at line 41 of file DAObjFuncForce.H.
Referenced by DAObjFuncForce::DAObjFuncForce(), and DAObjFuncForce::updateForceDir().
label normalAxisIndex_ protected
normalAxisIndex_ for the alpha design variable with tan(U_normal/U_flow)
Definition at line 44 of file DAObjFuncForce.H.
Referenced by DAObjFuncForce::DAObjFuncForce(), and DAObjFuncForce::updateForceDir().
const DATurbulenceModel& daTurb_ protected
DATurbulenceModel object.
Definition at line 50 of file DAObjFuncForce.H.
Referenced by DAObjFuncForce::calcObjFunc().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAObjFunc/DAObjFuncForce.H
dafoam/src/adjoint/DAObjFunc/DAObjFuncForce.C