DAFoam: DASpalartAllmarasFv3FieldInversion Class Reference
DASpalartAllmarasFv3FieldInversion Class Reference
Protected Member Functions
SA functions
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fv3 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fw (const volScalarField &Stilda) const
Protected Attributes
SA parameters
dimensionedScalar sigmaNut_
dimensionedScalar kappa_
dimensionedScalar Cb1_
dimensionedScalar Cb2_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar Cv1_
dimensionedScalar Cv2_
Protected Attributes inherited from DATurbulenceModel
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const dictionary & allOptions_
all DAFoam options
volScalarField & nut_
turbulence viscosity
volVectorField & U_
velocity
surfaceScalarField & phi_
face flux
volScalarField phase_
phase field
surfaceScalarField & phaseRhoPhi_
phase*phi*density field
IOdictionary turbDict_
turbulence model property dict
dictionary coeffDict_
turbulence model parameters dict
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
dimensionedScalar nuTildaMin_
Lower limit for nuTilda.
scalar Pr_
Prandtl number.
scalar Prt_ = -9999.0
turbulent Prandtl number
Augmented variables for residual computation
volScalarField & nuTilda_
volScalarField nuTildaRes_
volScalarField nuTildaResPartDeriv_
volScalarField & betaFieldInversion_
A beta field multiplying to the production term.
volVectorField UData_
reference velocity field
volScalarField surfaceFriction_
a surface friction 'field' when using skin friction data for field inversion
volScalarField surfaceFrictionData_
the reference field for surfaceFriction
volScalarField pData_
the reference field for pressure
volScalarField USingleComponentData_
reference field for profile data
const volScalarField & y_
3D wall distance
label solveTurbState_ = 0
whether to solve for turb states
label printInterval_
time step interval to print residual
TypeName ("SpalartAllmarasFv3FieldInversion")
DASpalartAllmarasFv3FieldInversion (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DASpalartAllmarasFv3FieldInversion ()
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
virtual void correctModelStates (wordList &modelStates) const
update the turbulence state for DAStateInfo::regStates_
virtual void correctNut ()
update nut based on other turbulence variables and update the BCs
virtual void correctBoundaryConditions ()
update turbulence variable boundary values
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctStateResidualModelCon (List< List< word >> &stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const
add the model residual connectivity to stateCon
virtual void calcResiduals (const dictionary &options)
compute the turbulence residuals
virtual void correct ()
solve the residual equations and update the state
virtual void getTurbProdTerm (scalarList &prodTerm) const
return the value of the production term from the turbulence model
Additional Inherited Members
Public Member Functions inherited from DATurbulenceModel
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable (autoPtr, DATurbulenceModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DATurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DATurbulenceModel ()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
void correctAlphat ()
update alphat
tmp< volSymmTensorField > devRhoReff () const
dev terms
tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U)
divDev terms
tmp< fvVectorMatrix > divDevReff (volVectorField &U)
divDev terms
tmp< volScalarField > nuEff () const
return effective viscosity
tmp< volScalarField > getNut ()
get the nut field
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
tmp< volScalarField > nu () const
get the nu field
tmp< volScalarField > getAlpha () const
get alpha field
tmp< volScalarField > getRho ()
get the density field
tmp< volScalarField > getPhase ()
get the phase field
scalar getPrt ()
get the turbulent Prandtl number
tmp< Foam::volScalarField > getMu () const
get mu
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void printYPlus () const
print the min max and mean yPlus to screen
label isPrintTime (const Time &runTime, const label printInterval) const
virtual void invTranProdNuTildaEqn (const volScalarField &mySource, volScalarField &pseudoNuTilda)
Inverse transpose product, M_nuTilda^(-T)
virtual void constructPseudoNuTildaEqn ()
virtual void rhsSolvePseudoNuTildaEqn (const volScalarField &nuTildaSource)
virtual void calcLduResidualTurb (volScalarField &nuTildaRes)
calculate the turbulence residual using LDU matrix
Static Public Member Functions inherited from DATurbulenceModel
static autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Detailed Description
Definition at line 50 of file DASpalartAllmarasFv3FieldInversion.H.
Constructor & Destructor Documentation
DASpalartAllmarasFv3FieldInversion()
DASpalartAllmarasFv3FieldInversion (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 41 of file DASpalartAllmarasFv3FieldInversion.C.
References daOption(), mesh, and DASpalartAllmarasFv3FieldInversion::printInterval_.
~DASpalartAllmarasFv3FieldInversion()
virtual ~DASpalartAllmarasFv3FieldInversion () inline virtual
Definition at line 131 of file DASpalartAllmarasFv3FieldInversion.H.
Member Function Documentation
chi()
tmp< volScalarField > chi () const protected
Definition at line 148 of file DASpalartAllmarasFv3FieldInversion.C.
References DATurbulenceModel::nu(), and DASpalartAllmarasFv3FieldInversion::nuTilda_.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::correctNut(), DASpalartAllmarasFv3FieldInversion::fv1(), DASpalartAllmarasFv3FieldInversion::fv2(), DASpalartAllmarasFv3FieldInversion::fv3(), and DASpalartAllmarasFv3FieldInversion::getTurbProdTerm().
fv1()
tmp< volScalarField > fv1 (const volScalarField & chi) const protected
Definition at line 153 of file DASpalartAllmarasFv3FieldInversion.C.
References DASpalartAllmarasFv3FieldInversion::chi(), and DASpalartAllmarasFv3FieldInversion::Cv1_.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::correctNut(), DASpalartAllmarasFv3FieldInversion::fv3(), and DASpalartAllmarasFv3FieldInversion::getTurbProdTerm().
fv2()
tmp< volScalarField > fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 160 of file DASpalartAllmarasFv3FieldInversion.C.
References DASpalartAllmarasFv3FieldInversion::chi(), and DASpalartAllmarasFv3FieldInversion::Cv2_.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), and DASpalartAllmarasFv3FieldInversion::getTurbProdTerm().
fv3()
tmp< volScalarField > fv3 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 167 of file DASpalartAllmarasFv3FieldInversion.C.
References DASpalartAllmarasFv3FieldInversion::chi(), DASpalartAllmarasFv3FieldInversion::Cv2_, and DASpalartAllmarasFv3FieldInversion::fv1().
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), and DASpalartAllmarasFv3FieldInversion::getTurbProdTerm().
fw()
tmp< volScalarField > fw (const volScalarField & Stilda) const protected
Definition at line 180 of file DASpalartAllmarasFv3FieldInversion.C.
References DASpalartAllmarasFv3FieldInversion::Cw2_, DASpalartAllmarasFv3FieldInversion::Cw3_, DASpalartAllmarasFv3FieldInversion::kappa_, DASpalartAllmarasFv3FieldInversion::nuTilda_, and DASpalartAllmarasFv3FieldInversion::y_.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals().
TypeName()
TypeName ("SpalartAllmarasFv3FieldInversion")
DnuTildaEff()
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
Definition at line 198 of file DASpalartAllmarasFv3FieldInversion.C.
References DATurbulenceModel::nu(), DASpalartAllmarasFv3FieldInversion::nuTilda_, and DASpalartAllmarasFv3FieldInversion::sigmaNut_.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals().
correctModelStates()
void correctModelStates (wordList & modelStates) const virtual
update the turbulence state for DAStateInfo::regStates_
Implements DATurbulenceModel.
Definition at line 205 of file DASpalartAllmarasFv3FieldInversion.C.
References forAll().
correctNut()
void correctNut () virtual
update nut based on other turbulence variables and update the BCs
Implements DATurbulenceModel.
Definition at line 239 of file DASpalartAllmarasFv3FieldInversion.C.
References DASpalartAllmarasFv3FieldInversion::chi(), DATurbulenceModel::correctAlphat(), DASpalartAllmarasFv3FieldInversion::fv1(), DATurbulenceModel::nut_, and DASpalartAllmarasFv3FieldInversion::nuTilda_.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), and DASpalartAllmarasFv3FieldInversion::updateIntermediateVariables().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update turbulence variable boundary values
Implements DATurbulenceModel.
Definition at line 259 of file DASpalartAllmarasFv3FieldInversion.C.
References DASpalartAllmarasFv3FieldInversion::nuTilda_.
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DATurbulenceModel.
Definition at line 270 of file DASpalartAllmarasFv3FieldInversion.C.
References DASpalartAllmarasFv3FieldInversion::correctNut().
correctStateResidualModelCon()
void correctStateResidualModelCon (List< List< word >> & stateCon) const virtual
update the original variable connectivity for the adjoint state residuals in stateCon
Implements DATurbulenceModel.
Definition at line 281 of file DASpalartAllmarasFv3FieldInversion.C.
References forAll().
addModelResidualCon()
void addModelResidualCon (HashTable< List< List< word >>> & allCon) const virtual
add the model residual connectivity to stateCon
Implements DATurbulenceModel.
Definition at line 331 of file DASpalartAllmarasFv3FieldInversion.C.
References DATurbulenceModel::mesh_.
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute the turbulence residuals
Implements DATurbulenceModel.
Definition at line 429 of file DASpalartAllmarasFv3FieldInversion.C.
References DATurbulenceModel::allOptions_, DASpalartAllmarasFv3FieldInversion::betaFieldInversion_, DAUtility::boundVar(), DASpalartAllmarasFv3FieldInversion::Cb1_, DASpalartAllmarasFv3FieldInversion::Cb2_, DASpalartAllmarasFv3FieldInversion::chi(), DASpalartAllmarasFv3FieldInversion::correctNut(), DASpalartAllmarasFv3FieldInversion::Cw1_, DASpalartAllmarasFv3FieldInversion::DnuTildaEff(), DASpalartAllmarasFv3FieldInversion::fv1(), DASpalartAllmarasFv3FieldInversion::fv2(), DASpalartAllmarasFv3FieldInversion::fv3(), DASpalartAllmarasFv3FieldInversion::fw(), DATurbulenceModel::isPrintTime(), DASpalartAllmarasFv3FieldInversion::kappa_, DATurbulenceModel::mesh_, normalizeResiduals, DASpalartAllmarasFv3FieldInversion::nuTilda_, DASpalartAllmarasFv3FieldInversion::nuTildaRes_, DATurbulenceModel::phase_, DATurbulenceModel::phaseRhoPhi_, DASpalartAllmarasFv3FieldInversion::printInterval_, DASpalartAllmarasFv3FieldInversion::sigmaNut_, solve(), DASpalartAllmarasFv3FieldInversion::solveTurbState_, DATurbulenceModel::U_, and DASpalartAllmarasFv3FieldInversion::y_.
Referenced by DASpalartAllmarasFv3FieldInversion::correct().
correct()
void correct () virtual
solve the residual equations and update the state
Implements DATurbulenceModel.
Definition at line 409 of file DASpalartAllmarasFv3FieldInversion.C.
References DASpalartAllmarasFv3FieldInversion::calcResiduals(), and DASpalartAllmarasFv3FieldInversion::solveTurbState_.
getTurbProdTerm()
void getTurbProdTerm (scalarList & prodTerm) const virtual
return the value of the production term from the turbulence model
Reimplemented from DATurbulenceModel.
Definition at line 516 of file DASpalartAllmarasFv3FieldInversion.C.
References DASpalartAllmarasFv3FieldInversion::Cb1_, DASpalartAllmarasFv3FieldInversion::chi(), forAll(), DASpalartAllmarasFv3FieldInversion::fv1(), DASpalartAllmarasFv3FieldInversion::fv2(), DASpalartAllmarasFv3FieldInversion::fv3(), DASpalartAllmarasFv3FieldInversion::kappa_, DASpalartAllmarasFv3FieldInversion::nuTilda_, DATurbulenceModel::phase_, DATurbulenceModel::U_, and DASpalartAllmarasFv3FieldInversion::y_.
Member Data Documentation
sigmaNut_
dimensionedScalar sigmaNut_ protected
Definition at line 57 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), and DASpalartAllmarasFv3FieldInversion::DnuTildaEff().
kappa_
dimensionedScalar kappa_ protected
Definition at line 58 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::fw(), and DASpalartAllmarasFv3FieldInversion::getTurbProdTerm().
Cb1_
dimensionedScalar Cb1_ protected
Definition at line 59 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), and DASpalartAllmarasFv3FieldInversion::getTurbProdTerm().
Cb2_
dimensionedScalar Cb2_ protected
Definition at line 60 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals().
Cw1_
dimensionedScalar Cw1_ protected
Definition at line 61 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals().
Cw2_
dimensionedScalar Cw2_ protected
Definition at line 62 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::fw().
Cw3_
dimensionedScalar Cw3_ protected
Definition at line 63 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::fw().
Cv1_
dimensionedScalar Cv1_ protected
Definition at line 64 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::fv1().
Cv2_
dimensionedScalar Cv2_ protected
Definition at line 65 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::fv2(), and DASpalartAllmarasFv3FieldInversion::fv3().
nuTilda_
volScalarField& nuTilda_ protected
Definition at line 88 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::chi(), DASpalartAllmarasFv3FieldInversion::correctBoundaryConditions(), DASpalartAllmarasFv3FieldInversion::correctNut(), DASpalartAllmarasFv3FieldInversion::DnuTildaEff(), DASpalartAllmarasFv3FieldInversion::fw(), and DASpalartAllmarasFv3FieldInversion::getTurbProdTerm().
nuTildaRes_
volScalarField nuTildaRes_ protected
Definition at line 89 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals().
nuTildaResPartDeriv_
volScalarField nuTildaResPartDeriv_ protected
Definition at line 90 of file DASpalartAllmarasFv3FieldInversion.H.
betaFieldInversion_
volScalarField& betaFieldInversion_ protected
A beta field multiplying to the production term.
Definition at line 94 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals().
UData_
volVectorField UData_ protected
reference velocity field
Definition at line 97 of file DASpalartAllmarasFv3FieldInversion.H.
surfaceFriction_
volScalarField surfaceFriction_ protected
a surface friction 'field' when using skin friction data for field inversion
Definition at line 100 of file DASpalartAllmarasFv3FieldInversion.H.
surfaceFrictionData_
volScalarField surfaceFrictionData_ protected
the reference field for surfaceFriction
Definition at line 103 of file DASpalartAllmarasFv3FieldInversion.H.
pData_
volScalarField pData_ protected
the reference field for pressure
Definition at line 106 of file DASpalartAllmarasFv3FieldInversion.H.
USingleComponentData_
volScalarField USingleComponentData_ protected
reference field for profile data
Definition at line 109 of file DASpalartAllmarasFv3FieldInversion.H.
y_
const volScalarField& y_ protected
3D wall distance
Definition at line 112 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::fw(), and DASpalartAllmarasFv3FieldInversion::getTurbProdTerm().
solveTurbState_
label solveTurbState_ = 0 protected
whether to solve for turb states
Definition at line 115 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), and DASpalartAllmarasFv3FieldInversion::correct().
printInterval_
label printInterval_ protected
time step interval to print residual
Definition at line 118 of file DASpalartAllmarasFv3FieldInversion.H.
Referenced by DASpalartAllmarasFv3FieldInversion::calcResiduals(), and DASpalartAllmarasFv3FieldInversion::DASpalartAllmarasFv3FieldInversion().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DATurbulenceModel/DASpalartAllmarasFv3FieldInversion.H
dafoam/src/adjoint/DAModel/DATurbulenceModel/DASpalartAllmarasFv3FieldInversion.C