DAFoam: DAkOmegaSST Class Reference
DAkOmegaSST Class Reference
Public Member Functions
TypeName ("kOmegaSST")
DAkOmegaSST (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DAkOmegaSST ()
virtual void correctModelStates (wordList &modelStates) const
update the turbulence state for DAStateInfo::regStates_
virtual void correctNut ()
update nut based on other turbulence variables and update the BCs
virtual void correctBoundaryConditions ()
update turbulence variable boundary values
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctStateResidualModelCon (List< List< word >> &stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const
add the model residual connectivity to stateCon
virtual void calcResiduals (const dictionary &options)
compute the turbulence residuals
virtual void correct ()
solve the residual equations and update the state
void saveOmegaNearWall ()
save near wall omega values to omegaNearWall_
void setOmegaNearWall ()
set omegaNearWall_ to near wall omega values
void correctOmegaBoundaryConditions ()
specially treatment to correct epsilon BC
Public Member Functions inherited from DATurbulenceModel
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable (autoPtr, DATurbulenceModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DATurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DATurbulenceModel ()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
void correctAlphat ()
update alphat
tmp< volSymmTensorField > devRhoReff () const
dev terms
tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U)
divDev terms
tmp< fvVectorMatrix > divDevReff (volVectorField &U)
divDev terms
tmp< volScalarField > nuEff () const
return effective viscosity
tmp< volScalarField > getNut ()
get the nut field
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
tmp< volScalarField > nu () const
get the nu field
tmp< volScalarField > getAlpha () const
get alpha field
tmp< volScalarField > getRho ()
get the density field
tmp< volScalarField > getPhase ()
get the phase field
scalar getPrt ()
get the turbulent Prandtl number
tmp< Foam::volScalarField > getMu () const
get mu
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void printYPlus () const
print the min max and mean yPlus to screen
label isPrintTime (const Time &runTime, const label printInterval) const
Protected Member Functions
SST functions
tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
tmp< volScalarField > F2 () const
tmp< volScalarField > F3 () const
tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
tmp< volScalarField > DkEff (const volScalarField &F1) const
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
tmp< volScalarField::Internal > epsilonByk (const volScalarField &F1, const volTensorField &gradU) const
tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal &GbyNu0, const volScalarField::Internal &F2, const volScalarField::Internal &S2) const
tmp< fvScalarMatrix > kSource () const
tmp< fvScalarMatrix > omegaSource () const
tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
Protected Attributes
const volScalarField & y_
3D wall distance
scalarList omegaNearWall_
label solveTurbState_ = 0
whether to solve for turb states
label printInterval_
time step interval to print residual
SST parameters
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
Augmented variables for adjoint residuals
volScalarField & omega_
volScalarField omegaRes_
volScalarField omegaResRef_
volScalarField omegaResPartDeriv_
volScalarField omegaRef_
volScalarField & k_
volScalarField kRes_
volScalarField kResRef_
volScalarField kResPartDeriv_
volScalarField kRef_
Protected Attributes inherited from DATurbulenceModel
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const dictionary & allOptions_
all DAFoam options
volScalarField & nut_
turbulence viscosity
volVectorField & U_
velocity
surfaceScalarField & phi_
face flux
volScalarField phase_
phase field
surfaceScalarField & phaseRhoPhi_
phase*phi*density field
IOdictionary turbDict_
turbulence model property dict
dictionary coeffDict_
turbulence model parameters dict
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
dimensionedScalar nuTildaMin_
Lower limit for nuTilda.
scalar Pr_
Prandtl number.
scalar Prt_ = -9999.0
turbulent Prandtl number
Additional Inherited Members
Static Public Member Functions inherited from DATurbulenceModel
static autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Detailed Description
Definition at line 26 of file DAkOmegaSST.H.
Constructor & Destructor Documentation
DAkOmegaSST()
DAkOmegaSST (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 19 of file DAkOmegaSST.C.
References DAOption::getAllOptions(), mesh, DAkOmegaSST::omega_, DAkOmegaSST::omegaNearWall_, and DAkOmegaSST::printInterval_.
~DAkOmegaSST()
virtual ~DAkOmegaSST () inline virtual
Definition at line 180 of file DAkOmegaSST.H.
References DAkOmegaSST::addModelResidualCon(), DAkOmegaSST::calcResiduals(), DAkOmegaSST::correct(), DAkOmegaSST::correctBoundaryConditions(), DAkOmegaSST::correctModelStates(), DAkOmegaSST::correctNut(), DAkOmegaSST::correctOmegaBoundaryConditions(), DAkOmegaSST::correctStateResidualModelCon(), DAkOmegaSST::saveOmegaNearWall(), DAkOmegaSST::setOmegaNearWall(), and DAkOmegaSST::updateIntermediateVariables().
Member Function Documentation
F1()
tmp< volScalarField > F1 (const volScalarField & CDkOmega) const protected
Definition at line 207 of file DAkOmegaSST.C.
References DAkOmegaSST::alphaOmega2_, DAkOmegaSST::betaStar_, DAkOmegaSST::k_, DATurbulenceModel::nu(), DAkOmegaSST::omega_, and DAkOmegaSST::y_.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DomegaEff().
F2()
tmp< volScalarField > F2 () const protected
Definition at line 226 of file DAkOmegaSST.C.
References DAkOmegaSST::betaStar_, DAkOmegaSST::k_, DATurbulenceModel::nu(), DAkOmegaSST::omega_, and DAkOmegaSST::y_.
Referenced by DAkOmegaSST::DomegaEff(), and DAkOmegaSST::F23().
F3()
tmp< volScalarField > F3 () const protected
Definition at line 238 of file DAkOmegaSST.C.
References DATurbulenceModel::nu(), DAkOmegaSST::omega_, and DAkOmegaSST::y_.
Referenced by DAkOmegaSST::F23().
F23()
tmp< volScalarField > F23 () const protected
Definition at line 248 of file DAkOmegaSST.C.
References DAkOmegaSST::F2(), DAkOmegaSST::F3(), and DAkOmegaSST::F3_.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::correctNut().
blend() [1/2]
tmp<volScalarField> blend (const volScalarField & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 61 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::alphaK(), DAkOmegaSST::alphaOmega(), DAkOmegaSST::beta(), and DAkOmegaSST::gamma().
blend() [2/2]
tmp<volScalarField::Internal> blend (const volScalarField::Internal & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 69 of file DAkOmegaSST.H.
alphaK()
tmp<volScalarField> alphaK (const volScalarField & F1) const inline protected
Definition at line 77 of file DAkOmegaSST.H.
References DAkOmegaSST::blend().
Referenced by DAkOmegaSST::DkEff().
alphaOmega()
tmp<volScalarField> alphaOmega (const volScalarField & F1) const inline protected
Definition at line 82 of file DAkOmegaSST.H.
References DAkOmegaSST::blend().
Referenced by DAkOmegaSST::DomegaEff().
beta()
tmp<volScalarField::Internal> beta (const volScalarField::Internal & F1) const inline protected
Definition at line 87 of file DAkOmegaSST.H.
References DAkOmegaSST::blend().
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DomegaEff().
gamma()
tmp<volScalarField::Internal> gamma (const volScalarField::Internal & F1) const inline protected
Definition at line 93 of file DAkOmegaSST.H.
References DAkOmegaSST::blend().
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DomegaEff().
DkEff()
tmp<volScalarField> DkEff (const volScalarField & F1) const inline protected
Definition at line 100 of file DAkOmegaSST.H.
References DAkOmegaSST::alphaK(), DATurbulenceModel::nu(), and DATurbulenceModel::nut_.
Referenced by DAkOmegaSST::calcResiduals().
DomegaEff()
tmp<volScalarField> DomegaEff (const volScalarField & F1) const inline protected
Definition at line 107 of file DAkOmegaSST.H.
References DAkOmegaSST::alphaOmega(), DAkOmegaSST::beta(), DAkOmegaSST::epsilonByk(), DAkOmegaSST::F1(), DAkOmegaSST::F2(), DAkOmegaSST::gamma(), DAkOmegaSST::GbyNu(), DAkOmegaSST::kSource(), DATurbulenceModel::nu(), DATurbulenceModel::nut_, DAkOmegaSST::omegaSource(), DAkOmegaSST::Pk(), and DAkOmegaSST::Qsas().
Referenced by DAkOmegaSST::calcResiduals().
Pk()
tmp< volScalarField::Internal > Pk (const volScalarField::Internal & G) const protected
Definition at line 271 of file DAkOmegaSST.C.
References DAkOmegaSST::betaStar_, DAkOmegaSST::c1_, DAkOmegaSST::k_, and DAkOmegaSST::omega_.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DomegaEff().
epsilonByk()
tmp< volScalarField::Internal > epsilonByk (const volScalarField & F1, const volTensorField & gradU) const protected
Definition at line 277 of file DAkOmegaSST.C.
References DAkOmegaSST::betaStar_, and DAkOmegaSST::omega_.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DomegaEff().
GbyNu()
tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal & GbyNu0, const volScalarField::Internal & F2, const volScalarField::Internal & S2) const protected
Definition at line 260 of file DAkOmegaSST.C.
References DAkOmegaSST::a1_, DAkOmegaSST::b1_, DAkOmegaSST::betaStar_, DAkOmegaSST::c1_, and DAkOmegaSST::omega_.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DomegaEff().
kSource()
tmp< fvScalarMatrix > kSource () const protected
Definition at line 284 of file DAkOmegaSST.C.
References DAkOmegaSST::k_, and rho.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DomegaEff().
omegaSource()
tmp< fvScalarMatrix > omegaSource () const protected
Definition at line 293 of file DAkOmegaSST.C.
References DAkOmegaSST::omega_, and rho.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DomegaEff().
Qsas()
tmp< fvScalarMatrix > Qsas (const volScalarField::Internal & S2, const volScalarField::Internal & gamma, const volScalarField::Internal & beta) const protected
Definition at line 302 of file DAkOmegaSST.C.
References DAkOmegaSST::omega_, and rho.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DomegaEff().
TypeName()
TypeName ("kOmegaSST")
correctModelStates()
void correctModelStates (wordList & modelStates) const virtual
update the turbulence state for DAStateInfo::regStates_
Implements DATurbulenceModel.
Definition at line 315 of file DAkOmegaSST.C.
Referenced by DAkOmegaSST::~DAkOmegaSST().
correctNut()
void correctNut () virtual
update nut based on other turbulence variables and update the BCs
Implements DATurbulenceModel.
Definition at line 351 of file DAkOmegaSST.C.
References DAkOmegaSST::a1_, DAkOmegaSST::b1_, DATurbulenceModel::correctAlphat(), DAkOmegaSST::F23(), DAkOmegaSST::k_, DATurbulenceModel::mesh_, DATurbulenceModel::nut_, DAkOmegaSST::omega_, and U.
Referenced by DAkOmegaSST::calcResiduals(), DAkOmegaSST::updateIntermediateVariables(), and DAkOmegaSST::~DAkOmegaSST().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update turbulence variable boundary values
Implements DATurbulenceModel.
Definition at line 373 of file DAkOmegaSST.C.
References DAkOmegaSST::k_.
Referenced by DAkOmegaSST::~DAkOmegaSST().
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DATurbulenceModel.
Definition at line 462 of file DAkOmegaSST.C.
References DAkOmegaSST::correctNut().
Referenced by DAkOmegaSST::~DAkOmegaSST().
correctStateResidualModelCon()
void correctStateResidualModelCon (List< List< word >> & stateCon) const virtual
update the original variable connectivity for the adjoint state residuals in stateCon
Implements DATurbulenceModel.
Definition at line 473 of file DAkOmegaSST.C.
Referenced by DAkOmegaSST::~DAkOmegaSST().
addModelResidualCon()
void addModelResidualCon (HashTable< List< List< word >>> & allCon) const virtual
add the model residual connectivity to stateCon
Implements DATurbulenceModel.
Definition at line 572 of file DAkOmegaSST.C.
References DATurbulenceModel::mesh_.
Referenced by DAkOmegaSST::~DAkOmegaSST().
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute the turbulence residuals
Implements DATurbulenceModel.
Definition at line 684 of file DAkOmegaSST.C.
References DATurbulenceModel::allOptions_, DAkOmegaSST::alphaOmega2_, DAkOmegaSST::beta(), DAUtility::boundVar(), DAkOmegaSST::correctNut(), DAkOmegaSST::correctOmegaBoundaryConditions(), DAkOmegaSST::DkEff(), DAkOmegaSST::DomegaEff(), DAkOmegaSST::epsilonByk(), DAkOmegaSST::F1(), DAkOmegaSST::F23(), DAkOmegaSST::gamma(), DAkOmegaSST::GbyNu(), DATurbulenceModel::isPrintTime(), DAkOmegaSST::k_, DAkOmegaSST::kRes_, DAkOmegaSST::kSource(), DATurbulenceModel::mesh_, normalizeResiduals, DATurbulenceModel::nut_, DAkOmegaSST::omega_, DAkOmegaSST::omegaRes_, DAkOmegaSST::omegaSource(), DATurbulenceModel::phase_, DATurbulenceModel::phaseRhoPhi_, DATurbulenceModel::phi_, DAkOmegaSST::Pk(), DAkOmegaSST::printInterval_, DAkOmegaSST::Qsas(), DAkOmegaSST::setOmegaNearWall(), DAkOmegaSST::solveTurbState_, and DATurbulenceModel::U_.
Referenced by DAkOmegaSST::correct(), and DAkOmegaSST::~DAkOmegaSST().
correct()
void correct () virtual
solve the residual equations and update the state
Implements DATurbulenceModel.
Definition at line 664 of file DAkOmegaSST.C.
References DAkOmegaSST::calcResiduals(), and DAkOmegaSST::solveTurbState_.
Referenced by DAkOmegaSST::~DAkOmegaSST().
saveOmegaNearWall()
void saveOmegaNearWall ()
save near wall omega values to omegaNearWall_
Definition at line 412 of file DAkOmegaSST.C.
References DATurbulenceModel::mesh_, DAkOmegaSST::omega_, and DAkOmegaSST::omegaNearWall_.
Referenced by DAkOmegaSST::correctOmegaBoundaryConditions(), and DAkOmegaSST::~DAkOmegaSST().
setOmegaNearWall()
void setOmegaNearWall ()
set omegaNearWall_ to near wall omega values
Definition at line 436 of file DAkOmegaSST.C.
References DATurbulenceModel::mesh_, DAkOmegaSST::omega_, and DAkOmegaSST::omegaNearWall_.
Referenced by DAkOmegaSST::calcResiduals(), DAkOmegaSST::correctOmegaBoundaryConditions(), and DAkOmegaSST::~DAkOmegaSST().
correctOmegaBoundaryConditions()
void correctOmegaBoundaryConditions ()
specially treatment to correct epsilon BC
Definition at line 385 of file DAkOmegaSST.C.
References DAkOmegaSST::omega_, DAkOmegaSST::saveOmegaNearWall(), and DAkOmegaSST::setOmegaNearWall().
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::~DAkOmegaSST().
Member Data Documentation
alphaK1_
dimensionedScalar alphaK1_ protected
Definition at line 33 of file DAkOmegaSST.H.
alphaK2_
dimensionedScalar alphaK2_ protected
Definition at line 34 of file DAkOmegaSST.H.
alphaOmega1_
dimensionedScalar alphaOmega1_ protected
Definition at line 36 of file DAkOmegaSST.H.
alphaOmega2_
dimensionedScalar alphaOmega2_ protected
Definition at line 37 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::F1().
gamma1_
dimensionedScalar gamma1_ protected
Definition at line 39 of file DAkOmegaSST.H.
gamma2_
dimensionedScalar gamma2_ protected
Definition at line 40 of file DAkOmegaSST.H.
beta1_
dimensionedScalar beta1_ protected
Definition at line 42 of file DAkOmegaSST.H.
beta2_
dimensionedScalar beta2_ protected
Definition at line 43 of file DAkOmegaSST.H.
betaStar_
dimensionedScalar betaStar_ protected
Definition at line 45 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::epsilonByk(), DAkOmegaSST::F1(), DAkOmegaSST::F2(), DAkOmegaSST::GbyNu(), and DAkOmegaSST::Pk().
a1_
dimensionedScalar a1_ protected
Definition at line 47 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::correctNut(), and DAkOmegaSST::GbyNu().
b1_
dimensionedScalar b1_ protected
Definition at line 48 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::correctNut(), and DAkOmegaSST::GbyNu().
c1_
dimensionedScalar c1_ protected
Definition at line 49 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::GbyNu(), and DAkOmegaSST::Pk().
F3_
Switch F3_ protected
Definition at line 51 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::F23().
omega_
volScalarField& omega_ protected
Definition at line 142 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::calcResiduals(), DAkOmegaSST::correctNut(), DAkOmegaSST::correctOmegaBoundaryConditions(), DAkOmegaSST::DAkOmegaSST(), DAkOmegaSST::epsilonByk(), DAkOmegaSST::F1(), DAkOmegaSST::F2(), DAkOmegaSST::F3(), DAkOmegaSST::GbyNu(), DAkOmegaSST::omegaSource(), DAkOmegaSST::Pk(), DAkOmegaSST::Qsas(), DAkOmegaSST::saveOmegaNearWall(), and DAkOmegaSST::setOmegaNearWall().
omegaRes_
volScalarField omegaRes_ protected
Definition at line 143 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::calcResiduals().
omegaResRef_
volScalarField omegaResRef_ protected
Definition at line 144 of file DAkOmegaSST.H.
omegaResPartDeriv_
volScalarField omegaResPartDeriv_ protected
Definition at line 145 of file DAkOmegaSST.H.
omegaRef_
volScalarField omegaRef_ protected
Definition at line 146 of file DAkOmegaSST.H.
k_
volScalarField& k_ protected
Definition at line 147 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::calcResiduals(), DAkOmegaSST::correctBoundaryConditions(), DAkOmegaSST::correctNut(), DAkOmegaSST::F1(), DAkOmegaSST::F2(), DAkOmegaSST::kSource(), and DAkOmegaSST::Pk().
kRes_
volScalarField kRes_ protected
Definition at line 148 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::calcResiduals().
kResRef_
volScalarField kResRef_ protected
Definition at line 149 of file DAkOmegaSST.H.
kResPartDeriv_
volScalarField kResPartDeriv_ protected
Definition at line 150 of file DAkOmegaSST.H.
kRef_
volScalarField kRef_ protected
Definition at line 151 of file DAkOmegaSST.H.
y_
const volScalarField& y_ protected
3D wall distance
Definition at line 155 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::F1(), DAkOmegaSST::F2(), and DAkOmegaSST::F3().
omegaNearWall_
scalarList omegaNearWall_ protected
cell-center omega values near the wall, this is to fix the issue that the omegaWallFunction will try to modify omega values for the cells near walls this will cause issue for FD-based partial derivatives, so here we basically implement a zeroGradient BC for near wall omega.
Definition at line 161 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::DAkOmegaSST(), DAkOmegaSST::saveOmegaNearWall(), and DAkOmegaSST::setOmegaNearWall().
solveTurbState_
label solveTurbState_ = 0 protected
whether to solve for turb states
Definition at line 164 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::correct().
printInterval_
label printInterval_ protected
time step interval to print residual
Definition at line 167 of file DAkOmegaSST.H.
Referenced by DAkOmegaSST::calcResiduals(), and DAkOmegaSST::DAkOmegaSST().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DATurbulenceModel/DAkOmegaSST.H
dafoam/src/adjoint/DAModel/DATurbulenceModel/DAkOmegaSST.C