DAFoam: DADummyTurbulenceModel Class Reference
DADummyTurbulenceModel Class Reference
Public Member Functions
TypeName ("dummyTurbulenceModel")
DADummyTurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DADummyTurbulenceModel ()
virtual void correctModelStates (wordList &modelStates) const
update the turbulence state for DAStateInfo::regStates_
virtual void correctNut ()
update nut based on other turbulence variables and update the BCs
virtual void correctBoundaryConditions ()
update turbulence variable boundary values
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctStateResidualModelCon (List< List< word >> &stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const
add the model residual connectivity to stateCon
virtual void calcResiduals (const dictionary &options)
compute the turbulence residuals
virtual void correct ()
solve the residual equations and update the state
Public Member Functions inherited from DATurbulenceModel
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable (autoPtr, DATurbulenceModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DATurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DATurbulenceModel ()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
void correctAlphat ()
update alphat
tmp< volSymmTensorField > devRhoReff () const
dev terms
tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U)
divDev terms
tmp< fvVectorMatrix > divDevReff (volVectorField &U)
divDev terms
tmp< volScalarField > nuEff () const
return effective viscosity
tmp< volScalarField > getNut ()
get the nut field
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
tmp< volScalarField > nu () const
get the nu field
tmp< volScalarField > getAlpha () const
get alpha field
tmp< volScalarField > getRho ()
get the density field
tmp< volScalarField > getPhase ()
get the phase field
scalar getPrt ()
get the turbulent Prandtl number
tmp< Foam::volScalarField > getMu () const
get mu
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void printYPlus () const
print the min max and mean yPlus to screen
Additional Inherited Members
Static Public Member Functions inherited from DATurbulenceModel
static autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Protected Attributes inherited from DATurbulenceModel
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const dictionary & allOptions_
all DAFoam options
volScalarField & nut_
turbulence viscosity
volVectorField & U_
velocity
surfaceScalarField & phi_
face flux
volScalarField phase_
phase field
surfaceScalarField & phaseRhoPhi_
phase*phi*density field
IOdictionary turbDict_
turbulence model property dict
dictionary coeffDict_
turbulence model parameters dict
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
dimensionedScalar nuTildaMin_
Lower limit for nuTilda.
scalar Pr_
Prandtl number.
scalar Prt_ = -9999.0
turbulent Prandtl number
Detailed Description
Definition at line 26 of file DADummyTurbulenceModel.H.
Constructor & Destructor Documentation
DADummyTurbulenceModel()
DADummyTurbulenceModel (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 19 of file DADummyTurbulenceModel.C.
~DADummyTurbulenceModel()
virtual ~DADummyTurbulenceModel () inline virtual
Definition at line 43 of file DADummyTurbulenceModel.H.
References DADummyTurbulenceModel::addModelResidualCon(), DADummyTurbulenceModel::calcResiduals(), DADummyTurbulenceModel::correct(), DADummyTurbulenceModel::correctBoundaryConditions(), DADummyTurbulenceModel::correctModelStates(), DADummyTurbulenceModel::correctNut(), DADummyTurbulenceModel::correctStateResidualModelCon(), and DADummyTurbulenceModel::updateIntermediateVariables().
Member Function Documentation
TypeName()
TypeName ("dummyTurbulenceModel")
correctModelStates()
void correctModelStates (wordList & modelStates) const virtual
update the turbulence state for DAStateInfo::regStates_
Implements DATurbulenceModel.
Definition at line 29 of file DADummyTurbulenceModel.C.
Referenced by DADummyTurbulenceModel::~DADummyTurbulenceModel().
correctNut()
void correctNut () virtual
update nut based on other turbulence variables and update the BCs
Implements DATurbulenceModel.
Definition at line 51 of file DADummyTurbulenceModel.C.
Referenced by DADummyTurbulenceModel::~DADummyTurbulenceModel().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update turbulence variable boundary values
Implements DATurbulenceModel.
Definition at line 56 of file DADummyTurbulenceModel.C.
Referenced by DADummyTurbulenceModel::~DADummyTurbulenceModel().
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DATurbulenceModel.
Definition at line 61 of file DADummyTurbulenceModel.C.
Referenced by DADummyTurbulenceModel::~DADummyTurbulenceModel().
correctStateResidualModelCon()
void correctStateResidualModelCon (List< List< word >> & stateCon) const virtual
update the original variable connectivity for the adjoint state residuals in stateCon
Implements DATurbulenceModel.
Definition at line 66 of file DADummyTurbulenceModel.C.
Referenced by DADummyTurbulenceModel::~DADummyTurbulenceModel().
addModelResidualCon()
void addModelResidualCon (HashTable< List< List< word >>> & allCon) const virtual
add the model residual connectivity to stateCon
Implements DATurbulenceModel.
Definition at line 100 of file DADummyTurbulenceModel.C.
Referenced by DADummyTurbulenceModel::~DADummyTurbulenceModel().
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute the turbulence residuals
Implements DATurbulenceModel.
Definition at line 110 of file DADummyTurbulenceModel.C.
Referenced by DADummyTurbulenceModel::~DADummyTurbulenceModel().
correct()
void correct () virtual
solve the residual equations and update the state
Implements DATurbulenceModel.
Definition at line 105 of file DADummyTurbulenceModel.C.
Referenced by DADummyTurbulenceModel::~DADummyTurbulenceModel().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DATurbulenceModel/DADummyTurbulenceModel.H
dafoam/src/adjoint/DAModel/DATurbulenceModel/DADummyTurbulenceModel.C