DAFoam: DAkEpsilon Class Reference
DAkEpsilon Class Reference
Public Member Functions
TypeName ("kEpsilon")
DAkEpsilon (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DAkEpsilon ()
virtual void correctModelStates (wordList &modelStates) const
update the turbulence state for DAStateInfo::regStates_
virtual void correctNut ()
update nut based on other turbulence variables and update the BCs
virtual void correctBoundaryConditions ()
update turbulence variable boundary values
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctStateResidualModelCon (List< List< word >> &stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const
add the model residual connectivity to stateCon
virtual void calcResiduals (const dictionary &options)
compute the turbulence residuals
virtual void correct ()
solve the residual equations and update the state
void saveEpsilonNearWall ()
save near wall epsilon values to epsilonNearWall_
void setEpsilonNearWall ()
set epsilonNearWall_ to near wall epsilon values
void correctEpsilonBoundaryConditions ()
specially treatment to correct epsilon BC
Public Member Functions inherited from DATurbulenceModel
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable (autoPtr, DATurbulenceModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DATurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DATurbulenceModel ()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
void correctAlphat ()
update alphat
tmp< volSymmTensorField > devRhoReff () const
dev terms
tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U)
divDev terms
tmp< fvVectorMatrix > divDevReff (volVectorField &U)
divDev terms
tmp< volScalarField > nuEff () const
return effective viscosity
tmp< volScalarField > getNut ()
get the nut field
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
tmp< volScalarField > nu () const
get the nu field
tmp< volScalarField > getAlpha () const
get alpha field
tmp< volScalarField > getRho ()
get the density field
tmp< volScalarField > getPhase ()
get the phase field
scalar getPrt ()
get the turbulent Prandtl number
tmp< Foam::volScalarField > getMu () const
get mu
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void printYPlus () const
print the min max and mean yPlus to screen
label isPrintTime (const Time &runTime, const label printInterval) const
Protected Member Functions
SST functions
tmp< fvScalarMatrix > kSource () const
tmp< fvScalarMatrix > epsilonSource () const
tmp< volScalarField > DkEff () const
tmp< volScalarField > DepsilonEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
Protected Attributes
scalarList epsilonNearWall_
label solveTurbState_ = 0
whether to solve for turb states
label printInterval_
time step interval to print residual
SST parameters
dimensionedScalar Cmu_
dimensionedScalar C1_
dimensionedScalar C2_
dimensionedScalar C3_
dimensionedScalar sigmak_
dimensionedScalar sigmaEps_
Augmented variables for adjoint residuals
volScalarField & epsilon_
volScalarField epsilonRes_
volScalarField & k_
volScalarField kRes_
Protected Attributes inherited from DATurbulenceModel
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const dictionary & allOptions_
all DAFoam options
volScalarField & nut_
turbulence viscosity
volVectorField & U_
velocity
surfaceScalarField & phi_
face flux
volScalarField phase_
phase field
surfaceScalarField & phaseRhoPhi_
phase*phi*density field
IOdictionary turbDict_
turbulence model property dict
dictionary coeffDict_
turbulence model parameters dict
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
dimensionedScalar nuTildaMin_
Lower limit for nuTilda.
scalar Pr_
Prandtl number.
scalar Prt_ = -9999.0
turbulent Prandtl number
Additional Inherited Members
Static Public Member Functions inherited from DATurbulenceModel
static autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Detailed Description
Definition at line 26 of file DAkEpsilon.H.
Constructor & Destructor Documentation
DAkEpsilon()
DAkEpsilon (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 19 of file DAkEpsilon.C.
References DAkEpsilon::epsilon_, DAkEpsilon::epsilonNearWall_, DAOption::getAllOptions(), mesh, and DAkEpsilon::printInterval_.
~DAkEpsilon()
virtual ~DAkEpsilon () inline virtual
Definition at line 93 of file DAkEpsilon.H.
References DAkEpsilon::addModelResidualCon(), DAkEpsilon::calcResiduals(), DAkEpsilon::correct(), DAkEpsilon::correctBoundaryConditions(), DAkEpsilon::correctEpsilonBoundaryConditions(), DAkEpsilon::correctModelStates(), DAkEpsilon::correctNut(), DAkEpsilon::correctStateResidualModelCon(), DAkEpsilon::saveEpsilonNearWall(), DAkEpsilon::setEpsilonNearWall(), and DAkEpsilon::updateIntermediateVariables().
Member Function Documentation
kSource()
tmp< fvScalarMatrix > kSource () const protected
Definition at line 130 of file DAkEpsilon.C.
References DAkEpsilon::k_.
Referenced by DAkEpsilon::calcResiduals().
epsilonSource()
tmp< fvScalarMatrix > epsilonSource () const protected
Definition at line 139 of file DAkEpsilon.C.
References DAkEpsilon::epsilon_.
Referenced by DAkEpsilon::calcResiduals().
DkEff()
tmp< volScalarField > DkEff () const protected
Definition at line 148 of file DAkEpsilon.C.
References DATurbulenceModel::nu(), DATurbulenceModel::nut_, and DAkEpsilon::sigmak_.
Referenced by DAkEpsilon::calcResiduals().
DepsilonEff()
tmp< volScalarField > DepsilonEff () const protected
Definition at line 156 of file DAkEpsilon.C.
References DATurbulenceModel::nu(), DATurbulenceModel::nut_, and DAkEpsilon::sigmaEps_.
Referenced by DAkEpsilon::calcResiduals().
k()
virtual tmp<volScalarField> k () const inline protected virtual
Definition at line 50 of file DAkEpsilon.H.
References DAkEpsilon::k_.
epsilon()
virtual tmp<volScalarField> epsilon () const inline protected virtual
Definition at line 56 of file DAkEpsilon.H.
References DAkEpsilon::epsilon_.
TypeName()
TypeName ("kEpsilon")
correctModelStates()
void correctModelStates (wordList & modelStates) const virtual
update the turbulence state for DAStateInfo::regStates_
Implements DATurbulenceModel.
Definition at line 165 of file DAkEpsilon.C.
Referenced by DAkEpsilon::~DAkEpsilon().
correctNut()
void correctNut () virtual
update nut based on other turbulence variables and update the BCs
Implements DATurbulenceModel.
Definition at line 201 of file DAkEpsilon.C.
References DAkEpsilon::Cmu_, DATurbulenceModel::correctAlphat(), DAkEpsilon::epsilon_, DAkEpsilon::k_, and DATurbulenceModel::nut_.
Referenced by DAkEpsilon::calcResiduals(), DAkEpsilon::updateIntermediateVariables(), and DAkEpsilon::~DAkEpsilon().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update turbulence variable boundary values
Implements DATurbulenceModel.
Definition at line 219 of file DAkEpsilon.C.
References DAkEpsilon::k_.
Referenced by DAkEpsilon::~DAkEpsilon().
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DATurbulenceModel.
Definition at line 308 of file DAkEpsilon.C.
References DAkEpsilon::correctNut().
Referenced by DAkEpsilon::~DAkEpsilon().
correctStateResidualModelCon()
void correctStateResidualModelCon (List< List< word >> & stateCon) const virtual
update the original variable connectivity for the adjoint state residuals in stateCon
Implements DATurbulenceModel.
Definition at line 319 of file DAkEpsilon.C.
Referenced by DAkEpsilon::~DAkEpsilon().
addModelResidualCon()
void addModelResidualCon (HashTable< List< List< word >>> & allCon) const virtual
add the model residual connectivity to stateCon
Implements DATurbulenceModel.
Definition at line 370 of file DAkEpsilon.C.
References DATurbulenceModel::mesh_.
Referenced by DAkEpsilon::~DAkEpsilon().
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute the turbulence residuals
Implements DATurbulenceModel.
Definition at line 482 of file DAkEpsilon.C.
References DATurbulenceModel::allOptions_, DAUtility::boundVar(), DAkEpsilon::C1_, DAkEpsilon::C2_, DAkEpsilon::C3_, DAkEpsilon::correctEpsilonBoundaryConditions(), DAkEpsilon::correctNut(), DAkEpsilon::DepsilonEff(), DAkEpsilon::DkEff(), DAkEpsilon::epsilon_, DAkEpsilon::epsilonRes_, DAkEpsilon::epsilonSource(), DATurbulenceModel::isPrintTime(), DAkEpsilon::k_, DAkEpsilon::kRes_, DAkEpsilon::kSource(), DATurbulenceModel::mesh_, normalizeResiduals, DATurbulenceModel::nut_, DATurbulenceModel::phase_, DATurbulenceModel::phaseRhoPhi_, DATurbulenceModel::phi_, DAkEpsilon::printInterval_, DAkEpsilon::setEpsilonNearWall(), DAkEpsilon::solveTurbState_, and DATurbulenceModel::U_.
Referenced by DAkEpsilon::correct(), and DAkEpsilon::~DAkEpsilon().
correct()
void correct () virtual
solve the residual equations and update the state
Implements DATurbulenceModel.
Definition at line 462 of file DAkEpsilon.C.
References DAkEpsilon::calcResiduals(), and DAkEpsilon::solveTurbState_.
Referenced by DAkEpsilon::~DAkEpsilon().
saveEpsilonNearWall()
void saveEpsilonNearWall ()
save near wall epsilon values to epsilonNearWall_
Definition at line 258 of file DAkEpsilon.C.
References DAkEpsilon::epsilon_, DAkEpsilon::epsilonNearWall_, and DATurbulenceModel::mesh_.
Referenced by DAkEpsilon::correctEpsilonBoundaryConditions(), and DAkEpsilon::~DAkEpsilon().
setEpsilonNearWall()
void setEpsilonNearWall ()
set epsilonNearWall_ to near wall epsilon values
Definition at line 282 of file DAkEpsilon.C.
References DAkEpsilon::epsilon_, DAkEpsilon::epsilonNearWall_, and DATurbulenceModel::mesh_.
Referenced by DAkEpsilon::calcResiduals(), DAkEpsilon::correctEpsilonBoundaryConditions(), and DAkEpsilon::~DAkEpsilon().
correctEpsilonBoundaryConditions()
void correctEpsilonBoundaryConditions ()
specially treatment to correct epsilon BC
Definition at line 231 of file DAkEpsilon.C.
References DAkEpsilon::epsilon_, DAkEpsilon::saveEpsilonNearWall(), and DAkEpsilon::setEpsilonNearWall().
Referenced by DAkEpsilon::calcResiduals(), and DAkEpsilon::~DAkEpsilon().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 33 of file DAkEpsilon.H.
Referenced by DAkEpsilon::correctNut().
C1_
dimensionedScalar C1_ protected
Definition at line 34 of file DAkEpsilon.H.
Referenced by DAkEpsilon::calcResiduals().
C2_
dimensionedScalar C2_ protected
Definition at line 35 of file DAkEpsilon.H.
Referenced by DAkEpsilon::calcResiduals().
C3_
dimensionedScalar C3_ protected
Definition at line 36 of file DAkEpsilon.H.
Referenced by DAkEpsilon::calcResiduals().
sigmak_
dimensionedScalar sigmak_ protected
Definition at line 37 of file DAkEpsilon.H.
Referenced by DAkEpsilon::DkEff().
sigmaEps_
dimensionedScalar sigmaEps_ protected
Definition at line 38 of file DAkEpsilon.H.
Referenced by DAkEpsilon::DepsilonEff().
epsilon_
volScalarField& epsilon_ protected
Definition at line 64 of file DAkEpsilon.H.
Referenced by DAkEpsilon::calcResiduals(), DAkEpsilon::correctEpsilonBoundaryConditions(), DAkEpsilon::correctNut(), DAkEpsilon::DAkEpsilon(), DAkEpsilon::epsilon(), DAkEpsilon::epsilonSource(), DAkEpsilon::saveEpsilonNearWall(), and DAkEpsilon::setEpsilonNearWall().
epsilonRes_
volScalarField epsilonRes_ protected
Definition at line 65 of file DAkEpsilon.H.
Referenced by DAkEpsilon::calcResiduals().
k_
volScalarField& k_ protected
Definition at line 66 of file DAkEpsilon.H.
Referenced by DAkEpsilon::calcResiduals(), DAkEpsilon::correctBoundaryConditions(), DAkEpsilon::correctNut(), DAkEpsilon::k(), and DAkEpsilon::kSource().
kRes_
volScalarField kRes_ protected
Definition at line 67 of file DAkEpsilon.H.
Referenced by DAkEpsilon::calcResiduals().
epsilonNearWall_
scalarList epsilonNearWall_ protected
cell-center epsilon values near the wall, this is to fix the issue that the epsilonWallFunction will try to modify epsilon values for the cells near walls this will cause issue for FD-based partial derivatives, so here we basically implement a zeroGradient BC for near wall epsilon.
Definition at line 74 of file DAkEpsilon.H.
Referenced by DAkEpsilon::DAkEpsilon(), DAkEpsilon::saveEpsilonNearWall(), and DAkEpsilon::setEpsilonNearWall().
solveTurbState_
label solveTurbState_ = 0 protected
whether to solve for turb states
Definition at line 77 of file DAkEpsilon.H.
Referenced by DAkEpsilon::calcResiduals(), and DAkEpsilon::correct().
printInterval_
label printInterval_ protected
time step interval to print residual
Definition at line 80 of file DAkEpsilon.H.
Referenced by DAkEpsilon::calcResiduals(), and DAkEpsilon::DAkEpsilon().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DATurbulenceModel/DAkEpsilon.H
dafoam/src/adjoint/DAModel/DATurbulenceModel/DAkEpsilon.C