DAFoam: multiFreqVectorFvPatchField Class Reference
multiFreqVectorFvPatchField Class Reference
Public Member Functions
TypeName ("multiFreqVector")
multiFreqVectorFvPatchField (const fvPatch &, const DimensionedField< vector, volMesh > &)
multiFreqVectorFvPatchField (const fvPatch &, const DimensionedField< vector, volMesh > &, const dictionary &)
multiFreqVectorFvPatchField (const multiFreqVectorFvPatchField &, const fvPatch &, const DimensionedField< vector, volMesh > &, const fvPatchFieldMapper &)
multiFreqVectorFvPatchField (const multiFreqVectorFvPatchField &)
virtual tmp< fvPatchVectorField > clone () const
multiFreqVectorFvPatchField (const multiFreqVectorFvPatchField &, const DimensionedField< vector, volMesh > &)
virtual tmp< fvPatchVectorField > clone (const DimensionedField< vector, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
vector & refValue ()
Detailed Description
Definition at line 63 of file multiFreqVectorFvPatchField.H.
Constructor & Destructor Documentation
multiFreqVectorFvPatchField() [1/5]
multiFreqVectorFvPatchField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF)
Definition at line 14 of file multiFreqVectorFvPatchField.C.
Referenced by multiFreqVectorFvPatchField::clone().
multiFreqVectorFvPatchField() [2/5]
multiFreqVectorFvPatchField (const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const dictionary & dict)
Definition at line 27 of file multiFreqVectorFvPatchField.C.
References p.
multiFreqVectorFvPatchField() [3/5]
multiFreqVectorFvPatchField (const multiFreqVectorFvPatchField & ptf, const fvPatch & p, const DimensionedField< vector, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 50 of file multiFreqVectorFvPatchField.C.
multiFreqVectorFvPatchField() [4/5]
multiFreqVectorFvPatchField (const multiFreqVectorFvPatchField & wbppsf)
Definition at line 66 of file multiFreqVectorFvPatchField.C.
multiFreqVectorFvPatchField() [5/5]
multiFreqVectorFvPatchField (const multiFreqVectorFvPatchField & wbppsf, const DimensionedField< vector, volMesh > & iF)
Definition at line 79 of file multiFreqVectorFvPatchField.C.
Member Function Documentation
TypeName()
TypeName ("multiFreqVector")
clone() [1/2]
virtual tmp<fvPatchVectorField> clone () const inline virtual
Definition at line 105 of file multiFreqVectorFvPatchField.H.
References multiFreqVectorFvPatchField::multiFreqVectorFvPatchField().
clone() [2/2]
virtual tmp<fvPatchVectorField> clone (const DimensionedField< vector, volMesh > & iF) const inline virtual
Definition at line 117 of file multiFreqVectorFvPatchField.H.
References multiFreqVectorFvPatchField::multiFreqVectorFvPatchField(), multiFreqVectorFvPatchField::updateCoeffs(), and multiFreqVectorFvPatchField::write().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 94 of file multiFreqVectorFvPatchField.C.
References p.
Referenced by multiFreqVectorFvPatchField::clone().
write()
void write (Ostream & os) const virtual
Definition at line 122 of file multiFreqVectorFvPatchField.C.
References Foam::makePatchTypeField().
Referenced by multiFreqVectorFvPatchField::clone().
refValue()
vector& refValue () inline
Definition at line 133 of file multiFreqVectorFvPatchField.H.
The documentation for this class was generated from the following files:
dafoam/src/adjoint/boundaryConditions/multiFreqVector/multiFreqVectorFvPatchField.H
dafoam/src/adjoint/boundaryConditions/multiFreqVector/multiFreqVectorFvPatchField.C