DAFoam: DAStateInfoSimpleFoam Class Reference
DAStateInfoSimpleFoam Class Reference
Public Member Functions
TypeName ("DASimpleFoam")
DAStateInfoSimpleFoam (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel)
virtual ~DAStateInfoSimpleFoam ()
Public Member Functions inherited from DAStateInfo
TypeName ("DAStateInfo")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAStateInfo, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel),(modelType, mesh, daOption, daModel))
DAStateInfo (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel)
virtual ~DAStateInfo ()
const HashTable< wordList > & getStateInfo () const
return the reference of stateInfo_
const HashTable< List< List< word > > > & getStateResConInfo () const
return the reference of stateResConInfo_
Additional Inherited Members
Static Public Member Functions inherited from DAStateInfo
static autoPtr< DAStateInfo > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel)
Protected Attributes inherited from DAStateInfo
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
HashTable< wordList > stateInfo_
registered states 1st hash: solverName, 2nd hash: fieldType, 3nd list, stateNames
HashTable< List< List< word > > > stateResConInfo_
table to specify how the states are connected to the residuals for a given solver
Detailed Description
Definition at line 26 of file DAStateInfoSimpleFoam.H.
Constructor & Destructor Documentation
DAStateInfoSimpleFoam()
DAStateInfoSimpleFoam (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel)
Definition at line 19 of file DAStateInfoSimpleFoam.C.
References DAModel::addModelResidualCon(), DAModel::correctModelStates(), DAModel::correctStateResidualModelCon(), DAStateInfo::stateInfo_, and DAStateInfo::stateResConInfo_.
~DAStateInfoSimpleFoam()
virtual ~DAStateInfoSimpleFoam () inline virtual
Definition at line 42 of file DAStateInfoSimpleFoam.H.
Member Function Documentation
TypeName()
TypeName ("DASimpleFoam")
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAStateInfo/DAStateInfoSimpleFoam.H
dafoam/src/adjoint/DAStateInfo/DAStateInfoSimpleFoam.C