DAFoam: DAResidualSimpleTFoam Class Reference
DAResidualSimpleTFoam Class Reference
Public Member Functions
TypeName ("DASimpleTFoam")
DAResidualSimpleTFoam (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAResidualSimpleTFoam ()
virtual void clear ()
clear the members
virtual void calcResiduals (const dictionary &options)
compute residual
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctBoundaryConditions ()
update the boundary condition for all the states in the selected solver
Public Member Functions inherited from DAResidual
TypeName ("DAResidual")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAResidual, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAResidual (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAResidual ()
void masterFunction (const dictionary &options, const Vec xvVec, const Vec wVec, Vec resVec)
the master function that compute the residual vector given the state and point vectors
Protected Attributes
volScalarField & alphat_
scalar Pr_ = -9999.0
scalar Prt_ = -9999.0
DATurbulenceModel & daTurb_
DATurbulenceModel object.
simpleControl simple_
simpleControl object which will be initialized in this class
These are state variables, state residuals, and partial derivatives
volVectorField & U_
volVectorField URes_
volVectorField UResPartDeriv_
volScalarField & p_
volScalarField pRes_
volScalarField pResPartDeriv_
volScalarField & T_
volScalarField TRes_
volScalarField TResPartDeriv_
surfaceScalarField & phi_
surfaceScalarField phiRes_
surfaceScalarField phiResPartDeriv_
Protected Attributes inherited from DAResidual
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex.
DAField daField_
DAField object.
Additional Inherited Members
Static Public Member Functions inherited from DAResidual
static autoPtr< DAResidual > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Detailed Description
Definition at line 28 of file DAResidualSimpleTFoam.H.
Constructor & Destructor Documentation
DAResidualSimpleTFoam()
DAResidualSimpleTFoam (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 19 of file DAResidualSimpleTFoam.C.
References mesh, DAResidualSimpleTFoam::Pr_, and DAResidualSimpleTFoam::Prt_.
~DAResidualSimpleTFoam()
virtual ~DAResidualSimpleTFoam () inline virtual
Definition at line 76 of file DAResidualSimpleTFoam.H.
References DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleTFoam::clear(), DAResidualSimpleTFoam::correctBoundaryConditions(), and DAResidualSimpleTFoam::updateIntermediateVariables().
Member Function Documentation
TypeName()
TypeName ("DASimpleTFoam")
clear()
void clear () virtual
clear the members
Implements DAResidual.
Definition at line 52 of file DAResidualSimpleTFoam.C.
References DAResidualSimpleTFoam::phiRes_, DAResidualSimpleTFoam::phiResPartDeriv_, DAResidualSimpleTFoam::pRes_, DAResidualSimpleTFoam::pResPartDeriv_, DAResidualSimpleTFoam::TRes_, DAResidualSimpleTFoam::TResPartDeriv_, DAResidualSimpleTFoam::URes_, and DAResidualSimpleTFoam::UResPartDeriv_.
Referenced by DAResidualSimpleTFoam::~DAResidualSimpleTFoam().
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute residual
Implements DAResidual.
Definition at line 70 of file DAResidualSimpleTFoam.C.
References adjustPhi(), alphaEff(), DAResidualSimpleTFoam::alphat_, DAResidualSimpleTFoam::daTurb_, DATurbulenceModel::divDevReff(), HbyA, DAResidual::mesh_, normalizePhiResiduals, normalizeResiduals, DATurbulenceModel::nu(), DAResidualSimpleTFoam::p_, DAResidualSimpleTFoam::phi_, phiHbyA, DAResidualSimpleTFoam::phiRes_, DAResidualSimpleTFoam::Pr_, pRefCell, pRefValue, DAResidualSimpleTFoam::pRes_, rAtU(), rAU(), DAResidualSimpleTFoam::simple_, DAResidualSimpleTFoam::T_, TEqn(), DAResidualSimpleTFoam::TRes_, tUEqn(), DAResidualSimpleTFoam::U_, UEqn, and DAResidualSimpleTFoam::URes_.
Referenced by DAResidualSimpleTFoam::~DAResidualSimpleTFoam().
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DAResidual.
Definition at line 169 of file DAResidualSimpleTFoam.C.
References DAResidualSimpleTFoam::alphat_, DAResidualSimpleTFoam::daTurb_, DATurbulenceModel::getNut(), and DAResidualSimpleTFoam::Prt_.
Referenced by DAResidualSimpleTFoam::~DAResidualSimpleTFoam().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update the boundary condition for all the states in the selected solver
Implements DAResidual.
Definition at line 180 of file DAResidualSimpleTFoam.C.
References DAResidualSimpleTFoam::p_, DAResidualSimpleTFoam::T_, and DAResidualSimpleTFoam::U_.
Referenced by DAResidualSimpleTFoam::~DAResidualSimpleTFoam().
Member Data Documentation
U_
volVectorField& U_ protected
Definition at line 34 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::correctBoundaryConditions().
URes_
volVectorField URes_ protected
Definition at line 35 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::clear().
UResPartDeriv_
volVectorField UResPartDeriv_ protected
Definition at line 36 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::clear().
p_
volScalarField& p_ protected
Definition at line 38 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::correctBoundaryConditions().
pRes_
volScalarField pRes_ protected
Definition at line 39 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::clear().
pResPartDeriv_
volScalarField pResPartDeriv_ protected
Definition at line 40 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::clear().
T_
volScalarField& T_ protected
Definition at line 42 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::correctBoundaryConditions().
TRes_
volScalarField TRes_ protected
Definition at line 43 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::clear().
TResPartDeriv_
volScalarField TResPartDeriv_ protected
Definition at line 44 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::clear().
phi_
surfaceScalarField& phi_ protected
Definition at line 46 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals().
phiRes_
surfaceScalarField phiRes_ protected
Definition at line 47 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::clear().
phiResPartDeriv_
surfaceScalarField phiResPartDeriv_ protected
Definition at line 48 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::clear().
alphat_
volScalarField& alphat_ protected
Definition at line 51 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::updateIntermediateVariables().
Pr_
scalar Pr_ = -9999.0 protected
Definition at line 53 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::DAResidualSimpleTFoam().
Prt_
scalar Prt_ = -9999.0 protected
Definition at line 55 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::DAResidualSimpleTFoam(), and DAResidualSimpleTFoam::updateIntermediateVariables().
daTurb_
DATurbulenceModel& daTurb_ protected
DATurbulenceModel object.
Definition at line 58 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals(), and DAResidualSimpleTFoam::updateIntermediateVariables().
simple_
simpleControl simple_ protected
simpleControl object which will be initialized in this class
Definition at line 61 of file DAResidualSimpleTFoam.H.
Referenced by DAResidualSimpleTFoam::calcResiduals().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAResidual/DAResidualSimpleTFoam.H
dafoam/src/adjoint/DAResidual/DAResidualSimpleTFoam.C