DAFoam: pimpleControlDF Class Reference
pimpleControlDF Class Reference
Public Member Functions
TypeName ("pimpleControlDF")
pimpleControlDF (fvMesh &mesh, const word &dictName="PIMPLE")
virtual ~pimpleControlDF ()=default
label nCorrPIMPLE () const
label nCorrPISO () const
label corrPISO () const
bool SIMPLErho () const
virtual bool loop ()
bool correct ()
bool storeInitialResiduals () const
bool firstIter () const
bool finalIter () const
bool finalInnerIter () const
bool solveFlow () const
bool turbCorr ()
Protected Member Functions
virtual void read ()
virtual bool criteriaSatisfied ()
virtual void setFirstIterFlag (const bool check=true, const bool force=false)
Protected Attributes
bool solveFlow_
label nCorrPIMPLE_
label nCorrPISO_
label corrPISO_
bool SIMPLErho_
bool turbOnFinalIterOnly_
bool converged_
Detailed Description
Definition at line 29 of file pimpleControlDF.H.
Constructor & Destructor Documentation
pimpleControlDF()
pimpleControlDF (fvMesh & mesh, const word & dictName = "PIMPLE")
Definition at line 114 of file pimpleControlDF.C.
References pimpleControlDF::nCorrPIMPLE_, and pimpleControlDF::read().
~pimpleControlDF()
virtual ~pimpleControlDF () virtual default
Member Function Documentation
read()
void read () protected virtual
Definition at line 19 of file pimpleControlDF.C.
Referenced by pimpleControlDF::loop(), and pimpleControlDF::pimpleControlDF().
criteriaSatisfied()
bool criteriaSatisfied () protected virtual
Definition at line 33 of file pimpleControlDF.C.
Referenced by pimpleControlDF::loop().
setFirstIterFlag()
void setFirstIterFlag (const bool check = true, const bool force = false) protected virtual
Definition at line 101 of file pimpleControlDF.C.
Referenced by pimpleControlDF::correct(), pimpleControlDF::loop(), and pimpleControlDF::turbCorr().
TypeName()
TypeName ("pimpleControlDF")
nCorrPIMPLE()
Foam::label nCorrPIMPLE () const inline
Definition at line 10 of file pimpleControlIDF.H.
References pimpleControlDF::nCorrPIMPLE_.
nCorrPISO()
Foam::label nCorrPISO () const inline
Definition at line 15 of file pimpleControlIDF.H.
References pimpleControlDF::nCorrPISO_.
corrPISO()
Foam::label corrPISO () const inline
Definition at line 20 of file pimpleControlIDF.H.
References pimpleControlDF::corrPISO_.
SIMPLErho()
bool SIMPLErho () const inline
Definition at line 25 of file pimpleControlIDF.H.
References pimpleControlDF::SIMPLErho_.
loop()
bool loop () virtual
Definition at line 160 of file pimpleControlDF.C.
References pimpleControlDF::converged_, pimpleControlDF::criteriaSatisfied(), pimpleControlDF::finalIter(), pimpleControlDF::nCorrPIMPLE_, pimpleControlDF::read(), and pimpleControlDF::setFirstIterFlag().
correct()
bool correct () inline
Definition at line 30 of file pimpleControlIDF.H.
References pimpleControlDF::corrPISO_, pimpleControlDF::nCorrPISO_, and pimpleControlDF::setFirstIterFlag().
storeInitialResiduals()
bool storeInitialResiduals () const inline
Definition at line 53 of file pimpleControlIDF.H.
References pimpleControlDF::corrPISO_.
firstIter()
bool firstIter () const inline
Definition at line 59 of file pimpleControlIDF.H.
Referenced by pimpleControlDF::turbCorr().
finalIter()
bool finalIter () const inline
Definition at line 64 of file pimpleControlIDF.H.
References pimpleControlDF::converged_, and pimpleControlDF::nCorrPIMPLE_.
Referenced by pimpleControlDF::loop(), and pimpleControlDF::turbCorr().
finalInnerIter()
bool finalInnerIter () const inline
Definition at line 69 of file pimpleControlIDF.H.
References pimpleControlDF::corrPISO_, and pimpleControlDF::nCorrPISO_.
solveFlow()
bool solveFlow () const inline
Definition at line 75 of file pimpleControlIDF.H.
References pimpleControlDF::solveFlow_.
turbCorr()
bool turbCorr () inline
Definition at line 80 of file pimpleControlIDF.H.
References pimpleControlDF::finalIter(), pimpleControlDF::firstIter(), pimpleControlDF::setFirstIterFlag(), and pimpleControlDF::turbOnFinalIterOnly_.
Member Data Documentation
solveFlow_
bool solveFlow_ protected
Definition at line 46 of file pimpleControlDF.H.
Referenced by pimpleControlDF::solveFlow().
nCorrPIMPLE_
label nCorrPIMPLE_ protected
Definition at line 49 of file pimpleControlDF.H.
Referenced by pimpleControlDF::finalIter(), pimpleControlDF::loop(), pimpleControlDF::nCorrPIMPLE(), and pimpleControlDF::pimpleControlDF().
nCorrPISO_
label nCorrPISO_ protected
Definition at line 52 of file pimpleControlDF.H.
Referenced by pimpleControlDF::correct(), pimpleControlDF::finalInnerIter(), and pimpleControlDF::nCorrPISO().
corrPISO_
label corrPISO_ protected
Definition at line 55 of file pimpleControlDF.H.
Referenced by pimpleControlDF::correct(), pimpleControlDF::corrPISO(), pimpleControlDF::finalInnerIter(), and pimpleControlDF::storeInitialResiduals().
SIMPLErho_
bool SIMPLErho_ protected
Definition at line 59 of file pimpleControlDF.H.
Referenced by pimpleControlDF::SIMPLErho().
turbOnFinalIterOnly_
bool turbOnFinalIterOnly_ protected
Definition at line 62 of file pimpleControlDF.H.
Referenced by pimpleControlDF::turbCorr().
converged_
bool converged_ protected
Definition at line 65 of file pimpleControlDF.H.
Referenced by pimpleControlDF::finalIter(), and pimpleControlDF::loop().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/models/pimpleControlDF/pimpleControlDF.H
dafoam/src/adjoint/models/pimpleControlDF/pimpleControlDF.C
dafoam/src/adjoint/models/pimpleControlDF/pimpleControlIDF.H