DAFoam: DAPartDerivdRdW Class Reference
DAPartDerivdRdW Class Reference
Public Member Functions
TypeName ("dRdW")
DAPartDerivdRdW (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAJacCon &daJacCon, const DAResidual &daResidual)
virtual ~DAPartDerivdRdW ()
virtual void initializePartDerivMat (const dictionary &options, Mat *jacMat)
initialize partial derivative matrix
virtual void calcPartDerivMat (const dictionary &options, const Vec xvVec, const Vec wVec, Mat jacMat)
compute the partial derivative matrix
Public Member Functions inherited from DAPartDeriv
TypeName ("DAPartDeriv")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAPartDeriv, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAJacCon &daJacCon, const DAResidual &daResidual),(modelType, mesh, daOption, daModel, daIndex, daJacCon, daResidual))
DAPartDeriv (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAJacCon &daJacCon, const DAResidual &daResidual)
virtual ~DAPartDeriv ()
void clear ()
clear members in parent and child objects
void setdXvdFFDMat (const Mat dXvdFFDMat)
setup dXvdFFD matrix
void setNormStatePerturbVec (Vec *normStatePerturbVec)
setup the state normalization vector
Additional Inherited Members
Static Public Member Functions inherited from DAPartDeriv
static autoPtr< DAPartDeriv > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAJacCon &daJacCon, const DAResidual &daResidual)
Protected Member Functions inherited from DAPartDeriv
void perturbStates (const Vec jacConColors, const Vec normStatePerturbVec, const label colorI, const scalar delta, Vec wVec)
perturb state variables given a color index
void perturbBC (const dictionary options, const scalar delta)
perturb the values in the boundary condition
void setPartDerivMat (const Vec resVec, const Vec coloredColumn, const label transposed, Mat jacMat, const scalar jacLowerBound=1e-30) const
set values for the partial derivative matrix
void perturbAOA (const dictionary options, const scalar delta)
perturb the angle of attack
Protected Attributes inherited from DAPartDeriv
const word modelType_
the name of the jacCon matrix
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
const DAJacCon & daJacCon_
DAJacCon object.
const DAResidual & daResidual_
DAResidual object.
const dictionary & allOptions_
all the DAFoam option
HashTable< wordList > stateInfo_
the stateInfo_ list from DAStateInfo object
Mat dXvdFFDMat_
volume mesh coordinates wrt the ffd point coordinate partials
Detailed Description
Definition at line 26 of file DAPartDerivdRdW.H.
Constructor & Destructor Documentation
DAPartDerivdRdW()
DAPartDerivdRdW (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex, const DAJacCon & daJacCon, const DAResidual & daResidual)
Definition at line 19 of file DAPartDerivdRdW.C.
~DAPartDerivdRdW()
virtual ~DAPartDerivdRdW () inline virtual
Definition at line 46 of file DAPartDerivdRdW.H.
References DAPartDerivdRdW::calcPartDerivMat(), and DAPartDerivdRdW::initializePartDerivMat().
Member Function Documentation
TypeName()
TypeName ("dRdW")
initializePartDerivMat()
void initializePartDerivMat (const dictionary & options, Mat * jacMat) virtual
initialize partial derivative matrix
Implements DAPartDeriv.
Definition at line 40 of file DAPartDerivdRdW.C.
References DAPartDeriv::daIndex_, DAPartDeriv::daJacCon_, DAPartDeriv::mesh_, DAIndex::nLocalAdjointStates, and DAJacCon::preallocatedRdW().
Referenced by DAPartDerivdRdW::~DAPartDerivdRdW().
calcPartDerivMat()
void calcPartDerivMat (const dictionary & options, const Vec xvVec, const Vec wVec, Mat jacMat) virtual
compute the partial derivative matrix
Implements DAPartDeriv.
Definition at line 73 of file DAPartDerivdRdW.C.
References DAJacCon::calcColoredColumns(), DAPartDeriv::daIndex_, DAPartDeriv::daJacCon_, DAPartDeriv::daOption_, DAPartDeriv::daResidual_, DAJacCon::getJacConColor(), DAJacCon::getNJacConColors(), DAOption::getOption(), DAOption::getSubDictOption(), DAResidual::masterFunction(), DAPartDeriv::mesh_, DAPartDeriv::modelType_, DAPartDeriv::perturbStates(), DAIndex::printMatChars(), DAPartDeriv::setNormStatePerturbVec(), and DAPartDeriv::setPartDerivMat().
Referenced by DAPartDerivdRdW::~DAPartDerivdRdW().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAPartDeriv/DAPartDerivdRdW.H
dafoam/src/adjoint/DAPartDeriv/DAPartDerivdRdW.C