DAFoam: SpalartAllmarasFv3< BasicTurbulenceModel > Class Template Reference
SpalartAllmarasFv3< BasicTurbulenceModel > Class Template Reference
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SpalartAllmarasFv3")
SpalartAllmarasFv3 (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~SpalartAllmarasFv3 ()
virtual bool read ()
tmp< volScalarField > DnuTildaEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
void boundVar (volScalarField &var)
bound the turbulence vars
TypeName ("SpalartAllmarasFv3")
SpalartAllmarasFv3 (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~SpalartAllmarasFv3 ()
virtual bool read ()
tmp< volScalarField > DnuTildaEff () const
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
void boundVar (volScalarField &var)
bound the turbulence vars
Protected Member Functions
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fv3 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fw (const volScalarField &Stilda) const
void correctNut (const volScalarField &fv1)
virtual void correctNut ()
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fv3 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fw (const volScalarField &Stilda) const
void correctNut (const volScalarField &fv1)
virtual void correctNut ()
Protected Attributes
dimensionedScalar sigmaNut_
dimensionedScalar kappa_
dimensionedScalar Cb1_
dimensionedScalar Cb2_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar Cv1_
dimensionedScalar Cv2_
dimensionedScalar nuTildaMin_
volScalarField nuTilda_
const volScalarField & y_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::SpalartAllmarasFv3< BasicTurbulenceModel >
Definition at line 30 of file SpalartAllmarasFv3.H.
Member Typedef Documentation
alphaField [1/2]
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 85 of file SpalartAllmarasFv3.H.
rhoField [1/2]
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 86 of file SpalartAllmarasFv3.H.
transportModel [1/2]
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 87 of file SpalartAllmarasFv3.H.
alphaField [2/2]
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 85 of file SpalartAllmarasFv3.H.
rhoField [2/2]
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 86 of file SpalartAllmarasFv3.H.
transportModel [2/2]
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 87 of file SpalartAllmarasFv3.H.
Constructor & Destructor Documentation
SpalartAllmarasFv3() [1/2]
SpalartAllmarasFv3 (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 97 of file SpalartAllmarasFv3.C.
~SpalartAllmarasFv3() [1/2]
virtual ~SpalartAllmarasFv3 () inline virtual
Definition at line 106 of file SpalartAllmarasFv3.H.
References SpalartAllmarasFv3< BasicTurbulenceModel >::boundVar(), SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), SpalartAllmarasFv3< BasicTurbulenceModel >::DnuTildaEff(), SpalartAllmarasFv3< BasicTurbulenceModel >::epsilon(), SpalartAllmarasFv3< BasicTurbulenceModel >::k(), and SpalartAllmarasFv3< BasicTurbulenceModel >::read().
SpalartAllmarasFv3() [2/2]
SpalartAllmarasFv3 (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
~SpalartAllmarasFv3() [2/2]
virtual ~SpalartAllmarasFv3 () inline virtual
Definition at line 106 of file SpalartAllmarasFv3.H.
References SpalartAllmarasFv3< BasicTurbulenceModel >::boundVar(), SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), SpalartAllmarasFv3< BasicTurbulenceModel >::DnuTildaEff(), SpalartAllmarasFv3< BasicTurbulenceModel >::epsilon(), SpalartAllmarasFv3< BasicTurbulenceModel >::k(), and SpalartAllmarasFv3< BasicTurbulenceModel >::read().
Member Function Documentation
chi() [1/2]
tmp< volScalarField > chi () const protected
Definition at line 23 of file SpalartAllmarasFv3.C.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct().
fv1() [1/2]
tmp< volScalarField > fv1 (const volScalarField & chi) const protected
Definition at line 29 of file SpalartAllmarasFv3.C.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct().
fv2() [1/2]
tmp< volScalarField > fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 37 of file SpalartAllmarasFv3.C.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct().
fv3() [1/2]
tmp< volScalarField > fv3 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 45 of file SpalartAllmarasFv3.C.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct().
fw() [1/2]
tmp< volScalarField > fw (const volScalarField & Stilda) const protected
Definition at line 59 of file SpalartAllmarasFv3.C.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct().
correctNut() [1/4]
void correctNut (const volScalarField & fv1) protected
Definition at line 78 of file SpalartAllmarasFv3.C.
correctNut() [2/4]
void correctNut () protected virtual
Definition at line 89 of file SpalartAllmarasFv3.C.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct().
TypeName() [1/2]
TypeName ("SpalartAllmarasFv3< BasicTurbulenceModel >")
read() [1/2]
bool read () virtual
Definition at line 184 of file SpalartAllmarasFv3.C.
References SpalartAllmarasFv3< BasicTurbulenceModel >::Cb1_, SpalartAllmarasFv3< BasicTurbulenceModel >::Cb2_, SpalartAllmarasFv3< BasicTurbulenceModel >::Cv1_, SpalartAllmarasFv3< BasicTurbulenceModel >::Cv2_, SpalartAllmarasFv3< BasicTurbulenceModel >::Cw1_, SpalartAllmarasFv3< BasicTurbulenceModel >::Cw2_, SpalartAllmarasFv3< BasicTurbulenceModel >::Cw3_, SpalartAllmarasFv3< BasicTurbulenceModel >::kappa_, and SpalartAllmarasFv3< BasicTurbulenceModel >::sigmaNut_.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::~SpalartAllmarasFv3().
DnuTildaEff() [1/2]
tmp< volScalarField > DnuTildaEff () const
Definition at line 208 of file SpalartAllmarasFv3.C.
References SpalartAllmarasFv3< BasicTurbulenceModel >::nuTilda_, and SpalartAllmarasFv3< BasicTurbulenceModel >::sigmaNut_.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), and SpalartAllmarasFv3< BasicTurbulenceModel >::~SpalartAllmarasFv3().
k() [1/2]
tmp< volScalarField > k () const virtual
Definition at line 215 of file SpalartAllmarasFv3.C.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::~SpalartAllmarasFv3().
epsilon() [1/2]
tmp< volScalarField > epsilon () const virtual
Definition at line 234 of file SpalartAllmarasFv3.C.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::~SpalartAllmarasFv3().
correct() [1/2]
void correct () virtual
Definition at line 286 of file SpalartAllmarasFv3.C.
References SpalartAllmarasFv3< BasicTurbulenceModel >::boundVar(), SpalartAllmarasFv3< BasicTurbulenceModel >::Cb1_, SpalartAllmarasFv3< BasicTurbulenceModel >::Cb2_, SpalartAllmarasFv3< BasicTurbulenceModel >::chi(), SpalartAllmarasFv3< BasicTurbulenceModel >::correctNut(), SpalartAllmarasFv3< BasicTurbulenceModel >::Cw1_, SpalartAllmarasFv3< BasicTurbulenceModel >::DnuTildaEff(), SpalartAllmarasFv3< BasicTurbulenceModel >::fv1(), SpalartAllmarasFv3< BasicTurbulenceModel >::fv2(), SpalartAllmarasFv3< BasicTurbulenceModel >::fv3(), SpalartAllmarasFv3< BasicTurbulenceModel >::fw(), SpalartAllmarasFv3< BasicTurbulenceModel >::kappa_, SpalartAllmarasFv3< BasicTurbulenceModel >::nuTilda_, SpalartAllmarasFv3< BasicTurbulenceModel >::nuTildaMin_, rho, SpalartAllmarasFv3< BasicTurbulenceModel >::sigmaNut_, and SpalartAllmarasFv3< BasicTurbulenceModel >::y_.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::~SpalartAllmarasFv3().
boundVar() [1/2]
void boundVar (volScalarField & var)
bound the turbulence vars
Definition at line 253 of file SpalartAllmarasFv3.C.
References simple.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), and SpalartAllmarasFv3< BasicTurbulenceModel >::~SpalartAllmarasFv3().
chi() [2/2]
tmp<volScalarField> chi () const protected
fv1() [2/2]
tmp<volScalarField> fv1 (const volScalarField & chi) const protected
fv2() [2/2]
tmp<volScalarField> fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
fv3() [2/2]
tmp<volScalarField> fv3 (const volScalarField & chi, const volScalarField & fv1) const protected
fw() [2/2]
tmp<volScalarField> fw (const volScalarField & Stilda) const protected
correctNut() [3/4]
void correctNut (const volScalarField & fv1) protected
correctNut() [4/4]
virtual void correctNut () protected virtual
TypeName() [2/2]
TypeName ("SpalartAllmarasFv3< BasicTurbulenceModel >")
read() [2/2]
virtual bool read () virtual
DnuTildaEff() [2/2]
tmp<volScalarField> DnuTildaEff () const
k() [2/2]
virtual tmp<volScalarField> k () const virtual
epsilon() [2/2]
virtual tmp<volScalarField> epsilon () const virtual
correct() [2/2]
virtual void correct () virtual
boundVar() [2/2]
void boundVar (volScalarField & var)
bound the turbulence vars
Member Data Documentation
sigmaNut_
dimensionedScalar sigmaNut_ protected
Definition at line 44 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), SpalartAllmarasFv3< BasicTurbulenceModel >::DnuTildaEff(), and SpalartAllmarasFv3< BasicTurbulenceModel >::read().
kappa_
dimensionedScalar kappa_ protected
Definition at line 45 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), and SpalartAllmarasFv3< BasicTurbulenceModel >::read().
Cb1_
dimensionedScalar Cb1_ protected
Definition at line 47 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), and SpalartAllmarasFv3< BasicTurbulenceModel >::read().
Cb2_
dimensionedScalar Cb2_ protected
Definition at line 48 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), and SpalartAllmarasFv3< BasicTurbulenceModel >::read().
Cw1_
dimensionedScalar Cw1_ protected
Definition at line 49 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), and SpalartAllmarasFv3< BasicTurbulenceModel >::read().
Cw2_
dimensionedScalar Cw2_ protected
Definition at line 50 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::read().
Cw3_
dimensionedScalar Cw3_ protected
Definition at line 51 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::read().
Cv1_
dimensionedScalar Cv1_ protected
Definition at line 52 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::read().
Cv2_
dimensionedScalar Cv2_ protected
Definition at line 53 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::read().
nuTildaMin_
dimensionedScalar nuTildaMin_ protected
Definition at line 54 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct().
nuTilda_
volScalarField nuTilda_ protected
Definition at line 58 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct(), and SpalartAllmarasFv3< BasicTurbulenceModel >::DnuTildaEff().
y_
const volScalarField & y_ protected
Definition at line 63 of file SpalartAllmarasFv3.H.
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::correct().
The documentation for this class was generated from the following files:
dafoam/src/models/SpalartAllmarasFv3Compressible/SpalartAllmarasFv3.H
dafoam/src/models/SpalartAllmarasFv3Compressible/SpalartAllmarasFv3.C