DAFoam: DAFvSource Class Reference
DAFvSource Class Reference
Public Member Functions
TypeName ("DAFvSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAFvSource, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAFvSource (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAFvSource ()
virtual void calcFvSource (volVectorField &fvSource)
compute the FvSource term
void setActuatorDVs (const word diskName, const label dvI, const scalar val)
set a new value to the actuator disk design variable
scalar getActuatorDVs (const word diskName, const label dvI)
get the value from the actuator disk design variable
void updateFvSource ()
calculate fvSource based on the latest actuatorDVs
void syncDAOptionToActuatorDVs ()
synchronize the values in DAOption and actuatorDiskDVs_
bool writeData (Ostream &os) const
virtual function for regIOobject
Static Public Member Functions
static autoPtr< DAFvSource > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Protected Attributes
const word & modelType_
model name
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
HashTable< List< scalar > > actuatorDiskDVs_
the list of design variables for all the actuator disks
Detailed Description
Definition at line 34 of file DAFvSource.H.
Constructor & Destructor Documentation
DAFvSource()
DAFvSource (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 22 of file DAFvSource.C.
~DAFvSource()
virtual ~DAFvSource () inline virtual
Definition at line 101 of file DAFvSource.H.
References DAFvSource::calcFvSource(), and fvSource.
Member Function Documentation
TypeName()
TypeName ("DAFvSource")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , DAFvSource , dictionary , (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex) , (modelType, mesh, daOption, daModel, daIndex))
New()
autoPtr< DAFvSource > New (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex) static
Definition at line 47 of file DAFvSource.C.
References daIndex(), daModel(), daOption(), DAOption::getAllOptions(), and mesh.
Referenced by DASimpleFoam::initSolver(), DARhoSimpleFoam::initSolver(), and DAPisoFoam::initSolver().
calcFvSource()
void calcFvSource (volVectorField & fvSource) virtual
compute the FvSource term
Reimplemented in DAFvSourceActuatorDisk, DAFvSourceActuatorLine, DAFvSourceActuatorPoint, and DAFvSourceUniformPressureGradient.
Definition at line 90 of file DAFvSource.C.
References DAFvSource::modelType_.
Referenced by DAResidualPisoFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), DAFvSource::updateFvSource(), and DAFvSource::~DAFvSource().
setActuatorDVs()
void setActuatorDVs (const word diskName, const label dvI, const scalar val) inline
set a new value to the actuator disk design variable
Definition at line 109 of file DAFvSource.H.
Referenced by DASolver::calcdFdACTAD(), and DASolver::calcdRdActTPsiAD().
getActuatorDVs()
scalar getActuatorDVs (const word diskName, const label dvI) inline
get the value from the actuator disk design variable
Definition at line 118 of file DAFvSource.H.
Referenced by DASolver::calcdFdACTAD(), and DASolver::calcdRdActTPsiAD().
updateFvSource()
void updateFvSource () inline
calculate fvSource based on the latest actuatorDVs
Definition at line 126 of file DAFvSource.H.
References DAFvSource::calcFvSource(), DAFvSource::syncDAOptionToActuatorDVs(), and DAFvSource::writeData().
Referenced by DASolver::calcdFdACTAD(), and DAPartDerivdFdACTD::calcPartDerivMat().
syncDAOptionToActuatorDVs()
void syncDAOptionToActuatorDVs ()
synchronize the values in DAOption and actuatorDiskDVs_
Definition at line 113 of file DAFvSource.C.
References DAFvSource::actuatorDiskDVs_, DAFvSource::daOption_, and DAOption::getAllOptions().
Referenced by DAPartDerivdFdACTD::calcPartDerivMat(), DAPartDerivdRdACTD::calcPartDerivMat(), DAFvSourceActuatorDisk::DAFvSourceActuatorDisk(), DASolver::syncDAOptionToActuatorDVs(), PYDAFOAM::updateDAOption(), and DAFvSource::updateFvSource().
writeData()
bool writeData (Ostream & os) const
virtual function for regIOobject
Definition at line 103 of file DAFvSource.C.
Referenced by DAFvSource::updateFvSource().
Member Data Documentation
modelType_
const word& modelType_ protected
model name
Definition at line 47 of file DAFvSource.H.
Referenced by DAFvSource::calcFvSource().
mesh_
const fvMesh& mesh_ protected
fvMesh
Definition at line 50 of file DAFvSource.H.
Referenced by DAFvSourceActuatorLine::calcFvSource(), DAFvSourceActuatorPoint::calcFvSource(), DAFvSourceActuatorDisk::calcFvSource(), and DAFvSourceActuatorDisk::calcFvSourceCellIndices().
daOption_
const DAOption& daOption_ protected
DAOption object.
Definition at line 53 of file DAFvSource.H.
Referenced by DAFvSourceUniformPressureGradient::calcFvSource(), DAFvSourceActuatorPoint::calcFvSource(), DAFvSourceActuatorLine::calcFvSource(), DAFvSourceActuatorDisk::calcFvSource(), DAFvSourceActuatorDisk::calcFvSourceCellIndices(), and DAFvSource::syncDAOptionToActuatorDVs().
daModel_
const DAModel& daModel_ protected
DAModel object.
Definition at line 56 of file DAFvSource.H.
daIndex_
const DAIndex& daIndex_ protected
DAIndex object.
Definition at line 59 of file DAFvSource.H.
actuatorDiskDVs_
HashTable<List<scalar> > actuatorDiskDVs_ protected
the list of design variables for all the actuator disks
Definition at line 62 of file DAFvSource.H.
Referenced by DAFvSourceActuatorDisk::calcFvSource(), and DAFvSource::syncDAOptionToActuatorDVs().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAFvSource/DAFvSource.H
dafoam/src/adjoint/DAFvSource/DAFvSource.C