DAFoam: DAkOmega Class Reference
DAkOmega Class Reference
Protected Member Functions
kOmega functions
tmp< volScalarField > DkEff () const
tmp< volScalarField > DomegaEff () const
Protected Attributes
kOmega parameters
dimensionedScalar Cmu_
dimensionedScalar beta_
dimensionedScalar gamma_
dimensionedScalar alphaK_
dimensionedScalar alphaOmega_
Protected Attributes inherited from DATurbulenceModel
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const dictionary & allOptions_
all DAFoam options
volScalarField & nut_
turbulence viscosity
volVectorField & U_
velocity
surfaceScalarField & phi_
face flux
volScalarField phase_
phase field
surfaceScalarField & phaseRhoPhi_
phase*phi*density field
IOdictionary turbDict_
turbulence model property dict
dictionary coeffDict_
turbulence model parameters dict
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
dimensionedScalar nuTildaMin_
Lower limit for nuTilda.
scalar Pr_
Prandtl number.
scalar Prt_ = -9999.0
turbulent Prandtl number
Augmented variables for adjoint residuals
volScalarField & omega_
volScalarField omegaRes_
volScalarField & k_
volScalarField kRes_
scalarList omegaNearWall_
label solveTurbState_ = 0
whether to solve for turb states
label printInterval_
time step interval to print residual
TypeName ("kOmega")
DAkOmega (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DAkOmega ()
virtual void correctModelStates (wordList &modelStates) const
update the turbulence state for DAStateInfo::regStates_
virtual void correctNut ()
update nut based on other turbulence variables and update the BCs
virtual void correctBoundaryConditions ()
update turbulence variable boundary values
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctStateResidualModelCon (List< List< word >> &stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const
add the model residual connectivity to stateCon
virtual void calcResiduals (const dictionary &options)
compute the turbulence residuals
virtual void correct ()
solve the residual equations and update the state
void saveOmegaNearWall ()
save near wall omega values to omegaNearWall_
void setOmegaNearWall ()
set omegaNearWall_ to near wall omega values
void correctOmegaBoundaryConditions ()
specially treatment to correct epsilon BC
Additional Inherited Members
Public Member Functions inherited from DATurbulenceModel
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable (autoPtr, DATurbulenceModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DATurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DATurbulenceModel ()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
void correctAlphat ()
update alphat
virtual void getTurbProdTerm (scalarList &prodTerm) const
return the value of the production term from the Spalart Allmaras model
tmp< volSymmTensorField > devRhoReff () const
dev terms
tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U)
divDev terms
tmp< fvVectorMatrix > divDevReff (volVectorField &U)
divDev terms
tmp< volScalarField > nuEff () const
return effective viscosity
tmp< volScalarField > getNut ()
get the nut field
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
tmp< volScalarField > nu () const
get the nu field
tmp< volScalarField > getAlpha () const
get alpha field
tmp< volScalarField > getRho ()
get the density field
tmp< volScalarField > getPhase ()
get the phase field
scalar getPrt ()
get the turbulent Prandtl number
tmp< Foam::volScalarField > getMu () const
get mu
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void printYPlus () const
print the min max and mean yPlus to screen
label isPrintTime (const Time &runTime, const label printInterval) const
Static Public Member Functions inherited from DATurbulenceModel
static autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Detailed Description
Definition at line 48 of file DAkOmega.H.
Constructor & Destructor Documentation
DAkOmega()
DAkOmega (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 41 of file DAkOmega.C.
References daOption(), mesh, DAkOmega::omega_, DAkOmega::omegaNearWall_, and DAkOmega::printInterval_.
~DAkOmega()
virtual ~DAkOmega () inline virtual
Definition at line 122 of file DAkOmega.H.
Member Function Documentation
DkEff()
tmp<volScalarField> DkEff () const inline protected
Definition at line 65 of file DAkOmega.H.
References DAkOmega::alphaK_, DATurbulenceModel::nu(), and DATurbulenceModel::nut_.
Referenced by DAkOmega::calcResiduals().
DomegaEff()
tmp<volScalarField> DomegaEff () const inline protected
Definition at line 78 of file DAkOmega.H.
References DAkOmega::alphaOmega_, DATurbulenceModel::nu(), and DATurbulenceModel::nut_.
Referenced by DAkOmega::calcResiduals().
TypeName()
TypeName ("kOmega")
correctModelStates()
void correctModelStates (wordList & modelStates) const virtual
update the turbulence state for DAStateInfo::regStates_
Implements DATurbulenceModel.
Definition at line 148 of file DAkOmega.C.
correctNut()
void correctNut () virtual
update nut based on other turbulence variables and update the BCs
Implements DATurbulenceModel.
Definition at line 184 of file DAkOmega.C.
References DATurbulenceModel::correctAlphat(), DAkOmega::k_, DATurbulenceModel::nut_, and DAkOmega::omega_.
Referenced by DAkOmega::calcResiduals(), and DAkOmega::updateIntermediateVariables().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update turbulence variable boundary values
Implements DATurbulenceModel.
Definition at line 202 of file DAkOmega.C.
References DAkOmega::k_.
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DATurbulenceModel.
Definition at line 291 of file DAkOmega.C.
References DAkOmega::correctNut().
correctStateResidualModelCon()
void correctStateResidualModelCon (List< List< word >> & stateCon) const virtual
update the original variable connectivity for the adjoint state residuals in stateCon
Implements DATurbulenceModel.
Definition at line 302 of file DAkOmega.C.
addModelResidualCon()
void addModelResidualCon (HashTable< List< List< word >>> & allCon) const virtual
add the model residual connectivity to stateCon
Implements DATurbulenceModel.
Definition at line 401 of file DAkOmega.C.
References DATurbulenceModel::mesh_.
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute the turbulence residuals
Implements DATurbulenceModel.
Definition at line 513 of file DAkOmega.C.
References DATurbulenceModel::allOptions_, DAkOmega::beta_, DAUtility::boundVar(), DAkOmega::Cmu_, DAkOmega::correctNut(), DAkOmega::correctOmegaBoundaryConditions(), DAkOmega::DkEff(), DAkOmega::DomegaEff(), DAkOmega::gamma_, DATurbulenceModel::isPrintTime(), DAkOmega::k_, DAkOmega::kRes_, DATurbulenceModel::mesh_, normalizeResiduals, DATurbulenceModel::nut_, DAkOmega::omega_, DAkOmega::omegaRes_, DATurbulenceModel::phase_, DATurbulenceModel::phaseRhoPhi_, DATurbulenceModel::phi_, DAkOmega::printInterval_, DAkOmega::setOmegaNearWall(), DAkOmega::solveTurbState_, and DATurbulenceModel::U_.
Referenced by DAkOmega::correct().
correct()
void correct () virtual
solve the residual equations and update the state
Implements DATurbulenceModel.
Definition at line 493 of file DAkOmega.C.
References DAkOmega::calcResiduals(), and DAkOmega::solveTurbState_.
saveOmegaNearWall()
void saveOmegaNearWall ()
save near wall omega values to omegaNearWall_
Definition at line 241 of file DAkOmega.C.
References DATurbulenceModel::mesh_, DAkOmega::omega_, and DAkOmega::omegaNearWall_.
Referenced by DAkOmega::correctOmegaBoundaryConditions().
setOmegaNearWall()
void setOmegaNearWall ()
set omegaNearWall_ to near wall omega values
Definition at line 265 of file DAkOmega.C.
References DATurbulenceModel::mesh_, DAkOmega::omega_, and DAkOmega::omegaNearWall_.
Referenced by DAkOmega::calcResiduals(), and DAkOmega::correctOmegaBoundaryConditions().
correctOmegaBoundaryConditions()
void correctOmegaBoundaryConditions ()
specially treatment to correct epsilon BC
Definition at line 214 of file DAkOmega.C.
References DAkOmega::omega_, DAkOmega::saveOmegaNearWall(), and DAkOmega::setOmegaNearWall().
Referenced by DAkOmega::calcResiduals().
Member Data Documentation
Cmu_
dimensionedScalar Cmu_ protected
Definition at line 55 of file DAkOmega.H.
Referenced by DAkOmega::calcResiduals().
beta_
dimensionedScalar beta_ protected
Definition at line 56 of file DAkOmega.H.
Referenced by DAkOmega::calcResiduals().
gamma_
dimensionedScalar gamma_ protected
Definition at line 57 of file DAkOmega.H.
Referenced by DAkOmega::calcResiduals().
alphaK_
dimensionedScalar alphaK_ protected
Definition at line 58 of file DAkOmega.H.
Referenced by DAkOmega::DkEff().
alphaOmega_
dimensionedScalar alphaOmega_ protected
Definition at line 59 of file DAkOmega.H.
Referenced by DAkOmega::DomegaEff().
omega_
volScalarField& omega_ protected
Definition at line 93 of file DAkOmega.H.
Referenced by DAkOmega::calcResiduals(), DAkOmega::correctNut(), DAkOmega::correctOmegaBoundaryConditions(), DAkOmega::DAkOmega(), DAkOmega::saveOmegaNearWall(), and DAkOmega::setOmegaNearWall().
omegaRes_
volScalarField omegaRes_ protected
Definition at line 94 of file DAkOmega.H.
Referenced by DAkOmega::calcResiduals().
k_
volScalarField& k_ protected
Definition at line 95 of file DAkOmega.H.
Referenced by DAkOmega::calcResiduals(), DAkOmega::correctBoundaryConditions(), and DAkOmega::correctNut().
kRes_
volScalarField kRes_ protected
Definition at line 96 of file DAkOmega.H.
Referenced by DAkOmega::calcResiduals().
omegaNearWall_
scalarList omegaNearWall_ protected
cell-center omega values near the wall, this is to fix the issue that the omegaWallFunction will try to modify omega values for the cells near walls this will cause issue for FD-based partial derivatives, so here we basically implement a zeroGradient BC for near wall omega.
Definition at line 103 of file DAkOmega.H.
Referenced by DAkOmega::DAkOmega(), DAkOmega::saveOmegaNearWall(), and DAkOmega::setOmegaNearWall().
solveTurbState_
label solveTurbState_ = 0 protected
whether to solve for turb states
Definition at line 106 of file DAkOmega.H.
Referenced by DAkOmega::calcResiduals(), and DAkOmega::correct().
printInterval_
label printInterval_ protected
time step interval to print residual
Definition at line 109 of file DAkOmega.H.
Referenced by DAkOmega::calcResiduals(), and DAkOmega::DAkOmega().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DATurbulenceModel/DAkOmega.H
dafoam/src/adjoint/DAModel/DATurbulenceModel/DAkOmega.C