DAFoam: DATurbulenceModel Class Reference
DATurbulenceModel Class Reference abstract
Public Member Functions
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable (autoPtr, DATurbulenceModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DATurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DATurbulenceModel ()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
void correctAlphat ()
update alphat
virtual void correctNut ()=0
update nut based on other turbulence variables and update the BCs
virtual void correctModelStates (wordList &modelStates) const =0
update the turbulence state for DAStateInfo::regStates_
virtual void correctBoundaryConditions ()=0
update turbulence variable boundary values
virtual void updateIntermediateVariables ()=0
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctStateResidualModelCon (List< List< word >> &stateCon) const =0
update the original variable connectivity for the adjoint state residuals in stateCon
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const =0
add the model residual connectivity to stateCon
virtual void calcResiduals (const dictionary &options)=0
compute the turbulence residuals
virtual void correct ()=0
solve the residual equations and update the state
virtual void getTurbProdTerm (scalarList &prodTerm) const
return the value of the production term from the Spalart Allmaras model
tmp< volSymmTensorField > devRhoReff () const
dev terms
tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U)
divDev terms
tmp< fvVectorMatrix > divDevReff (volVectorField &U)
divDev terms
tmp< volScalarField > nuEff () const
return effective viscosity
tmp< volScalarField > getNut ()
get the nut field
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
tmp< volScalarField > nu () const
get the nu field
tmp< volScalarField > getAlpha () const
get alpha field
tmp< volScalarField > getRho ()
get the density field
tmp< volScalarField > getPhase ()
get the phase field
scalar getPrt ()
get the turbulent Prandtl number
tmp< Foam::volScalarField > getMu () const
get mu
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void printYPlus () const
print the min max and mean yPlus to screen
label isPrintTime (const Time &runTime, const label printInterval) const
Static Public Member Functions
static autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Protected Attributes
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const dictionary & allOptions_
all DAFoam options
volScalarField & nut_
turbulence viscosity
volVectorField & U_
velocity
surfaceScalarField & phi_
face flux
volScalarField phase_
phase field
surfaceScalarField & phaseRhoPhi_
phase*phi*density field
IOdictionary turbDict_
turbulence model property dict
dictionary coeffDict_
turbulence model parameters dict
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
dimensionedScalar nuTildaMin_
Lower limit for nuTilda.
scalar Pr_
Prandtl number.
scalar Prt_ = -9999.0
turbulent Prandtl number
Detailed Description
Definition at line 61 of file DATurbulenceModel.H.
Constructor & Destructor Documentation
DATurbulenceModel()
DATurbulenceModel (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 22 of file DATurbulenceModel.C.
References mesh, DATurbulenceModel::mesh_, DATurbulenceModel::Pr_, and DATurbulenceModel::Prt_.
~DATurbulenceModel()
virtual ~DATurbulenceModel () inline virtual
Definition at line 178 of file DATurbulenceModel.H.
Member Function Documentation
TypeName()
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , DATurbulenceModel , dictionary , (const word modelType, const fvMesh &mesh, const DAOption &daOption) , (modelType, mesh, daOption))
New()
autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh & mesh, const DAOption & daOption) static
Definition at line 164 of file DATurbulenceModel.C.
References daOption(), and mesh.
correctWallDist()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
Definition at line 358 of file DATurbulenceModel.C.
References DATurbulenceModel::correctBoundaryConditions().
correctAlphat()
void correctAlphat ()
update alphat
Definition at line 206 of file DATurbulenceModel.C.
References alphat, DATurbulenceModel::mesh_, DATurbulenceModel::nut_, Prt, and DATurbulenceModel::Prt_.
Referenced by DASpalartAllmaras::correctNut(), DASpalartAllmarasFv3::correctNut(), DAkEpsilon::correctNut(), DAkOmega::correctNut(), DAkOmegaFieldInversionk::correctNut(), DAkOmegaFieldInversionOmega::correctNut(), DAkOmegaFieldInversion::correctNut(), DASpalartAllmarasFv3FieldInversion::correctNut(), DAkOmegaSST::correctNut(), DAkOmegaSSTFieldInversion::correctNut(), and DAkOmegaSSTLM::correctNut().
correctNut()
virtual void correctNut () pure virtual
update nut based on other turbulence variables and update the BCs
Implemented in DAkOmegaSSTLM, DAkOmegaSSTFieldInversion, DAkOmegaSST, DASpalartAllmarasFv3FieldInversion, DAkOmegaFieldInversion, DAkOmegaFieldInversionk, DAkOmegaFieldInversionOmega, DAkOmega, DAkEpsilon, DASpalartAllmaras, DASpalartAllmarasFv3, and DADummyTurbulenceModel.
correctModelStates()
virtual void correctModelStates (wordList & modelStates) const pure virtual
update the turbulence state for DAStateInfo::regStates_
Implemented in DAkOmegaSSTLM, DAkOmegaSSTFieldInversion, DAkOmegaSST, DASpalartAllmarasFv3FieldInversion, DAkOmegaFieldInversion, DAkOmegaFieldInversionk, DAkOmegaFieldInversionOmega, DAkOmega, DAkEpsilon, DASpalartAllmaras, DASpalartAllmarasFv3, and DADummyTurbulenceModel.
Referenced by DAModel::correctModelStates().
correctBoundaryConditions()
virtual void correctBoundaryConditions () pure virtual
update turbulence variable boundary values
Implemented in DAkOmegaSSTLM, DAkOmegaSSTFieldInversion, DAkOmegaSST, DASpalartAllmarasFv3FieldInversion, DAkOmegaFieldInversion, DAkOmegaFieldInversionk, DAkOmegaFieldInversionOmega, DAkOmega, DAkEpsilon, DASpalartAllmaras, DASpalartAllmarasFv3, and DADummyTurbulenceModel.
Referenced by DAModel::correctBoundaryConditions(), and DATurbulenceModel::correctWallDist().
updateIntermediateVariables()
virtual void updateIntermediateVariables () pure virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implemented in DAkOmegaSSTLM, DAkOmegaSSTFieldInversion, DAkOmegaSST, DASpalartAllmarasFv3FieldInversion, DAkOmegaFieldInversion, DAkOmegaFieldInversionk, DAkOmegaFieldInversionOmega, DAkOmega, DAkEpsilon, DASpalartAllmaras, DASpalartAllmarasFv3, and DADummyTurbulenceModel.
Referenced by DAModel::updateIntermediateVariables().
correctStateResidualModelCon()
virtual void correctStateResidualModelCon (List< List< word >> & stateCon) const pure virtual
update the original variable connectivity for the adjoint state residuals in stateCon
Implemented in DAkOmegaSSTLM, DAkOmegaSSTFieldInversion, DAkOmegaSST, DASpalartAllmarasFv3FieldInversion, DAkOmegaFieldInversion, DAkOmegaFieldInversionk, DAkOmegaFieldInversionOmega, DAkOmega, DAkEpsilon, DASpalartAllmaras, DASpalartAllmarasFv3, and DADummyTurbulenceModel.
Referenced by DAModel::correctStateResidualModelCon().
addModelResidualCon()
virtual void addModelResidualCon (HashTable< List< List< word >>> & allCon) const pure virtual
add the model residual connectivity to stateCon
Implemented in DAkOmegaSSTLM, DAkOmegaSSTFieldInversion, DAkOmegaSST, DASpalartAllmarasFv3FieldInversion, DAkOmegaFieldInversion, DAkOmegaFieldInversionk, DAkOmegaFieldInversionOmega, DAkOmega, DAkEpsilon, DASpalartAllmaras, DASpalartAllmarasFv3, and DADummyTurbulenceModel.
Referenced by DAModel::addModelResidualCon().
calcResiduals()
virtual void calcResiduals (const dictionary & options) pure virtual
compute the turbulence residuals
Implemented in DAkOmegaSSTLM, DAkOmegaSSTFieldInversion, DAkOmegaSST, DASpalartAllmarasFv3FieldInversion, DAkOmegaFieldInversion, DAkOmegaFieldInversionk, DAkOmegaFieldInversionOmega, DAkOmega, DAkEpsilon, DASpalartAllmaras, DASpalartAllmarasFv3, and DADummyTurbulenceModel.
Referenced by DAModel::calcResiduals().
correct()
virtual void correct () pure virtual
solve the residual equations and update the state
Implemented in DAkOmegaSSTLM, DAkOmegaSSTFieldInversion, DAkOmegaSST, DASpalartAllmarasFv3FieldInversion, DAkOmegaFieldInversion, DAkOmegaFieldInversionk, DAkOmegaFieldInversionOmega, DAkOmega, DAkEpsilon, DASpalartAllmaras, DASpalartAllmarasFv3, and DADummyTurbulenceModel.
getTurbProdTerm()
void getTurbProdTerm (scalarList & prodTerm) const virtual
return the value of the production term from the Spalart Allmaras model
Reimplemented in DASpalartAllmarasFv3FieldInversion.
Definition at line 483 of file DATurbulenceModel.C.
Referenced by DAModel::getTurbProdTerm().
devRhoReff()
tmp< volSymmTensorField > devRhoReff () const
dev terms
Definition at line 306 of file DATurbulenceModel.C.
References DATurbulenceModel::mesh_, DATurbulenceModel::nuEff(), DATurbulenceModel::phase_, and DATurbulenceModel::U_.
Referenced by DAObjFuncMoment::calcObjFunc(), DAObjFuncForce::calcObjFunc(), DAObjFuncFieldInversion::calcObjFunc(), DAResidualTurboFoam::calcResiduals(), and DASolver::getForcesInternal().
divDevRhoReff()
tmp< fvVectorMatrix > divDevRhoReff (volVectorField & U)
divDev terms
Definition at line 324 of file DATurbulenceModel.C.
References DATurbulenceModel::nuEff(), DATurbulenceModel::phase_, rho, T, and U.
Referenced by DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), and DATurbulenceModel::divDevReff().
divDevReff()
tmp< fvVectorMatrix > divDevReff (volVectorField & U)
divDev terms
Definition at line 347 of file DATurbulenceModel.C.
References DATurbulenceModel::divDevRhoReff(), and U.
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), and DAResidualSimpleTFoam::calcResiduals().
nuEff()
tmp< volScalarField > nuEff () const
return effective viscosity
Definition at line 223 of file DATurbulenceModel.C.
References DATurbulenceModel::nu(), and DATurbulenceModel::nut_.
Referenced by DATurbulenceModel::devRhoReff(), DATurbulenceModel::divDevRhoReff(), and DATurbulenceModel::printYPlus().
getNut()
tmp<volScalarField> getNut () inline
get the nut field
Definition at line 230 of file DATurbulenceModel.H.
References DATurbulenceModel::nut_.
Referenced by DAResidualSimpleTFoam::updateIntermediateVariables().
alphaEff()
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
Definition at line 236 of file DATurbulenceModel.C.
References alphat, DATurbulenceModel::getAlpha(), and DATurbulenceModel::mesh_.
Referenced by DAObjFuncWallHeatFlux::calcObjFunc().
nu()
tmp< volScalarField > nu () const
get the nu field
Definition at line 262 of file DATurbulenceModel.C.
Referenced by DAResidualSimpleTFoam::calcResiduals(), DAkOmegaSSTLM::calcResiduals(), DASpalartAllmarasFv3::chi(), DASpalartAllmaras::chi(), DASpalartAllmarasFv3FieldInversion::chi(), DAkEpsilon::DepsilonEff(), DAkOmegaSSTLM::DgammaIntEff(), DAkOmegaFieldInversionOmega::DkEff(), DAkOmegaFieldInversion::DkEff(), DAkOmega::DkEff(), DAkOmegaFieldInversionk::DkEff(), DAkEpsilon::DkEff(), DAkOmegaSST::DkEff(), DAkOmegaSSTFieldInversion::DkEff(), DAkOmegaSSTLM::DkEff(), DASpalartAllmaras::DnuTildaEff(), DASpalartAllmarasFv3::DnuTildaEff(), DASpalartAllmarasFv3FieldInversion::DnuTildaEff(), DAkOmegaFieldInversionk::DomegaEff(), DAkOmegaFieldInversionOmega::DomegaEff(), DAkOmegaFieldInversion::DomegaEff(), DAkOmega::DomegaEff(), DAkOmegaSST::DomegaEff(), DAkOmegaSSTFieldInversion::DomegaEff(), DAkOmegaSSTLM::DomegaEff(), DAkOmegaSSTLM::DReThetatEff(), DAkOmegaSST::F1(), DAkOmegaSSTFieldInversion::F1(), DAkOmegaSSTLM::F1(), DAkOmegaSSTLM::F1SST(), DAkOmegaSST::F2(), DAkOmegaSSTFieldInversion::F2(), DAkOmegaSSTLM::F2(), DAkOmegaSST::F3(), DAkOmegaSSTFieldInversion::F3(), DAkOmegaSSTLM::F3(), DAkOmegaSSTLM::Flength(), DAkOmegaSSTLM::Fthetat(), DATurbulenceModel::getAlpha(), DATurbulenceModel::nuEff(), DATurbulenceModel::printYPlus(), and DAkOmegaSSTLM::ReThetat0().
getAlpha()
tmp< volScalarField > getAlpha () const
get alpha field
Definition at line 280 of file DATurbulenceModel.C.
References DATurbulenceModel::nu(), and DATurbulenceModel::Pr_.
Referenced by DATurbulenceModel::alphaEff().
getRho()
tmp<volScalarField> getRho () inline
get the density field
Definition at line 245 of file DATurbulenceModel.H.
getPhase()
tmp<volScalarField> getPhase () inline
get the phase field
Definition at line 251 of file DATurbulenceModel.H.
References DATurbulenceModel::phase_.
getPrt()
scalar getPrt () inline
get the turbulent Prandtl number
Definition at line 257 of file DATurbulenceModel.H.
References DATurbulenceModel::Prt_.
getMu()
tmp< Foam::volScalarField > getMu () const
get mu
Definition at line 289 of file DATurbulenceModel.C.
References DATurbulenceModel::nut_.
writeData()
bool writeData (Ostream & os) const
this is a virtual function for regIOobject
Definition at line 200 of file DATurbulenceModel.C.
printYPlus()
void printYPlus () const
print the min max and mean yPlus to screen
Definition at line 385 of file DATurbulenceModel.C.
References DATurbulenceModel::mesh_, DATurbulenceModel::nu(), DATurbulenceModel::nuEff(), DATurbulenceModel::nut_, and DATurbulenceModel::U_.
isPrintTime()
label isPrintTime (const Time & runTime, const label printInterval) const
Definition at line 464 of file DATurbulenceModel.C.
References runTime.
Referenced by DASpalartAllmaras::calcResiduals(), DASpalartAllmarasFv3::calcResiduals(), DAkEpsilon::calcResiduals(), DAkOmega::calcResiduals(), DAkOmegaFieldInversionk::calcResiduals(), DAkOmegaFieldInversionOmega::calcResiduals(), DAkOmegaFieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::calcResiduals(), DAkOmegaSST::calcResiduals(), DAkOmegaSSTFieldInversion::calcResiduals(), and DAkOmegaSSTLM::calcResiduals().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
fvMesh
Definition at line 74 of file DATurbulenceModel.H.
Referenced by DASpalartAllmaras::addModelResidualCon(), DASpalartAllmarasFv3::addModelResidualCon(), DAkEpsilon::addModelResidualCon(), DAkOmega::addModelResidualCon(), DAkOmegaFieldInversion::addModelResidualCon(), DAkOmegaFieldInversionOmega::addModelResidualCon(), DAkOmegaFieldInversionk::addModelResidualCon(), DASpalartAllmarasFv3FieldInversion::addModelResidualCon(), DAkOmegaSST::addModelResidualCon(), DAkOmegaSSTFieldInversion::addModelResidualCon(), DAkOmegaSSTLM::addModelResidualCon(), DATurbulenceModel::alphaEff(), DASpalartAllmaras::calcResiduals(), DASpalartAllmarasFv3::calcResiduals(), DAkEpsilon::calcResiduals(), DAkOmega::calcResiduals(), DAkOmegaFieldInversionk::calcResiduals(), DAkOmegaFieldInversionOmega::calcResiduals(), DAkOmegaFieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::calcResiduals(), DAkOmegaSST::calcResiduals(), DAkOmegaSSTFieldInversion::calcResiduals(), DAkOmegaSSTLM::calcResiduals(), DATurbulenceModel::correctAlphat(), DAkOmegaSST::correctNut(), DAkOmegaSSTFieldInversion::correctNut(), DAkOmegaSSTLM::correctNut(), DATurbulenceModel::DATurbulenceModel(), DATurbulenceModel::devRhoReff(), DAkOmegaSSTLM::Flength(), DATurbulenceModel::printYPlus(), DAkOmegaSSTLM::ReThetac(), DAkOmegaSSTLM::ReThetat0(), DAkEpsilon::saveEpsilonNearWall(), DAkOmega::saveOmegaNearWall(), DAkOmegaFieldInversionOmega::saveOmegaNearWall(), DAkOmegaFieldInversion::saveOmegaNearWall(), DAkOmegaFieldInversionk::saveOmegaNearWall(), DAkOmegaSST::saveOmegaNearWall(), DAkOmegaSSTFieldInversion::saveOmegaNearWall(), DAkOmegaSSTLM::saveOmegaNearWall(), DAkEpsilon::setEpsilonNearWall(), DAkOmega::setOmegaNearWall(), DAkOmegaFieldInversionOmega::setOmegaNearWall(), DAkOmegaFieldInversion::setOmegaNearWall(), DAkOmegaFieldInversionk::setOmegaNearWall(), DAkOmegaSST::setOmegaNearWall(), DAkOmegaSSTFieldInversion::setOmegaNearWall(), and DAkOmegaSSTLM::setOmegaNearWall().
daOption_
const DAOption& daOption_ protected
DAOption object.
Definition at line 77 of file DATurbulenceModel.H.
allOptions_
const dictionary& allOptions_ protected
all DAFoam options
Definition at line 80 of file DATurbulenceModel.H.
Referenced by DASpalartAllmaras::calcResiduals(), DASpalartAllmarasFv3::calcResiduals(), DAkEpsilon::calcResiduals(), DAkOmega::calcResiduals(), DAkOmegaFieldInversionk::calcResiduals(), DAkOmegaFieldInversionOmega::calcResiduals(), DAkOmegaFieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::calcResiduals(), DAkOmegaSST::calcResiduals(), DAkOmegaSSTFieldInversion::calcResiduals(), and DAkOmegaSSTLM::calcResiduals().
nut_
volScalarField& nut_ protected
turbulence viscosity
Definition at line 83 of file DATurbulenceModel.H.
Referenced by DAkEpsilon::calcResiduals(), DAkOmega::calcResiduals(), DAkOmegaFieldInversion::calcResiduals(), DAkOmegaFieldInversionOmega::calcResiduals(), DAkOmegaFieldInversionk::calcResiduals(), DAkOmegaSST::calcResiduals(), DAkOmegaSSTFieldInversion::calcResiduals(), DAkOmegaSSTLM::calcResiduals(), DATurbulenceModel::correctAlphat(), DASpalartAllmaras::correctNut(), DASpalartAllmarasFv3::correctNut(), DAkEpsilon::correctNut(), DAkOmega::correctNut(), DAkOmegaFieldInversionOmega::correctNut(), DAkOmegaFieldInversion::correctNut(), DAkOmegaFieldInversionk::correctNut(), DASpalartAllmarasFv3FieldInversion::correctNut(), DAkOmegaSST::correctNut(), DAkOmegaSSTFieldInversion::correctNut(), DAkOmegaSSTLM::correctNut(), DAkEpsilon::DepsilonEff(), DAkOmegaSSTLM::DgammaIntEff(), DAkOmegaFieldInversionOmega::DkEff(), DAkOmega::DkEff(), DAkOmegaFieldInversion::DkEff(), DAkOmegaFieldInversionk::DkEff(), DAkEpsilon::DkEff(), DAkOmegaSST::DkEff(), DAkOmegaSSTFieldInversion::DkEff(), DAkOmegaSSTLM::DkEff(), DAkOmegaFieldInversionk::DomegaEff(), DAkOmega::DomegaEff(), DAkOmegaFieldInversionOmega::DomegaEff(), DAkOmegaFieldInversion::DomegaEff(), DAkOmegaSST::DomegaEff(), DAkOmegaSSTFieldInversion::DomegaEff(), DAkOmegaSSTLM::DomegaEff(), DAkOmegaSSTLM::DReThetatEff(), DATurbulenceModel::getMu(), DATurbulenceModel::getNut(), DATurbulenceModel::nuEff(), and DATurbulenceModel::printYPlus().
U_
volVectorField& U_ protected
velocity
Definition at line 86 of file DATurbulenceModel.H.
Referenced by DASpalartAllmarasFv3::calcResiduals(), DAkEpsilon::calcResiduals(), DAkOmega::calcResiduals(), DAkOmegaFieldInversionk::calcResiduals(), DAkOmegaFieldInversionOmega::calcResiduals(), DAkOmegaFieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::calcResiduals(), DAkOmegaSST::calcResiduals(), DAkOmegaSSTFieldInversion::calcResiduals(), DAkOmegaSSTLM::calcResiduals(), DATurbulenceModel::devRhoReff(), DAkOmegaSSTLM::Flength(), DAkOmegaSSTLM::Fonset(), DAkOmegaSSTLM::Fthetat(), DASpalartAllmarasFv3FieldInversion::getTurbProdTerm(), DATurbulenceModel::printYPlus(), DAkOmegaSSTLM::ReThetac(), DAkOmegaSSTLM::ReThetat0(), and DASpalartAllmaras::Stilda().
phi_
surfaceScalarField& phi_ protected
face flux
Definition at line 89 of file DATurbulenceModel.H.
Referenced by DAkEpsilon::calcResiduals(), DAkOmega::calcResiduals(), DAkOmegaFieldInversionk::calcResiduals(), DAkOmegaFieldInversionOmega::calcResiduals(), DAkOmegaFieldInversion::calcResiduals(), DAkOmegaSST::calcResiduals(), DAkOmegaSSTFieldInversion::calcResiduals(), and DAkOmegaSSTLM::calcResiduals().
phase_
volScalarField phase_ protected
phase field
Definition at line 92 of file DATurbulenceModel.H.
Referenced by DASpalartAllmaras::calcResiduals(), DASpalartAllmarasFv3::calcResiduals(), DAkEpsilon::calcResiduals(), DAkOmega::calcResiduals(), DAkOmegaFieldInversionk::calcResiduals(), DAkOmegaFieldInversionOmega::calcResiduals(), DAkOmegaFieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::calcResiduals(), DAkOmegaSST::calcResiduals(), DAkOmegaSSTFieldInversion::calcResiduals(), DAkOmegaSSTLM::calcResiduals(), DATurbulenceModel::devRhoReff(), DATurbulenceModel::divDevRhoReff(), DATurbulenceModel::getPhase(), and DASpalartAllmarasFv3FieldInversion::getTurbProdTerm().
phaseRhoPhi_
surfaceScalarField& phaseRhoPhi_ protected
phase*phi*density field
Definition at line 95 of file DATurbulenceModel.H.
Referenced by DASpalartAllmaras::calcResiduals(), DASpalartAllmarasFv3::calcResiduals(), DAkEpsilon::calcResiduals(), DAkOmega::calcResiduals(), DAkOmegaFieldInversionk::calcResiduals(), DAkOmegaFieldInversionOmega::calcResiduals(), DAkOmegaFieldInversion::calcResiduals(), DASpalartAllmarasFv3FieldInversion::calcResiduals(), DAkOmegaSST::calcResiduals(), DAkOmegaSSTFieldInversion::calcResiduals(), and DAkOmegaSSTLM::calcResiduals().
turbDict_
IOdictionary turbDict_ protected
turbulence model property dict
Definition at line 124 of file DATurbulenceModel.H.
coeffDict_
dictionary coeffDict_ protected
turbulence model parameters dict
Definition at line 127 of file DATurbulenceModel.H.
kMin_
dimensionedScalar kMin_ protected
Lower limit of k.
Definition at line 130 of file DATurbulenceModel.H.
epsilonMin_
dimensionedScalar epsilonMin_ protected
Lower limit of epsilon.
Definition at line 133 of file DATurbulenceModel.H.
omegaMin_
dimensionedScalar omegaMin_ protected
Lower limit for omega.
Definition at line 136 of file DATurbulenceModel.H.
nuTildaMin_
dimensionedScalar nuTildaMin_ protected
Lower limit for nuTilda.
Definition at line 139 of file DATurbulenceModel.H.
Pr_
scalar Pr_ protected
Prandtl number.
Definition at line 142 of file DATurbulenceModel.H.
Referenced by DATurbulenceModel::DATurbulenceModel(), and DATurbulenceModel::getAlpha().
Prt_
scalar Prt_ = -9999.0 protected
turbulent Prandtl number
Definition at line 145 of file DATurbulenceModel.H.
Referenced by DATurbulenceModel::correctAlphat(), DATurbulenceModel::DATurbulenceModel(), and DATurbulenceModel::getPrt().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DATurbulenceModel/DATurbulenceModel.H
dafoam/src/adjoint/DAModel/DATurbulenceModel/DATurbulenceModel.C