DAFoam: DAFvSourceActuatorPoint Class Reference
DAFvSourceActuatorPoint Class Reference
Public Member Functions
TypeName ("actuatorPoint")
DAFvSourceActuatorPoint (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAFvSourceActuatorPoint ()
virtual void calcFvSource (volVectorField &fvSource)
compute the FvSource term
Public Member Functions inherited from DAFvSource
TypeName ("DAFvSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAFvSource, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAFvSource (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAFvSource ()
void setActuatorDVs (const word diskName, const label dvI, const scalar val)
set a new value to the actuator disk design variable
scalar getActuatorDVs (const word diskName, const label dvI)
get the value from the actuator disk design variable
void updateFvSource ()
calculate fvSource based on the latest actuatorDVs
void syncDAOptionToActuatorDVs ()
synchronize the values in DAOption and actuatorDiskDVs_
bool writeData (Ostream &os) const
virtual function for regIOobject
Protected Attributes
label printIntervalUnsteady_
print interval
Protected Attributes inherited from DAFvSource
const word & modelType_
model name
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
HashTable< List< scalar > > actuatorDiskDVs_
the list of design variables for all the actuator disks
Additional Inherited Members
Static Public Member Functions inherited from DAFvSource
static autoPtr< DAFvSource > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Detailed Description
Definition at line 26 of file DAFvSourceActuatorPoint.H.
Constructor & Destructor Documentation
DAFvSourceActuatorPoint()
DAFvSourceActuatorPoint (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 19 of file DAFvSourceActuatorPoint.C.
References daOption(), and DAFvSourceActuatorPoint::printIntervalUnsteady_.
~DAFvSourceActuatorPoint()
virtual ~DAFvSourceActuatorPoint () inline virtual
Definition at line 48 of file DAFvSourceActuatorPoint.H.
Member Function Documentation
TypeName()
TypeName ("actuatorPoint")
calcFvSource()
void calcFvSource (volVectorField & fvSource) virtual
compute the FvSource term
Reimplemented from DAFvSource.
Definition at line 31 of file DAFvSourceActuatorPoint.C.
References DAFvSource::daOption_, fvSource, DAOption::getAllOptions(), DAOption::getOption(), DAFvSource::mesh_, and DAFvSourceActuatorPoint::printIntervalUnsteady_.
Member Data Documentation
printIntervalUnsteady_
label printIntervalUnsteady_ protected
print interval
Definition at line 33 of file DAFvSourceActuatorPoint.H.
Referenced by DAFvSourceActuatorPoint::calcFvSource(), and DAFvSourceActuatorPoint::DAFvSourceActuatorPoint().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAFvSource/DAFvSourceActuatorPoint.H
dafoam/src/adjoint/DAFvSource/DAFvSourceActuatorPoint.C