DAFoam: DARadiationModel Class Reference
DARadiationModel Class Reference abstract
Public Member Functions
TypeName ("DARadiationModel")
declareRunTimeSelectionTable (autoPtr, DARadiationModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DARadiationModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DARadiationModel ()
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const =0
Static Public Member Functions
static autoPtr< DARadiationModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Protected Attributes
const fvMesh & mesh_
const DAOption & daOption_
Detailed Description
Definition at line 27 of file DARadiationModel.H.
Constructor & Destructor Documentation
DARadiationModel()
DARadiationModel (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 22 of file DARadiationModel.C.
~DARadiationModel()
virtual ~DARadiationModel () inline virtual
Definition at line 74 of file DARadiationModel.H.
References DARadiationModel::addModelResidualCon(), and DARadiationModel::writeData().
Member Function Documentation
TypeName()
TypeName ("DARadiationModel")
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , DARadiationModel , dictionary , (const word modelType, const fvMesh &mesh, const DAOption &daOption) , (modelType, mesh, daOption))
New()
autoPtr< DARadiationModel > New (const word modelType, const fvMesh & mesh, const DAOption & daOption) static
Definition at line 42 of file DARadiationModel.C.
References daOption(), DAOption::getAllOptions(), and mesh.
writeData()
bool writeData (Ostream & os) const
this is a virtual function for regIOobject
Definition at line 78 of file DARadiationModel.C.
Referenced by DARadiationModel::~DARadiationModel().
addModelResidualCon()
virtual void addModelResidualCon (HashTable< List< List< word >>> & allCon) const pure virtual
Implemented in DAP1.
Referenced by DAModel::addModelResidualCon(), and DARadiationModel::~DARadiationModel().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 39 of file DARadiationModel.H.
daOption_
const DAOption& daOption_ protected
Definition at line 41 of file DARadiationModel.H.
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DARadiationModel/DARadiationModel.H
dafoam/src/adjoint/DAModel/DARadiationModel/DARadiationModel.C