DAFoam: DAField Class Reference
DAField Class Reference
Public Member Functions
DAField (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Constructors.
virtual ~DAField ()
Destructor.
void ofField2StateVec (Vec stateVec) const
set the state vector based on the latest fields in OpenFOAM
void stateVec2OFField (const Vec stateVec) const
assign the fields in OpenFOAM based on the state vector
void pointVec2OFMesh (const Vec xvVec) const
assign the points in fvMesh of OpenFOAM based on the point vector
void ofMesh2PointVec (Vec xvVec) const
assign the point vector based on the points in fvMesh of OpenFOAM
void resVec2OFResField (const Vec resVec) const
assign the residual field in OpenFOAM based on the residual vector
void ofResField2ResVec (Vec resVec) const
assign the residual vector based on the residual field in OpenFOAM
void setPrimalBoundaryConditions ()
set the boundary conditions based on parameters defined in DAOption
void specialBCTreatment ()
apply special treatment for boundary conditions
void checkSpecialBCs ()
check if we need to do special treatment for boundary conditions
Public Attributes
wordList specialBCs
a list that contains the names of detected special boundary conditions
Protected Attributes
const fvMesh & mesh_
Foam::fvMesh object.
const DAOption & daOption_
Foam::DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
HashTable< wordList > stateInfo_
the StateInfo_ list from DAStateInfo object
Detailed Description
Definition at line 36 of file DAField.H.
Constructor & Destructor Documentation
DAField()
DAField (const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Constructors.
Definition at line 17 of file DAField.C.
References DAField::checkSpecialBCs(), DAOption::getOption(), DAStateInfo::New(), solverName, and DAField::stateInfo_.
~DAField()
virtual ~DAField () inline virtual
Destructor.
Definition at line 71 of file DAField.H.
References DAField::checkSpecialBCs(), DAField::ofField2StateVec(), DAField::ofMesh2PointVec(), DAField::ofResField2ResVec(), DAField::pointVec2OFMesh(), DAField::resVec2OFResField(), DAField::setPrimalBoundaryConditions(), DAField::specialBCTreatment(), and DAField::stateVec2OFField().
Member Function Documentation
ofField2StateVec()
void ofField2StateVec (Vec stateVec) const
set the state vector based on the latest fields in OpenFOAM
Definition at line 36 of file DAField.C.
References DAIndex::bFaceFaceI, DAIndex::bFacePatchI, DAField::daIndex_, DAIndex::getLocalAdjointStateIndex(), makeState, DAField::mesh_, DAIndex::nLocalInternalFaces, and DAField::stateInfo_.
Referenced by DAField::~DAField().
stateVec2OFField()
void stateVec2OFField (const Vec stateVec) const
assign the fields in OpenFOAM based on the state vector
Definition at line 126 of file DAField.C.
References DAIndex::bFaceFaceI, DAIndex::bFacePatchI, DAField::daIndex_, DAIndex::getLocalAdjointStateIndex(), makeState, DAField::mesh_, DAIndex::nLocalInternalFaces, and DAField::stateInfo_.
Referenced by DAResidual::masterFunction(), DAObjFunc::masterFunction(), and DAField::~DAField().
pointVec2OFMesh()
void pointVec2OFMesh (const Vec xvVec) const
assign the points in fvMesh of OpenFOAM based on the point vector
Definition at line 216 of file DAField.C.
References DAField::daIndex_, DAIndex::getLocalXvIndex(), mesh, and DAField::mesh_.
Referenced by DAResidual::masterFunction(), DAObjFunc::masterFunction(), and DAField::~DAField().
ofMesh2PointVec()
void ofMesh2PointVec (Vec xvVec) const
assign the point vector based on the points in fvMesh of OpenFOAM
Definition at line 261 of file DAField.C.
References DAField::daIndex_, DAIndex::getLocalXvIndex(), and DAField::mesh_.
Referenced by DAField::~DAField().
resVec2OFResField()
void resVec2OFResField (const Vec resVec) const
assign the residual field in OpenFOAM based on the residual vector
Definition at line 391 of file DAField.C.
References DAIndex::bFaceFaceI, DAIndex::bFacePatchI, DAField::daIndex_, DAIndex::getLocalAdjointStateIndex(), makeStateRes, DAField::mesh_, DAIndex::nLocalInternalFaces, and DAField::stateInfo_.
Referenced by DAField::~DAField().
ofResField2ResVec()
void ofResField2ResVec (Vec resVec) const
assign the residual vector based on the residual field in OpenFOAM
Definition at line 300 of file DAField.C.
References DAIndex::bFaceFaceI, DAIndex::bFacePatchI, DAField::daIndex_, DAIndex::getLocalAdjointStateIndex(), makeStateRes, DAField::mesh_, DAIndex::nLocalInternalFaces, and DAField::stateInfo_.
Referenced by DAResidual::masterFunction(), and DAField::~DAField().
setPrimalBoundaryConditions()
void setPrimalBoundaryConditions ()
set the boundary conditions based on parameters defined in DAOption
Definition at line 546 of file DAField.C.
References allOptions, DAField::daOption_, DAOption::getAllOptions(), and DAField::mesh_.
Referenced by DAField::~DAField().
specialBCTreatment()
void specialBCTreatment ()
apply special treatment for boundary conditions
Definition at line 521 of file DAField.C.
References DAField::mesh_, DAField::specialBCs, and U.
Referenced by DAResidual::masterFunction(), DAObjFunc::masterFunction(), and DAField::~DAField().
checkSpecialBCs()
void checkSpecialBCs ()
check if we need to do special treatment for boundary conditions
Definition at line 481 of file DAField.C.
References DAField::mesh_, DAField::specialBCs, and U.
Referenced by DAField::DAField(), and DAField::~DAField().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Foam::fvMesh object.
Definition at line 48 of file DAField.H.
Referenced by DAField::checkSpecialBCs(), DAField::ofField2StateVec(), DAField::ofMesh2PointVec(), DAField::ofResField2ResVec(), DAField::pointVec2OFMesh(), DAField::resVec2OFResField(), DAField::setPrimalBoundaryConditions(), DAField::specialBCTreatment(), and DAField::stateVec2OFField().
daOption_
const DAOption& daOption_ protected
Foam::DAOption object.
Definition at line 51 of file DAField.H.
Referenced by DAField::setPrimalBoundaryConditions().
daModel_
const DAModel& daModel_ protected
DAModel object.
Definition at line 54 of file DAField.H.
daIndex_
const DAIndex& daIndex_ protected
DAIndex object.
Definition at line 57 of file DAField.H.
Referenced by DAField::ofField2StateVec(), DAField::ofMesh2PointVec(), DAField::ofResField2ResVec(), DAField::pointVec2OFMesh(), DAField::resVec2OFResField(), and DAField::stateVec2OFField().
stateInfo_
HashTable<wordList> stateInfo_ protected
the StateInfo_ list from DAStateInfo object
Definition at line 60 of file DAField.H.
Referenced by DAField::DAField(), DAField::ofField2StateVec(), DAField::ofResField2ResVec(), DAField::resVec2OFResField(), and DAField::stateVec2OFField().
specialBCs
wordList specialBCs
a list that contains the names of detected special boundary conditions
Definition at line 105 of file DAField.H.
Referenced by DAField::checkSpecialBCs(), DAJacCon::checkSpecialBCs(), DAJacCondRdW::setupdRdWCon(), and DAField::specialBCTreatment().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAField/DAField.H
dafoam/src/adjoint/DAField/DAField.C