DAFoam: DASpalartAllmaras Class Reference
DASpalartAllmaras Class Reference
Public Member Functions
TypeName ("SpalartAllmaras")
DASpalartAllmaras (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DASpalartAllmaras ()
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
virtual void correctModelStates (wordList &modelStates) const
update the turbulence state for DAStateInfo::regStates_
virtual void correctNut ()
update nut based on other turbulence variables and update the BCs
virtual void correctBoundaryConditions ()
update turbulence variable boundary values
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctStateResidualModelCon (List< List< word >> &stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const
add the model residual connectivity to stateCon
virtual void calcResiduals (const dictionary &options)
compute the turbulence residuals
virtual void correct ()
solve the residual equations and update the state
Public Member Functions inherited from DATurbulenceModel
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable (autoPtr, DATurbulenceModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DATurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DATurbulenceModel ()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
void correctAlphat ()
update alphat
tmp< volSymmTensorField > devRhoReff () const
dev terms
tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U)
divDev terms
tmp< fvVectorMatrix > divDevReff (volVectorField &U)
divDev terms
tmp< volScalarField > nuEff () const
return effective viscosity
tmp< volScalarField > getNut ()
get the nut field
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
tmp< volScalarField > nu () const
get the nu field
tmp< volScalarField > getAlpha () const
get alpha field
tmp< volScalarField > getRho ()
get the density field
tmp< volScalarField > getPhase ()
get the phase field
scalar getPrt ()
get the turbulent Prandtl number
tmp< Foam::volScalarField > getMu () const
get mu
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void printYPlus () const
print the min max and mean yPlus to screen
Protected Member Functions
SA functions
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > Stilda (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fw (const volScalarField &Stilda) const
Protected Attributes
const volScalarField & y_
3D wall distance
label solveTurbState_ = 0
whether to solve for turb states
label printInterval_
time step interval to print residual
SA parameters
dimensionedScalar sigmaNut_
dimensionedScalar kappa_
dimensionedScalar Cb1_
dimensionedScalar Cb2_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar Cv1_
dimensionedScalar Cs_
Augmented variables for residual computation
volScalarField & nuTilda_
volScalarField nuTildaRes_
volScalarField nuTildaResPartDeriv_
Protected Attributes inherited from DATurbulenceModel
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const dictionary & allOptions_
all DAFoam options
volScalarField & nut_
turbulence viscosity
volVectorField & U_
velocity
surfaceScalarField & phi_
face flux
volScalarField phase_
phase field
surfaceScalarField & phaseRhoPhi_
phase*phi*density field
IOdictionary turbDict_
turbulence model property dict
dictionary coeffDict_
turbulence model parameters dict
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
dimensionedScalar nuTildaMin_
Lower limit for nuTilda.
scalar Pr_
Prandtl number.
scalar Prt_ = -9999.0
turbulent Prandtl number
Additional Inherited Members
Static Public Member Functions inherited from DATurbulenceModel
static autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Detailed Description
Definition at line 26 of file DASpalartAllmaras.H.
Constructor & Destructor Documentation
DASpalartAllmaras()
DASpalartAllmaras (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 19 of file DASpalartAllmaras.C.
References DAOption::getAllOptions(), and DASpalartAllmaras::printInterval_.
~DASpalartAllmaras()
virtual ~DASpalartAllmaras () inline virtual
Definition at line 89 of file DASpalartAllmaras.H.
References DASpalartAllmaras::addModelResidualCon(), DASpalartAllmaras::calcResiduals(), DASpalartAllmaras::correct(), DASpalartAllmaras::correctBoundaryConditions(), DASpalartAllmaras::correctModelStates(), DASpalartAllmaras::correctNut(), DASpalartAllmaras::correctStateResidualModelCon(), DASpalartAllmaras::DnuTildaEff(), and DASpalartAllmaras::updateIntermediateVariables().
Member Function Documentation
chi()
tmp< volScalarField > chi () const protected
Definition at line 95 of file DASpalartAllmaras.C.
References DATurbulenceModel::nu(), and DASpalartAllmaras::nuTilda_.
Referenced by DASpalartAllmaras::calcResiduals(), and DASpalartAllmaras::correctNut().
fv1()
tmp< volScalarField > fv1 (const volScalarField & chi) const protected
Definition at line 100 of file DASpalartAllmaras.C.
References DASpalartAllmaras::Cv1_.
Referenced by DASpalartAllmaras::calcResiduals(), DASpalartAllmaras::correctNut(), and DASpalartAllmaras::fv2().
fv2()
tmp< volScalarField > fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 107 of file DASpalartAllmaras.C.
References DASpalartAllmaras::fv1().
Referenced by DASpalartAllmaras::Stilda().
Stilda()
tmp< volScalarField > Stilda (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 114 of file DASpalartAllmaras.C.
References DASpalartAllmaras::Cs_, DASpalartAllmaras::fv2(), DASpalartAllmaras::kappa_, DASpalartAllmaras::nuTilda_, DATurbulenceModel::U_, and DASpalartAllmaras::y_.
Referenced by DASpalartAllmaras::calcResiduals().
fw()
tmp< volScalarField > fw (const volScalarField & Stilda) const protected
Definition at line 127 of file DASpalartAllmaras.C.
References DASpalartAllmaras::Cw2_, DASpalartAllmaras::Cw3_, DASpalartAllmaras::kappa_, DASpalartAllmaras::nuTilda_, and DASpalartAllmaras::y_.
Referenced by DASpalartAllmaras::calcResiduals().
TypeName()
TypeName ("SpalartAllmaras")
DnuTildaEff()
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
Definition at line 145 of file DASpalartAllmaras.C.
References DATurbulenceModel::nu(), DASpalartAllmaras::nuTilda_, and DASpalartAllmaras::sigmaNut_.
Referenced by DASpalartAllmaras::calcResiduals(), and DASpalartAllmaras::~DASpalartAllmaras().
correctModelStates()
void correctModelStates (wordList & modelStates) const virtual
update the turbulence state for DAStateInfo::regStates_
Implements DATurbulenceModel.
Definition at line 152 of file DASpalartAllmaras.C.
Referenced by DASpalartAllmaras::~DASpalartAllmaras().
correctNut()
void correctNut () virtual
update nut based on other turbulence variables and update the BCs
Implements DATurbulenceModel.
Definition at line 186 of file DASpalartAllmaras.C.
References DASpalartAllmaras::chi(), DATurbulenceModel::correctAlphat(), DASpalartAllmaras::fv1(), DATurbulenceModel::nut_, and DASpalartAllmaras::nuTilda_.
Referenced by DASpalartAllmaras::calcResiduals(), DASpalartAllmaras::updateIntermediateVariables(), and DASpalartAllmaras::~DASpalartAllmaras().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update turbulence variable boundary values
Implements DATurbulenceModel.
Definition at line 206 of file DASpalartAllmaras.C.
References DASpalartAllmaras::nuTilda_.
Referenced by DASpalartAllmaras::~DASpalartAllmaras().
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DATurbulenceModel.
Definition at line 217 of file DASpalartAllmaras.C.
References DASpalartAllmaras::correctNut().
Referenced by DASpalartAllmaras::~DASpalartAllmaras().
correctStateResidualModelCon()
void correctStateResidualModelCon (List< List< word >> & stateCon) const virtual
update the original variable connectivity for the adjoint state residuals in stateCon
Implements DATurbulenceModel.
Definition at line 228 of file DASpalartAllmaras.C.
Referenced by DASpalartAllmaras::~DASpalartAllmaras().
addModelResidualCon()
void addModelResidualCon (HashTable< List< List< word >>> & allCon) const virtual
add the model residual connectivity to stateCon
Implements DATurbulenceModel.
Definition at line 278 of file DASpalartAllmaras.C.
References DATurbulenceModel::mesh_.
Referenced by DASpalartAllmaras::~DASpalartAllmaras().
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute the turbulence residuals
Implements DATurbulenceModel.
Definition at line 376 of file DASpalartAllmaras.C.
References DATurbulenceModel::allOptions_, DAUtility::boundVar(), DASpalartAllmaras::Cb1_, DASpalartAllmaras::Cb2_, DASpalartAllmaras::chi(), DASpalartAllmaras::correctNut(), DASpalartAllmaras::Cw1_, DASpalartAllmaras::DnuTildaEff(), DASpalartAllmaras::fv1(), DASpalartAllmaras::fw(), DATurbulenceModel::mesh_, normalizeResiduals, DASpalartAllmaras::nuTilda_, DASpalartAllmaras::nuTildaRes_, DATurbulenceModel::phase_, DATurbulenceModel::phaseRhoPhi_, DASpalartAllmaras::printInterval_, DASpalartAllmaras::sigmaNut_, DASpalartAllmaras::solveTurbState_, DASpalartAllmaras::Stilda(), and DASpalartAllmaras::y_.
Referenced by DASpalartAllmaras::correct(), and DASpalartAllmaras::~DASpalartAllmaras().
correct()
void correct () virtual
solve the residual equations and update the state
Implements DATurbulenceModel.
Definition at line 356 of file DASpalartAllmaras.C.
References DASpalartAllmaras::calcResiduals(), and DASpalartAllmaras::solveTurbState_.
Referenced by DASpalartAllmaras::~DASpalartAllmaras().
Member Data Documentation
sigmaNut_
dimensionedScalar sigmaNut_ protected
Definition at line 33 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::calcResiduals(), and DASpalartAllmaras::DnuTildaEff().
kappa_
dimensionedScalar kappa_ protected
Definition at line 34 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::fw(), and DASpalartAllmaras::Stilda().
Cb1_
dimensionedScalar Cb1_ protected
Definition at line 35 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::calcResiduals().
Cb2_
dimensionedScalar Cb2_ protected
Definition at line 36 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::calcResiduals().
Cw1_
dimensionedScalar Cw1_ protected
Definition at line 37 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::calcResiduals().
Cw2_
dimensionedScalar Cw2_ protected
Definition at line 38 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::fw().
Cw3_
dimensionedScalar Cw3_ protected
Definition at line 39 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::fw().
Cv1_
dimensionedScalar Cv1_ protected
Definition at line 40 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::fv1().
Cs_
dimensionedScalar Cs_ protected
Definition at line 41 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::Stilda().
nuTilda_
volScalarField& nuTilda_ protected
Definition at line 64 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::calcResiduals(), DASpalartAllmaras::chi(), DASpalartAllmaras::correctBoundaryConditions(), DASpalartAllmaras::correctNut(), DASpalartAllmaras::DnuTildaEff(), DASpalartAllmaras::fw(), and DASpalartAllmaras::Stilda().
nuTildaRes_
volScalarField nuTildaRes_ protected
Definition at line 65 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::calcResiduals().
nuTildaResPartDeriv_
volScalarField nuTildaResPartDeriv_ protected
Definition at line 66 of file DASpalartAllmaras.H.
y_
const volScalarField& y_ protected
3D wall distance
Definition at line 70 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::calcResiduals(), DASpalartAllmaras::fw(), and DASpalartAllmaras::Stilda().
solveTurbState_
label solveTurbState_ = 0 protected
whether to solve for turb states
Definition at line 73 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::calcResiduals(), and DASpalartAllmaras::correct().
printInterval_
label printInterval_ protected
time step interval to print residual
Definition at line 76 of file DASpalartAllmaras.H.
Referenced by DASpalartAllmaras::calcResiduals(), and DASpalartAllmaras::DASpalartAllmaras().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DATurbulenceModel/DASpalartAllmaras.H
dafoam/src/adjoint/DAModel/DATurbulenceModel/DASpalartAllmaras.C