DAFoam: ColoringIncompressible Class Reference
ColoringIncompressible Class Reference
Public Member Functions
ColoringIncompressible (char *argsAll, PyObject *pyOptions)
Construct from components.
virtual ~ColoringIncompressible ()
Destructor.
void run ()
run
Detailed Description
Definition at line 39 of file ColoringIncompressible.H.
Constructor & Destructor Documentation
ColoringIncompressible (char * argsAll, PyObject * pyOptions)
Construct from components.
Definition at line 16 of file ColoringIncompressible.C.
~ColoringIncompressible () virtual
Destructor.
Definition at line 27 of file ColoringIncompressible.C.
Member Function Documentation
void run ()
run
Definition at line 31 of file ColoringIncompressible.C.
References allOptions, daIndex(), daModel(), daOption(), Foam::daStateInfo(), Foam::forAll(), mesh, DAStateInfo::New(), DAResidual::New(), DAObjFunc::New(), DAJacCon::New(), and solverName.
The documentation for this class was generated from the following files:
dafoam/src/utilities/pyColoringIncompressible/ColoringIncompressible.H
dafoam/src/utilities/pyColoringIncompressible/ColoringIncompressible.C