DAFoam: DAPartDerivdFdAOA Class Reference
DAPartDerivdFdAOA Class Reference
Public Member Functions
TypeName ("dFdAOA")
DAPartDerivdFdAOA (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAJacCon &daJacCon, const DAResidual &daResidual)
virtual ~DAPartDerivdFdAOA ()
virtual void initializePartDerivMat (const dictionary &options, Mat jacMat)
initialize partial derivative matrix
virtual void calcPartDerivMat (const dictionary &options, const Vec xvVec, const Vec wVec, Mat jacMat)
compute the partial derivative matrix
Public Member Functions inherited from DAPartDeriv
TypeName ("DAPartDeriv")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAPartDeriv, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAJacCon &daJacCon, const DAResidual &daResidual),(modelType, mesh, daOption, daModel, daIndex, daJacCon, daResidual))
DAPartDeriv (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAJacCon &daJacCon, const DAResidual &daResidual)
virtual ~DAPartDeriv ()
void clear ()
clear members in parent and child objects
void setdXvdFFDMat (const Mat dXvdFFDMat)
setup dXvdFFD matrix
void setNormStatePerturbVec (Vec *normStatePerturbVec)
setup the state normalization vector
Protected Attributes
label nLocalObjFuncGeoElements_
the number of objFunc discrete elements for local procs
Protected Attributes inherited from DAPartDeriv
const word modelType_
the name of the jacCon matrix
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
const DAJacCon & daJacCon_
DAJacCon object.
const DAResidual & daResidual_
DAResidual object.
const dictionary & allOptions_
all the DAFoam option
HashTable< wordList > stateInfo_
the stateInfo_ list from DAStateInfo object
Mat dXvdFFDMat_
volume mesh coordinates wrt the ffd point coordinate partials
Additional Inherited Members
Static Public Member Functions inherited from DAPartDeriv
static autoPtr< DAPartDeriv > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAJacCon &daJacCon, const DAResidual &daResidual)
Protected Member Functions inherited from DAPartDeriv
void perturbStates (const Vec jacConColors, const Vec normStatePerturbVec, const label colorI, const scalar delta, Vec wVec)
perturb state variables given a color index
void perturbBC (const dictionary options, const scalar delta)
perturb the values in the boundary condition
void setPartDerivMat (const Vec resVec, const Vec coloredColumn, const label transposed, Mat jacMat, const scalar jacLowerBound=1e-30) const
set values for the partial derivative matrix
void perturbAOA (const dictionary options, const scalar delta)
perturb the angle of attack
Detailed Description
Definition at line 26 of file DAPartDerivdFdAOA.H.
Constructor & Destructor Documentation
DAPartDerivdFdAOA()
DAPartDerivdFdAOA (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex, const DAJacCon & daJacCon, const DAResidual & daResidual)
Definition at line 19 of file DAPartDerivdFdAOA.C.
~DAPartDerivdFdAOA()
virtual ~DAPartDerivdFdAOA () inline virtual
Definition at line 49 of file DAPartDerivdFdAOA.H.
Member Function Documentation
TypeName()
TypeName ("dFdAOA")
initializePartDerivMat()
void initializePartDerivMat (const dictionary & options, Mat jacMat) virtual
initialize partial derivative matrix
Implements DAPartDeriv.
Definition at line 40 of file DAPartDerivdFdAOA.C.
References DAPartDeriv::mesh_.
calcPartDerivMat()
void calcPartDerivMat (const dictionary & options, const Vec xvVec, const Vec wVec, Mat jacMat) virtual
compute the partial derivative matrix
Implements DAPartDeriv.
Definition at line 69 of file DAPartDerivdFdAOA.C.
References assignValueCheckAD, DAPartDeriv::daIndex_, DAPartDeriv::daModel_, DAPartDeriv::daOption_, DAPartDeriv::daResidual_, DAOption::getOption(), DAOption::getSubDictOption(), DAPartDeriv::mesh_, DAObjFunc::New(), and DAPartDeriv::perturbAOA().
Member Data Documentation
nLocalObjFuncGeoElements_
label nLocalObjFuncGeoElements_ protected
the number of objFunc discrete elements for local procs
Definition at line 32 of file DAPartDerivdFdAOA.H.
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAPartDeriv/DAPartDerivdFdAOA.H
dafoam/src/adjoint/DAPartDeriv/DAPartDerivdFdAOA.C