DAFoam: DAObjFunc Class Reference
DAObjFunc Class Reference abstract
Public Member Functions
TypeName ("DAObjFunc")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAObjFunc, dictionary,(const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict),(mesh, daOption, daModel, daIndex, daResidual, objFuncName, objFuncPart, objFuncDict))
DAObjFunc (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict)
virtual ~DAObjFunc ()
void clear ()
clear up members
void calcObjFuncSources (labelList &faceSources, labelList &cellSources)
calculate DAObjFunc::objFuncFaceSources_ and DAObjFunc::objFuncCellSources_
virtual void calcObjFunc (const labelList &objFuncFaceSources, const labelList &objFuncCellSources, scalarList &objFuncFaceValues, scalarList &objFuncCellValues, scalar &objFuncValue)=0
calculate the value of objective function
scalar getObjFuncValue ()
calcluate the value of objective function
scalar masterFunction (const dictionary &options, const Vec xvVec, const Vec wVec)
the master function to compute objective function given the state and point vectors
word getObjFuncName ()
return the name of objective function
word getObjFuncPart ()
return the part of objective function
word getObjFuncType ()
return the part of objective function
const labelList & getObjFuncFaceSources () const
return DAObjFunc::objFuncFaceSources_
const labelList & getObjFuncCellSources () const
return DAObjFunc::objFuncCellSources_
const scalarList & getObjFuncFaceValues () const
return DAObjFunc::objFuncFaceValues_
const scalarList & getObjFuncCellValues () const
return DAObjFunc::objFuncCellValues_
const List< List< word > > & getObjFuncConInfo () const
return DAObjFunc::objFuncConInfo_
Static Public Member Functions
static autoPtr< DAObjFunc > New (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict)
Public Attributes
scalar expSumKS = 1.0
expSumKS stores sum[exp(coeffKS*x_i)] for KS function which will be used to scale dFdW
Protected Attributes
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
const DAResidual & daResidual_
DAResidual object.
word objFuncName_
the name of the objective function
word objFuncPart_
the part of the objective function
word objFuncType_
the type of the objective function
const dictionary & objFuncDict_
dictionary containing the information for the objective function
DAField daField_
DAField object.
labelList objFuncFaceSources_
a sorted list of all face sources for the objective function
labelList objFuncCellSources_
a sorted list of all cell sources for the objective function
scalarList objFuncFaceValues_
value of the obj function on the discrete faces
scalarList objFuncCellValues_
value of the obj function in the discrete cells
scalar scale_
scale of the objective function
scalar objFuncValue_
the value of the objective function
List< List< word > > objFuncConInfo_
the connectivity information for the objective function
Detailed Description
Definition at line 33 of file DAObjFunc.H.
Constructor & Destructor Documentation
DAObjFunc()
DAObjFunc (const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex, const DAResidual & daResidual, const word objFuncName, const word objFuncPart, const dictionary & objFuncDict)
Definition at line 22 of file DAObjFunc.C.
References DAObjFunc::calcObjFuncSources(), DAObjFunc::objFuncCellSources_, DAObjFunc::objFuncCellValues_, DAObjFunc::objFuncFaceSources_, and DAObjFunc::objFuncFaceValues_.
~DAObjFunc()
virtual ~DAObjFunc () inline virtual
Definition at line 150 of file DAObjFunc.H.
Member Function Documentation
TypeName()
TypeName ("DAObjFunc")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , DAObjFunc , dictionary , (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict) , (mesh, daOption, daModel, daIndex, daResidual, objFuncName, objFuncPart, objFuncDict))
New()
autoPtr< DAObjFunc > New (const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex, const DAResidual & daResidual, const word objFuncName, const word objFuncPart, const dictionary & objFuncDict) static
Definition at line 62 of file DAObjFunc.C.
References daIndex(), daModel(), daOption(), DAOption::getAllOptions(), and mesh.
Referenced by DAPartDerivdFdFFD::calcPartDerivMat(), DAPartDerivdFdBC::calcPartDerivMat(), DAPartDerivdFdAOA::calcPartDerivMat(), DAPartDerivdFdW::calcPartDerivMat(), ColoringSolid::run(), ColoringCompressible::run(), ColoringIncompressible::run(), DASolver::setDAObjFuncList(), and DASolver::solveAdjoint().
clear()
void clear () inline
clear up members
Definition at line 155 of file DAObjFunc.H.
References DAObjFunc::calcObjFunc(), DAObjFunc::calcObjFuncSources(), DAObjFunc::getObjFuncValue(), and DAObjFunc::masterFunction().
calcObjFuncSources()
void calcObjFuncSources (labelList & faceSources, labelList & cellSources)
calculate DAObjFunc::objFuncFaceSources_ and DAObjFunc::objFuncCellSources_
Definition at line 123 of file DAObjFunc.C.
References DAObjFunc::mesh_, and DAObjFunc::objFuncDict_.
Referenced by DAObjFunc::clear(), and DAObjFunc::DAObjFunc().
calcObjFunc()
virtual void calcObjFunc (const labelList & objFuncFaceSources, const labelList & objFuncCellSources, scalarList & objFuncFaceValues, scalarList & objFuncCellValues, scalar & objFuncValue) pure virtual
calculate the value of objective function
Implemented in DAObjFuncForce, DAObjFuncWallHeatFlux, DAObjFuncTotalPressure, DAObjFuncMoment, and DAObjFuncVonMisesStressKS.
Referenced by DAObjFunc::clear(), and DAObjFunc::getObjFuncValue().
getObjFuncValue()
scalar getObjFuncValue ()
calcluate the value of objective function
Definition at line 291 of file DAObjFunc.C.
References DAObjFunc::calcObjFunc(), DAObjFunc::objFuncCellSources_, DAObjFunc::objFuncCellValues_, DAObjFunc::objFuncFaceSources_, DAObjFunc::objFuncFaceValues_, and DAObjFunc::objFuncValue_.
Referenced by DAObjFunc::clear(), DASolver::getObjFuncValue(), DAObjFunc::masterFunction(), and DASolver::printAllObjFuncs().
masterFunction()
scalar masterFunction (const dictionary & options, const Vec xvVec, const Vec wVec)
the master function to compute objective function given the state and point vectors
Definition at line 228 of file DAObjFunc.C.
References DAModel::correctBoundaryConditions(), DAResidual::correctBoundaryConditions(), DAObjFunc::daField_, daModel(), DAObjFunc::daModel_, DAObjFunc::daResidual_, DAObjFunc::getObjFuncValue(), DAField::pointVec2OFMesh(), DAField::specialBCTreatment(), DAField::stateVec2OFField(), DAModel::updateIntermediateVariables(), and DAResidual::updateIntermediateVariables().
Referenced by DAObjFunc::clear().
getObjFuncName()
word getObjFuncName () inline
return the name of objective function
Definition at line 187 of file DAObjFunc.H.
References DAObjFunc::objFuncName_.
Referenced by DASolver::getObjFuncValue(), and DASolver::printAllObjFuncs().
getObjFuncPart()
word getObjFuncPart () inline
return the part of objective function
Definition at line 193 of file DAObjFunc.H.
References DAObjFunc::objFuncPart_.
Referenced by DASolver::printAllObjFuncs().
getObjFuncType()
word getObjFuncType () inline
return the part of objective function
Definition at line 199 of file DAObjFunc.H.
References DAObjFunc::objFuncType_.
Referenced by DASolver::printAllObjFuncs().
getObjFuncFaceSources()
const labelList& getObjFuncFaceSources () const inline
return DAObjFunc::objFuncFaceSources_
Definition at line 205 of file DAObjFunc.H.
References DAObjFunc::objFuncFaceSources_.
getObjFuncCellSources()
const labelList& getObjFuncCellSources () const inline
return DAObjFunc::objFuncCellSources_
Definition at line 211 of file DAObjFunc.H.
References DAObjFunc::objFuncCellSources_.
getObjFuncFaceValues()
const scalarList& getObjFuncFaceValues () const inline
return DAObjFunc::objFuncFaceValues_
Definition at line 217 of file DAObjFunc.H.
References DAObjFunc::objFuncFaceValues_.
getObjFuncCellValues()
const scalarList& getObjFuncCellValues () const inline
return DAObjFunc::objFuncCellValues_
Definition at line 223 of file DAObjFunc.H.
References DAObjFunc::objFuncCellValues_.
getObjFuncConInfo()
const List<List<word> >& getObjFuncConInfo () const inline
return DAObjFunc::objFuncConInfo_
Definition at line 229 of file DAObjFunc.H.
References DAObjFunc::objFuncConInfo_.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
fvMesh
Definition at line 45 of file DAObjFunc.H.
Referenced by DAObjFuncVonMisesStressKS::calcObjFunc(), DAObjFuncMoment::calcObjFunc(), DAObjFuncTotalPressure::calcObjFunc(), DAObjFuncWallHeatFlux::calcObjFunc(), DAObjFuncForce::calcObjFunc(), DAObjFunc::calcObjFuncSources(), DAObjFuncForce::DAObjFuncForce(), DAObjFuncMoment::DAObjFuncMoment(), and DAObjFuncForce::updateForceDir().
daOption_
const DAOption& daOption_ protected
DAOption object.
Definition at line 48 of file DAObjFunc.H.
Referenced by DAObjFuncForce::DAObjFuncForce().
daModel_
const DAModel& daModel_ protected
DAModel object.
Definition at line 51 of file DAObjFunc.H.
Referenced by DAObjFunc::masterFunction().
daIndex_
const DAIndex& daIndex_ protected
DAIndex object.
Definition at line 54 of file DAObjFunc.H.
Referenced by DAObjFuncMoment::calcObjFunc(), DAObjFuncTotalPressure::calcObjFunc(), DAObjFuncWallHeatFlux::calcObjFunc(), and DAObjFuncForce::calcObjFunc().
daResidual_
const DAResidual& daResidual_ protected
DAResidual object.
Definition at line 57 of file DAObjFunc.H.
Referenced by DAObjFunc::masterFunction().
objFuncName_
word objFuncName_ protected
the name of the objective function
Definition at line 60 of file DAObjFunc.H.
Referenced by DAObjFunc::getObjFuncName().
objFuncPart_
word objFuncPart_ protected
the part of the objective function
Definition at line 63 of file DAObjFunc.H.
Referenced by DAObjFunc::getObjFuncPart().
objFuncType_
word objFuncType_ protected
the type of the objective function
Definition at line 66 of file DAObjFunc.H.
Referenced by DAObjFuncForce::DAObjFuncForce(), DAObjFuncMoment::DAObjFuncMoment(), DAObjFuncTotalPressure::DAObjFuncTotalPressure(), DAObjFuncVonMisesStressKS::DAObjFuncVonMisesStressKS(), DAObjFuncWallHeatFlux::DAObjFuncWallHeatFlux(), and DAObjFunc::getObjFuncType().
objFuncDict_
const dictionary& objFuncDict_ protected
dictionary containing the information for the objective function
Definition at line 69 of file DAObjFunc.H.
Referenced by DAObjFunc::calcObjFuncSources(), DAObjFuncForce::DAObjFuncForce(), DAObjFuncMoment::DAObjFuncMoment(), DAObjFuncTotalPressure::DAObjFuncTotalPressure(), DAObjFuncVonMisesStressKS::DAObjFuncVonMisesStressKS(), and DAObjFuncWallHeatFlux::DAObjFuncWallHeatFlux().
daField_
DAField daField_ protected
DAField object.
Definition at line 72 of file DAObjFunc.H.
Referenced by DAObjFunc::masterFunction().
objFuncFaceSources_
labelList objFuncFaceSources_ protected
a sorted list of all face sources for the objective function
Definition at line 75 of file DAObjFunc.H.
Referenced by DAObjFunc::DAObjFunc(), DAObjFunc::getObjFuncFaceSources(), and DAObjFunc::getObjFuncValue().
objFuncCellSources_
labelList objFuncCellSources_ protected
a sorted list of all cell sources for the objective function
Definition at line 78 of file DAObjFunc.H.
Referenced by DAObjFunc::DAObjFunc(), DAObjFunc::getObjFuncCellSources(), and DAObjFunc::getObjFuncValue().
objFuncFaceValues_
scalarList objFuncFaceValues_ protected
value of the obj function on the discrete faces
Definition at line 81 of file DAObjFunc.H.
Referenced by DAObjFunc::DAObjFunc(), DAObjFunc::getObjFuncFaceValues(), and DAObjFunc::getObjFuncValue().
objFuncCellValues_
scalarList objFuncCellValues_ protected
value of the obj function in the discrete cells
Definition at line 84 of file DAObjFunc.H.
Referenced by DAObjFunc::DAObjFunc(), DAObjFunc::getObjFuncCellValues(), and DAObjFunc::getObjFuncValue().
scale_
scalar scale_ protected
scale of the objective function
Definition at line 87 of file DAObjFunc.H.
Referenced by DAObjFuncVonMisesStressKS::calcObjFunc(), DAObjFuncMoment::calcObjFunc(), DAObjFuncTotalPressure::calcObjFunc(), DAObjFuncWallHeatFlux::calcObjFunc(), DAObjFuncForce::calcObjFunc(), DAObjFuncForce::DAObjFuncForce(), DAObjFuncMoment::DAObjFuncMoment(), DAObjFuncTotalPressure::DAObjFuncTotalPressure(), DAObjFuncVonMisesStressKS::DAObjFuncVonMisesStressKS(), and DAObjFuncWallHeatFlux::DAObjFuncWallHeatFlux().
objFuncValue_
scalar objFuncValue_ protected
the value of the objective function
Definition at line 90 of file DAObjFunc.H.
Referenced by DAObjFunc::getObjFuncValue().
objFuncConInfo_
List<List<word> > objFuncConInfo_ protected
the connectivity information for the objective function
Definition at line 93 of file DAObjFunc.H.
Referenced by DAObjFuncForce::DAObjFuncForce(), DAObjFuncMoment::DAObjFuncMoment(), DAObjFuncTotalPressure::DAObjFuncTotalPressure(), DAObjFuncVonMisesStressKS::DAObjFuncVonMisesStressKS(), DAObjFuncWallHeatFlux::DAObjFuncWallHeatFlux(), and DAObjFunc::getObjFuncConInfo().
expSumKS
scalar expSumKS = 1.0
expSumKS stores sum[exp(coeffKS*x_i)] for KS function which will be used to scale dFdW
Definition at line 235 of file DAObjFunc.H.
Referenced by DAObjFuncVonMisesStressKS::calcObjFunc().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAObjFunc/DAObjFunc.H
dafoam/src/adjoint/DAObjFunc/DAObjFunc.C