DAFoam: DAJacCon Class Reference
DAJacCon Class Reference abstract
Public Member Functions
TypeName ("DAJacCon")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAJacCon, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAJacCon (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAJacCon ()
virtual void clear ()=0
clear members in parent and child objects
virtual void setupJacConPreallocation (const dictionary &options)
calculate the preallocation vector for initializing the JacCon mat, if necessary
virtual void initializeJacCon (const dictionary &options)=0
initialize the state Jacobian connectivity matrix
virtual void setupJacCon (const dictionary &options)=0
assign 1 to all non-zero elements for the Jacobian connecitivyt matrix
label getNJacConColors () const
get the number of JacCon colors
virtual void preallocatedRdW (Mat dRMat, const label transposed) const
preallocate dRdW matrix using the preallocVec
void calcJacConColoring (const word postFix="")
compute graph coloring for Jacobian connectivity matrix
void readJacConColoring (const word postFix="")
read colors for JacCon
label coloringExists (const word postFix="") const
whether the coloring file exists
Vec getJacConColor () const
return DAJacCon::jacConColors_
void calcColoredColumns (const label colorI, Vec coloredColumn) const
calculate the colored column vector
virtual void setObjFuncVec (scalarList objFuncFaceValues, scalarList objFuncCellValues, Vec objFuncVec) const
assign values for the objective function vector based on the face and cell value lists
Static Public Member Functions
static autoPtr< DAJacCon > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Protected Member Functions
void initializeStateBoundaryCon ()
initialize state boundary connection
void calcNeiBFaceGlobalCompact (labelList &neiBFaceGlobalCompact)
calculate DAJacCon::neiBFaceGlobalCompact_
label getLocalCoupledBFaceIndex (const label localFaceI) const
given a local face index, return the local index of the coupled boundary face
void setupStateBoundaryCon (Mat *stateBoundaryCon)
calculate DAJacCon::stateBoundaryCon_
void setupStateBoundaryConID (Mat *stateBoundaryConID)
calculate DAJacCon::stateBoundaryConID_
void createConnectionMat (Mat *connectedStates)
allocate connectedState matrix
void addStateConnections (Mat connections, const label cellI, const label connectedLevelLocal, const wordList connectedStatesLocal, const List< List< word >> connectedStateInterProc, const label addFace)
a high-level function to add connected state column indices to the connectivity matrix
void setConnections (Mat conMat, const label idx) const
add value 1 for the colume idx to conMat
void setupJacobianConnections (Mat conMat, Mat connections, const label idxI)
assign values in connections to a specific row idxI in conMat
void combineStateBndCon (Mat *stateBoundaryCon, Mat *stateBoundaryConTmp)
combine stateBoundaryCon and stateBoundaryConTmp, this is to ensure including all connected states for parallel cases
void addConMatCell (Mat conMat, const label gRow, const label cellI, const word stateName, const PetscScalar val)
add val to the gRow row in conMat, the column indice are the state (given by stateName) for a given cellI
void addConMatNeighbourCells (Mat conMat, const label gRow, const label cellI, const word stateName, const PetscScalar val)
add val to gRow row in conMat, column indice are the neighbouring states (given by stateName) for a given cellI
void addConMatCellFaces (Mat conMat, const label gRow, const label cellI, const word stateName, const PetscScalar val)
add val to gRow row in conMat, column indice are the faces (given by stateName) for a given cellI
void addBoundaryFaceConnections (Mat conMat, const label gRow, const label cellI, const labelList v, const List< List< word >> connectedStates, const label addFaces)
add the column index of the (iner-proc) connected states and faces to conMat, given a local face index
void clearDAJacConMembers ()
clear members in DAJacCon
void checkSpecialBCs ()
check if there is special boundary conditions that need special treatment in jacCon_
void setPIVVec (Vec iSPIV, const label idxI)
function used to add connectivity for pressureInletVelocity
label addPhi4PIV (const word stateName, const label idxI, const label comp=-1)
add connectivity phi for pressureInletVelocity
Protected Attributes
const word modelType_
the name of the jacCon matrix
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
DAColoring daColoring_
DAColoring object.
DAField daField_
DAField object.
HashTable< wordList > stateInfo_
the regState_ list from DAStateInfo object
Mat stateBoundaryCon_
matrix to store boundary connectivity levels for state Jacobians
Mat stateBoundaryConID_
matrix to store boundary connectivity ID for state Jacobians
labelList neiBFaceGlobalCompact_
neibough face global index for a given local boundary face
Mat jacCon_
Jacobian connectivity mat.
Vec jacConColors_
jacCon matrix colors
label nJacConColors_
number of jacCon colors
Vec isPIVBCState_
a vector to show whether a state is connected to a pressureInletVelocity boundary face (3 level max)
Detailed Description
Definition at line 34 of file DAJacCon.H.
Constructor & Destructor Documentation
DAJacCon()
DAJacCon (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 22 of file DAJacCon.C.
References DAJacCon::checkSpecialBCs(), DAOption::getOption(), DAStateInfo::New(), solverName, and DAJacCon::stateInfo_.
~DAJacCon()
virtual ~DAJacCon () inline virtual
Definition at line 233 of file DAJacCon.H.
References DAJacCon::clear(), DAJacCon::initializeJacCon(), DAJacCon::setupJacCon(), and DAJacCon::setupJacConPreallocation().
Member Function Documentation
initializeStateBoundaryCon()
void initializeStateBoundaryCon () protected
initialize state boundary connection
Definition at line 88 of file DAJacCon.C.
References DAJacCon::calcNeiBFaceGlobalCompact(), DAJacCon::daOption_, DAOption::getOption(), DAJacCon::neiBFaceGlobalCompact_, DAJacCon::setupStateBoundaryCon(), DAJacCon::setupStateBoundaryConID(), DAJacCon::stateBoundaryCon_, DAJacCon::stateBoundaryConID_, and DAUtility::writeMatrixBinary().
Referenced by DAJacCondFdW::DAJacCondFdW(), and DAJacCondRdW::DAJacCondRdW().
calcNeiBFaceGlobalCompact()
void calcNeiBFaceGlobalCompact (labelList & neiBFaceGlobalCompact) protected
calculate DAJacCon::neiBFaceGlobalCompact_
Definition at line 568 of file DAJacCon.C.
References DAJacCon::daIndex_, DAIndex::globalCoupledBFaceNumbering, DAJacCon::mesh_, DAIndex::nLocalBoundaryFaces, and DAIndex::nLocalInternalFaces.
Referenced by DAJacCon::initializeStateBoundaryCon().
getLocalCoupledBFaceIndex()
label getLocalCoupledBFaceIndex (const label localFaceI) const protected
given a local face index, return the local index of the coupled boundary face
Definition at line 635 of file DAJacCon.C.
References DAJacCon::mesh_.
Referenced by DAJacCon::addBoundaryFaceConnections(), and DAJacCondRdW::setupdRdWCon().
setupStateBoundaryCon()
void setupStateBoundaryCon (Mat * stateBoundaryCon) protected
calculate DAJacCon::stateBoundaryCon_
Definition at line 682 of file DAJacCon.C.
References DAJacCon::addBoundaryFaceConnections(), DAJacCon::addConMatCell(), DAJacCon::addConMatCellFaces(), DAJacCon::addConMatNeighbourCells(), DAIndex::adjStateNames, DAIndex::adjStateType, DAJacCon::combineStateBndCon(), DAJacCon::daIndex_, DAJacCon::mesh_, DAJacCon::neiBFaceGlobalCompact_, DAIndex::nLocalAdjointStates, DAIndex::nLocalCoupledBFaces, DAIndex::nLocalInternalFaces, and DAJacCon::stateInfo_.
Referenced by DAJacCon::initializeStateBoundaryCon().
setupStateBoundaryConID()
void setupStateBoundaryConID (Mat * stateBoundaryConID) protected
calculate DAJacCon::stateBoundaryConID_
Definition at line 1325 of file DAJacCon.C.
References DAIndex::calcAdjStateID4GlobalAdjIdx(), DAJacCon::daIndex_, DAUtility::isValueCloseToRef(), DAIndex::nGlobalAdjointStates, DAIndex::nLocalAdjointStates, DAIndex::nLocalCoupledBFaces, DAJacCon::stateBoundaryCon_, and dafoam_plot3dtransform::vals.
Referenced by DAJacCon::initializeStateBoundaryCon().
createConnectionMat()
void createConnectionMat (Mat * connectedStates) protected
allocate connectedState matrix
Definition at line 159 of file DAJacCon.C.
References DAJacCon::daIndex_, and DAIndex::nGlobalAdjointStates.
Referenced by DAJacCondRdW::setupdRdWCon(), and DAJacCondFdW::setupJacCon().
addStateConnections()
void addStateConnections (Mat connections, const label cellI, const label connectedLevelLocal, const wordList connectedStatesLocal, const List< List< word >> connectedStateInterProc, const label addFace) protected
a high-level function to add connected state column indices to the connectivity matrix
Definition at line 186 of file DAJacCon.C.
References DAJacCon::addBoundaryFaceConnections(), DAJacCon::addConMatCellFaces(), DAJacCon::addConMatNeighbourCells(), DAIndex::adjStateType, DAJacCon::daIndex_, DAIndex::getGlobalAdjointStateIndex(), DAJacCon::mesh_, DAJacCon::setConnections(), and DAJacCon::stateInfo_.
Referenced by DAJacCondRdW::setupdRdWCon(), and DAJacCondFdW::setupJacCon().
setConnections()
void setConnections (Mat conMat, const label idx) const protected
add value 1 for the colume idx to conMat
Definition at line 551 of file DAJacCon.C.
Referenced by DAJacCon::addStateConnections(), and DAJacCondRdW::setupdRdWCon().
setupJacobianConnections()
void setupJacobianConnections (Mat conMat, Mat connections, const label idxI) protected
assign values in connections to a specific row idxI in conMat
Definition at line 124 of file DAJacCon.C.
References dafoam_plot3dtransform::vals.
Referenced by DAJacCondRdW::setupdRdWCon(), and DAJacCondFdW::setupJacCon().
combineStateBndCon()
void combineStateBndCon (Mat * stateBoundaryCon, Mat * stateBoundaryConTmp) protected
combine stateBoundaryCon and stateBoundaryConTmp, this is to ensure including all connected states for parallel cases
Definition at line 1089 of file DAJacCon.C.
References DAJacCon::addBoundaryFaceConnections(), DAJacCon::daIndex_, DAJacCon::mesh_, DAJacCon::neiBFaceGlobalCompact_, DAIndex::nLocalAdjointStates, DAIndex::nLocalCoupledBFaces, DAIndex::nLocalInternalFaces, and dafoam_plot3dtransform::vals.
Referenced by DAJacCon::setupStateBoundaryCon().
addConMatCell()
void addConMatCell (Mat conMat, const label gRow, const label cellI, const word stateName, const PetscScalar val) protected
add val to the gRow row in conMat, the column indice are the state (given by stateName) for a given cellI
Definition at line 1391 of file DAJacCon.C.
References DAIndex::adjStateType, DAJacCon::daIndex_, and DAIndex::getGlobalAdjointStateIndex().
Referenced by DAJacCon::setupStateBoundaryCon().
addConMatNeighbourCells()
void addConMatNeighbourCells (Mat conMat, const label gRow, const label cellI, const word stateName, const PetscScalar val) protected
add val to gRow row in conMat, column indice are the neighbouring states (given by stateName) for a given cellI
Definition at line 1450 of file DAJacCon.C.
References DAIndex::adjStateType, DAJacCon::daIndex_, DAIndex::getGlobalAdjointStateIndex(), and DAJacCon::mesh_.
Referenced by DAJacCon::addStateConnections(), and DAJacCon::setupStateBoundaryCon().
addConMatCellFaces()
void addConMatCellFaces (Mat conMat, const label gRow, const label cellI, const word stateName, const PetscScalar val) protected
add val to gRow row in conMat, column indice are the faces (given by stateName) for a given cellI
Definition at line 1519 of file DAJacCon.C.
References DAJacCon::daIndex_, DAIndex::getGlobalAdjointStateIndex(), and DAJacCon::mesh_.
Referenced by DAJacCon::addStateConnections(), and DAJacCon::setupStateBoundaryCon().
addBoundaryFaceConnections()
void addBoundaryFaceConnections (Mat conMat, const label gRow, const label cellI, const labelList v, const List< List< word >> connectedStates, const label addFaces) protected
add the column index of the (iner-proc) connected states and faces to conMat, given a local face index
Definition at line 1575 of file DAJacCon.C.
References DAIndex::adjStateID, DAJacCon::daIndex_, DAJacCon::getLocalCoupledBFaceIndex(), DAIndex::globalCoupledBFaceNumbering, DAIndex::isCoupledFace, DAJacCon::mesh_, DAJacCon::stateBoundaryCon_, DAJacCon::stateBoundaryConID_, and dafoam_plot3dtransform::vals.
Referenced by DAJacCon::addStateConnections(), DAJacCon::combineStateBndCon(), and DAJacCon::setupStateBoundaryCon().
clearDAJacConMembers()
void clearDAJacConMembers () inline protected
clear members in DAJacCon
Definition at line 164 of file DAJacCon.H.
References DAJacCon::checkSpecialBCs().
Referenced by DAJacCondFdW::clear(), and DAJacCondRdW::clear().
checkSpecialBCs()
void checkSpecialBCs () protected
check if there is special boundary conditions that need special treatment in jacCon_
Definition at line 2081 of file DAJacCon.C.
References DAJacCon::daField_, DAJacCon::daIndex_, DAJacCon::daOption_, DAOption::getOption(), DAJacCon::isPIVBCState_, DAJacCon::mesh_, DAIndex::nLocalAdjointStates, DAJacCon::setPIVVec(), DAField::specialBCs, U, and DAUtility::writeVectorASCII().
Referenced by DAJacCon::clearDAJacConMembers(), and DAJacCon::DAJacCon().
setPIVVec()
void setPIVVec (Vec iSPIV, const label idxI) protected
function used to add connectivity for pressureInletVelocity
Definition at line 2160 of file DAJacCon.C.
References DAIndex::adjStateNames, DAIndex::adjStateType, DAJacCon::daIndex_, DAIndex::getGlobalAdjointStateIndex(), and DAJacCon::mesh_.
Referenced by DAJacCon::checkSpecialBCs().
addPhi4PIV()
label addPhi4PIV (const word stateName, const label idxI, const label comp = -1) protected
add connectivity phi for pressureInletVelocity
Definition at line 2197 of file DAJacCon.C.
References DAJacCon::daIndex_, DAIndex::getLocalAdjointStateIndex(), DAJacCon::isPIVBCState_, and DAUtility::isValueCloseToRef().
TypeName()
TypeName ("DAJacCon")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , DAJacCon , dictionary , (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex) , (modelType, mesh, daOption, daModel, daIndex))
New()
autoPtr< DAJacCon > New (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex) static
Definition at line 47 of file DAJacCon.C.
References daIndex(), daModel(), daOption(), DAOption::getAllOptions(), and mesh.
Referenced by DASolver::calcdFdACT(), DASolver::calcdFdAOA(), DASolver::calcdFdBC(), DASolver::calcdFdFFD(), DASolver::calcdFdW(), DASolver::calcdRdACT(), DASolver::calcdRdAOA(), DASolver::calcdRdBC(), DASolver::calcdRdFFD(), DASolver::calcdRdWT(), ColoringSolid::run(), ColoringIncompressible::run(), and ColoringCompressible::run().
clear()
virtual void clear () pure virtual
clear members in parent and child objects
Implemented in DAJacCondRdW, DAJacCondFdW, and DAJacConDummy.
Referenced by DAJacCon::~DAJacCon().
setupJacConPreallocation()
void setupJacConPreallocation (const dictionary & options) virtual
calculate the preallocation vector for initializing the JacCon mat, if necessary
Reimplemented in DAJacCondRdW.
Definition at line 1898 of file DAJacCon.C.
References DAJacCon::modelType_.
Referenced by DAJacCon::~DAJacCon().
initializeJacCon()
virtual void initializeJacCon (const dictionary & options) pure virtual
initialize the state Jacobian connectivity matrix
Implemented in DAJacCondRdW, DAJacCondFdW, and DAJacConDummy.
Referenced by DAJacCon::~DAJacCon().
setupJacCon()
virtual void setupJacCon (const dictionary & options) pure virtual
assign 1 to all non-zero elements for the Jacobian connecitivyt matrix
Implemented in DAJacCondRdW, DAJacCondFdW, and DAJacConDummy.
Referenced by DAJacCon::~DAJacCon().
getNJacConColors()
label getNJacConColors () const inline
get the number of JacCon colors
Definition at line 252 of file DAJacCon.H.
References DAJacCon::calcJacConColoring(), DAJacCon::coloringExists(), DAJacCon::nJacConColors_, DAJacCon::preallocatedRdW(), and DAJacCon::readJacConColoring().
Referenced by DAPartDerivdRdW::calcPartDerivMat(), and DAPartDerivdFdW::calcPartDerivMat().
preallocatedRdW()
void preallocatedRdW (Mat dRMat, const label transposed) const virtual
preallocate dRdW matrix using the preallocVec
Reimplemented in DAJacCondRdW.
Definition at line 1913 of file DAJacCon.C.
References DAJacCon::modelType_.
Referenced by DAJacCon::getNJacConColors(), and DAPartDerivdRdW::initializePartDerivMat().
calcJacConColoring()
void calcJacConColoring (const word postFix = "")
compute graph coloring for Jacobian connectivity matrix
Definition at line 1799 of file DAJacCon.C.
References DAJacCon::daColoring_, DAJacCon::daOption_, DAOption::getOption(), DAJacCon::jacCon_, DAJacCon::jacConColors_, DAJacCon::modelType_, DAJacCon::nJacConColors_, DAColoring::parallelD2Coloring(), DAColoring::validateColoring(), and DAUtility::writeVectorBinary().
Referenced by DAJacCon::getNJacConColors().
readJacConColoring()
void readJacConColoring (const word postFix = "")
read colors for JacCon
Definition at line 1862 of file DAJacCon.C.
References DAJacCon::daColoring_, DAJacCon::jacCon_, DAJacCon::jacConColors_, DAJacCon::modelType_, DAJacCon::nJacConColors_, DAUtility::readVectorBinary(), and DAColoring::validateColoring().
Referenced by DAJacCon::getNJacConColors().
coloringExists()
label coloringExists (const word postFix = "") const
whether the coloring file exists
Definition at line 1768 of file DAJacCon.C.
References DAJacCon::modelType_.
Referenced by DAJacCon::getNJacConColors().
getJacConColor()
Vec getJacConColor () const inline
return DAJacCon::jacConColors_
Definition at line 272 of file DAJacCon.H.
References DAJacCon::calcColoredColumns(), DAJacCon::jacConColors_, and DAJacCon::setObjFuncVec().
Referenced by DAPartDerivdRdW::calcPartDerivMat(), and DAPartDerivdFdW::calcPartDerivMat().
calcColoredColumns()
void calcColoredColumns (const label colorI, Vec coloredColumn) const
calculate the colored column vector
Definition at line 1948 of file DAJacCon.C.
References DAJacCon::daOption_, DAOption::getOption(), DAUtility::isValueCloseToRef(), DAJacCon::jacCon_, and DAJacCon::jacConColors_.
Referenced by DAPartDerivdRdW::calcPartDerivMat(), DAPartDerivdFdW::calcPartDerivMat(), and DAJacCon::getJacConColor().
setObjFuncVec()
void setObjFuncVec (scalarList objFuncFaceValues, scalarList objFuncCellValues, Vec objFuncVec) const virtual
assign values for the objective function vector based on the face and cell value lists
Reimplemented in DAJacCondFdW.
Definition at line 1930 of file DAJacCon.C.
References DAJacCon::modelType_.
Referenced by DAPartDerivdFdW::calcPartDerivMat(), and DAJacCon::getJacConColor().
Member Data Documentation
modelType_
const word modelType_ protected
the name of the jacCon matrix
Definition at line 46 of file DAJacCon.H.
Referenced by DAJacCon::calcJacConColoring(), DAJacCon::coloringExists(), DAJacCon::preallocatedRdW(), DAJacCon::readJacConColoring(), DAJacCon::setObjFuncVec(), and DAJacCon::setupJacConPreallocation().
mesh_
const fvMesh& mesh_ protected
fvMesh
Definition at line 49 of file DAJacCon.H.
Referenced by DAJacCon::addBoundaryFaceConnections(), DAJacCon::addConMatCellFaces(), DAJacCon::addConMatNeighbourCells(), DAJacCon::addStateConnections(), DAJacCon::calcNeiBFaceGlobalCompact(), DAJacCon::checkSpecialBCs(), DAJacCon::combineStateBndCon(), DAJacCon::getLocalCoupledBFaceIndex(), DAJacCon::setPIVVec(), DAJacCondRdW::setupdRdWCon(), DAJacCondFdW::setupJacCon(), and DAJacCon::setupStateBoundaryCon().
daOption_
const DAOption& daOption_ protected
DAOption object.
Definition at line 52 of file DAJacCon.H.
Referenced by DAJacCon::calcColoredColumns(), DAJacCon::calcJacConColoring(), DAJacCon::checkSpecialBCs(), DAJacCondRdW::initializeJacCon(), DAJacCon::initializeStateBoundaryCon(), DAJacCondRdW::setupdRdWCon(), and DAJacCondFdW::setupJacCon().
daModel_
const DAModel& daModel_ protected
DAModel object.
Definition at line 55 of file DAJacCon.H.
daIndex_
const DAIndex& daIndex_ protected
DAIndex object.
Definition at line 58 of file DAJacCon.H.
Referenced by DAJacCon::addBoundaryFaceConnections(), DAJacCon::addConMatCell(), DAJacCon::addConMatCellFaces(), DAJacCon::addConMatNeighbourCells(), DAJacCon::addPhi4PIV(), DAJacCon::addStateConnections(), DAJacCondRdW::allocateJacobianConnections(), DAJacCon::calcNeiBFaceGlobalCompact(), DAJacCon::checkSpecialBCs(), DAJacCon::combineStateBndCon(), DAJacCon::createConnectionMat(), DAJacCondFdW::initializeJacCon(), DAJacCondRdW::initializeJacCon(), DAJacCondFdW::initializePetscVecs(), DAJacCondRdW::initializePetscVecs(), DAJacCondRdW::preallocateJacobianMatrix(), DAJacCon::setPIVVec(), DAJacCondRdW::setupdRdWCon(), DAJacCondFdW::setupJacCon(), DAJacCon::setupStateBoundaryCon(), and DAJacCon::setupStateBoundaryConID().
daColoring_
DAColoring daColoring_ protected
DAColoring object.
Definition at line 61 of file DAJacCon.H.
Referenced by DAJacCon::calcJacConColoring(), and DAJacCon::readJacConColoring().
daField_
DAField daField_ protected
DAField object.
Definition at line 64 of file DAJacCon.H.
Referenced by DAJacCon::checkSpecialBCs(), and DAJacCondRdW::setupdRdWCon().
stateInfo_
HashTable<wordList> stateInfo_ protected
the regState_ list from DAStateInfo object
Definition at line 67 of file DAJacCon.H.
Referenced by DAJacCon::addStateConnections(), DAJacCon::DAJacCon(), DAJacCondRdW::setupdRdWCon(), DAJacCondFdW::setupJacCon(), and DAJacCon::setupStateBoundaryCon().
stateBoundaryCon_
Mat stateBoundaryCon_ protected
matrix to store boundary connectivity levels for state Jacobians
Definition at line 70 of file DAJacCon.H.
Referenced by DAJacCon::addBoundaryFaceConnections(), DAJacCon::initializeStateBoundaryCon(), DAJacCondRdW::setupdRdWCon(), and DAJacCon::setupStateBoundaryConID().
stateBoundaryConID_
Mat stateBoundaryConID_ protected
matrix to store boundary connectivity ID for state Jacobians
Definition at line 73 of file DAJacCon.H.
Referenced by DAJacCon::addBoundaryFaceConnections(), DAJacCon::initializeStateBoundaryCon(), and DAJacCondRdW::setupdRdWCon().
neiBFaceGlobalCompact_
labelList neiBFaceGlobalCompact_ protected
neibough face global index for a given local boundary face
Definition at line 76 of file DAJacCon.H.
Referenced by DAJacCon::combineStateBndCon(), DAJacCon::initializeStateBoundaryCon(), and DAJacCon::setupStateBoundaryCon().
jacCon_
Mat jacCon_ protected
Jacobian connectivity mat.
Definition at line 79 of file DAJacCon.H.
Referenced by DAJacCon::calcColoredColumns(), DAJacCon::calcJacConColoring(), DAJacCondFdW::initializeJacCon(), DAJacCondRdW::initializeJacCon(), DAJacCon::readJacConColoring(), DAJacCondRdW::setupdRdWCon(), and DAJacCondFdW::setupJacCon().
jacConColors_
Vec jacConColors_ protected
jacCon matrix colors
Definition at line 82 of file DAJacCon.H.
Referenced by DAJacCon::calcColoredColumns(), DAJacCon::calcJacConColoring(), DAJacCon::getJacConColor(), DAJacCondFdW::initializePetscVecs(), DAJacCondRdW::initializePetscVecs(), and DAJacCon::readJacConColoring().
nJacConColors_
label nJacConColors_ protected
number of jacCon colors
Definition at line 85 of file DAJacCon.H.
Referenced by DAJacCon::calcJacConColoring(), DAJacCon::getNJacConColors(), and DAJacCon::readJacConColoring().
isPIVBCState_
Vec isPIVBCState_ protected
a vector to show whether a state is connected to a pressureInletVelocity boundary face (3 level max)
Definition at line 179 of file DAJacCon.H.
Referenced by DAJacCon::addPhi4PIV(), and DAJacCon::checkSpecialBCs().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAJacCon/DAJacCon.H
dafoam/src/adjoint/DAJacCon/DAJacCon.C