DAFoam: DAResidualDummy Class Reference
DAResidualDummy Class Reference
Public Member Functions
TypeName ("dummy")
DAResidualDummy (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAResidualDummy ()
virtual void clear ()
clear the members
virtual void calcResiduals (const dictionary &options)
compute residual
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctBoundaryConditions ()
update the boundary condition for all the states in the selected solver
Public Member Functions inherited from DAResidual
TypeName ("DAResidual")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAResidual, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAResidual (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAResidual ()
void masterFunction (const dictionary &options, const Vec xvVec, const Vec wVec, Vec resVec)
the master function that compute the residual vector given the state and point vectors
Additional Inherited Members
Static Public Member Functions inherited from DAResidual
static autoPtr< DAResidual > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Protected Attributes inherited from DAResidual
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex.
DAField daField_
DAField object.
Detailed Description
Definition at line 27 of file DAResidualDummy.H.
Constructor & Destructor Documentation
DAResidualDummy()
DAResidualDummy (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 19 of file DAResidualDummy.C.
~DAResidualDummy()
virtual ~DAResidualDummy () inline virtual
Definition at line 46 of file DAResidualDummy.H.
References DAResidualDummy::calcResiduals(), DAResidualDummy::clear(), DAResidualDummy::correctBoundaryConditions(), and DAResidualDummy::updateIntermediateVariables().
Member Function Documentation
TypeName()
TypeName ("dummy")
clear()
void clear () virtual
clear the members
Implements DAResidual.
Definition at line 31 of file DAResidualDummy.C.
Referenced by DAResidualDummy::~DAResidualDummy().
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute residual
Implements DAResidual.
Definition at line 35 of file DAResidualDummy.C.
Referenced by DAResidualDummy::~DAResidualDummy().
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DAResidual.
Definition at line 39 of file DAResidualDummy.C.
Referenced by DAResidualDummy::~DAResidualDummy().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update the boundary condition for all the states in the selected solver
Implements DAResidual.
Definition at line 44 of file DAResidualDummy.C.
Referenced by DAResidualDummy::~DAResidualDummy().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAResidual/DAResidualDummy.H
dafoam/src/adjoint/DAResidual/DAResidualDummy.C