DAFoam: DAkOmegaSSTLM Class Reference
DAkOmegaSSTLM Class Reference
Protected Member Functions
SST functions
tmp< volScalarField > F1SST (const volScalarField &CDkOmega) const
tmp< volScalarField > F2 () const
tmp< volScalarField > F3 () const
tmp< volScalarField > F23 () const
tmp< volScalarField > blend (const volScalarField &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField::Internal > blend (const volScalarField::Internal &F1, const dimensionedScalar &psi1, const dimensionedScalar &psi2) const
tmp< volScalarField > alphaK (const volScalarField &F1) const
tmp< volScalarField > alphaOmega (const volScalarField &F1) const
tmp< volScalarField::Internal > beta (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > gamma (const volScalarField::Internal &F1) const
tmp< volScalarField::Internal > PkSST (const volScalarField::Internal &G) const
tmp< volScalarField::Internal > epsilonBykSST (const volScalarField &F1, const volTensorField &gradU) const
tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal &GbyNu0, const volScalarField::Internal &F2, const volScalarField::Internal &S2) const
tmp< fvScalarMatrix > kSource () const
tmp< fvScalarMatrix > omegaSource () const
tmp< fvScalarMatrix > Qsas (const volScalarField::Internal &S2, const volScalarField::Internal &gamma, const volScalarField::Internal &beta) const
tmp< volScalarField > F1 (const volScalarField &CDkOmega) const
tmp< volScalarField::Internal > Pk (const volScalarField::Internal &G) const
tmp< volScalarField::Internal > epsilonByk (const volScalarField &F1, const volTensorField &gradU) const
tmp< volScalarField::Internal > Fthetat (const volScalarField::Internal &Us, const volScalarField::Internal &Omega, const volScalarField::Internal &nu) const
tmp< volScalarField::Internal > ReThetac () const
tmp< volScalarField::Internal > Flength (const volScalarField::Internal &nu) const
tmp< volScalarField::Internal > Fonset (const volScalarField::Internal &Rev, const volScalarField::Internal &ReThetac, const volScalarField::Internal &RT) const
tmp< volScalarField::Internal > ReThetat0 (const volScalarField::Internal &Us, const volScalarField::Internal &dUsds, const volScalarField::Internal &nu) const
Protected Attributes
SST parameters
dimensionedScalar alphaK1_
dimensionedScalar alphaK2_
dimensionedScalar alphaOmega1_
dimensionedScalar alphaOmega2_
dimensionedScalar gamma1_
dimensionedScalar gamma2_
dimensionedScalar beta1_
dimensionedScalar beta2_
dimensionedScalar betaStar_
dimensionedScalar a1_
dimensionedScalar b1_
dimensionedScalar c1_
Switch F3_
SSTLM parameters
dimensionedScalar ca1_
dimensionedScalar ca2_
dimensionedScalar ce1_
dimensionedScalar ce2_
dimensionedScalar cThetat_
dimensionedScalar sigmaThetat_
scalar lambdaErr_
label maxLambdaIter_
const dimensionedScalar deltaU_
Protected Attributes inherited from DATurbulenceModel
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const dictionary & allOptions_
all DAFoam options
volScalarField & nut_
turbulence viscosity
volVectorField & U_
velocity
surfaceScalarField & phi_
face flux
volScalarField phase_
phase field
surfaceScalarField & phaseRhoPhi_
phase*phi*density field
IOdictionary turbDict_
turbulence model property dict
dictionary coeffDict_
turbulence model parameters dict
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
dimensionedScalar nuTildaMin_
Lower limit for nuTilda.
scalar Pr_
Prandtl number.
scalar Prt_ = -9999.0
turbulent Prandtl number
Augmented variables for adjoint residuals
volScalarField & omega_
volScalarField omegaRes_
volScalarField & k_
volScalarField kRes_
volScalarField & ReThetat_
volScalarField ReThetatRes_
volScalarField & gammaInt_
volScalarField gammaIntRes_
volScalarField::Internal & gammaIntEff_
Effective intermittency.
const volScalarField & y_
3D wall distance
scalarList omegaNearWall_
label solveTurbState_ = 0
whether to solve for turb states
label printInterval_
time step interval to print residual
TypeName ("kOmegaSSTLM")
DAkOmegaSSTLM (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DAkOmegaSSTLM ()
tmp< volScalarField > DkEff (const volScalarField &F1) const
tmp< volScalarField > DomegaEff (const volScalarField &F1) const
tmp< volScalarField > DReThetatEff () const
tmp< volScalarField > DgammaIntEff () const
virtual void correctModelStates (wordList &modelStates) const
update the turbulence state for DAStateInfo::regStates_
virtual void correctNut ()
update nut based on other turbulence variables and update the BCs
virtual void correctBoundaryConditions ()
update turbulence variable boundary values
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctStateResidualModelCon (List< List< word >> &stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const
add the model residual connectivity to stateCon
virtual void calcResiduals (const dictionary &options)
compute the turbulence residuals
virtual void correct ()
solve the residual equations and update the state
void saveOmegaNearWall ()
save near wall omega values to omegaNearWall_
void setOmegaNearWall ()
set omegaNearWall_ to near wall omega values
void correctOmegaBoundaryConditions ()
specially treatment to correct epsilon BC
Additional Inherited Members
Public Member Functions inherited from DATurbulenceModel
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable (autoPtr, DATurbulenceModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DATurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DATurbulenceModel ()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
void correctAlphat ()
update alphat
virtual void getTurbProdTerm (scalarList &prodTerm) const
return the value of the production term from the Spalart Allmaras model
tmp< volSymmTensorField > devRhoReff () const
dev terms
tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U)
divDev terms
tmp< fvVectorMatrix > divDevReff (volVectorField &U)
divDev terms
tmp< volScalarField > nuEff () const
return effective viscosity
tmp< volScalarField > getNut ()
get the nut field
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
tmp< volScalarField > nu () const
get the nu field
tmp< volScalarField > getAlpha () const
get alpha field
tmp< volScalarField > getRho ()
get the density field
tmp< volScalarField > getPhase ()
get the phase field
scalar getPrt ()
get the turbulent Prandtl number
tmp< Foam::volScalarField > getMu () const
get mu
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void printYPlus () const
print the min max and mean yPlus to screen
label isPrintTime (const Time &runTime, const label printInterval) const
virtual void invTranProdNuTildaEqn (const volScalarField &mySource, volScalarField &pseudoNuTilda)
Inverse transpose product, M_nuTilda^(-T)
virtual void constructPseudoNuTildaEqn ()
virtual void rhsSolvePseudoNuTildaEqn (const volScalarField &nuTildaSource)
virtual void calcLduResidualTurb (volScalarField &nuTildaRes)
calculate the turbulence residual using LDU matrix
Static Public Member Functions inherited from DATurbulenceModel
static autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Detailed Description
Definition at line 48 of file DAkOmegaSSTLM.H.
Constructor & Destructor Documentation
DAkOmegaSSTLM()
DAkOmegaSSTLM (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 41 of file DAkOmegaSSTLM.C.
References daOption(), forAll(), mesh, DAkOmegaSSTLM::omega_, DAkOmegaSSTLM::omegaNearWall_, and DAkOmegaSSTLM::printInterval_.
~DAkOmegaSSTLM()
virtual ~DAkOmegaSSTLM () inline virtual
Definition at line 240 of file DAkOmegaSSTLM.H.
Member Function Documentation
F1SST()
tmp< volScalarField > F1SST (const volScalarField & CDkOmega) const protected
Definition at line 243 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::alphaOmega2_, DAkOmegaSSTLM::betaStar_, DAkOmegaSSTLM::k_, DATurbulenceModel::nu(), DAkOmegaSSTLM::omega_, and DAkOmegaSSTLM::y_.
Referenced by DAkOmegaSSTLM::F1().
F2()
tmp< volScalarField > F2 () const protected
Definition at line 262 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::betaStar_, DAkOmegaSSTLM::k_, DATurbulenceModel::nu(), DAkOmegaSSTLM::omega_, and DAkOmegaSSTLM::y_.
Referenced by DAkOmegaSSTLM::F23(), and DAkOmegaSSTLM::GbyNu().
F3()
tmp< volScalarField > F3 () const protected
Definition at line 274 of file DAkOmegaSSTLM.C.
References DATurbulenceModel::nu(), DAkOmegaSSTLM::omega_, and DAkOmegaSSTLM::y_.
Referenced by DAkOmegaSSTLM::F1(), and DAkOmegaSSTLM::F23().
F23()
tmp< volScalarField > F23 () const protected
Definition at line 284 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::F2(), DAkOmegaSSTLM::F3(), and DAkOmegaSSTLM::F3_.
Referenced by DAkOmegaSSTLM::calcResiduals(), and DAkOmegaSSTLM::correctNut().
blend() [1/2]
tmp<volScalarField> blend (const volScalarField & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 96 of file DAkOmegaSSTLM.H.
References DAkOmegaSSTLM::F1().
Referenced by DAkOmegaSSTLM::alphaK(), DAkOmegaSSTLM::alphaOmega(), DAkOmegaSSTLM::beta(), and DAkOmegaSSTLM::gamma().
blend() [2/2]
tmp<volScalarField::Internal> blend (const volScalarField::Internal & F1, const dimensionedScalar & psi1, const dimensionedScalar & psi2) const inline protected
Definition at line 104 of file DAkOmegaSSTLM.H.
References DAkOmegaSSTLM::F1().
alphaK()
tmp<volScalarField> alphaK (const volScalarField & F1) const inline protected
Definition at line 112 of file DAkOmegaSSTLM.H.
References DAkOmegaSSTLM::alphaK1_, DAkOmegaSSTLM::alphaK2_, DAkOmegaSSTLM::blend(), and DAkOmegaSSTLM::F1().
Referenced by DAkOmegaSSTLM::DkEff().
alphaOmega()
tmp<volScalarField> alphaOmega (const volScalarField & F1) const inline protected
Definition at line 117 of file DAkOmegaSSTLM.H.
References DAkOmegaSSTLM::alphaOmega1_, DAkOmegaSSTLM::alphaOmega2_, DAkOmegaSSTLM::blend(), and DAkOmegaSSTLM::F1().
Referenced by DAkOmegaSSTLM::DomegaEff().
beta()
tmp<volScalarField::Internal> beta (const volScalarField::Internal & F1) const inline protected
Definition at line 122 of file DAkOmegaSSTLM.H.
References DAkOmegaSSTLM::beta1_, DAkOmegaSSTLM::beta2_, DAkOmegaSSTLM::blend(), and DAkOmegaSSTLM::F1().
Referenced by DAkOmegaSSTLM::calcResiduals().
gamma()
tmp<volScalarField::Internal> gamma (const volScalarField::Internal & F1) const inline protected
Definition at line 128 of file DAkOmegaSSTLM.H.
References DAkOmegaSSTLM::blend(), DAkOmegaSSTLM::F1(), DAkOmegaSSTLM::gamma1_, and DAkOmegaSSTLM::gamma2_.
Referenced by DAkOmegaSSTLM::calcResiduals().
PkSST()
tmp< volScalarField::Internal > PkSST (const volScalarField::Internal & G) const protected
Definition at line 307 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::betaStar_, DAkOmegaSSTLM::c1_, DAkOmegaSSTLM::k_, and DAkOmegaSSTLM::omega_.
Referenced by DAkOmegaSSTLM::Pk().
epsilonBykSST()
tmp< volScalarField::Internal > epsilonBykSST (const volScalarField & F1, const volTensorField & gradU) const protected
Definition at line 313 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::betaStar_, and DAkOmegaSSTLM::omega_.
Referenced by DAkOmegaSSTLM::epsilonByk().
GbyNu()
tmp< volScalarField::Internal > GbyNu (const volScalarField::Internal & GbyNu0, const volScalarField::Internal & F2, const volScalarField::Internal & S2) const protected
Definition at line 296 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::a1_, DAkOmegaSSTLM::b1_, DAkOmegaSSTLM::betaStar_, DAkOmegaSSTLM::c1_, DAkOmegaSSTLM::F2(), and DAkOmegaSSTLM::omega_.
Referenced by DAkOmegaSSTLM::calcResiduals().
kSource()
tmp< fvScalarMatrix > kSource () const protected
Definition at line 320 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::k_, and rho.
Referenced by DAkOmegaSSTLM::calcResiduals().
omegaSource()
tmp< fvScalarMatrix > omegaSource () const protected
Definition at line 329 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::omega_, and rho.
Referenced by DAkOmegaSSTLM::calcResiduals().
Qsas()
tmp< fvScalarMatrix > Qsas (const volScalarField::Internal & S2, const volScalarField::Internal & gamma, const volScalarField::Internal & beta) const protected
Definition at line 338 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::omega_, and rho.
Referenced by DAkOmegaSSTLM::calcResiduals().
F1()
tmp< volScalarField > F1 (const volScalarField & CDkOmega) const protected
Definition at line 351 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::F1SST(), DAkOmegaSSTLM::F3(), DAkOmegaSSTLM::k_, DATurbulenceModel::nu(), and DAkOmegaSSTLM::y_.
Referenced by DAkOmegaSSTLM::alphaK(), DAkOmegaSSTLM::alphaOmega(), DAkOmegaSSTLM::beta(), DAkOmegaSSTLM::blend(), DAkOmegaSSTLM::calcResiduals(), DAkOmegaSSTLM::DkEff(), DAkOmegaSSTLM::DomegaEff(), and DAkOmegaSSTLM::gamma().
Pk()
tmp< volScalarField::Internal > Pk (const volScalarField::Internal & G) const protected
Definition at line 360 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::gammaIntEff_, and DAkOmegaSSTLM::PkSST().
Referenced by DAkOmegaSSTLM::calcResiduals().
epsilonByk()
tmp< volScalarField::Internal > epsilonByk (const volScalarField & F1, const volTensorField & gradU) const protected
Definition at line 366 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::epsilonBykSST(), and DAkOmegaSSTLM::gammaIntEff_.
Referenced by DAkOmegaSSTLM::calcResiduals().
Fthetat()
tmp< volScalarField::Internal > Fthetat (const volScalarField::Internal & Us, const volScalarField::Internal & Omega, const volScalarField::Internal & nu) const protected
Definition at line 374 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::ce2_, DAkOmegaSSTLM::gammaInt_, DATurbulenceModel::nu(), DAkOmegaSSTLM::omega_, DAkOmegaSSTLM::ReThetat_, DATurbulenceModel::U_, and DAkOmegaSSTLM::y_.
Referenced by DAkOmegaSSTLM::calcResiduals().
ReThetac()
tmp< volScalarField::Internal > ReThetac () const protected
Definition at line 396 of file DAkOmegaSSTLM.C.
References forAll(), DATurbulenceModel::mesh_, DAkOmegaSSTLM::ReThetat_, and DATurbulenceModel::U_.
Referenced by DAkOmegaSSTLM::calcResiduals(), and DAkOmegaSSTLM::Fonset().
Flength()
tmp< volScalarField::Internal > Flength (const volScalarField::Internal & nu) const protected
Definition at line 427 of file DAkOmegaSSTLM.C.
References forAll(), DATurbulenceModel::mesh_, DATurbulenceModel::nu(), DAkOmegaSSTLM::omega_, DAkOmegaSSTLM::ReThetat_, DATurbulenceModel::U_, and DAkOmegaSSTLM::y_.
Referenced by DAkOmegaSSTLM::calcResiduals().
Fonset()
tmp< volScalarField::Internal > Fonset (const volScalarField::Internal & Rev, const volScalarField::Internal & ReThetac, const volScalarField::Internal & RT) const protected
Definition at line 481 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::ReThetac(), and DATurbulenceModel::U_.
Referenced by DAkOmegaSSTLM::calcResiduals().
ReThetat0()
tmp< volScalarField::Internal > ReThetat0 (const volScalarField::Internal & Us, const volScalarField::Internal & dUsds, const volScalarField::Internal & nu) const protected
Definition at line 499 of file DAkOmegaSSTLM.C.
References forAll(), k, DAkOmegaSSTLM::k_, lambda, DAkOmegaSSTLM::lambdaErr_, DAkOmegaSSTLM::maxLambdaIter_, DATurbulenceModel::mesh_, DATurbulenceModel::nu(), and DATurbulenceModel::U_.
Referenced by DAkOmegaSSTLM::calcResiduals().
TypeName()
TypeName ("kOmegaSSTLM")
DkEff()
tmp<volScalarField> DkEff (const volScalarField & F1) const inline
Definition at line 247 of file DAkOmegaSSTLM.H.
References DAkOmegaSSTLM::alphaK(), DAkOmegaSSTLM::F1(), DATurbulenceModel::nu(), and DATurbulenceModel::nut_.
Referenced by DAkOmegaSSTLM::calcResiduals().
DomegaEff()
tmp<volScalarField> DomegaEff (const volScalarField & F1) const inline
Definition at line 254 of file DAkOmegaSSTLM.H.
References DAkOmegaSSTLM::alphaOmega(), DAkOmegaSSTLM::F1(), DATurbulenceModel::nu(), and DATurbulenceModel::nut_.
Referenced by DAkOmegaSSTLM::calcResiduals().
DReThetatEff()
tmp<volScalarField> DReThetatEff () const inline
Definition at line 264 of file DAkOmegaSSTLM.H.
References DATurbulenceModel::nu(), DATurbulenceModel::nut_, and DAkOmegaSSTLM::sigmaThetat_.
Referenced by DAkOmegaSSTLM::calcResiduals().
DgammaIntEff()
tmp<volScalarField> DgammaIntEff () const inline
Definition at line 272 of file DAkOmegaSSTLM.H.
References DATurbulenceModel::nu(), and DATurbulenceModel::nut_.
Referenced by DAkOmegaSSTLM::calcResiduals().
correctModelStates()
void correctModelStates (wordList & modelStates) const virtual
update the turbulence state for DAStateInfo::regStates_
Implements DATurbulenceModel.
Definition at line 597 of file DAkOmegaSSTLM.C.
References forAll().
correctNut()
void correctNut () virtual
update nut based on other turbulence variables and update the BCs
Implements DATurbulenceModel.
Definition at line 635 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::a1_, DAkOmegaSSTLM::b1_, DATurbulenceModel::correctAlphat(), DAkOmegaSSTLM::F23(), DAkOmegaSSTLM::k_, DATurbulenceModel::mesh_, DATurbulenceModel::nut_, DAkOmegaSSTLM::omega_, and U.
Referenced by DAkOmegaSSTLM::calcResiduals(), and DAkOmegaSSTLM::updateIntermediateVariables().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update turbulence variable boundary values
Implements DATurbulenceModel.
Definition at line 657 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::gammaInt_, DAkOmegaSSTLM::k_, and DAkOmegaSSTLM::ReThetat_.
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DATurbulenceModel.
Definition at line 749 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::correctNut().
correctStateResidualModelCon()
void correctStateResidualModelCon (List< List< word >> & stateCon) const virtual
update the original variable connectivity for the adjoint state residuals in stateCon
Implements DATurbulenceModel.
Definition at line 763 of file DAkOmegaSSTLM.C.
References forAll().
addModelResidualCon()
void addModelResidualCon (HashTable< List< List< word >>> & allCon) const virtual
add the model residual connectivity to stateCon
Implements DATurbulenceModel.
Definition at line 864 of file DAkOmegaSSTLM.C.
References DATurbulenceModel::mesh_.
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute the turbulence residuals
Implements DATurbulenceModel.
Definition at line 1008 of file DAkOmegaSSTLM.C.
References DATurbulenceModel::allOptions_, DAkOmegaSSTLM::alphaOmega2_, DAkOmegaSSTLM::beta(), DAUtility::boundVar(), DAkOmegaSSTLM::ca1_, DAkOmegaSSTLM::ca2_, DAkOmegaSSTLM::ce1_, DAkOmegaSSTLM::ce2_, DAkOmegaSSTLM::correctNut(), DAkOmegaSSTLM::correctOmegaBoundaryConditions(), DAkOmegaSSTLM::cThetat_, DAkOmegaSSTLM::deltaU_, DAkOmegaSSTLM::DgammaIntEff(), DAkOmegaSSTLM::DkEff(), DAkOmegaSSTLM::DomegaEff(), DAkOmegaSSTLM::DReThetatEff(), DAkOmegaSSTLM::epsilonByk(), DAkOmegaSSTLM::F1(), DAkOmegaSSTLM::F23(), DAkOmegaSSTLM::Flength(), DAkOmegaSSTLM::Fonset(), DAkOmegaSSTLM::Fthetat(), DAkOmegaSSTLM::gamma(), DAkOmegaSSTLM::gammaInt_, DAkOmegaSSTLM::gammaIntEff_, DAkOmegaSSTLM::gammaIntRes_, DAkOmegaSSTLM::GbyNu(), DATurbulenceModel::isPrintTime(), DAkOmegaSSTLM::k_, DAkOmegaSSTLM::kRes_, DAkOmegaSSTLM::kSource(), DATurbulenceModel::mesh_, normalizeResiduals, DATurbulenceModel::nu(), DATurbulenceModel::nut_, DAkOmegaSSTLM::omega_, DAkOmegaSSTLM::omegaRes_, DAkOmegaSSTLM::omegaSource(), DATurbulenceModel::phase_, DATurbulenceModel::phaseRhoPhi_, DATurbulenceModel::phi_, DAkOmegaSSTLM::Pk(), DAkOmegaSSTLM::printInterval_, DAkOmegaSSTLM::Qsas(), DAkOmegaSSTLM::ReThetac(), DAkOmegaSSTLM::ReThetat0(), DAkOmegaSSTLM::ReThetat_, DAkOmegaSSTLM::ReThetatRes_, DAkOmegaSSTLM::setOmegaNearWall(), solve(), DAkOmegaSSTLM::solveTurbState_, DATurbulenceModel::U_, and DAkOmegaSSTLM::y_.
Referenced by DAkOmegaSSTLM::correct().
correct()
void correct () virtual
solve the residual equations and update the state
Implements DATurbulenceModel.
Definition at line 988 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::calcResiduals(), and DAkOmegaSSTLM::solveTurbState_.
saveOmegaNearWall()
void saveOmegaNearWall ()
save near wall omega values to omegaNearWall_
Definition at line 699 of file DAkOmegaSSTLM.C.
References forAll(), DATurbulenceModel::mesh_, DAkOmegaSSTLM::omega_, and DAkOmegaSSTLM::omegaNearWall_.
Referenced by DAkOmegaSSTLM::correctOmegaBoundaryConditions().
setOmegaNearWall()
void setOmegaNearWall ()
set omegaNearWall_ to near wall omega values
Definition at line 723 of file DAkOmegaSSTLM.C.
References forAll(), DATurbulenceModel::mesh_, DAkOmegaSSTLM::omega_, and DAkOmegaSSTLM::omegaNearWall_.
Referenced by DAkOmegaSSTLM::calcResiduals(), and DAkOmegaSSTLM::correctOmegaBoundaryConditions().
correctOmegaBoundaryConditions()
void correctOmegaBoundaryConditions ()
specially treatment to correct epsilon BC
Definition at line 672 of file DAkOmegaSSTLM.C.
References DAkOmegaSSTLM::omega_, DAkOmegaSSTLM::saveOmegaNearWall(), and DAkOmegaSSTLM::setOmegaNearWall().
Referenced by DAkOmegaSSTLM::calcResiduals().
Member Data Documentation
alphaK1_
dimensionedScalar alphaK1_ protected
Definition at line 55 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::alphaK().
alphaK2_
dimensionedScalar alphaK2_ protected
Definition at line 56 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::alphaK().
alphaOmega1_
dimensionedScalar alphaOmega1_ protected
Definition at line 58 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::alphaOmega().
alphaOmega2_
dimensionedScalar alphaOmega2_ protected
Definition at line 59 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::alphaOmega(), DAkOmegaSSTLM::calcResiduals(), and DAkOmegaSSTLM::F1SST().
gamma1_
dimensionedScalar gamma1_ protected
Definition at line 61 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::gamma().
gamma2_
dimensionedScalar gamma2_ protected
Definition at line 62 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::gamma().
beta1_
dimensionedScalar beta1_ protected
Definition at line 64 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::beta().
beta2_
dimensionedScalar beta2_ protected
Definition at line 65 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::beta().
betaStar_
dimensionedScalar betaStar_ protected
Definition at line 67 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::epsilonBykSST(), DAkOmegaSSTLM::F1SST(), DAkOmegaSSTLM::F2(), DAkOmegaSSTLM::GbyNu(), and DAkOmegaSSTLM::PkSST().
a1_
dimensionedScalar a1_ protected
Definition at line 69 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::correctNut(), and DAkOmegaSSTLM::GbyNu().
b1_
dimensionedScalar b1_ protected
Definition at line 70 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::correctNut(), and DAkOmegaSSTLM::GbyNu().
c1_
dimensionedScalar c1_ protected
Definition at line 71 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::GbyNu(), and DAkOmegaSSTLM::PkSST().
F3_
Switch F3_ protected
Definition at line 73 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::F23().
ca1_
dimensionedScalar ca1_ protected
Definition at line 78 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals().
ca2_
dimensionedScalar ca2_ protected
Definition at line 79 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals().
ce1_
dimensionedScalar ce1_ protected
Definition at line 80 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals().
ce2_
dimensionedScalar ce2_ protected
Definition at line 81 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals(), and DAkOmegaSSTLM::Fthetat().
cThetat_
dimensionedScalar cThetat_ protected
Definition at line 82 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals().
sigmaThetat_
dimensionedScalar sigmaThetat_ protected
Definition at line 83 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::DReThetatEff().
lambdaErr_
scalar lambdaErr_ protected
Definition at line 84 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::ReThetat0().
maxLambdaIter_
label maxLambdaIter_ protected
Definition at line 85 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::ReThetat0().
deltaU_
const dimensionedScalar deltaU_ protected
Definition at line 86 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals().
omega_
volScalarField& omega_ protected
Definition at line 201 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals(), DAkOmegaSSTLM::correctNut(), DAkOmegaSSTLM::correctOmegaBoundaryConditions(), DAkOmegaSSTLM::DAkOmegaSSTLM(), DAkOmegaSSTLM::epsilonBykSST(), DAkOmegaSSTLM::F1SST(), DAkOmegaSSTLM::F2(), DAkOmegaSSTLM::F3(), DAkOmegaSSTLM::Flength(), DAkOmegaSSTLM::Fthetat(), DAkOmegaSSTLM::GbyNu(), DAkOmegaSSTLM::omegaSource(), DAkOmegaSSTLM::PkSST(), DAkOmegaSSTLM::Qsas(), DAkOmegaSSTLM::saveOmegaNearWall(), and DAkOmegaSSTLM::setOmegaNearWall().
omegaRes_
volScalarField omegaRes_ protected
Definition at line 202 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals().
k_
volScalarField& k_ protected
Definition at line 203 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals(), DAkOmegaSSTLM::correctBoundaryConditions(), DAkOmegaSSTLM::correctNut(), DAkOmegaSSTLM::F1(), DAkOmegaSSTLM::F1SST(), DAkOmegaSSTLM::F2(), DAkOmegaSSTLM::kSource(), DAkOmegaSSTLM::PkSST(), and DAkOmegaSSTLM::ReThetat0().
kRes_
volScalarField kRes_ protected
Definition at line 204 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals().
ReThetat_
volScalarField& ReThetat_ protected
Definition at line 205 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals(), DAkOmegaSSTLM::correctBoundaryConditions(), DAkOmegaSSTLM::Flength(), DAkOmegaSSTLM::Fthetat(), and DAkOmegaSSTLM::ReThetac().
ReThetatRes_
volScalarField ReThetatRes_ protected
Definition at line 206 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals().
gammaInt_
volScalarField& gammaInt_ protected
Definition at line 207 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals(), DAkOmegaSSTLM::correctBoundaryConditions(), and DAkOmegaSSTLM::Fthetat().
gammaIntRes_
volScalarField gammaIntRes_ protected
Definition at line 208 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals().
gammaIntEff_
volScalarField::Internal& gammaIntEff_ protected
Effective intermittency.
Definition at line 212 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals(), DAkOmegaSSTLM::epsilonByk(), and DAkOmegaSSTLM::Pk().
y_
const volScalarField& y_ protected
3D wall distance
Definition at line 215 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals(), DAkOmegaSSTLM::F1(), DAkOmegaSSTLM::F1SST(), DAkOmegaSSTLM::F2(), DAkOmegaSSTLM::F3(), DAkOmegaSSTLM::Flength(), and DAkOmegaSSTLM::Fthetat().
omegaNearWall_
scalarList omegaNearWall_ protected
cell-center omega values near the wall, this is to fix the issue that the omegaWallFunction will try to modify omega values for the cells near walls this will cause issue for FD-based partial derivatives, so here we basically implement a zeroGradient BC for near wall omega.
Definition at line 221 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::DAkOmegaSSTLM(), DAkOmegaSSTLM::saveOmegaNearWall(), and DAkOmegaSSTLM::setOmegaNearWall().
solveTurbState_
label solveTurbState_ = 0 protected
whether to solve for turb states
Definition at line 224 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals(), and DAkOmegaSSTLM::correct().
printInterval_
label printInterval_ protected
time step interval to print residual
Definition at line 227 of file DAkOmegaSSTLM.H.
Referenced by DAkOmegaSSTLM::calcResiduals(), and DAkOmegaSSTLM::DAkOmegaSSTLM().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DATurbulenceModel/DAkOmegaSSTLM.H
dafoam/src/adjoint/DAModel/DATurbulenceModel/DAkOmegaSSTLM.C