DAFoam: DAObjFuncMoment Class Reference
DAObjFuncMoment Class Reference
Public Member Functions
TypeName ("moment")
DAObjFuncMoment (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict)
virtual ~DAObjFuncMoment ()
virtual void calcObjFunc (const labelList &objFuncFaceSources, const labelList &objFuncCellSources, scalarList &objFuncFaceValues, scalarList &objFuncCellValues, scalar &objFuncValue)
calculate the value of objective function
Public Member Functions inherited from DAObjFunc
TypeName ("DAObjFunc")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAObjFunc, dictionary,(const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict),(mesh, daOption, daModel, daIndex, daResidual, objFuncName, objFuncPart, objFuncDict))
DAObjFunc (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict)
virtual ~DAObjFunc ()
void clear ()
clear up members
void calcObjFuncSources (labelList &faceSources, labelList &cellSources)
calculate DAObjFunc::objFuncFaceSources_ and DAObjFunc::objFuncCellSources_
scalar getObjFuncValue ()
calcluate the value of objective function
scalar masterFunction (const dictionary &options, const Vec xvVec, const Vec wVec)
the master function to compute objective function given the state and point vectors
word getObjFuncName ()
return the name of objective function
word getObjFuncPart ()
return the part of objective function
word getObjFuncType ()
return the part of objective function
const labelList & getObjFuncFaceSources () const
return DAObjFunc::objFuncFaceSources_
const labelList & getObjFuncCellSources () const
return DAObjFunc::objFuncCellSources_
const scalarList & getObjFuncFaceValues () const
return DAObjFunc::objFuncFaceValues_
const scalarList & getObjFuncCellValues () const
return DAObjFunc::objFuncCellValues_
const List< List< word > > & getObjFuncConInfo () const
return DAObjFunc::objFuncConInfo_
Protected Attributes
vector momentDir_
the direction of the moment
vector momentCenter_
the center of rotation for moment
const DATurbulenceModel & daTurb_
DATurbulenceModel object.
Protected Attributes inherited from DAObjFunc
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
const DAResidual & daResidual_
DAResidual object.
word objFuncName_
the name of the objective function
word objFuncPart_
the part of the objective function
word objFuncType_
the type of the objective function
const dictionary & objFuncDict_
dictionary containing the information for the objective function
DAField daField_
DAField object.
labelList objFuncFaceSources_
a sorted list of all face sources for the objective function
labelList objFuncCellSources_
a sorted list of all cell sources for the objective function
scalarList objFuncFaceValues_
value of the obj function on the discrete faces
scalarList objFuncCellValues_
value of the obj function in the discrete cells
scalar scale_
scale of the objective function
scalar objFuncValue_
the value of the objective function
List< List< word > > objFuncConInfo_
the connectivity information for the objective function
Additional Inherited Members
Static Public Member Functions inherited from DAObjFunc
static autoPtr< DAObjFunc > New (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex, const DAResidual &daResidual, const word objFuncName, const word objFuncPart, const dictionary &objFuncDict)
Detailed Description
Definition at line 26 of file DAObjFuncMoment.H.
Constructor & Destructor Documentation
DAObjFuncMoment()
DAObjFuncMoment (const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex, const DAResidual & daResidual, const word objFuncName, const word objFuncPart, const dictionary & objFuncDict)
Definition at line 19 of file DAObjFuncMoment.C.
References DAModel::correctModelStates(), DAObjFunc::mesh_, DAObjFuncMoment::momentCenter_, DAObjFuncMoment::momentDir_, DAObjFunc::objFuncConInfo_, DAObjFunc::objFuncDict_, DAObjFunc::objFuncType_, and DAObjFunc::scale_.
~DAObjFuncMoment()
virtual ~DAObjFuncMoment () inline virtual
Definition at line 56 of file DAObjFuncMoment.H.
References DAObjFuncMoment::calcObjFunc().
Member Function Documentation
TypeName()
TypeName ("moment")
calcObjFunc()
void calcObjFunc (const labelList & objFuncFaceSources, const labelList & objFuncCellSources, scalarList & objFuncFaceValues, scalarList & objFuncCellValues, scalar & objFuncValue) virtual
calculate the value of objective function
Implements DAObjFunc.
Definition at line 94 of file DAObjFuncMoment.C.
References DAIndex::bFaceFaceI, DAIndex::bFacePatchI, DAObjFunc::daIndex_, DAObjFuncMoment::daTurb_, DATurbulenceModel::devRhoReff(), DAObjFunc::mesh_, DAObjFuncMoment::momentCenter_, DAObjFuncMoment::momentDir_, DAIndex::nLocalInternalFaces, p, and DAObjFunc::scale_.
Referenced by DAObjFuncMoment::~DAObjFuncMoment().
Member Data Documentation
momentDir_
vector momentDir_ protected
the direction of the moment
Definition at line 32 of file DAObjFuncMoment.H.
Referenced by DAObjFuncMoment::calcObjFunc(), and DAObjFuncMoment::DAObjFuncMoment().
momentCenter_
vector momentCenter_ protected
the center of rotation for moment
Definition at line 35 of file DAObjFuncMoment.H.
Referenced by DAObjFuncMoment::calcObjFunc(), and DAObjFuncMoment::DAObjFuncMoment().
daTurb_
const DATurbulenceModel& daTurb_ protected
DATurbulenceModel object.
Definition at line 38 of file DAObjFuncMoment.H.
Referenced by DAObjFuncMoment::calcObjFunc().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAObjFunc/DAObjFuncMoment.H
dafoam/src/adjoint/DAObjFunc/DAObjFuncMoment.C