DAFoam: nutUSpaldingWallFunctionFvPatchScalarFieldDF Class Reference
nutUSpaldingWallFunctionFvPatchScalarFieldDF Class Reference
Public Member Functions
TypeName ("nutUSpaldingWallFunctionDF")
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const fvPatch &, const DimensionedField< scalar, volMesh > &)
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const nutUSpaldingWallFunctionFvPatchScalarFieldDF &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const nutUSpaldingWallFunctionFvPatchScalarFieldDF &)
virtual tmp< fvPatchScalarField > clone () const
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const nutUSpaldingWallFunctionFvPatchScalarFieldDF &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual ~nutUSpaldingWallFunctionFvPatchScalarFieldDF ()
virtual tmp< scalarField > yPlus () const
virtual void write (Ostream &os) const
Protected Member Functions
virtual tmp< scalarField > calcNut () const
virtual tmp< scalarField > calcUTau (const scalarField &magGradU) const
virtual tmp< scalarField > calcUTau (const scalarField &magGradU, const label maxIter, scalarField &err) const
virtual void writeLocalEntries (Ostream &) const
Protected Attributes
const label maxIter_
const scalar tolerance_
Detailed Description
Definition at line 90 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.H.
Constructor & Destructor Documentation
nutUSpaldingWallFunctionFvPatchScalarFieldDF() [1/5]
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 153 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
Referenced by nutUSpaldingWallFunctionFvPatchScalarFieldDF::clone(), nutUSpaldingWallFunctionFvPatchScalarFieldDF::nutUSpaldingWallFunctionFvPatchScalarFieldDF(), and nutUSpaldingWallFunctionFvPatchScalarFieldDF::writeLocalEntries().
nutUSpaldingWallFunctionFvPatchScalarFieldDF() [2/5]
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 175 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::nutUSpaldingWallFunctionFvPatchScalarFieldDF().
nutUSpaldingWallFunctionFvPatchScalarFieldDF() [3/5]
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const nutUSpaldingWallFunctionFvPatchScalarFieldDF & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 163 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::nutUSpaldingWallFunctionFvPatchScalarFieldDF().
nutUSpaldingWallFunctionFvPatchScalarFieldDF() [4/5]
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const nutUSpaldingWallFunctionFvPatchScalarFieldDF & wfpsf)
Definition at line 186 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::nutUSpaldingWallFunctionFvPatchScalarFieldDF().
nutUSpaldingWallFunctionFvPatchScalarFieldDF() [5/5]
nutUSpaldingWallFunctionFvPatchScalarFieldDF (const nutUSpaldingWallFunctionFvPatchScalarFieldDF & wfpsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 195 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
~nutUSpaldingWallFunctionFvPatchScalarFieldDF()
virtual ~nutUSpaldingWallFunctionFvPatchScalarFieldDF () inline virtual
Definition at line 169 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.H.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::write(), and nutUSpaldingWallFunctionFvPatchScalarFieldDF::yPlus().
Member Function Documentation
calcNut()
tmp< scalarField > calcNut () const protected virtual
Definition at line 21 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::calcUTau(), and nutUSpaldingWallFunctionFvPatchScalarFieldDF::tolerance_.
calcUTau() [1/2]
tmp< scalarField > calcUTau (const scalarField & magGradU) const protected virtual
Definition at line 64 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::maxIter_.
Referenced by nutUSpaldingWallFunctionFvPatchScalarFieldDF::calcNut(), and nutUSpaldingWallFunctionFvPatchScalarFieldDF::yPlus().
calcUTau() [2/2]
tmp< scalarField > calcUTau (const scalarField & magGradU, const label maxIter, scalarField & err) const protected virtual
Definition at line 71 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::tolerance_.
writeLocalEntries()
void writeLocalEntries (Ostream & os) const protected virtual
Definition at line 141 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::maxIter_, nutUSpaldingWallFunctionFvPatchScalarFieldDF::nutUSpaldingWallFunctionFvPatchScalarFieldDF(), and nutUSpaldingWallFunctionFvPatchScalarFieldDF::tolerance_.
Referenced by nutUSpaldingWallFunctionFvPatchScalarFieldDF::write().
TypeName()
TypeName ("nutUSpaldingWallFunctionDF")
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Definition at line 149 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.H.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::nutUSpaldingWallFunctionFvPatchScalarFieldDF().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 161 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.H.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::nutUSpaldingWallFunctionFvPatchScalarFieldDF().
yPlus()
tmp< scalarField > yPlus () const virtual
Definition at line 206 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
References nutUSpaldingWallFunctionFvPatchScalarFieldDF::calcUTau().
Referenced by nutUSpaldingWallFunctionFvPatchScalarFieldDF::~nutUSpaldingWallFunctionFvPatchScalarFieldDF().
write()
void write (Ostream & os) const virtual
Definition at line 222 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.C.
References Foam::makePatchTypeField(), and nutUSpaldingWallFunctionFvPatchScalarFieldDF::writeLocalEntries().
Referenced by nutUSpaldingWallFunctionFvPatchScalarFieldDF::~nutUSpaldingWallFunctionFvPatchScalarFieldDF().
Member Data Documentation
maxIter_
const label maxIter_ protected
Definition at line 103 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.H.
Referenced by nutUSpaldingWallFunctionFvPatchScalarFieldDF::calcUTau(), and nutUSpaldingWallFunctionFvPatchScalarFieldDF::writeLocalEntries().
tolerance_
const scalar tolerance_ protected
Definition at line 106 of file nutUSpaldingWallFunctionFvPatchScalarFieldDF.H.
Referenced by nutUSpaldingWallFunctionFvPatchScalarFieldDF::calcNut(), nutUSpaldingWallFunctionFvPatchScalarFieldDF::calcUTau(), and nutUSpaldingWallFunctionFvPatchScalarFieldDF::writeLocalEntries().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/boundaryConditions/nutUSpaldingWallFunctionDF/nutUSpaldingWallFunctionFvPatchScalarFieldDF.H
dafoam/src/adjoint/boundaryConditions/nutUSpaldingWallFunctionDF/nutUSpaldingWallFunctionFvPatchScalarFieldDF.C