DAFoam: DAModel Class Reference
DAModel Class Reference
Public Member Functions
DAModel (const fvMesh &mesh, const DAOption &daOption)
Constructors.
virtual ~DAModel ()
Destructor.
void correctModelStates (wordList &modelStates) const
update the name in modelStates based on the selected physical model at runtime
void correctStateResidualModelCon (List< List< word >> &stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
void addModelResidualCon (HashTable< List< List< word >>> &allCon) const
add the model residual connectivity to stateCon
void calcResiduals (const dictionary &options)
calculate the residuals for model state variables
void correctBoundaryConditions ()
correct boundary conditions for model states
void updateIntermediateVariables ()
update intermediate variables that are dependent on the model states
void getTurbProdTerm (scalarList &prodTerm) const
return the value of the production term from the turbulence model
const DATurbulenceModel & getDATurbulenceModel () const
get a reference to DATurbulenceModel
Detailed Description
Definition at line 59 of file DAModel.H.
Constructor & Destructor Documentation
DAModel()
DAModel (const fvMesh & mesh, const DAOption & daOption)
Constructors.
Definition at line 16 of file DAModel.C.
~DAModel()
~DAModel () virtual
Destructor.
Definition at line 29 of file DAModel.C.
Member Function Documentation
correctModelStates()
void correctModelStates (wordList & modelStates) const
update the name in modelStates based on the selected physical model at runtime
Definition at line 33 of file DAModel.C.
References DATurbulenceModel::correctModelStates().
Referenced by DAObjFuncForce::DAObjFuncForce(), DAObjFuncMoment::DAObjFuncMoment(), DAObjFuncWallHeatFlux::DAObjFuncWallHeatFlux(), DAStateInfoPisoFoam::DAStateInfoPisoFoam(), DAStateInfoRhoSimpleCFoam::DAStateInfoRhoSimpleCFoam(), DAStateInfoRhoSimpleFoam::DAStateInfoRhoSimpleFoam(), DAStateInfoSimpleFoam::DAStateInfoSimpleFoam(), DAStateInfoSimpleTFoam::DAStateInfoSimpleTFoam(), and DAStateInfoTurboFoam::DAStateInfoTurboFoam().
correctStateResidualModelCon()
void correctStateResidualModelCon (List< List< word >> & stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
Definition at line 73 of file DAModel.C.
References DATurbulenceModel::correctStateResidualModelCon().
Referenced by DAStateInfoPisoFoam::DAStateInfoPisoFoam(), DAStateInfoRhoSimpleCFoam::DAStateInfoRhoSimpleCFoam(), DAStateInfoRhoSimpleFoam::DAStateInfoRhoSimpleFoam(), DAStateInfoSimpleFoam::DAStateInfoSimpleFoam(), DAStateInfoSimpleTFoam::DAStateInfoSimpleTFoam(), and DAStateInfoTurboFoam::DAStateInfoTurboFoam().
addModelResidualCon()
void addModelResidualCon (HashTable< List< List< word >>> & allCon) const
add the model residual connectivity to stateCon
Definition at line 127 of file DAModel.C.
References DARadiationModel::addModelResidualCon(), and DATurbulenceModel::addModelResidualCon().
Referenced by DAStateInfoPisoFoam::DAStateInfoPisoFoam(), DAStateInfoRhoSimpleCFoam::DAStateInfoRhoSimpleCFoam(), DAStateInfoRhoSimpleFoam::DAStateInfoRhoSimpleFoam(), DAStateInfoSimpleFoam::DAStateInfoSimpleFoam(), DAStateInfoSimpleTFoam::DAStateInfoSimpleTFoam(), and DAStateInfoTurboFoam::DAStateInfoTurboFoam().
calcResiduals()
void calcResiduals (const dictionary & options)
calculate the residuals for model state variables
Definition at line 200 of file DAModel.C.
References DATurbulenceModel::calcResiduals().
Referenced by DAResidual::masterFunction().
correctBoundaryConditions()
void correctBoundaryConditions ()
correct boundary conditions for model states
Definition at line 227 of file DAModel.C.
References DATurbulenceModel::correctBoundaryConditions().
Referenced by DAResidual::masterFunction(), and DAObjFunc::masterFunction().
updateIntermediateVariables()
void updateIntermediateVariables ()
update intermediate variables that are dependent on the model states
Definition at line 250 of file DAModel.C.
References DATurbulenceModel::updateIntermediateVariables().
Referenced by DAResidual::masterFunction(), and DAObjFunc::masterFunction().
getTurbProdTerm()
void getTurbProdTerm (scalarList & prodTerm) const
return the value of the production term from the turbulence model
Definition at line 273 of file DAModel.C.
References DATurbulenceModel::getTurbProdTerm().
Referenced by DAPartDerivdRdState::calcPartDerivMat().
getDATurbulenceModel()
const DATurbulenceModel & getDATurbulenceModel () const
get a reference to DATurbulenceModel
Definition at line 185 of file DAModel.C.
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DAModel.H
dafoam/src/adjoint/DAModel/DAModel.C