DAFoam: DAOption Class Reference
DAOption Class Reference
Public Member Functions
DAOption (const fvMesh &mesh, PyObject *pyOptions)
Constructors.
virtual ~DAOption ()
Destructor.
const dictionary & getAllOptions () const
return a reference of allOptions_ dictionary
template<class classType >
classType getOption (const word key) const
get an option from subDict and key
template<class classType >
void setOption (const word key, const classType value)
set an option to subDict and key
template<class classType >
classType getSubDictOption (const word subDict, const word subDictKey) const
get an dictionary option from subDict and key
template<class classType >
void setSubDictOption (const word subDict, const word subDictKey, const classType value)
set an dictionary option to subDict and key
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void updateDAOption (PyObject *pyOptions)
update the allOptions_ dict in DAOption based on the pyOptions from pyDAFoam
Detailed Description
Definition at line 29 of file DAOption.H.
Constructor & Destructor Documentation
DAOption()
DAOption (const fvMesh & mesh, PyObject * pyOptions)
Constructors.
Definition at line 16 of file DAOption.C.
References DAUtility::pyDict2OFDict().
~DAOption()
~DAOption () virtual
Destructor.
Definition at line 46 of file DAOption.C.
Member Function Documentation
getAllOptions()
const dictionary& getAllOptions () const inline
return a reference of allOptions_ dictionary
Definition at line 56 of file DAOption.H.
References DAOption::getOption(), DAOption::getSubDictOption(), DAOption::setOption(), DAOption::setSubDictOption(), DAOption::updateDAOption(), and DAOption::writeData().
Referenced by DAFvSourceUniformPressureGradient::calcFvSource(), DAFvSourceActuatorLine::calcFvSource(), DAFvSourceActuatorPoint::calcFvSource(), DAFvSourceActuatorDisk::calcFvSource(), DAFvSourceActuatorDisk::calcFvSourceCellIndices(), DAPartDerivdFdACTD::calcPartDerivMat(), DAPartDerivdRdACTD::calcPartDerivMat(), DAPartDerivdRdACTL::calcPartDerivMat(), DAPartDerivdRdACTP::calcPartDerivMat(), DAJacCon::checkSpecialBCs(), DAkEpsilon::DAkEpsilon(), DAkOmega::DAkOmega(), DAkOmegaSST::DAkOmegaSST(), DAkOmegaSSTLM::DAkOmegaSSTLM(), DAObjFuncForce::DAObjFuncForce(), DAResidualPimpleFoam::DAResidualPimpleFoam(), DAResidualPisoFoam::DAResidualPisoFoam(), DAResidualRhoSimpleFoam::DAResidualRhoSimpleFoam(), DAResidualSimpleFoam::DAResidualSimpleFoam(), DASpalartAllmaras::DASpalartAllmaras(), DASpalartAllmarasFv3::DASpalartAllmarasFv3(), DASpalartAllmarasFv3Beta::DASpalartAllmarasFv3Beta(), DAJacCon::initializeStateBoundaryCon(), DARadiationModel::New(), DAStateInfo::New(), DAResidual::New(), DAFvSource::New(), DAObjFunc::New(), DAPartDeriv::New(), DATurbulenceModel::New(), DAJacCon::New(), DAField::setPrimalBoundaryConditions(), DAJacCondRdW::setupdRdWCon(), DAJacCondFdW::setupJacCon(), and DAFvSource::syncDAOptionToActuatorDVs().
getOption()
classType getOption (const word key) const
get an option from subDict and key
Definition at line 92 of file DAOption.H.
Referenced by PYDAFOAM::array2Vec(), DAJacCon::calcColoredColumns(), PYDAFOAM::calcdFdAOAAnalytical(), PYDAFOAM::calcFFD2XvSeedVec(), DAFvSourceActuatorLine::calcFvSource(), DAFvSourceActuatorPoint::calcFvSource(), DAFvSourceActuatorDisk::calcFvSource(), DAFvSourceActuatorDisk::calcFvSourceCellIndices(), DAJacCon::calcJacConColoring(), DAPartDerivdFdFFD::calcPartDerivMat(), DAPartDerivdRdFFD::calcPartDerivMat(), DAPartDerivdRdW::calcPartDerivMat(), DAPartDerivdFdAOA::calcPartDerivMat(), DAPartDerivdFdBC::calcPartDerivMat(), DAPartDerivdFdACTD::calcPartDerivMat(), DAPartDerivdFdW::calcPartDerivMat(), PYDAFOAM::calcPrimalResidualStatistics(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAIndex::calcStateLocalIndexOffset(), DAField::DAField(), DAFvSourceActuatorDisk::DAFvSourceActuatorDisk(), DAFvSourceActuatorLine::DAFvSourceActuatorLine(), DAFvSourceActuatorPoint::DAFvSourceActuatorPoint(), DAIndex::DAIndex(), DAJacCon::DAJacCon(), DAObjFuncTotalPressureRatio::DAObjFuncTotalPressureRatio(), DAObjFuncTotalTemperatureRatio::DAObjFuncTotalTemperatureRatio(), DAPartDeriv::DAPartDeriv(), DAResidualRhoSimpleCFoam::DAResidualRhoSimpleCFoam(), DAResidualRhoSimpleFoam::DAResidualRhoSimpleFoam(), DAResidualTurboFoam::DAResidualTurboFoam(), DAOption::getAllOptions(), DAIndex::getLocalAdjointStateIndex(), DALinearEqn::getPrintInterval(), DAJacCondRdW::initializeJacCon(), DAJacCon::initializeStateBoundaryCon(), PYDAFOAM::initTimeInstanceMats(), DAColoring::parallelD2Coloring(), PYDAFOAM::runColoring(), PYDAFOAM::setdXvdFFDMat(), PYDAFOAM::setEvalFuncs(), PYDAFOAM::setStates(), PYDAFOAM::setTimeInstanceField(), PYDAFOAM::setTimeInstanceVar(), DAJacCondRdW::setupdRdWCon(), PYDAFOAM::solveAdjoint(), PYDAFOAM::solvePrimal(), PYDAFOAM::syncDAOptionToActuatorDVs(), DAResidualSolidDisplacementFoam::updateDAndGradD(), PYDAFOAM::updateDAOption(), PYDAFOAM::writeDeformedFFDs(), and PYDAFOAM::zeroTimeAccurateAdjointVectors().
setOption()
void setOption (const word key, const classType value)
set an option to subDict and key
Definition at line 127 of file DAOption.H.
Referenced by DAOption::getAllOptions(), PYDAFOAM::solveAdjoint(), and PYDAFOAM::zeroTimeAccurateAdjointVectors().
getSubDictOption()
classType getSubDictOption (const word subDict, const word subDictKey) const
get an dictionary option from subDict and key
Definition at line 165 of file DAOption.H.
Referenced by DAPartDerivdFdFFD::calcPartDerivMat(), DAPartDerivdRdW::calcPartDerivMat(), DAPartDerivdRdAOA::calcPartDerivMat(), DAPartDerivdRdBC::calcPartDerivMat(), DAPartDerivdRdFFD::calcPartDerivMat(), DAPartDerivdFdAOA::calcPartDerivMat(), DAPartDerivdFdBC::calcPartDerivMat(), DAPartDerivdFdW::calcPartDerivMat(), DAPartDerivdRdACTD::calcPartDerivMat(), DAPartDerivdRdACTL::calcPartDerivMat(), DAPartDerivdRdACTP::calcPartDerivMat(), DAPartDerivdFdACTD::calcPartDerivMat(), DALinearEqn::createMLRKSP(), DACheckMesh::DACheckMesh(), DAResidualPimpleFoam::DAResidualPimpleFoam(), DAResidualPisoFoam::DAResidualPisoFoam(), DAOption::getAllOptions(), and DALinearEqn::solveLinearEqn().
setSubDictOption()
void setSubDictOption (const word subDict, const word subDictKey, const classType value)
set an dictionary option to subDict and key
Definition at line 201 of file DAOption.H.
Referenced by DAOption::getAllOptions().
writeData()
bool writeData (Ostream & os) const
this is a virtual function for regIOobject
Definition at line 68 of file DAOption.C.
Referenced by DAOption::getAllOptions().
updateDAOption()
void updateDAOption (PyObject * pyOptions)
update the allOptions_ dict in DAOption based on the pyOptions from pyDAFoam
Definition at line 50 of file DAOption.C.
References DAUtility::pyDict2OFDict().
Referenced by DAOption::getAllOptions(), and PYDAFOAM::solveAdjoint().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAOption/DAOption.H
dafoam/src/adjoint/DAOption/DAOption.C