DAFoam: DAJacCondRdW Class Reference
DAJacCondRdW Class Reference
Public Member Functions
TypeName ("dRdW")
DAJacCondRdW (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAJacCondRdW ()
virtual void setupJacConPreallocation (const dictionary &options)
calculate the
virtual void initializeJacCon (const dictionary &options)
initialize the state Jacobian connectivity matrix
virtual void setupJacCon (const dictionary &options)
assign 1 to all non-zero elements for the Jacobian connecitivyt matrix
virtual void preallocatedRdW (Mat dRMat, const label transposed) const
preallocate memory for dRdW using the computed preallocation vectors
virtual void clear ()
clear members in parent and child objects
Public Member Functions inherited from DAJacCon
TypeName ("DAJacCon")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAJacCon, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAJacCon (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAJacCon ()
label getNJacConColors () const
get the number of JacCon colors
void calcJacConColoring (const word postFix="")
compute graph coloring for Jacobian connectivity matrix
void readJacConColoring (const word postFix="")
read colors for JacCon
label coloringExists (const word postFix="") const
whether the coloring file exists
Vec getJacConColor () const
return DAJacCon::jacConColors_
void calcColoredColumns (const label colorI, Vec coloredColumn) const
calculate the colored column vector
virtual void setObjFuncVec (scalarList objFuncFaceValues, scalarList objFuncCellValues, Vec objFuncVec) const
assign values for the objective function vector based on the face and cell value lists
Protected Member Functions
void initializePetscVecs ()
initialize petsc vectors
void allocateJacobianConnections (Vec preallocOnProc, Vec preallocOffProc, Vec preallocOnProcT, Vec preallocOffProcT, Mat connections, const label row)
compute preallocation vectors
void preallocateJacobianMatrix (Mat dRMat, const Vec preallocOnProc, const Vec preallocOffProc) const
compute preallocation vectors
void setupdRdWCon (const HashTable< List< List< word >>> &stateResConInfo, const label isPrealloc)
Protected Member Functions inherited from DAJacCon
void initializeStateBoundaryCon ()
initialize state boundary connection
void calcNeiBFaceGlobalCompact (labelList &neiBFaceGlobalCompact)
calculate DAJacCon::neiBFaceGlobalCompact_
label getLocalCoupledBFaceIndex (const label localFaceI) const
given a local face index, return the local index of the coupled boundary face
void setupStateBoundaryCon (Mat *stateBoundaryCon)
calculate DAJacCon::stateBoundaryCon_
void setupStateBoundaryConID (Mat *stateBoundaryConID)
calculate DAJacCon::stateBoundaryConID_
void createConnectionMat (Mat *connectedStates)
allocate connectedState matrix
void addStateConnections (Mat connections, const label cellI, const label connectedLevelLocal, const wordList connectedStatesLocal, const List< List< word >> connectedStateInterProc, const label addFace)
a high-level function to add connected state column indices to the connectivity matrix
void setConnections (Mat conMat, const label idx) const
add value 1 for the colume idx to conMat
void setupJacobianConnections (Mat conMat, Mat connections, const label idxI)
assign values in connections to a specific row idxI in conMat
void combineStateBndCon (Mat *stateBoundaryCon, Mat *stateBoundaryConTmp)
combine stateBoundaryCon and stateBoundaryConTmp, this is to ensure including all connected states for parallel cases
void addConMatCell (Mat conMat, const label gRow, const label cellI, const word stateName, const scalar val)
add val to the gRow row in conMat, the column indice are the state (given by stateName) for a given cellI
void addConMatNeighbourCells (Mat conMat, const label gRow, const label cellI, const word stateName, const scalar val)
add val to gRow row in conMat, column indice are the neighbouring states (given by stateName) for a given cellI
void addConMatCellFaces (Mat conMat, const label gRow, const label cellI, const word stateName, const scalar val)
add val to gRow row in conMat, column indice are the faces (given by stateName) for a given cellI
void addBoundaryFaceConnections (Mat conMat, const label gRow, const label cellI, const labelList v, const List< List< word >> connectedStates, const label addFaces)
add the column index of the (iner-proc) connected states and faces to conMat, given a local face index
void clearDAJacConMembers ()
clear members in DAJacCon
void checkSpecialBCs ()
check if there is special boundary conditions that need special treatment in jacCon_
void setPIVVec (Vec iSPIV, const label idxI)
function used to add connectivity for pressureInletVelocity
label addPhi4PIV (const word stateName, const label idxI, const label comp=-1)
add connectivity phi for pressureInletVelocity
Protected Attributes
on- and off-diagonal preallocation sizes for each row of dRdW, dRdWT, and dRdXv
Vec dRdWTPreallocOn_
Vec dRdWTPreallocOff_
Vec dRdWPreallocOn_
Vec dRdWPreallocOff_
Protected Attributes inherited from DAJacCon
const word modelType_
the name of the jacCon matrix
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
DAColoring daColoring_
DAColoring object.
DAField daField_
DAField object.
HashTable< wordList > stateInfo_
the regState_ list from DAStateInfo object
Mat stateBoundaryCon_
matrix to store boundary connectivity levels for state Jacobians
Mat stateBoundaryConID_
matrix to store boundary connectivity ID for state Jacobians
labelList neiBFaceGlobalCompact_
neibough face global index for a given local boundary face
Mat jacCon_
Jacobian connectivity mat.
Vec jacConColors_
jacCon matrix colors
label nJacConColors_
number of jacCon colors
Vec isPIVBCState_
a vector to show whether a state is connected to a pressureInletVelocity boundary face (3 level max)
Additional Inherited Members
Static Public Member Functions inherited from DAJacCon
static autoPtr< DAJacCon > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Detailed Description
Definition at line 26 of file DAJacCondRdW.H.
Constructor & Destructor Documentation
DAJacCondRdW()
DAJacCondRdW (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 19 of file DAJacCondRdW.C.
References DAJacCondRdW::initializePetscVecs(), and DAJacCon::initializeStateBoundaryCon().
~DAJacCondRdW()
virtual ~DAJacCondRdW () inline virtual
Definition at line 74 of file DAJacCondRdW.H.
References DAJacCondRdW::clear(), DAJacCondRdW::initializeJacCon(), DAJacCondRdW::preallocatedRdW(), DAJacCondRdW::setupJacCon(), and DAJacCondRdW::setupJacConPreallocation().
Member Function Documentation
initializePetscVecs()
void initializePetscVecs () protected
initialize petsc vectors
Definition at line 50 of file DAJacCondRdW.C.
References DAJacCon::daIndex_, DAJacCondRdW::dRdWPreallocOff_, DAJacCondRdW::dRdWPreallocOn_, DAJacCondRdW::dRdWTPreallocOff_, DAJacCondRdW::dRdWTPreallocOn_, DAJacCon::jacConColors_, and DAIndex::nLocalAdjointStates.
Referenced by DAJacCondRdW::DAJacCondRdW().
allocateJacobianConnections()
void allocateJacobianConnections (Vec preallocOnProc, Vec preallocOffProc, Vec preallocOnProcT, Vec preallocOffProcT, Mat connections, const label row) protected
compute preallocation vectors
Definition at line 710 of file DAJacCondRdW.C.
References DAJacCon::daIndex_, DAIndex::globalAdjointStateNumbering, DAUtility::isValueCloseToRef(), and DAIndex::nLocalAdjointStates.
Referenced by DAJacCondRdW::setupdRdWCon().
preallocateJacobianMatrix()
void preallocateJacobianMatrix (Mat dRMat, const Vec preallocOnProc, const Vec preallocOffProc) const protected
compute preallocation vectors
Definition at line 799 of file DAJacCondRdW.C.
References DAJacCon::daIndex_, and DAIndex::nLocalAdjointStates.
Referenced by DAJacCondRdW::initializeJacCon(), and DAJacCondRdW::preallocatedRdW().
setupdRdWCon()
void setupdRdWCon (const HashTable< List< List< word >>> & stateResConInfo, const label isPrealloc) protected
Definition at line 151 of file DAJacCondRdW.C.
References DAJacCon::addStateConnections(), DAIndex::adjStateNames, DAIndex::adjStateType, DAJacCondRdW::allocateJacobianConnections(), DAIndex::bFaceFaceI, DAIndex::bFacePatchI, DAJacCon::createConnectionMat(), DAJacCon::daField_, DAJacCon::daIndex_, DAJacCon::daOption_, DAJacCondRdW::dRdWPreallocOff_, DAJacCondRdW::dRdWPreallocOn_, DAJacCondRdW::dRdWTPreallocOff_, DAJacCondRdW::dRdWTPreallocOn_, DAIndex::getGlobalAdjointStateIndex(), DAJacCon::getLocalCoupledBFaceIndex(), DAOption::getOption(), DAIndex::globalCoupledBFaceNumbering, DAJacCon::jacCon_, DAJacCon::mesh_, DAIndex::nLocalInternalFaces, DAJacCon::setConnections(), DAJacCon::setupJacobianConnections(), DAField::specialBCs, DAJacCon::stateBoundaryCon_, DAJacCon::stateBoundaryConID_, DAJacCon::stateInfo_, DAUtility::writeMatrixBinary(), and DAUtility::writeVectorASCII().
Referenced by DAJacCondRdW::setupJacCon(), and DAJacCondRdW::setupJacConPreallocation().
TypeName()
TypeName ("dRdW")
setupJacConPreallocation()
void setupJacConPreallocation (const dictionary & options) virtual
calculate the
Reimplemented from DAJacCon.
Definition at line 78 of file DAJacCondRdW.C.
References DAJacCondRdW::setupdRdWCon().
Referenced by DAJacCondRdW::~DAJacCondRdW().
initializeJacCon()
void initializeJacCon (const dictionary & options) virtual
initialize the state Jacobian connectivity matrix
Implements DAJacCon.
Definition at line 119 of file DAJacCondRdW.C.
References DAJacCon::daIndex_, DAJacCon::daOption_, DAJacCondRdW::dRdWPreallocOff_, DAJacCondRdW::dRdWPreallocOn_, DAOption::getOption(), DAJacCon::jacCon_, DAIndex::nLocalAdjointStates, and DAJacCondRdW::preallocateJacobianMatrix().
Referenced by DAJacCondRdW::~DAJacCondRdW().
setupJacCon()
void setupJacCon (const dictionary & options) virtual
assign 1 to all non-zero elements for the Jacobian connecitivyt matrix
Implements DAJacCon.
Definition at line 101 of file DAJacCondRdW.C.
References DAJacCondRdW::setupdRdWCon().
Referenced by DAJacCondRdW::~DAJacCondRdW().
preallocatedRdW()
void preallocatedRdW (Mat dRMat, const label transposed) const virtual
preallocate memory for dRdW using the computed preallocation vectors
Reimplemented from DAJacCon.
Definition at line 854 of file DAJacCondRdW.C.
References DAJacCondRdW::dRdWPreallocOff_, DAJacCondRdW::dRdWPreallocOn_, DAJacCondRdW::dRdWTPreallocOff_, DAJacCondRdW::dRdWTPreallocOn_, and DAJacCondRdW::preallocateJacobianMatrix().
Referenced by DAJacCondRdW::~DAJacCondRdW().
clear()
void clear () virtual
clear members in parent and child objects
Implements DAJacCon.
Definition at line 34 of file DAJacCondRdW.C.
References DAJacCon::clearDAJacConMembers(), DAJacCondRdW::dRdWPreallocOff_, DAJacCondRdW::dRdWPreallocOn_, DAJacCondRdW::dRdWTPreallocOff_, and DAJacCondRdW::dRdWTPreallocOn_.
Referenced by DAJacCondRdW::~DAJacCondRdW().
Member Data Documentation
dRdWTPreallocOn_
Vec dRdWTPreallocOn_ protected
Definition at line 33 of file DAJacCondRdW.H.
Referenced by DAJacCondRdW::clear(), DAJacCondRdW::initializePetscVecs(), DAJacCondRdW::preallocatedRdW(), and DAJacCondRdW::setupdRdWCon().
dRdWTPreallocOff_
Vec dRdWTPreallocOff_ protected
Definition at line 34 of file DAJacCondRdW.H.
Referenced by DAJacCondRdW::clear(), DAJacCondRdW::initializePetscVecs(), DAJacCondRdW::preallocatedRdW(), and DAJacCondRdW::setupdRdWCon().
dRdWPreallocOn_
Vec dRdWPreallocOn_ protected
Definition at line 35 of file DAJacCondRdW.H.
Referenced by DAJacCondRdW::clear(), DAJacCondRdW::initializeJacCon(), DAJacCondRdW::initializePetscVecs(), DAJacCondRdW::preallocatedRdW(), and DAJacCondRdW::setupdRdWCon().
dRdWPreallocOff_
Vec dRdWPreallocOff_ protected
Definition at line 36 of file DAJacCondRdW.H.
Referenced by DAJacCondRdW::clear(), DAJacCondRdW::initializeJacCon(), DAJacCondRdW::initializePetscVecs(), DAJacCondRdW::preallocatedRdW(), and DAJacCondRdW::setupdRdWCon().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAJacCon/DAJacCondRdW.H
dafoam/src/adjoint/DAJacCon/DAJacCondRdW.C