DAFoam: DAFvSourceActuatorDisk Class Reference
DAFvSourceActuatorDisk Class Reference
Public Member Functions
TypeName ("actuatorDisk")
DAFvSourceActuatorDisk (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAFvSourceActuatorDisk ()
virtual void calcFvSource (volVectorField &fvSource)
compute the FvSource term
Public Member Functions inherited from DAFvSource
TypeName ("DAFvSource")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAFvSource, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAFvSource (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAFvSource ()
Protected Member Functions
void calcFvSourceCellIndices (HashTable< labelList > &fvSourceCellIndices)
calculate DAFvSourceActuatorDisk::fvSourceCellIndices_
Protected Attributes
HashTable< labelList > fvSourceCellIndices_
HashTable that contains lists of cell indices that are within the actuator disk space.
dictionary fvSourceSubDict_
the subDict of fvSource in DAOption
Protected Attributes inherited from DAFvSource
const word & modelType_
model name
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
Additional Inherited Members
Static Public Member Functions inherited from DAFvSource
static autoPtr< DAFvSource > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Detailed Description
Definition at line 26 of file DAFvSourceActuatorDisk.H.
Constructor & Destructor Documentation
DAFvSourceActuatorDisk (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 19 of file DAFvSourceActuatorDisk.C.
References allOptions, DAFvSourceActuatorDisk::calcFvSourceCellIndices(), DAFvSource::daOption_, DAFvSourceActuatorDisk::fvSourceCellIndices_, DAFvSourceActuatorDisk::fvSourceSubDict_, and DAOption::getAllOptions().
virtual ~DAFvSourceActuatorDisk () inline virtual
Definition at line 54 of file DAFvSourceActuatorDisk.H.
Member Function Documentation
void calcFvSourceCellIndices (HashTable< labelList > & fvSourceCellIndices) protected
calculate DAFvSourceActuatorDisk::fvSourceCellIndices_
Definition at line 183 of file DAFvSourceActuatorDisk.C.
References DAFvSource::daOption_, Foam::forAll(), DAFvSourceActuatorDisk::fvSourceSubDict_, DAOption::getOption(), and DAFvSource::mesh_.
Referenced by DAFvSourceActuatorDisk::DAFvSourceActuatorDisk().
TypeName ("actuatorDisk")
void calcFvSource (volVectorField & fvSource) virtual
compute the FvSource term
Reimplemented from DAFvSource.
Definition at line 33 of file DAFvSourceActuatorDisk.C.
References Foam::forAll(), DAFvSourceActuatorDisk::fvSourceCellIndices_, DAFvSourceActuatorDisk::fvSourceSubDict_, DAFvSource::mesh_, and Foam::reduce().
Member Data Documentation
HashTable<labelList> fvSourceCellIndices_ protected
HashTable that contains lists of cell indices that are within the actuator disk space.
Definition at line 33 of file DAFvSourceActuatorDisk.H.
Referenced by DAFvSourceActuatorDisk::calcFvSource(), and DAFvSourceActuatorDisk::DAFvSourceActuatorDisk().
dictionary fvSourceSubDict_ protected
the subDict of fvSource in DAOption
Definition at line 39 of file DAFvSourceActuatorDisk.H.
Referenced by DAFvSourceActuatorDisk::calcFvSource(), DAFvSourceActuatorDisk::calcFvSourceCellIndices(), and DAFvSourceActuatorDisk::DAFvSourceActuatorDisk().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAFvSource/DAFvSourceActuatorDisk.H
dafoam/src/adjoint/DAFvSource/DAFvSourceActuatorDisk.C