DAFoam: DAColoring Class Reference
DAColoring Class Reference
Public Member Functions
DAColoring (const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Constructors.
virtual ~DAColoring ()
Destructor.
void getMatNonZeros (const Mat conMat, label &maxCols, scalar &allNonZeros) const
number of non-zero elements in a matrix
label find_index (const label target, const label start, const label size, const label *valArray) const
find the index of a prescribed value in an array
void coloringComplete (const Vec colors, label &colorCounter, label &notColored) const
check if there is non-colored columns
void parallelD2Coloring (const Mat conMat, Vec colors, label &nColors) const
a parallel distance-2 graph coloring function
void validateColoring (Mat conMat, Vec colors) const
validate if there is coloring conflict
Protected Attributes
const fvMesh & mesh_
fvMesh object
const DAOption & daOption_
DAOption object.
const DAIndex & daIndex_
DAIndex object.
Detailed Description
Definition at line 32 of file DAColoring.H.
Constructor & Destructor Documentation
DAColoring()
DAColoring (const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Constructors.
Definition at line 17 of file DAColoring.C.
~DAColoring()
virtual ~DAColoring () inline virtual
Destructor.
Definition at line 62 of file DAColoring.H.
References DAColoring::coloringComplete(), DAColoring::find_index(), DAColoring::getMatNonZeros(), DAColoring::parallelD2Coloring(), and DAColoring::validateColoring().
Member Function Documentation
getMatNonZeros()
void getMatNonZeros (const Mat conMat, label & maxCols, scalar & allNonZeros) const
number of non-zero elements in a matrix
Definition at line 786 of file DAColoring.C.
References dafoam_plot3dtransform::vals.
Referenced by DAColoring::parallelD2Coloring(), and DAColoring::~DAColoring().
find_index()
label find_index (const label target, const label start, const label size, const label * valArray) const
find the index of a prescribed value in an array
Definition at line 844 of file DAColoring.C.
Referenced by DAColoring::parallelD2Coloring(), and DAColoring::~DAColoring().
coloringComplete()
void coloringComplete (const Vec colors, label & colorCounter, label & notColored) const
check if there is non-colored columns
Definition at line 881 of file DAColoring.C.
Referenced by DAColoring::parallelD2Coloring(), and DAColoring::~DAColoring().
parallelD2Coloring()
void parallelD2Coloring (const Mat conMat, Vec colors, label & nColors) const
a parallel distance-2 graph coloring function
Definition at line 32 of file DAColoring.C.
References DAColoring::coloringComplete(), DAColoring::daIndex_, DAColoring::daOption_, DAColoring::find_index(), DAColoring::getMatNonZeros(), DAOption::getOption(), DAUtility::isValueCloseToRef(), DAColoring::mesh_, DAIndex::nGlobalAdjointStates, DAIndex::nLocalAdjointStates, and dafoam_plot3dtransform::vals.
Referenced by DAJacCon::calcJacConColoring(), and DAColoring::~DAColoring().
validateColoring()
void validateColoring (Mat conMat, Vec colors) const
validate if there is coloring conflict
Definition at line 931 of file DAColoring.C.
References DAUtility::isValueCloseToRef(), and dafoam_plot3dtransform::vals.
Referenced by DAJacCon::calcJacConColoring(), DAJacCon::readJacConColoring(), and DAColoring::~DAColoring().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
fvMesh object
Definition at line 45 of file DAColoring.H.
Referenced by DAColoring::parallelD2Coloring().
daOption_
const DAOption& daOption_ protected
DAOption object.
Definition at line 48 of file DAColoring.H.
Referenced by DAColoring::parallelD2Coloring().
daIndex_
const DAIndex& daIndex_ protected
DAIndex object.
Definition at line 51 of file DAColoring.H.
Referenced by DAColoring::parallelD2Coloring().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAColoring/DAColoring.H
dafoam/src/adjoint/DAColoring/DAColoring.C