DAFoam: DASpalartAllmarasFv3 Class Reference
DASpalartAllmarasFv3 Class Reference
Protected Member Functions
SA functions
tmp< volScalarField > chi () const
tmp< volScalarField > fv1 (const volScalarField &chi) const
tmp< volScalarField > fv2 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fv3 (const volScalarField &chi, const volScalarField &fv1) const
tmp< volScalarField > fw (const volScalarField &Stilda) const
Protected Attributes
SA parameters
dimensionedScalar sigmaNut_
dimensionedScalar kappa_
dimensionedScalar Cb1_
dimensionedScalar Cb2_
dimensionedScalar Cw1_
dimensionedScalar Cw2_
dimensionedScalar Cw3_
dimensionedScalar Cv1_
dimensionedScalar Cv2_
Protected Attributes inherited from DATurbulenceModel
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const dictionary & allOptions_
all DAFoam options
volScalarField & nut_
turbulence viscosity
volVectorField & U_
velocity
surfaceScalarField & phi_
face flux
volScalarField phase_
phase field
surfaceScalarField & phaseRhoPhi_
phase*phi*density field
IOdictionary turbDict_
turbulence model property dict
dictionary coeffDict_
turbulence model parameters dict
dimensionedScalar kMin_
Lower limit of k.
dimensionedScalar epsilonMin_
Lower limit of epsilon.
dimensionedScalar omegaMin_
Lower limit for omega.
dimensionedScalar nuTildaMin_
Lower limit for nuTilda.
scalar Pr_
Prandtl number.
scalar Prt_ = -9999.0
turbulent Prandtl number
Augmented variables for residual computation
volScalarField & nuTilda_
volScalarField nuTildaRes_
volScalarField pseudoNuTilda_
pseudoNuTilda_ and pseudoNuTildaEqn_ for solving adjoint equation
fvScalarMatrix pseudoNuTildaEqn_
const volScalarField & y_
3D wall distance
label solveTurbState_ = 0
whether to solve for turb states
label printInterval_
time step interval to print residual
scalar relaxNuTildaEqn_ = 1.0
dictionary solverDictNuTilda_
TypeName ("SpalartAllmarasFv3")
DASpalartAllmarasFv3 (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DASpalartAllmarasFv3 ()
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
virtual void correctModelStates (wordList &modelStates) const
update the turbulence state for DAStateInfo::regStates_
virtual void correctNut ()
update nut based on other turbulence variables and update the BCs
virtual void correctBoundaryConditions ()
update turbulence variable boundary values
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctStateResidualModelCon (List< List< word >> &stateCon) const
update the original variable connectivity for the adjoint state residuals in stateCon
virtual void addModelResidualCon (HashTable< List< List< word >>> &allCon) const
add the model residual connectivity to stateCon
virtual void calcResiduals (const dictionary &options)
compute the turbulence residuals
virtual void correct ()
solve the residual equations and update the state
virtual void invTranProdNuTildaEqn (const volScalarField &mySource, volScalarField &pseudoNuTilda)
Inverse transpose product, A_nuTilda^(-T)
virtual void constructPseudoNuTildaEqn ()
construct pseudoNuTildaEqn_, which is nuTildaEqn with swapped upper and lower arrays
virtual void rhsSolvePseudoNuTildaEqn (const volScalarField &nuTildaSource)
solve pseudoNuTildaEqn_ with overwritten rhs
virtual void calcLduResidualTurb (volScalarField &nuTildaRes)
calculate the turbulence residual using LDU matrix
Additional Inherited Members
Public Member Functions inherited from DATurbulenceModel
TypeName ("DATurbulenceModel")
declareRunTimeSelectionTable (autoPtr, DATurbulenceModel, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption),(modelType, mesh, daOption))
DATurbulenceModel (const word modelType, const fvMesh &mesh, const DAOption &daOption)
virtual ~DATurbulenceModel ()
void correctWallDist ()
update wall distance for d_. Note: y_ will be automatically updated in mesh_ object
void correctAlphat ()
update alphat
virtual void getTurbProdTerm (scalarList &prodTerm) const
return the value of the production term from the Spalart Allmaras model
tmp< volSymmTensorField > devRhoReff () const
dev terms
tmp< fvVectorMatrix > divDevRhoReff (volVectorField &U)
divDev terms
tmp< fvVectorMatrix > divDevReff (volVectorField &U)
divDev terms
tmp< volScalarField > nuEff () const
return effective viscosity
tmp< volScalarField > getNut ()
get the nut field
tmp< volScalarField > alphaEff ()
return effective thermal diffusivity
tmp< volScalarField > nu () const
get the nu field
tmp< volScalarField > getAlpha () const
get alpha field
tmp< volScalarField > getRho ()
get the density field
tmp< volScalarField > getPhase ()
get the phase field
scalar getPrt ()
get the turbulent Prandtl number
tmp< Foam::volScalarField > getMu () const
get mu
bool writeData (Ostream &os) const
this is a virtual function for regIOobject
void printYPlus () const
print the min max and mean yPlus to screen
label isPrintTime (const Time &runTime, const label printInterval) const
Static Public Member Functions inherited from DATurbulenceModel
static autoPtr< DATurbulenceModel > New (const word modelType, const fvMesh &mesh, const DAOption &daOption)
Detailed Description
Definition at line 48 of file DASpalartAllmarasFv3.H.
Constructor & Destructor Documentation
DASpalartAllmarasFv3()
DASpalartAllmarasFv3 (const word modelType, const fvMesh & mesh, const DAOption & daOption)
Definition at line 41 of file DASpalartAllmarasFv3.C.
References daOption(), mesh, DASpalartAllmarasFv3::printInterval_, DASpalartAllmarasFv3::relaxNuTildaEqn_, and DASpalartAllmarasFv3::solverDictNuTilda_.
~DASpalartAllmarasFv3()
virtual ~DASpalartAllmarasFv3 () inline virtual
Definition at line 118 of file DASpalartAllmarasFv3.H.
Member Function Documentation
chi()
tmp< volScalarField > chi () const protected
Definition at line 152 of file DASpalartAllmarasFv3.C.
References DATurbulenceModel::nu(), and DASpalartAllmarasFv3::nuTilda_.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), DASpalartAllmarasFv3::constructPseudoNuTildaEqn(), DASpalartAllmarasFv3::correctNut(), DASpalartAllmarasFv3::fv1(), DASpalartAllmarasFv3::fv2(), and DASpalartAllmarasFv3::fv3().
fv1()
tmp< volScalarField > fv1 (const volScalarField & chi) const protected
Definition at line 157 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::chi(), and DASpalartAllmarasFv3::Cv1_.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), DASpalartAllmarasFv3::constructPseudoNuTildaEqn(), DASpalartAllmarasFv3::correctNut(), and DASpalartAllmarasFv3::fv3().
fv2()
tmp< volScalarField > fv2 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 164 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::chi(), and DASpalartAllmarasFv3::Cv2_.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::constructPseudoNuTildaEqn().
fv3()
tmp< volScalarField > fv3 (const volScalarField & chi, const volScalarField & fv1) const protected
Definition at line 171 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::chi(), DASpalartAllmarasFv3::Cv2_, and DASpalartAllmarasFv3::fv1().
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::constructPseudoNuTildaEqn().
fw()
tmp< volScalarField > fw (const volScalarField & Stilda) const protected
Definition at line 184 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::Cw2_, DASpalartAllmarasFv3::Cw3_, DASpalartAllmarasFv3::kappa_, DASpalartAllmarasFv3::nuTilda_, and DASpalartAllmarasFv3::y_.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::constructPseudoNuTildaEqn().
TypeName()
TypeName ("SpalartAllmarasFv3")
DnuTildaEff()
tmp< volScalarField > DnuTildaEff () const
Return the effective diffusivity for nuTilda.
Definition at line 202 of file DASpalartAllmarasFv3.C.
References DATurbulenceModel::nu(), DASpalartAllmarasFv3::nuTilda_, and DASpalartAllmarasFv3::sigmaNut_.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::constructPseudoNuTildaEqn().
correctModelStates()
void correctModelStates (wordList & modelStates) const virtual
update the turbulence state for DAStateInfo::regStates_
Implements DATurbulenceModel.
Definition at line 209 of file DASpalartAllmarasFv3.C.
References forAll().
correctNut()
void correctNut () virtual
update nut based on other turbulence variables and update the BCs
Implements DATurbulenceModel.
Definition at line 243 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::chi(), DATurbulenceModel::correctAlphat(), DASpalartAllmarasFv3::fv1(), DATurbulenceModel::nut_, and DASpalartAllmarasFv3::nuTilda_.
Referenced by DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::updateIntermediateVariables().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update turbulence variable boundary values
Implements DATurbulenceModel.
Definition at line 263 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::nuTilda_.
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DATurbulenceModel.
Definition at line 274 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::correctNut().
correctStateResidualModelCon()
void correctStateResidualModelCon (List< List< word >> & stateCon) const virtual
update the original variable connectivity for the adjoint state residuals in stateCon
Implements DATurbulenceModel.
Definition at line 285 of file DASpalartAllmarasFv3.C.
References forAll().
addModelResidualCon()
void addModelResidualCon (HashTable< List< List< word >>> & allCon) const virtual
add the model residual connectivity to stateCon
Implements DATurbulenceModel.
Definition at line 335 of file DASpalartAllmarasFv3.C.
References DATurbulenceModel::mesh_.
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute the turbulence residuals
Implements DATurbulenceModel.
Definition at line 433 of file DASpalartAllmarasFv3.C.
References DATurbulenceModel::allOptions_, DAUtility::boundVar(), DASpalartAllmarasFv3::Cb1_, DASpalartAllmarasFv3::Cb2_, DASpalartAllmarasFv3::chi(), DASpalartAllmarasFv3::correctNut(), DASpalartAllmarasFv3::Cw1_, DASpalartAllmarasFv3::DnuTildaEff(), DASpalartAllmarasFv3::fv1(), DASpalartAllmarasFv3::fv2(), DASpalartAllmarasFv3::fv3(), DASpalartAllmarasFv3::fw(), DATurbulenceModel::isPrintTime(), DASpalartAllmarasFv3::kappa_, DATurbulenceModel::mesh_, normalizeResiduals, DASpalartAllmarasFv3::nuTilda_, DASpalartAllmarasFv3::nuTildaRes_, DATurbulenceModel::phase_, DATurbulenceModel::phaseRhoPhi_, DASpalartAllmarasFv3::printInterval_, DASpalartAllmarasFv3::sigmaNut_, solve(), DASpalartAllmarasFv3::solveTurbState_, DATurbulenceModel::U_, and DASpalartAllmarasFv3::y_.
Referenced by DASpalartAllmarasFv3::correct().
correct()
void correct () virtual
solve the residual equations and update the state
Implements DATurbulenceModel.
Definition at line 413 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::solveTurbState_.
invTranProdNuTildaEqn()
void invTranProdNuTildaEqn (const volScalarField & mySource, volScalarField & pseudoNuTilda) virtual
Inverse transpose product, A_nuTilda^(-T)
Reimplemented from DATurbulenceModel.
Definition at line 520 of file DASpalartAllmarasFv3.C.
constructPseudoNuTildaEqn()
void constructPseudoNuTildaEqn () virtual
construct pseudoNuTildaEqn_, which is nuTildaEqn with swapped upper and lower arrays
Reimplemented from DATurbulenceModel.
Definition at line 595 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::chi(), DASpalartAllmarasFv3::Cw1_, DASpalartAllmarasFv3::DnuTildaEff(), DASpalartAllmarasFv3::fv1(), DASpalartAllmarasFv3::fv2(), DASpalartAllmarasFv3::fv3(), DASpalartAllmarasFv3::fw(), DASpalartAllmarasFv3::kappa_, DASpalartAllmarasFv3::nuTilda_, DATurbulenceModel::phi_, DASpalartAllmarasFv3::pseudoNuTilda_, DASpalartAllmarasFv3::pseudoNuTildaEqn_, DASpalartAllmarasFv3::relaxNuTildaEqn_, DATurbulenceModel::U_, and DASpalartAllmarasFv3::y_.
rhsSolvePseudoNuTildaEqn()
void rhsSolvePseudoNuTildaEqn (const volScalarField & nuTildaSource) virtual
solve pseudoNuTildaEqn_ with overwritten rhs
Reimplemented from DATurbulenceModel.
Definition at line 633 of file DASpalartAllmarasFv3.C.
References forAll(), DASpalartAllmarasFv3::pseudoNuTilda_, DASpalartAllmarasFv3::pseudoNuTildaEqn_, and DASpalartAllmarasFv3::solverDictNuTilda_.
calcLduResidualTurb()
void calcLduResidualTurb (volScalarField & nuTildaRes) virtual
calculate the turbulence residual using LDU matrix
Reimplemented from DATurbulenceModel.
Definition at line 665 of file DASpalartAllmarasFv3.C.
References DASpalartAllmarasFv3::Cb1_, DASpalartAllmarasFv3::Cb2_, DASpalartAllmarasFv3::chi(), DASpalartAllmarasFv3::Cw1_, DASpalartAllmarasFv3::DnuTildaEff(), forAll(), DASpalartAllmarasFv3::fv1(), DASpalartAllmarasFv3::fv2(), DASpalartAllmarasFv3::fv3(), DASpalartAllmarasFv3::fw(), DASpalartAllmarasFv3::kappa_, DASpalartAllmarasFv3::nuTilda_, DATurbulenceModel::phi_, DASpalartAllmarasFv3::sigmaNut_, DATurbulenceModel::U_, and DASpalartAllmarasFv3::y_.
Member Data Documentation
sigmaNut_
dimensionedScalar sigmaNut_ protected
Definition at line 55 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::DnuTildaEff().
kappa_
dimensionedScalar kappa_ protected
Definition at line 56 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), DASpalartAllmarasFv3::constructPseudoNuTildaEqn(), and DASpalartAllmarasFv3::fw().
Cb1_
dimensionedScalar Cb1_ protected
Definition at line 57 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), and DASpalartAllmarasFv3::calcResiduals().
Cb2_
dimensionedScalar Cb2_ protected
Definition at line 58 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), and DASpalartAllmarasFv3::calcResiduals().
Cw1_
dimensionedScalar Cw1_ protected
Definition at line 59 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::constructPseudoNuTildaEqn().
Cw2_
dimensionedScalar Cw2_ protected
Definition at line 60 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::fw().
Cw3_
dimensionedScalar Cw3_ protected
Definition at line 61 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::fw().
Cv1_
dimensionedScalar Cv1_ protected
Definition at line 62 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::fv1().
Cv2_
dimensionedScalar Cv2_ protected
Definition at line 63 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::fv2(), and DASpalartAllmarasFv3::fv3().
nuTilda_
volScalarField& nuTilda_ protected
Definition at line 86 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), DASpalartAllmarasFv3::chi(), DASpalartAllmarasFv3::constructPseudoNuTildaEqn(), DASpalartAllmarasFv3::correctBoundaryConditions(), DASpalartAllmarasFv3::correctNut(), DASpalartAllmarasFv3::DnuTildaEff(), and DASpalartAllmarasFv3::fw().
nuTildaRes_
volScalarField nuTildaRes_ protected
Definition at line 87 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcResiduals().
pseudoNuTilda_
volScalarField pseudoNuTilda_ protected
pseudoNuTilda_ and pseudoNuTildaEqn_ for solving adjoint equation
Definition at line 91 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::constructPseudoNuTildaEqn(), and DASpalartAllmarasFv3::rhsSolvePseudoNuTildaEqn().
pseudoNuTildaEqn_
fvScalarMatrix pseudoNuTildaEqn_ protected
Definition at line 92 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::constructPseudoNuTildaEqn(), and DASpalartAllmarasFv3::rhsSolvePseudoNuTildaEqn().
y_
const volScalarField& y_ protected
3D wall distance
Definition at line 95 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcLduResidualTurb(), DASpalartAllmarasFv3::calcResiduals(), DASpalartAllmarasFv3::constructPseudoNuTildaEqn(), and DASpalartAllmarasFv3::fw().
solveTurbState_
label solveTurbState_ = 0 protected
whether to solve for turb states
Definition at line 98 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::correct().
printInterval_
label printInterval_ protected
time step interval to print residual
Definition at line 101 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::calcResiduals(), and DASpalartAllmarasFv3::DASpalartAllmarasFv3().
relaxNuTildaEqn_
scalar relaxNuTildaEqn_ = 1.0 protected
Definition at line 104 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::constructPseudoNuTildaEqn(), and DASpalartAllmarasFv3::DASpalartAllmarasFv3().
solverDictNuTilda_
dictionary solverDictNuTilda_ protected
Definition at line 105 of file DASpalartAllmarasFv3.H.
Referenced by DASpalartAllmarasFv3::DASpalartAllmarasFv3(), and DASpalartAllmarasFv3::rhsSolvePseudoNuTildaEqn().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAModel/DATurbulenceModel/DASpalartAllmarasFv3.H
dafoam/src/adjoint/DAModel/DATurbulenceModel/DASpalartAllmarasFv3.C