DAFoam: DALinearEqn Class Reference
DALinearEqn Class Reference
Public Member Functions
DALinearEqn (const fvMesh &mesh, const DAOption &daOption)
Constructors.
virtual ~DALinearEqn ()
Destructor.
void createMLRKSP (const Mat jacMat, const Mat jacPCMat, KSP ksp)
create a multi-level, Richardson KSP object
label solveLinearEqn (const KSP ksp, const Vec rhsVec, Vec solVec)
solve the linear equation given a ksp and right-hand-side vector
label getRunTime ()
return the runtime for the adjoint solver
label getPrintInterval ()
return printInterval from DAOption
Static Public Member Functions
static PetscErrorCode myKSPMonitor (KSP, PetscInt, PetscReal, void *)
ksp monitor function
Protected Attributes
const fvMesh & mesh_
Foam::fvMesh object.
const DAOption & daOption_
Foam::DAOption object.
Detailed Description
Definition at line 31 of file DALinearEqn.H.
Constructor & Destructor Documentation
DALinearEqn()
DALinearEqn (const fvMesh & mesh, const DAOption & daOption)
Constructors.
Definition at line 17 of file DALinearEqn.C.
~DALinearEqn()
virtual ~DALinearEqn () inline virtual
Destructor.
Definition at line 55 of file DALinearEqn.H.
Member Function Documentation
createMLRKSP()
void createMLRKSP (const Mat jacMat, const Mat jacPCMat, KSP ksp)
create a multi-level, Richardson KSP object
Definition at line 27 of file DALinearEqn.C.
References assignValueCheckAD, DALinearEqn::daOption_, DAOption::getSubDictOption(), and DALinearEqn::myKSPMonitor().
solveLinearEqn()
label solveLinearEqn (const KSP ksp, const Vec rhsVec, Vec solVec)
solve the linear equation given a ksp and right-hand-side vector
Definition at line 335 of file DALinearEqn.C.
References DALinearEqn::daOption_, DALinearEqn::getRunTime(), and DAOption::getSubDictOption().
myKSPMonitor()
PetscErrorCode myKSPMonitor (KSP ksp, PetscInt n, PetscReal rnorm, void * ctx) static
ksp monitor function
Definition at line 408 of file DALinearEqn.C.
References DALinearEqn::getPrintInterval(), and DALinearEqn::getRunTime().
Referenced by DALinearEqn::createMLRKSP().
getRunTime()
label getRunTime ()
return the runtime for the adjoint solver
Definition at line 441 of file DALinearEqn.C.
References DALinearEqn::mesh_.
Referenced by DALinearEqn::myKSPMonitor(), and DALinearEqn::solveLinearEqn().
getPrintInterval()
label getPrintInterval ()
return printInterval from DAOption
Definition at line 450 of file DALinearEqn.C.
References DALinearEqn::daOption_, and DAOption::getOption().
Referenced by DALinearEqn::myKSPMonitor().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Foam::fvMesh object.
Definition at line 43 of file DALinearEqn.H.
Referenced by DALinearEqn::getRunTime().
daOption_
const DAOption& daOption_ protected
Foam::DAOption object.
Definition at line 46 of file DALinearEqn.H.
Referenced by DALinearEqn::createMLRKSP(), DALinearEqn::getPrintInterval(), and DALinearEqn::solveLinearEqn().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DALinearEqn/DALinearEqn.H
dafoam/src/adjoint/DALinearEqn/DALinearEqn.C