DAFoam: DAJacCondFdW Class Reference
DAJacCondFdW Class Reference
Public Member Functions
TypeName ("dFdW")
DAJacCondFdW (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAJacCondFdW ()
virtual void initializeJacCon (const dictionary &options)
virtual void setupJacCon (const dictionary &options)
assign 1 to all non-zero elements for the Jacobian connecitivyt matrix
virtual void setObjFuncVec (scalarList objFuncFaceValues, scalarList objFuncCellValues, Vec objFuncVec) const
assign values for the objective function vector based on the face and cell value lists
virtual void clear ()
clear members in parent and child objects
Public Member Functions inherited from DAJacCon
TypeName ("DAJacCon")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAJacCon, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAJacCon (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAJacCon ()
virtual void setupJacConPreallocation (const dictionary &options)
calculate the preallocation vector for initializing the JacCon mat, if necessary
label getNJacConColors () const
get the number of JacCon colors
virtual void preallocatedRdW (Mat dRMat, const label transposed) const
preallocate dRdW matrix using the preallocVec
void calcJacConColoring (const word postFix="")
compute graph coloring for Jacobian connectivity matrix
void readJacConColoring (const word postFix="")
read colors for JacCon
label coloringExists (const word postFix="") const
whether the coloring file exists
Vec getJacConColor () const
return DAJacCon::jacConColors_
void calcColoredColumns (const label colorI, Vec coloredColumn) const
calculate the colored column vector
Protected Member Functions
void initializePetscVecs ()
initialize petsc vectors
label getLocalObjFuncGeoIndex (const word idxType, const label idxI) const
get the local index of geometry element for objective
label getGlobalObjFuncGeoIndex (const word idxType, const label idxI) const
get the global index of geometry element for objective
Protected Member Functions inherited from DAJacCon
void initializeStateBoundaryCon ()
initialize state boundary connection
void calcNeiBFaceGlobalCompact (labelList &neiBFaceGlobalCompact)
calculate DAJacCon::neiBFaceGlobalCompact_
label getLocalCoupledBFaceIndex (const label localFaceI) const
given a local face index, return the local index of the coupled boundary face
void setupStateBoundaryCon (Mat *stateBoundaryCon)
calculate DAJacCon::stateBoundaryCon_
void setupStateBoundaryConID (Mat *stateBoundaryConID)
calculate DAJacCon::stateBoundaryConID_
void createConnectionMat (Mat *connectedStates)
allocate connectedState matrix
void addStateConnections (Mat connections, const label cellI, const label connectedLevelLocal, const wordList connectedStatesLocal, const List< List< word >> connectedStateInterProc, const label addFace)
a high-level function to add connected state column indices to the connectivity matrix
void setConnections (Mat conMat, const label idx) const
add value 1 for the colume idx to conMat
void setupJacobianConnections (Mat conMat, Mat connections, const label idxI)
assign values in connections to a specific row idxI in conMat
void combineStateBndCon (Mat *stateBoundaryCon, Mat *stateBoundaryConTmp)
combine stateBoundaryCon and stateBoundaryConTmp, this is to ensure including all connected states for parallel cases
void addConMatCell (Mat conMat, const label gRow, const label cellI, const word stateName, const scalar val)
add val to the gRow row in conMat, the column indice are the state (given by stateName) for a given cellI
void addConMatNeighbourCells (Mat conMat, const label gRow, const label cellI, const word stateName, const scalar val)
add val to gRow row in conMat, column indice are the neighbouring states (given by stateName) for a given cellI
void addConMatCellFaces (Mat conMat, const label gRow, const label cellI, const word stateName, const scalar val)
add val to gRow row in conMat, column indice are the faces (given by stateName) for a given cellI
void addBoundaryFaceConnections (Mat conMat, const label gRow, const label cellI, const labelList v, const List< List< word >> connectedStates, const label addFaces)
add the column index of the (iner-proc) connected states and faces to conMat, given a local face index
void clearDAJacConMembers ()
clear members in DAJacCon
void checkSpecialBCs ()
check if there is special boundary conditions that need special treatment in jacCon_
void setPIVVec (Vec iSPIV, const label idxI)
function used to add connectivity for pressureInletVelocity
label addPhi4PIV (const word stateName, const label idxI, const label comp=-1)
add connectivity phi for pressureInletVelocity
Protected Attributes
globalIndex globalObjFuncGeoNumbering_
the global numbering for the discrete source of objective function
label objFuncFaceSize_ = 0
the size of objFunc faces
label objFuncCellSize_ = 0
the size of objFunc cells
Protected Attributes inherited from DAJacCon
const word modelType_
the name of the jacCon matrix
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex object.
DAColoring daColoring_
DAColoring object.
DAField daField_
DAField object.
HashTable< wordList > stateInfo_
the regState_ list from DAStateInfo object
Mat stateBoundaryCon_
matrix to store boundary connectivity levels for state Jacobians
Mat stateBoundaryConID_
matrix to store boundary connectivity ID for state Jacobians
labelList neiBFaceGlobalCompact_
neibough face global index for a given local boundary face
Mat jacCon_
Jacobian connectivity mat.
Vec jacConColors_
jacCon matrix colors
label nJacConColors_
number of jacCon colors
Vec isPIVBCState_
a vector to show whether a state is connected to a pressureInletVelocity boundary face (3 level max)
Additional Inherited Members
Static Public Member Functions inherited from DAJacCon
static autoPtr< DAJacCon > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Detailed Description
Definition at line 26 of file DAJacCondFdW.H.
Constructor & Destructor Documentation
DAJacCondFdW()
DAJacCondFdW (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 19 of file DAJacCondFdW.C.
References DAJacCondFdW::initializePetscVecs(), and DAJacCon::initializeStateBoundaryCon().
~DAJacCondFdW()
virtual ~DAJacCondFdW () inline virtual
Definition at line 66 of file DAJacCondFdW.H.
References DAJacCondFdW::clear(), DAJacCondFdW::initializeJacCon(), DAJacCondFdW::setObjFuncVec(), and DAJacCondFdW::setupJacCon().
Member Function Documentation
initializePetscVecs()
void initializePetscVecs () protected
initialize petsc vectors
Definition at line 47 of file DAJacCondFdW.C.
References DAJacCon::daIndex_, DAJacCon::jacConColors_, and DAIndex::nLocalAdjointStates.
Referenced by DAJacCondFdW::DAJacCondFdW().
getLocalObjFuncGeoIndex()
label getLocalObjFuncGeoIndex (const word idxType, const label idxI) const protected
get the local index of geometry element for objective
Definition at line 318 of file DAJacCondFdW.C.
References DAJacCondFdW::objFuncFaceSize_.
Referenced by DAJacCondFdW::getGlobalObjFuncGeoIndex(), and DAJacCondFdW::setObjFuncVec().
getGlobalObjFuncGeoIndex()
label getGlobalObjFuncGeoIndex (const word idxType, const label idxI) const protected
get the global index of geometry element for objective
Definition at line 370 of file DAJacCondFdW.C.
References DAJacCondFdW::getLocalObjFuncGeoIndex(), and DAJacCondFdW::globalObjFuncGeoNumbering_.
Referenced by DAJacCondFdW::setupJacCon().
TypeName()
TypeName ("dFdW")
initializeJacCon()
void initializeJacCon (const dictionary & options) virtual
calculate the initialize the state Jacobian connectivity matrix
Implements DAJacCon.
Definition at line 63 of file DAJacCondFdW.C.
References DAJacCon::daIndex_, DAUtility::genGlobalIndex(), DAJacCondFdW::globalObjFuncGeoNumbering_, DAJacCon::jacCon_, DAIndex::nLocalAdjointStates, DAJacCondFdW::objFuncCellSize_, and DAJacCondFdW::objFuncFaceSize_.
Referenced by DAJacCondFdW::~DAJacCondFdW().
setupJacCon()
void setupJacCon (const dictionary & options) virtual
assign 1 to all non-zero elements for the Jacobian connecitivyt matrix
Implements DAJacCon.
Definition at line 115 of file DAJacCondFdW.C.
References DAJacCon::addStateConnections(), DAIndex::adjStateType, DAIndex::bFaceFaceI, DAIndex::bFacePatchI, DAJacCon::createConnectionMat(), DAJacCon::daIndex_, DAJacCon::daOption_, DAJacCondFdW::getGlobalObjFuncGeoIndex(), DAOption::getOption(), DAJacCon::jacCon_, DAJacCon::mesh_, DAIndex::nLocalInternalFaces, DAJacCon::setupJacobianConnections(), DAJacCon::stateInfo_, and DAUtility::writeMatrixBinary().
Referenced by DAJacCondFdW::~DAJacCondFdW().
setObjFuncVec()
void setObjFuncVec (scalarList objFuncFaceValues, scalarList objFuncCellValues, Vec objFuncVec) const virtual
assign values for the objective function vector based on the face and cell value lists
Reimplemented from DAJacCon.
Definition at line 409 of file DAJacCondFdW.C.
References DAJacCondFdW::getLocalObjFuncGeoIndex().
Referenced by DAJacCondFdW::~DAJacCondFdW().
clear()
void clear () virtual
clear members in parent and child objects
Implements DAJacCon.
Definition at line 35 of file DAJacCondFdW.C.
References DAJacCon::clearDAJacConMembers(), and DAJacCondFdW::globalObjFuncGeoNumbering_.
Referenced by DAJacCondFdW::~DAJacCondFdW().
Member Data Documentation
globalObjFuncGeoNumbering_
globalIndex globalObjFuncGeoNumbering_ protected
the global numbering for the discrete source of objective function
Definition at line 35 of file DAJacCondFdW.H.
Referenced by DAJacCondFdW::clear(), DAJacCondFdW::getGlobalObjFuncGeoIndex(), and DAJacCondFdW::initializeJacCon().
objFuncFaceSize_
label objFuncFaceSize_ = 0 protected
the size of objFunc faces
Definition at line 48 of file DAJacCondFdW.H.
Referenced by DAJacCondFdW::getLocalObjFuncGeoIndex(), and DAJacCondFdW::initializeJacCon().
objFuncCellSize_
label objFuncCellSize_ = 0 protected
the size of objFunc cells
Definition at line 51 of file DAJacCondFdW.H.
Referenced by DAJacCondFdW::initializeJacCon().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAJacCon/DAJacCondFdW.H
dafoam/src/adjoint/DAJacCon/DAJacCondFdW.C