DAFoam: SpalartAllmarasFv3Beta< BasicTurbulenceModel > Class Template Reference
SpalartAllmarasFv3Beta< BasicTurbulenceModel > Class Template Reference
Public Types
typedef BasicTurbulenceModel::alphaField alphaField
typedef BasicTurbulenceModel::rhoField rhoField
typedef BasicTurbulenceModel::transportModel transportModel
Public Member Functions
TypeName ("SpalartAllmarasFv3Beta")
SpalartAllmarasFv3Beta (const alphaField &alpha, const rhoField &rho, const volVectorField &U, const surfaceScalarField &alphaRhoPhi, const surfaceScalarField &phi, const transportModel &transport, const word &propertiesName=turbulenceModel::propertiesName, const word &type=typeName)
virtual ~SpalartAllmarasFv3Beta ()
virtual bool read ()
virtual tmp< volScalarField > k () const
virtual tmp< volScalarField > epsilon () const
virtual void correct ()
Protected Member Functions
virtual void correctNut ()
Protected Attributes
volScalarField nuTilda_
turbulence variable for SA
volScalarField betaSA_
betaSA field that will be multiplied to the SA production term
volScalarField betaSATrue_
the reference betaSA, usually be 1
volVectorField UTrue_
the reference velocity field, usually from experiment or DNS
const volScalarField & y_
Detailed Description
template<class BasicTurbulenceModel>
class Foam::RASModels::SpalartAllmarasFv3Beta< BasicTurbulenceModel >
Definition at line 32 of file SpalartAllmarasFv3Beta.H.
Member Typedef Documentation
alphaField
typedef BasicTurbulenceModel::alphaField alphaField
Definition at line 66 of file SpalartAllmarasFv3Beta.H.
rhoField
typedef BasicTurbulenceModel::rhoField rhoField
Definition at line 67 of file SpalartAllmarasFv3Beta.H.
transportModel
typedef BasicTurbulenceModel::transportModel transportModel
Definition at line 68 of file SpalartAllmarasFv3Beta.H.
Constructor & Destructor Documentation
SpalartAllmarasFv3Beta()
SpalartAllmarasFv3Beta (const alphaField & alpha, const rhoField & rho, const volVectorField & U, const surfaceScalarField & alphaRhoPhi, const surfaceScalarField & phi, const transportModel & transport, const word & propertiesName = turbulenceModel::propertiesName, const word & type = typeName)
Definition at line 30 of file SpalartAllmarasFv3Beta.C.
~SpalartAllmarasFv3Beta()
virtual ~SpalartAllmarasFv3Beta () inline virtual
Definition at line 87 of file SpalartAllmarasFv3Beta.H.
References SpalartAllmarasFv3Beta< BasicTurbulenceModel >::correct(), SpalartAllmarasFv3Beta< BasicTurbulenceModel >::epsilon(), SpalartAllmarasFv3Beta< BasicTurbulenceModel >::k(), and SpalartAllmarasFv3Beta< BasicTurbulenceModel >::read().
Member Function Documentation
correctNut()
void correctNut () protected virtual
Definition at line 23 of file SpalartAllmarasFv3Beta.C.
TypeName()
TypeName ("SpalartAllmarasFv3Beta< BasicTurbulenceModel >")
read()
bool read () virtual
Definition at line 87 of file SpalartAllmarasFv3Beta.C.
Referenced by SpalartAllmarasFv3Beta< BasicTurbulenceModel >::~SpalartAllmarasFv3Beta().
k()
tmp< volScalarField > k () const virtual
Definition at line 93 of file SpalartAllmarasFv3Beta.C.
Referenced by SpalartAllmarasFv3Beta< BasicTurbulenceModel >::~SpalartAllmarasFv3Beta().
epsilon()
tmp< volScalarField > epsilon () const virtual
Definition at line 99 of file SpalartAllmarasFv3Beta.C.
Referenced by SpalartAllmarasFv3Beta< BasicTurbulenceModel >::~SpalartAllmarasFv3Beta().
correct()
void correct () virtual
Definition at line 106 of file SpalartAllmarasFv3Beta.C.
Referenced by SpalartAllmarasFv3Beta< BasicTurbulenceModel >::~SpalartAllmarasFv3Beta().
Member Data Documentation
nuTilda_
volScalarField nuTilda_ protected
turbulence variable for SA
Definition at line 47 of file SpalartAllmarasFv3Beta.H.
betaSA_
volScalarField betaSA_ protected
betaSA field that will be multiplied to the SA production term
Definition at line 50 of file SpalartAllmarasFv3Beta.H.
betaSATrue_
volScalarField betaSATrue_ protected
the reference betaSA, usually be 1
Definition at line 53 of file SpalartAllmarasFv3Beta.H.
UTrue_
volVectorField UTrue_ protected
the reference velocity field, usually from experiment or DNS
Definition at line 56 of file SpalartAllmarasFv3Beta.H.
y_
const volScalarField& y_ protected
Definition at line 61 of file SpalartAllmarasFv3Beta.H.
The documentation for this class was generated from the following files:
dafoam/src/adjoint/models/SpalartAllmarasFv3Beta/SpalartAllmarasFv3Beta.H
dafoam/src/adjoint/models/SpalartAllmarasFv3Beta/SpalartAllmarasFv3Beta.C