DAFoam: DAStateInfo Class Reference
DAStateInfo Class Reference
Public Member Functions
TypeName ("DAStateInfo")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAStateInfo, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel),(modelType, mesh, daOption, daModel))
DAStateInfo (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel)
virtual ~DAStateInfo ()
const HashTable< wordList > & getStateInfo () const
return the reference of stateInfo_
const HashTable< List< List< word > > > & getStateResConInfo () const
return the reference of stateResConInfo_
Static Public Member Functions
static autoPtr< DAStateInfo > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel)
Protected Attributes
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
HashTable< wordList > stateInfo_
registered states 1st hash: solverName, 2nd hash: fieldType, 3nd list, stateNames
HashTable< List< List< word > > > stateResConInfo_
table to specify how the states are connected to the residuals for a given solver
Detailed Description
Definition at line 30 of file DAStateInfo.H.
Constructor & Destructor Documentation
DAStateInfo()
DAStateInfo (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel)
Definition at line 22 of file DAStateInfo.C.
References DAStateInfo::stateInfo_.
~DAStateInfo()
virtual ~DAStateInfo () inline virtual
Definition at line 90 of file DAStateInfo.H.
Member Function Documentation
TypeName()
TypeName ("DAStateInfo")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , DAStateInfo , dictionary , (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel) , (modelType, mesh, daOption, daModel))
New()
autoPtr< DAStateInfo > New (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel) static
Definition at line 43 of file DAStateInfo.C.
References daModel(), daOption(), DAOption::getAllOptions(), and mesh.
Referenced by DAField::DAField(), DAIndex::DAIndex(), DAJacCon::DAJacCon(), DAPartDeriv::DAPartDeriv(), ColoringSolid::run(), ColoringIncompressible::run(), and ColoringCompressible::run().
getStateInfo()
const HashTable<wordList>& getStateInfo () const inline
return the reference of stateInfo_
Definition at line 95 of file DAStateInfo.H.
References DAStateInfo::stateInfo_.
getStateResConInfo()
const HashTable<List<List<word> > >& getStateResConInfo () const inline
return the reference of stateResConInfo_
Definition at line 101 of file DAStateInfo.H.
References DAStateInfo::stateResConInfo_.
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
fvMesh
Definition at line 42 of file DAStateInfo.H.
daOption_
const DAOption& daOption_ protected
DAOption object.
Definition at line 45 of file DAStateInfo.H.
daModel_
const DAModel& daModel_ protected
DAModel object.
Definition at line 48 of file DAStateInfo.H.
stateInfo_
HashTable<wordList> stateInfo_ protected
registered states 1st hash: solverName, 2nd hash: fieldType, 3nd list, stateNames
Definition at line 51 of file DAStateInfo.H.
Referenced by DAStateInfo::DAStateInfo(), DAStateInfoPisoFoam::DAStateInfoPisoFoam(), DAStateInfoRhoSimpleCFoam::DAStateInfoRhoSimpleCFoam(), DAStateInfoRhoSimpleFoam::DAStateInfoRhoSimpleFoam(), DAStateInfoSimpleFoam::DAStateInfoSimpleFoam(), DAStateInfoSimpleTFoam::DAStateInfoSimpleTFoam(), DAStateInfoSolidDisplacementFoam::DAStateInfoSolidDisplacementFoam(), DAStateInfoTurboFoam::DAStateInfoTurboFoam(), and DAStateInfo::getStateInfo().
stateResConInfo_
HashTable<List<List<word> > > stateResConInfo_ protected
table to specify how the states are connected to the residuals for a given solver
Definition at line 54 of file DAStateInfo.H.
Referenced by DAStateInfoPisoFoam::DAStateInfoPisoFoam(), DAStateInfoRhoSimpleCFoam::DAStateInfoRhoSimpleCFoam(), DAStateInfoRhoSimpleFoam::DAStateInfoRhoSimpleFoam(), DAStateInfoSimpleFoam::DAStateInfoSimpleFoam(), DAStateInfoSimpleTFoam::DAStateInfoSimpleTFoam(), DAStateInfoSolidDisplacementFoam::DAStateInfoSolidDisplacementFoam(), DAStateInfoTurboFoam::DAStateInfoTurboFoam(), and DAStateInfo::getStateResConInfo().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAStateInfo/DAStateInfo.H
dafoam/src/adjoint/DAStateInfo/DAStateInfo.C