DAFoam: DAResidual Class Reference
DAResidual Class Reference abstract
Public Member Functions
TypeName ("DAResidual")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAResidual, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAResidual (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAResidual ()
virtual void clear ()=0
clear the members
virtual void calcResiduals (const dictionary &options)=0
compute residuals
virtual void updateIntermediateVariables ()=0
update any intermdiate variables that are dependent on state variables and are used in calcResiduals
virtual void correctBoundaryConditions ()=0
update the boundary condition for all the states in the selected solver
void masterFunction (const dictionary &options, const Vec xvVec, const Vec wVec, Vec resVec)
the master function that compute the residual vector given the state and point vectors
Static Public Member Functions
static autoPtr< DAResidual > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Protected Attributes
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex.
DAField daField_
DAField object.
Detailed Description
Definition at line 35 of file DAResidual.H.
Constructor & Destructor Documentation
DAResidual()
DAResidual (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 22 of file DAResidual.C.
~DAResidual()
virtual ~DAResidual () inline virtual
Definition at line 98 of file DAResidual.H.
Member Function Documentation
TypeName()
TypeName ("DAResidual")
Runtime type information.
declareRunTimeSelectionTable()
declareRunTimeSelectionTable (autoPtr , DAResidual , dictionary , (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex) , (modelType, mesh, daOption, daModel, daIndex))
New()
autoPtr< DAResidual > New (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex) static
Definition at line 38 of file DAResidual.C.
References daIndex(), daModel(), daOption(), and mesh.
Referenced by ColoringSolid::run(), ColoringIncompressible::run(), and ColoringCompressible::run().
clear()
virtual void clear () pure virtual
clear the members
Implemented in DAResidualRhoSimpleFoam, DAResidualTurboFoam, DAResidualRhoSimpleCFoam, DAResidualSimpleTFoam, DAResidualSimpleFoam, DAResidualPimpleFoam, DAResidualPisoFoam, DAResidualSolidDisplacementFoam, DAResidualScalarTransportFoam, DAResidualLaplacianFoam, and DAResidualDummy.
calcResiduals()
virtual void calcResiduals (const dictionary & options) pure virtual
compute residuals
Implemented in DAResidualRhoSimpleFoam, DAResidualTurboFoam, DAResidualRhoSimpleCFoam, DAResidualSimpleTFoam, DAResidualSimpleFoam, DAResidualPimpleFoam, DAResidualPisoFoam, DAResidualSolidDisplacementFoam, DAResidualScalarTransportFoam, DAResidualLaplacianFoam, and DAResidualDummy.
Referenced by DAResidual::masterFunction().
updateIntermediateVariables()
virtual void updateIntermediateVariables () pure virtual
update any intermdiate variables that are dependent on state variables and are used in calcResiduals
Implemented in DAResidualRhoSimpleFoam, DAResidualTurboFoam, DAResidualRhoSimpleCFoam, DAResidualSimpleTFoam, DAResidualSimpleFoam, DAResidualPimpleFoam, DAResidualPisoFoam, DAResidualSolidDisplacementFoam, DAResidualScalarTransportFoam, DAResidualLaplacianFoam, and DAResidualDummy.
Referenced by DAResidual::masterFunction(), and DAObjFunc::masterFunction().
correctBoundaryConditions()
virtual void correctBoundaryConditions () pure virtual
update the boundary condition for all the states in the selected solver
Implemented in DAResidualRhoSimpleFoam, DAResidualTurboFoam, DAResidualRhoSimpleCFoam, DAResidualSimpleTFoam, DAResidualSimpleFoam, DAResidualPimpleFoam, DAResidualPisoFoam, DAResidualSolidDisplacementFoam, DAResidualScalarTransportFoam, DAResidualLaplacianFoam, and DAResidualDummy.
Referenced by DAResidual::masterFunction(), and DAObjFunc::masterFunction().
masterFunction()
void masterFunction (const dictionary & options, const Vec xvVec, const Vec wVec, Vec resVec)
the master function that compute the residual vector given the state and point vectors
Definition at line 81 of file DAResidual.C.
References DAResidual::calcResiduals(), DAModel::correctBoundaryConditions(), DAResidual::correctBoundaryConditions(), DAResidual::daField_, daModel(), DAResidual::daModel_, DAField::ofResField2ResVec(), DAField::pointVec2OFMesh(), DAField::specialBCTreatment(), DAField::stateVec2OFField(), and DAResidual::updateIntermediateVariables().
Referenced by DAPartDerivdRdAOA::calcPartDerivMat(), DAPartDerivdRdW::calcPartDerivMat(), DAPartDerivdRdBC::calcPartDerivMat(), DAPartDerivdRdFFD::calcPartDerivMat(), DAPartDerivdRdACTL::calcPartDerivMat(), DAPartDerivdRdACTD::calcPartDerivMat(), and DAPartDerivdRdACTP::calcPartDerivMat().
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
fvMesh
Definition at line 47 of file DAResidual.H.
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), DAResidualLaplacianFoam::DAResidualLaplacianFoam(), and DAResidualScalarTransportFoam::DAResidualScalarTransportFoam().
daOption_
const DAOption& daOption_ protected
DAOption object.
Definition at line 50 of file DAResidual.H.
Referenced by DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleCFoam::DAResidualRhoSimpleCFoam(), DAResidualRhoSimpleFoam::DAResidualRhoSimpleFoam(), DAResidualTurboFoam::DAResidualTurboFoam(), and DAResidualSolidDisplacementFoam::updateDAndGradD().
daModel_
const DAModel& daModel_ protected
DAModel object.
Definition at line 53 of file DAResidual.H.
Referenced by DAResidual::masterFunction().
daIndex_
const DAIndex& daIndex_ protected
DAIndex.
Definition at line 56 of file DAResidual.H.
daField_
DAField daField_ protected
DAField object.
Definition at line 59 of file DAResidual.H.
Referenced by DAResidual::masterFunction().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAResidual/DAResidual.H
dafoam/src/adjoint/DAResidual/DAResidual.C