DAFoam: DAResidualSolidDisplacementFoam Class Reference
DAResidualSolidDisplacementFoam Class Reference
Public Member Functions
TypeName ("DASolidDisplacementFoam")
DAResidualSolidDisplacementFoam (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAResidualSolidDisplacementFoam ()
virtual void clear ()
clear the members
virtual void calcResiduals (const dictionary &options)
compute residual
virtual void updateIntermediateVariables ()
update any intermediate variables that are dependent on state variables and are used in calcResiduals
virtual void correctBoundaryConditions ()
update the boundary condition for all the states in the selected solver
Public Member Functions inherited from DAResidual
TypeName ("DAResidual")
Runtime type information.
declareRunTimeSelectionTable (autoPtr, DAResidual, dictionary,(const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex),(modelType, mesh, daOption, daModel, daIndex))
DAResidual (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
virtual ~DAResidual ()
void masterFunction (const dictionary &options, const Vec xvVec, const Vec wVec, Vec resVec)
the master function that compute the residual vector given the state and point vectors
Protected Member Functions
void updateDAndGradD ()
Protected Attributes
volTensorField & gradD_
volSymmTensorField & sigmaD_
volVectorField & divSigmaExp_
volScalarField & lambda_
volScalarField & mu_
label isTractionDisplacementBC_
These are state variables, state residuals, and partial derivatives
volVectorField & D_
volVectorField DRes_
volVectorField DResPartDeriv_
Protected Attributes inherited from DAResidual
const fvMesh & mesh_
fvMesh
const DAOption & daOption_
DAOption object.
const DAModel & daModel_
DAModel object.
const DAIndex & daIndex_
DAIndex.
DAField daField_
DAField object.
Additional Inherited Members
Static Public Member Functions inherited from DAResidual
static autoPtr< DAResidual > New (const word modelType, const fvMesh &mesh, const DAOption &daOption, const DAModel &daModel, const DAIndex &daIndex)
Detailed Description
Definition at line 26 of file DAResidualSolidDisplacementFoam.H.
Constructor & Destructor Documentation
DAResidualSolidDisplacementFoam()
DAResidualSolidDisplacementFoam (const word modelType, const fvMesh & mesh, const DAOption & daOption, const DAModel & daModel, const DAIndex & daIndex)
Definition at line 19 of file DAResidualSolidDisplacementFoam.C.
References DAResidualSolidDisplacementFoam::D_, DAResidualSolidDisplacementFoam::isTractionDisplacementBC_, mesh, and stressControl.
~DAResidualSolidDisplacementFoam()
virtual ~DAResidualSolidDisplacementFoam () inline virtual
Definition at line 61 of file DAResidualSolidDisplacementFoam.H.
References DAResidualSolidDisplacementFoam::calcResiduals(), DAResidualSolidDisplacementFoam::clear(), DAResidualSolidDisplacementFoam::correctBoundaryConditions(), and DAResidualSolidDisplacementFoam::updateIntermediateVariables().
Member Function Documentation
updateDAndGradD()
void updateDAndGradD () protected
Definition at line 112 of file DAResidualSolidDisplacementFoam.C.
References DAResidualSolidDisplacementFoam::D_, DAResidual::daOption_, DAOption::getOption(), DAResidualSolidDisplacementFoam::gradD_, and DAResidualSolidDisplacementFoam::isTractionDisplacementBC_.
Referenced by DAResidualSolidDisplacementFoam::updateIntermediateVariables().
TypeName()
TypeName ("DASolidDisplacementFoam")
clear()
void clear () virtual
clear the members
Implements DAResidual.
Definition at line 75 of file DAResidualSolidDisplacementFoam.C.
References DAResidualSolidDisplacementFoam::DRes_, and DAResidualSolidDisplacementFoam::DResPartDeriv_.
Referenced by DAResidualSolidDisplacementFoam::~DAResidualSolidDisplacementFoam().
calcResiduals()
void calcResiduals (const dictionary & options) virtual
compute residual
Implements DAResidual.
Definition at line 87 of file DAResidualSolidDisplacementFoam.C.
References DAResidualSolidDisplacementFoam::D_, DAResidualSolidDisplacementFoam::divSigmaExp_, DAResidualSolidDisplacementFoam::DRes_, DAResidualSolidDisplacementFoam::lambda_, DAResidualSolidDisplacementFoam::mu_, and normalizeResiduals.
Referenced by DAResidualSolidDisplacementFoam::~DAResidualSolidDisplacementFoam().
updateIntermediateVariables()
void updateIntermediateVariables () virtual
update any intermediate variables that are dependent on state variables and are used in calcResiduals
Implements DAResidual.
Definition at line 139 of file DAResidualSolidDisplacementFoam.C.
References DAResidualSolidDisplacementFoam::divSigmaExp_, DAResidualSolidDisplacementFoam::gradD_, DAResidualSolidDisplacementFoam::lambda_, DAResidualSolidDisplacementFoam::mu_, DAResidualSolidDisplacementFoam::sigmaD_, and DAResidualSolidDisplacementFoam::updateDAndGradD().
Referenced by DAResidualSolidDisplacementFoam::~DAResidualSolidDisplacementFoam().
correctBoundaryConditions()
void correctBoundaryConditions () virtual
update the boundary condition for all the states in the selected solver
Implements DAResidual.
Definition at line 153 of file DAResidualSolidDisplacementFoam.C.
References DAResidualSolidDisplacementFoam::D_.
Referenced by DAResidualSolidDisplacementFoam::~DAResidualSolidDisplacementFoam().
Member Data Documentation
D_
volVectorField& D_ protected
Definition at line 33 of file DAResidualSolidDisplacementFoam.H.
Referenced by DAResidualSolidDisplacementFoam::calcResiduals(), DAResidualSolidDisplacementFoam::correctBoundaryConditions(), DAResidualSolidDisplacementFoam::DAResidualSolidDisplacementFoam(), and DAResidualSolidDisplacementFoam::updateDAndGradD().
DRes_
volVectorField DRes_ protected
Definition at line 34 of file DAResidualSolidDisplacementFoam.H.
Referenced by DAResidualSolidDisplacementFoam::calcResiduals(), and DAResidualSolidDisplacementFoam::clear().
DResPartDeriv_
volVectorField DResPartDeriv_ protected
Definition at line 35 of file DAResidualSolidDisplacementFoam.H.
Referenced by DAResidualSolidDisplacementFoam::clear().
gradD_
volTensorField& gradD_ protected
Definition at line 38 of file DAResidualSolidDisplacementFoam.H.
Referenced by DAResidualSolidDisplacementFoam::updateDAndGradD(), and DAResidualSolidDisplacementFoam::updateIntermediateVariables().
sigmaD_
volSymmTensorField& sigmaD_ protected
Definition at line 39 of file DAResidualSolidDisplacementFoam.H.
Referenced by DAResidualSolidDisplacementFoam::updateIntermediateVariables().
divSigmaExp_
volVectorField& divSigmaExp_ protected
Definition at line 40 of file DAResidualSolidDisplacementFoam.H.
Referenced by DAResidualSolidDisplacementFoam::calcResiduals(), and DAResidualSolidDisplacementFoam::updateIntermediateVariables().
lambda_
volScalarField& lambda_ protected
Definition at line 41 of file DAResidualSolidDisplacementFoam.H.
Referenced by DAResidualSolidDisplacementFoam::calcResiduals(), and DAResidualSolidDisplacementFoam::updateIntermediateVariables().
mu_
volScalarField& mu_ protected
Definition at line 42 of file DAResidualSolidDisplacementFoam.H.
Referenced by DAResidualSolidDisplacementFoam::calcResiduals(), and DAResidualSolidDisplacementFoam::updateIntermediateVariables().
isTractionDisplacementBC_
label isTractionDisplacementBC_ protected
Definition at line 44 of file DAResidualSolidDisplacementFoam.H.
Referenced by DAResidualSolidDisplacementFoam::DAResidualSolidDisplacementFoam(), and DAResidualSolidDisplacementFoam::updateDAndGradD().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/DAResidual/DAResidualSolidDisplacementFoam.H
dafoam/src/adjoint/DAResidual/DAResidualSolidDisplacementFoam.C