DAFoam: multiFreqScalarFvPatchField Class Reference
multiFreqScalarFvPatchField Class Reference
Public Member Functions
TypeName ("multiFreqScalar")
multiFreqScalarFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &)
multiFreqScalarFvPatchField (const fvPatch &, const DimensionedField< scalar, volMesh > &, const dictionary &)
multiFreqScalarFvPatchField (const multiFreqScalarFvPatchField &, const fvPatch &, const DimensionedField< scalar, volMesh > &, const fvPatchFieldMapper &)
multiFreqScalarFvPatchField (const multiFreqScalarFvPatchField &)
virtual tmp< fvPatchScalarField > clone () const
multiFreqScalarFvPatchField (const multiFreqScalarFvPatchField &, const DimensionedField< scalar, volMesh > &)
virtual tmp< fvPatchScalarField > clone (const DimensionedField< scalar, volMesh > &iF) const
virtual void updateCoeffs ()
virtual void write (Ostream &) const
Detailed Description
Definition at line 60 of file multiFreqScalarFvPatchField.H.
Constructor & Destructor Documentation
multiFreqScalarFvPatchField() [1/5]
multiFreqScalarFvPatchField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF)
Definition at line 14 of file multiFreqScalarFvPatchField.C.
Referenced by multiFreqScalarFvPatchField::clone().
multiFreqScalarFvPatchField() [2/5]
multiFreqScalarFvPatchField (const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const dictionary & dict)
Definition at line 25 of file multiFreqScalarFvPatchField.C.
References p.
multiFreqScalarFvPatchField() [3/5]
multiFreqScalarFvPatchField (const multiFreqScalarFvPatchField & ptf, const fvPatch & p, const DimensionedField< scalar, volMesh > & iF, const fvPatchFieldMapper & mapper)
Definition at line 47 of file multiFreqScalarFvPatchField.C.
multiFreqScalarFvPatchField() [4/5]
multiFreqScalarFvPatchField (const multiFreqScalarFvPatchField & wbppsf)
Definition at line 61 of file multiFreqScalarFvPatchField.C.
multiFreqScalarFvPatchField() [5/5]
multiFreqScalarFvPatchField (const multiFreqScalarFvPatchField & wbppsf, const DimensionedField< scalar, volMesh > & iF)
Definition at line 72 of file multiFreqScalarFvPatchField.C.
Member Function Documentation
TypeName()
TypeName ("multiFreqScalar")
clone() [1/2]
virtual tmp<fvPatchScalarField> clone () const inline virtual
Definition at line 100 of file multiFreqScalarFvPatchField.H.
References multiFreqScalarFvPatchField::multiFreqScalarFvPatchField().
clone() [2/2]
virtual tmp<fvPatchScalarField> clone (const DimensionedField< scalar, volMesh > & iF) const inline virtual
Definition at line 112 of file multiFreqScalarFvPatchField.H.
References multiFreqScalarFvPatchField::multiFreqScalarFvPatchField(), multiFreqScalarFvPatchField::updateCoeffs(), and multiFreqScalarFvPatchField::write().
updateCoeffs()
void updateCoeffs () virtual
Definition at line 85 of file multiFreqScalarFvPatchField.C.
References p.
Referenced by multiFreqScalarFvPatchField::clone().
write()
void write (Ostream & os) const virtual
Definition at line 110 of file multiFreqScalarFvPatchField.C.
Referenced by multiFreqScalarFvPatchField::clone().
The documentation for this class was generated from the following files:
dafoam/src/adjoint/boundaryConditions/multiFreqScalar/multiFreqScalarFvPatchField.H
dafoam/src/adjoint/boundaryConditions/multiFreqScalar/multiFreqScalarFvPatchField.C