DAFoam: MRFZoneListDF Class Reference
MRFZoneListDF Class Reference
Public Member Functions
MRFZoneListDF (const fvMesh &mesh, const dictionary &dict)
~MRFZoneListDF ()
bool active (const bool warn=false) const
void reset (const dictionary &dict)
tmp< volVectorField > DDt (const volVectorField &U) const
tmp< volVectorField > DDt (const volScalarField &rho, const volVectorField &U) const
void makeRelative (volVectorField &U) const
void makeRelative (surfaceScalarField &phi) const
tmp< surfaceScalarField > relative (const tmp< surfaceScalarField > &phi) const
tmp< FieldField< fvsPatchField, scalar > > relative (const tmp< FieldField< fvsPatchField, scalar >> &tphi) const
tmp< Field< scalar > > relative (const tmp< Field< scalar >> &tphi, const label patchi) const
void makeRelative (const surfaceScalarField &rho, surfaceScalarField &phi) const
void correctBoundaryVelocity (volVectorField &U) const
void update ()
const scalar & getOmegaRef () const
bool read (const dictionary &dict)
bool writeData (Ostream &os) const
Protected Attributes
const fvMesh & mesh_
Friends
Ostream & operator<< (Ostream &os, const MRFZoneListDF &models)
Detailed Description
Definition at line 55 of file MRFZoneListDF.H.
Constructor & Destructor Documentation
MRFZoneListDF()
MRFZoneListDF (const fvMesh & mesh, const dictionary & dict)
Definition at line 40 of file MRFZoneListDF.C.
References MRFZoneListDF::active(), and MRFZoneListDF::reset().
~MRFZoneListDF()
~MRFZoneListDF ()
Definition at line 53 of file MRFZoneListDF.C.
Member Function Documentation
active()
bool active (const bool warn = false) const
Definition at line 59 of file MRFZoneListDF.C.
Referenced by MRFZoneListDF::MRFZoneListDF().
reset()
void reset (const dictionary & dict)
Definition at line 75 of file MRFZoneListDF.C.
Referenced by DASolver::calcdRdBCTPsiAD(), and MRFZoneListDF::MRFZoneListDF().
DDt() [1/2]
Foam::tmp< Foam::volVectorField > DDt (const volVectorField & U) const
Definition at line 118 of file MRFZoneListDF.C.
References U.
Referenced by DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), and DAResidualRhoSimpleFoam::calcResiduals().
DDt() [2/2]
Foam::tmp< Foam::volVectorField > DDt (const volScalarField & rho, const volVectorField & U) const
Definition at line 139 of file MRFZoneListDF.C.
References rho, and U.
makeRelative() [1/3]
void makeRelative (volVectorField & U) const
Definition at line 146 of file MRFZoneListDF.C.
References U.
Referenced by DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), and DAResidualRhoSimpleFoam::calcResiduals().
makeRelative() [2/3]
void makeRelative (surfaceScalarField & phi) const
Definition at line 154 of file MRFZoneListDF.C.
References phi.
relative() [1/3]
Foam::tmp< Foam::surfaceScalarField > relative (const tmp< surfaceScalarField > & phi) const
Definition at line 162 of file MRFZoneListDF.C.
relative() [2/3]
Foam::tmp< Foam::FieldField< Foam::fvsPatchField, Foam::scalar > > relative (const tmp< FieldField< fvsPatchField, scalar >> & tphi) const
Definition at line 173 of file MRFZoneListDF.C.
relative() [3/3]
Foam::tmp< Foam::Field< Foam::scalar > > relative (const tmp< Field< scalar >> & tphi, const label patchi) const
Definition at line 184 of file MRFZoneListDF.C.
makeRelative() [3/3]
void makeRelative (const surfaceScalarField & rho, surfaceScalarField & phi) const
Definition at line 195 of file MRFZoneListDF.C.
References phi, and rho.
correctBoundaryVelocity()
void correctBoundaryVelocity (volVectorField & U) const
Definition at line 205 of file MRFZoneListDF.C.
References U.
Referenced by DAResidualSimpleFoam::updateIntermediateVariables(), DAResidualSimpleTFoam::updateIntermediateVariables(), DAResidualTurboFoam::updateIntermediateVariables(), and DAResidualRhoSimpleFoam::updateIntermediateVariables().
update()
void update ()
Definition at line 231 of file MRFZoneListDF.C.
getOmegaRef()
const Foam::scalar & getOmegaRef () const
Definition at line 213 of file MRFZoneListDF.C.
read()
bool read (const dictionary & dict)
Definition at line 105 of file MRFZoneListDF.C.
writeData()
bool writeData (Ostream & os) const
Definition at line 111 of file MRFZoneListDF.C.
Referenced by Foam::operator<<().
Friends And Related Function Documentation
operator<<
Ostream& operator<< (Ostream & os, const MRFZoneListDF & models) friend
Member Data Documentation
mesh_
const fvMesh& mesh_ protected
Definition at line 70 of file MRFZoneListDF.H.
The documentation for this class was generated from the following files:
dafoam/src/adjoint/models/MRFDF/MRFZoneListDF.H
dafoam/src/adjoint/models/MRFDF/MRFZoneListDF.C