DAFoam: DASolvers Class Reference
DASolvers Class Reference
Public Member Functions
DASolvers (char *argsAll, PyObject *pyOptions)
Construct from components.
virtual ~DASolvers ()
Destructor.
void initSolver ()
initialize fields and variables
label solvePrimal (const Vec xvVec, Vec wVec)
solve the primal equations
void calcdRdWT (const Vec xvVec, const Vec wVec, const label isPC, Mat dRdWT)
compute dRdWT
void calcdFdW (const Vec xvVec, const Vec wVec, const word objFuncName, Vec dFdW)
compute dFdW
void calcdFdWAD (const Vec xvVec, const Vec wVec, const word objFuncName, Vec dFdW)
compute dFdW using reverse-mode AD
void calcdFdXvAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdXv)
compute dFdXv using reverse-mode AD
void calcdRdXvTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, Vec dRdXvTPsi)
compute dRdXv^T*Psi
void calcdRdActTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdActTPsi)
compute dRdAct^T*Psi
void calcdRdAOATPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdAOATPsi)
compute dRdAOA^T*Psi
void createMLRKSP (const Mat jacMat, const Mat jacPCMat, KSP ksp)
create the multi-level Richardson KSP for solving linear equation
void createMLRKSPMatrixFree (const Mat jacPCMat, KSP ksp)
create a multi-level, Richardson KSP object with matrix-free Jacobians
void initializedRdWTMatrixFree (const Vec xvVec, const Vec wVec)
initialize matrix free dRdWT
void destroydRdWTMatrixFree ()
destroy matrix free dRdWT
void solveLinearEqn (const KSP ksp, const Vec rhsVec, Vec solVec)
solve the linear equation
void convertMPIVec2SeqVec (const Vec mpiVec, Vec seqVec)
convert the mpi vec to a seq vec
void calcdRdBC (const Vec xvVec, const Vec wVec, const word designVarName, Mat dRdBC)
compute dRdBC
void calcdFdBC (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdBC)
compute dFdBC
void calcdRdBCTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdBCTPsi)
compute dRdBC^T*Psi
void calcdRdAOA (const Vec xvVec, const Vec wVec, const word designVarName, Mat dRdAOA)
compute dRdAOA
void calcdFdAOA (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdAOA)
compute dFdAOA
void calcdRdFFD (const Vec xvVec, const Vec wVec, const word designVarName, Mat dRdFFD)
compute dRdFFD
void calcdFdFFD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdFFD)
compute dFdFFD
void calcdRdACT (const Vec xvVec, const Vec wVec, const word designVarName, const word designVarType, Mat dRdACT)
compute dRdACT
void calcdFdACTAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdACT)
compute dFdACT
void calcdFdACT (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, const word designVarType, Vec dFdACT)
compute dFdACT
void calcdRdFieldTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdFieldTPsi)
compute dRdField
void calcdFdFieldAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdField)
compute dFdField
void calcdRdWOldTPsiAD (const label oldTimeLevel, const Vec psi, Vec dRdWOldTPsi)
compute dRdWOld^T*Psi
void calcdRdWTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, Vec dRdWTPsi)
compute [dRdW]^T*Psi
void updateOFField (const Vec wVec)
Update the OpenFOAM field values (including both internal and boundary fields) based on the state vector wVec.
void updateOFMesh (const Vec xvVec)
Update the OpenFoam mesh point coordinates based on the point vector xvVec.
label getGlobalXvIndex (const label idxPoint, const label idxCoord) const
basically, we call DAIndex::getGlobalXvIndex
void ofField2StateVec (Vec stateVec) const
basically, we call DASolver::ofField2StateVec
void stateVec2OFField (const Vec stateVec) const
basically, we call DASolver::stateVec2OFField
label checkMesh () const
basically, we call DASolver::checkMesh
label getNLocalAdjointStates () const
return the number of local adjoint states
label getNLocalAdjointBoundaryStates () const
return the number of local adjoint boundary states
label getNLocalCells () const
return the number of local cells
void syncDAOptionToActuatorDVs ()
synchronize the values in DAOption and actuatorDiskDVs_
double getObjFuncValue (const word objFuncName)
return the value of objective
void printAllOptions ()
call DASolver::printAllOptions
void setdXvdFFDMat (const Mat dXvdFFDMat)
set values for dXvdFFDMat
void setFFD2XvSeedVec (Vec vecIn)
set the value for DASolver::FFD2XvSeedVec_
void updateDAOption (PyObject *pyOptions)
update the allOptions_ dict in DAOption based on the pyOptions from pyDAFoam
double getPrevPrimalSolTime ()
get the solution time folder for previous primal solution
void pointVec2OFMesh (const Vec xvVec) const
assign the points in fvMesh of OpenFOAM based on the point vector
void ofMesh2PointVec (Vec xvVec) const
assign the point vector based on the points in fvMesh of OpenFOAM
void resVec2OFResField (const Vec resVec) const
assign the OpenFOAM residual fields based on the resVec
void ofResField2ResVec (Vec resVec) const
assign the resVec based on OpenFOAM residual fields
void writeMatrixBinary (const Mat matIn, const word prefix)
write the matrix in binary format
void writeMatrixASCII (const Mat matIn, const word prefix)
write the matrix in ASCII format
void readMatrixBinary (Mat matIn, const word prefix)
read petsc matrix in binary format
void writeVectorASCII (const Vec vecIn, const word prefix)
write petsc vector in ascii format
void readVectorBinary (Vec vecIn, const word prefix)
read petsc vector in binary format
void writeVectorBinary (const Vec vecIn, const word prefix)
write petsc vector in binary format
void setTimeInstanceField (const label instanceI)
assign primal variables based on the current time instance
void setTimeInstanceVar (const word mode, Mat stateMat, Mat stateBCMat, Vec timeVec, Vec timeIdxVec)
assign the time instance mats to/from the lists in the OpenFOAM layer depending on the mode
double getTimeInstanceObjFunc (const label instanceI, const word objFuncName)
return the value of objective function at the given time instance and name
void setFieldValue4GlobalCellI (const word fieldName, const scalar val, const label globalCellI, const label compI=0)
set the field value
void updateBoundaryConditions (const word fieldName, const word fieldType)
update the boundary condition for a field
void calcPrimalResidualStatistics (const word mode)
Calculate the mean, max, and norm2 for all residuals and print it to screen.
PetscScalar getForwardADDerivVal (const word objFuncName)
get forwardADDerivVal_
void calcResidualVec (Vec resVec)
calculate the residual and assign it to the resVec vector
Detailed Description
Definition at line 27 of file DASolvers.H.
Constructor & Destructor Documentation
DASolvers()
DASolvers (char * argsAll, PyObject * pyOptions)
Construct from components.
Definition at line 15 of file DASolvers.C.
References DASolver::New().
~DASolvers()
~DASolvers () virtual
Destructor.
Definition at line 25 of file DASolvers.C.
Member Function Documentation
initSolver()
void initSolver () inline
initialize fields and variables
Definition at line 58 of file DASolvers.H.
solvePrimal()
label solvePrimal (const Vec xvVec, Vec wVec) inline
solve the primal equations
Definition at line 64 of file DASolvers.H.
calcdRdWT()
void calcdRdWT (const Vec xvVec, const Vec wVec, const label isPC, Mat dRdWT) inline
compute dRdWT
Definition at line 72 of file DASolvers.H.
calcdFdW()
void calcdFdW (const Vec xvVec, const Vec wVec, const word objFuncName, Vec dFdW) inline
compute dFdW
Definition at line 82 of file DASolvers.H.
calcdFdWAD()
void calcdFdWAD (const Vec xvVec, const Vec wVec, const word objFuncName, Vec dFdW) inline
compute dFdW using reverse-mode AD
Definition at line 92 of file DASolvers.H.
calcdFdXvAD()
void calcdFdXvAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdXv) inline
compute dFdXv using reverse-mode AD
Definition at line 102 of file DASolvers.H.
calcdRdXvTPsiAD()
void calcdRdXvTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, Vec dRdXvTPsi) inline
compute dRdXv^T*Psi
Definition at line 113 of file DASolvers.H.
calcdRdActTPsiAD()
void calcdRdActTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdActTPsi) inline
compute dRdAct^T*Psi
Definition at line 123 of file DASolvers.H.
calcdRdAOATPsiAD()
void calcdRdAOATPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdAOATPsi) inline
compute dRdAOA^T*Psi
Definition at line 134 of file DASolvers.H.
createMLRKSP()
void createMLRKSP (const Mat jacMat, const Mat jacPCMat, KSP ksp) inline
create the multi-level Richardson KSP for solving linear equation
Definition at line 145 of file DASolvers.H.
createMLRKSPMatrixFree()
void createMLRKSPMatrixFree (const Mat jacPCMat, KSP ksp) inline
create a multi-level, Richardson KSP object with matrix-free Jacobians
Definition at line 154 of file DASolvers.H.
initializedRdWTMatrixFree()
void initializedRdWTMatrixFree (const Vec xvVec, const Vec wVec) inline
initialize matrix free dRdWT
Definition at line 162 of file DASolvers.H.
destroydRdWTMatrixFree()
void destroydRdWTMatrixFree () inline
destroy matrix free dRdWT
Definition at line 170 of file DASolvers.H.
solveLinearEqn()
void solveLinearEqn (const KSP ksp, const Vec rhsVec, Vec solVec) inline
solve the linear equation
Definition at line 176 of file DASolvers.H.
convertMPIVec2SeqVec()
void convertMPIVec2SeqVec (const Vec mpiVec, Vec seqVec) inline
convert the mpi vec to a seq vec
Definition at line 185 of file DASolvers.H.
calcdRdBC()
void calcdRdBC (const Vec xvVec, const Vec wVec, const word designVarName, Mat dRdBC) inline
compute dRdBC
Definition at line 193 of file DASolvers.H.
calcdFdBC()
void calcdFdBC (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdBC) inline
compute dFdBC
Definition at line 203 of file DASolvers.H.
calcdRdBCTPsiAD()
void calcdRdBCTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdBCTPsi) inline
compute dRdBC^T*Psi
Definition at line 214 of file DASolvers.H.
calcdRdAOA()
void calcdRdAOA (const Vec xvVec, const Vec wVec, const word designVarName, Mat dRdAOA) inline
compute dRdAOA
Definition at line 225 of file DASolvers.H.
calcdFdAOA()
void calcdFdAOA (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdAOA) inline
compute dFdAOA
Definition at line 235 of file DASolvers.H.
calcdRdFFD()
void calcdRdFFD (const Vec xvVec, const Vec wVec, const word designVarName, Mat dRdFFD) inline
compute dRdFFD
Definition at line 246 of file DASolvers.H.
calcdFdFFD()
void calcdFdFFD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdFFD) inline
compute dFdFFD
Definition at line 256 of file DASolvers.H.
calcdRdACT()
void calcdRdACT (const Vec xvVec, const Vec wVec, const word designVarName, const word designVarType, Mat dRdACT) inline
compute dRdACT
Definition at line 267 of file DASolvers.H.
calcdFdACTAD()
void calcdFdACTAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdACT) inline
compute dFdACT
Definition at line 278 of file DASolvers.H.
calcdFdACT()
void calcdFdACT (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, const word designVarType, Vec dFdACT) inline
compute dFdACT
Definition at line 289 of file DASolvers.H.
calcdRdFieldTPsiAD()
void calcdRdFieldTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, const word designVarName, Vec dRdFieldTPsi) inline
compute dRdField
Definition at line 301 of file DASolvers.H.
calcdFdFieldAD()
void calcdFdFieldAD (const Vec xvVec, const Vec wVec, const word objFuncName, const word designVarName, Vec dFdField) inline
compute dFdField
Definition at line 312 of file DASolvers.H.
calcdRdWOldTPsiAD()
void calcdRdWOldTPsiAD (const label oldTimeLevel, const Vec psi, Vec dRdWOldTPsi) inline
compute dRdWOld^T*Psi
Definition at line 323 of file DASolvers.H.
calcdRdWTPsiAD()
void calcdRdWTPsiAD (const Vec xvVec, const Vec wVec, const Vec psi, Vec dRdWTPsi) inline
compute [dRdW]^T*Psi
Definition at line 332 of file DASolvers.H.
updateOFField()
void updateOFField (const Vec wVec) inline
Update the OpenFOAM field values (including both internal and boundary fields) based on the state vector wVec.
Definition at line 342 of file DASolvers.H.
updateOFMesh()
void updateOFMesh (const Vec xvVec) inline
Update the OpenFoam mesh point coordinates based on the point vector xvVec.
Definition at line 348 of file DASolvers.H.
getGlobalXvIndex()
label getGlobalXvIndex (const label idxPoint, const label idxCoord) const inline
basically, we call DAIndex::getGlobalXvIndex
Definition at line 354 of file DASolvers.H.
ofField2StateVec()
void ofField2StateVec (Vec stateVec) const inline
basically, we call DASolver::ofField2StateVec
Definition at line 362 of file DASolvers.H.
stateVec2OFField()
void stateVec2OFField (const Vec stateVec) const inline
basically, we call DASolver::stateVec2OFField
Definition at line 368 of file DASolvers.H.
checkMesh()
label checkMesh () const inline
basically, we call DASolver::checkMesh
Definition at line 374 of file DASolvers.H.
getNLocalAdjointStates()
label getNLocalAdjointStates () const inline
return the number of local adjoint states
Definition at line 380 of file DASolvers.H.
getNLocalAdjointBoundaryStates()
label getNLocalAdjointBoundaryStates () const inline
return the number of local adjoint boundary states
Definition at line 386 of file DASolvers.H.
getNLocalCells()
label getNLocalCells () const inline
return the number of local cells
Definition at line 392 of file DASolvers.H.
syncDAOptionToActuatorDVs()
void syncDAOptionToActuatorDVs () inline
synchronize the values in DAOption and actuatorDiskDVs_
Definition at line 398 of file DASolvers.H.
Referenced by PYDAFOAM::updateDAOption().
getObjFuncValue()
double getObjFuncValue (const word objFuncName) inline
return the value of objective
Definition at line 404 of file DASolvers.H.
References assignValueCheckAD.
printAllOptions()
void printAllOptions () inline
call DASolver::printAllOptions
Definition at line 412 of file DASolvers.H.
setdXvdFFDMat()
void setdXvdFFDMat (const Mat dXvdFFDMat) inline
set values for dXvdFFDMat
Definition at line 418 of file DASolvers.H.
Referenced by PYDAFOAM::solveAdjoint().
setFFD2XvSeedVec()
void setFFD2XvSeedVec (Vec vecIn) inline
set the value for DASolver::FFD2XvSeedVec_
Definition at line 424 of file DASolvers.H.
updateDAOption()
void updateDAOption (PyObject * pyOptions) inline
update the allOptions_ dict in DAOption based on the pyOptions from pyDAFoam
Definition at line 430 of file DASolvers.H.
Referenced by PYDAFOAM::solveAdjoint().
getPrevPrimalSolTime()
double getPrevPrimalSolTime () inline
get the solution time folder for previous primal solution
Definition at line 436 of file DASolvers.H.
References assignValueCheckAD.
pointVec2OFMesh()
void pointVec2OFMesh (const Vec xvVec) const inline
assign the points in fvMesh of OpenFOAM based on the point vector
Definition at line 444 of file DASolvers.H.
ofMesh2PointVec()
void ofMesh2PointVec (Vec xvVec) const inline
assign the point vector based on the points in fvMesh of OpenFOAM
Definition at line 450 of file DASolvers.H.
resVec2OFResField()
void resVec2OFResField (const Vec resVec) const inline
assign the OpenFOAM residual fields based on the resVec
Definition at line 456 of file DASolvers.H.
ofResField2ResVec()
void ofResField2ResVec (Vec resVec) const inline
assign the resVec based on OpenFOAM residual fields
Definition at line 462 of file DASolvers.H.
writeMatrixBinary()
void writeMatrixBinary (const Mat matIn, const word prefix) inline
write the matrix in binary format
Definition at line 468 of file DASolvers.H.
writeMatrixASCII()
void writeMatrixASCII (const Mat matIn, const word prefix) inline
write the matrix in ASCII format
Definition at line 476 of file DASolvers.H.
readMatrixBinary()
void readMatrixBinary (Mat matIn, const word prefix) inline
read petsc matrix in binary format
Definition at line 484 of file DASolvers.H.
writeVectorASCII()
void writeVectorASCII (const Vec vecIn, const word prefix) inline
write petsc vector in ascii format
Definition at line 492 of file DASolvers.H.
readVectorBinary()
void readVectorBinary (Vec vecIn, const word prefix) inline
read petsc vector in binary format
Definition at line 500 of file DASolvers.H.
writeVectorBinary()
void writeVectorBinary (const Vec vecIn, const word prefix) inline
write petsc vector in binary format
Definition at line 508 of file DASolvers.H.
setTimeInstanceField()
void setTimeInstanceField (const label instanceI) inline
assign primal variables based on the current time instance
Definition at line 516 of file DASolvers.H.
setTimeInstanceVar()
void setTimeInstanceVar (const word mode, Mat stateMat, Mat stateBCMat, Vec timeVec, Vec timeIdxVec) inline
assign the time instance mats to/from the lists in the OpenFOAM layer depending on the mode
Definition at line 522 of file DASolvers.H.
getTimeInstanceObjFunc()
double getTimeInstanceObjFunc (const label instanceI, const word objFuncName) inline
return the value of objective function at the given time instance and name
Definition at line 533 of file DASolvers.H.
References assignValueCheckAD.
setFieldValue4GlobalCellI()
void setFieldValue4GlobalCellI (const word fieldName, const scalar val, const label globalCellI, const label compI = 0) inline
set the field value
Definition at line 543 of file DASolvers.H.
updateBoundaryConditions()
void updateBoundaryConditions (const word fieldName, const word fieldType) inline
update the boundary condition for a field
Definition at line 553 of file DASolvers.H.
calcPrimalResidualStatistics()
void calcPrimalResidualStatistics (const word mode) inline
Calculate the mean, max, and norm2 for all residuals and print it to screen.
Definition at line 561 of file DASolvers.H.
getForwardADDerivVal()
PetscScalar getForwardADDerivVal (const word objFuncName) inline
get forwardADDerivVal_
Definition at line 567 of file DASolvers.H.
calcResidualVec()
void calcResidualVec (Vec resVec) inline
calculate the residual and assign it to the resVec vector
Definition at line 573 of file DASolvers.H.
The documentation for this class was generated from the following files:
dafoam/src/pyDASolvers/DASolvers.H
dafoam/src/pyDASolvers/DASolvers.C