DAFoam: dafoam/src/adjoint/DASolver/DASolidDisplacementFoam/createRefsSolidDisplacement.H File Reference
createRefsSolidDisplacement.H File Reference
Functions
runTime setTime (0.0, 0)
this setDAObjFuncList ()
Variables
Time & runTime = runTimePtr_()
fvMesh & mesh = meshPtr_()
volScalarField & rho = rhoPtr_()
volScalarField & mu = muPtr_()
volScalarField & lambda = lambdaPtr_()
volVectorField & D = DPtr_()
volSymmTensorField & sigmaD = sigmaDPtr_()
volTensorField & gradD = gradDPtr_()
volVectorField & divSigmaExp = divSigmaExpPtr_()
Function Documentation
setTime()
runTime setTime (0. 0, 0)
setDAObjFuncList()
this setDAObjFuncList ()
Variable Documentation
runTime
Time& runTime = runTimePtr_()
Definition at line 1 of file createRefsSolidDisplacement.H.
mesh
fvMesh& mesh = meshPtr_()
Definition at line 4 of file createRefsSolidDisplacement.H.
rho
volScalarField& rho = rhoPtr_()
Definition at line 5 of file createRefsSolidDisplacement.H.
mu
volScalarField& mu = muPtr_()
Definition at line 6 of file createRefsSolidDisplacement.H.
Referenced by DAObjFuncVonMisesStressKS::calcObjFunc(), DASolidDisplacementFoam::solvePrimal(), and tractionDisplacementFvPatchVectorField::updateCoeffs().
lambda
volScalarField& lambda = lambdaPtr_()
Definition at line 7 of file createRefsSolidDisplacement.H.
Referenced by DAObjFuncVonMisesStressKS::calcObjFunc(), DASolidDisplacementFoam::solvePrimal(), and tractionDisplacementFvPatchVectorField::updateCoeffs().
D
volVectorField& D = DPtr_()
Definition at line 8 of file createRefsSolidDisplacement.H.
Referenced by DASolidDisplacementFoam::solvePrimal().
sigmaD
volSymmTensorField& sigmaD = sigmaDPtr_()
Definition at line 9 of file createRefsSolidDisplacement.H.
Referenced by DASolidDisplacementFoam::solvePrimal().
gradD
volTensorField& gradD = gradDPtr_()
Definition at line 10 of file createRefsSolidDisplacement.H.
Referenced by DAObjFuncVonMisesStressKS::calcObjFunc(), DASolidDisplacementFoam::solvePrimal(), and tractionDisplacementFvPatchVectorField::updateCoeffs().
divSigmaExp
volVectorField& divSigmaExp = divSigmaExpPtr_()
Definition at line 11 of file createRefsSolidDisplacement.H.
Referenced by DASolidDisplacementFoam::solvePrimal().