DAFoam: dafoam/src/adjoint/DASolver/DARhoSimpleCFoam/createRefsRhoSimpleC.H File Reference
createRefsRhoSimpleC.H File Reference
Functions
runTime setTime (0.0, 0)
this setDAObjFuncList ()
Variables
Time & runTime = runTimePtr_()
fvMesh & mesh = meshPtr_()
simpleControl & simple = simplePtr_()
fluidThermo & thermo = pThermoPtr_()
volScalarField & p = thermo.p()
volScalarField & rho = rhoPtr_()
volVectorField & U = UPtr_()
surfaceScalarField & phi = phiPtr_()
scalar & cumulativeContErr = cumulativeContErr_
pressureControl & pressureControl = pressureControlPtr_()
initialMass_ = fvc::domainIntegrate(rho)
const volScalarField & psi = thermo.psi()
const dictionary & allOptions = daOptionPtr_->getAllOptions()
Function Documentation
setTime()
runTime setTime (0. 0, 0)
setDAObjFuncList()
this setDAObjFuncList ()
Variable Documentation
runTime
Time& runTime = runTimePtr_()
Definition at line 1 of file createRefsRhoSimpleC.H.
mesh
fvMesh& mesh = meshPtr_()
Definition at line 4 of file createRefsRhoSimpleC.H.
simple
simpleControl& simple = simplePtr_()
Definition at line 5 of file createRefsRhoSimpleC.H.
Referenced by if(), and while().
thermo
fluidThermo& thermo = pThermoPtr_()
Definition at line 6 of file createRefsRhoSimpleC.H.
Referenced by if().
p
volScalarField& p = thermo.p()
Definition at line 7 of file createRefsRhoSimpleC.H.
rho
volScalarField& rho = rhoPtr_()
Definition at line 8 of file createRefsRhoSimpleC.H.
Referenced by DAObjFuncMass::calcObjFunc(), DAObjFuncVonMisesStressKS::calcObjFunc(), DATurbulenceModel::divDevRhoReff(), DAkOmegaSST::kSource(), DAkOmegaSST::omegaSource(), DAkOmegaSST::Qsas(), DARhoSimpleCFoam::solvePrimal(), DATurboFoam::solvePrimal(), DARhoSimpleFoam::solvePrimal(), and tractionDisplacementFvPatchVectorField::updateCoeffs().
U
volVectorField& U = UPtr_()
Definition at line 9 of file createRefsRhoSimpleC.H.
phi
surfaceScalarField& phi = phiPtr_()
Definition at line 10 of file createRefsRhoSimpleC.H.
cumulativeContErr
scalar& cumulativeContErr = cumulativeContErr_
Definition at line 11 of file createRefsRhoSimpleC.H.
pressureControl
pressureControl& pressureControl = pressureControlPtr_()
Definition at line 12 of file createRefsRhoSimpleC.H.
Referenced by if(), and while().
initialMass_
initialMass_ = fvc::domainIntegrate(rho)
Definition at line 13 of file createRefsRhoSimpleC.H.
Referenced by if().
psi
const volScalarField& psi = thermo.psi()
Definition at line 14 of file createRefsRhoSimpleC.H.
Referenced by if().
allOptions
const dictionary& allOptions = daOptionPtr_->getAllOptions()
Definition at line 15 of file createRefsRhoSimpleC.H.
Referenced by DASolver::calcTotalDeriv(), DAFvSourceActuatorDisk::DAFvSourceActuatorDisk(), DAFvSourceActuatorPoint::DAFvSourceActuatorPoint(), DAResidualPisoFoam::DAResidualPisoFoam(), DAResidualRhoSimpleFoam::DAResidualRhoSimpleFoam(), DAResidualSimpleFoam::DAResidualSimpleFoam(), if(), DASimpleFoam::initSolver(), DARhoSimpleFoam::initSolver(), DAPisoFoam::initSolver(), DASolver::New(), ColoringSolid::run(), ColoringCompressible::run(), ColoringIncompressible::run(), DASolver::setDAObjFuncList(), DAField::setPrimalBoundaryConditions(), and DASolver::solveAdjoint().