DAFoam: dafoam/src/adjoint/DASolver/DAPimpleFoam/createRefsPimple.H File Reference
createRefsPimple.H File Reference
Functions
runTime setTime (0.0, 0)
Variables
Time & runTime = runTimePtr_()
fvMesh & mesh = meshPtr_()
pimpleControlDF & pimple = pimplePtr_()
volScalarField & p = pPtr_()
volVectorField & U = UPtr_()
surfaceScalarField & phi = phiPtr_()
singlePhaseTransportModel & laminarTransport = laminarTransportPtr_()
scalar & cumulativeContErr = cumulativeContErr_
label & pRefCell = pRefCell_
scalar & pRefValue = pRefValue_
volVectorField & fvSource = fvSourcePtr_()
Function Documentation
setTime()
runTime setTime (0. 0, 0)
Variable Documentation
runTime
Time& runTime = runTimePtr_()
Definition at line 1 of file createRefsPimple.H.
mesh
fvMesh& mesh = meshPtr_()
Definition at line 4 of file createRefsPimple.H.
pimple
pimpleControlDF& pimple = pimplePtr_()
Definition at line 5 of file createRefsPimple.H.
Referenced by DAPimpleDyMFoam::solvePrimal(), DAPimpleFoam::solvePrimal(), and while().
p
volScalarField& p = pPtr_()
Definition at line 6 of file createRefsPimple.H.
Referenced by DASimpleFoam::calcAdjointResidual(), DASimpleFoam::calcLduResiduals(), DAObjFuncMoment::calcObjFunc(), DAObjFuncCenterOfPressure::calcObjFunc(), DAObjFuncPower::calcObjFunc(), DAObjFuncTotalPressure::calcObjFunc(), DAObjFuncFieldInversion::calcObjFunc(), DAObjFuncTotalPressureRatio::calcObjFunc(), DAObjFuncForce::calcObjFunc(), Foam::checkCoupledPoints(), DASolver::getAcousticDataInternal(), DAMotion::getForce(), DASolver::getForcesInternal(), if(), main(), DASimpleFoam::runFPAdj(), DATurboFoam::solvePrimal(), DARhoSimpleCFoam::solvePrimal(), DARhoSimpleFoam::solvePrimal(), DASimpleTFoam::solvePrimal(), DASimpleFoam::solvePrimal(), multiFreqScalarFvPatchField::updateCoeffs(), multiFreqVectorFvPatchField::updateCoeffs(), and while().
U
volVectorField& U = UPtr_()
Definition at line 7 of file createRefsPimple.H.
phi
surfaceScalarField& phi = phiPtr_()
Definition at line 8 of file createRefsPimple.H.
Referenced by DASimpleFoam::calcAdjointResidual(), DASimpleFoam::calcLduResiduals(), if(), MRFZoneListDF::makeRelative(), MRFZoneDF::makeRelative(), DASimpleFoam::runFPAdj(), DAPimpleDyMFoam::solvePrimal(), DAScalarTransportFoam::solvePrimal(), and while().
laminarTransport
singlePhaseTransportModel& laminarTransport = laminarTransportPtr_()
Definition at line 9 of file createRefsPimple.H.
Referenced by DAPimpleDyMFoam::solvePrimal(), DAPimpleFoam::solvePrimal(), DAPisoFoam::solvePrimal(), DASimpleTFoam::solvePrimal(), and DASimpleFoam::solvePrimal().
cumulativeContErr
scalar& cumulativeContErr = cumulativeContErr_
Definition at line 10 of file createRefsPimple.H.
pRefCell
label& pRefCell = pRefCell_
Definition at line 11 of file createRefsPimple.H.
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), and while().
pRefValue
scalar& pRefValue = pRefValue_
Definition at line 12 of file createRefsPimple.H.
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), and while().
fvSource
volVectorField& fvSource = fvSourcePtr_()
Definition at line 13 of file createRefsPimple.H.