DAFoam: dafoam/src/adjoint/DASolver/DALaplacianFoam/createRefsLaplacian.H File Reference
createRefsLaplacian.H File Reference
Functions
runTime setTime (0.0, 0)
Variables
Time & runTime = runTimePtr_()
fvMesh & mesh = meshPtr_()
volScalarField & T = TPtr_()
dimensionedScalar & DT = DTPtr_()
Function Documentation
setTime()
runTime setTime (0. 0, 0)
Variable Documentation
runTime
Time& runTime = runTimePtr_()
Definition at line 1 of file createRefsLaplacian.H.
Referenced by DATurbulenceModel::getPrt(), DALaplacianFoam::initSolver(), DAScalarTransportFoam::initSolver(), DARhoSimpleCFoam::initSolver(), DASolidDisplacementFoam::initSolver(), DATurboFoam::initSolver(), DAPimpleFoam::initSolver(), DAPisoFoam::initSolver(), DASimpleTFoam::initSolver(), DASimpleFoam::initSolver(), DARhoSimpleFoam::initSolver(), DASolver::loop(), main(), DALaplacianFoam::solvePrimal(), DAScalarTransportFoam::solvePrimal(), DARhoSimpleCFoam::solvePrimal(), DASolidDisplacementFoam::solvePrimal(), DATurboFoam::solvePrimal(), DAPimpleFoam::solvePrimal(), DAPisoFoam::solvePrimal(), DASimpleTFoam::solvePrimal(), DASimpleFoam::solvePrimal(), DARhoSimpleFoam::solvePrimal(), and DASolver::~DASolver().
mesh
fvMesh& mesh = meshPtr_()
Definition at line 4 of file createRefsLaplacian.H.
Referenced by DAIndex::DAIndex(), DAkEpsilon::DAkEpsilon(), DAkOmega::DAkOmega(), DAkOmegaSST::DAkOmegaSST(), DAkOmegaSSTLM::DAkOmegaSSTLM(), DAObjFuncWallHeatFlux::DAObjFuncWallHeatFlux(), DAResidualSimpleTFoam::DAResidualSimpleTFoam(), DAResidualSolidDisplacementFoam::DAResidualSolidDisplacementFoam(), DASpalartAllmaras::DASpalartAllmaras(), DASpalartAllmarasFv3::DASpalartAllmarasFv3(), DASpalartAllmarasFv3Beta::DASpalartAllmarasFv3Beta(), DATurbulenceModel::DATurbulenceModel(), if(), DALaplacianFoam::initSolver(), DAScalarTransportFoam::initSolver(), DARhoSimpleCFoam::initSolver(), DASolidDisplacementFoam::initSolver(), DATurboFoam::initSolver(), DAPimpleFoam::initSolver(), DAPisoFoam::initSolver(), DASimpleTFoam::initSolver(), DASimpleFoam::initSolver(), DARhoSimpleFoam::initSolver(), main(), Foam::mergeAndWrite(), DARadiationModel::New(), DAStateInfo::New(), DAResidual::New(), DAFvSource::New(), DAObjFunc::New(), DAPartDeriv::New(), DATurbulenceModel::New(), DAJacCon::New(), DAField::pointVec2OFMesh(), ColoringSolid::run(), ColoringIncompressible::run(), ColoringCompressible::run(), DASolver::setDAObjFuncList(), DALaplacianFoam::solvePrimal(), DAScalarTransportFoam::solvePrimal(), DARhoSimpleCFoam::solvePrimal(), DASolidDisplacementFoam::solvePrimal(), DATurboFoam::solvePrimal(), DAPisoFoam::solvePrimal(), DAPimpleFoam::solvePrimal(), DASimpleTFoam::solvePrimal(), DASimpleFoam::solvePrimal(), DARhoSimpleFoam::solvePrimal(), and while().
T
volScalarField& T = TPtr_()
Definition at line 5 of file createRefsLaplacian.H.
Referenced by DAObjFuncWallHeatFlux::calcObjFunc(), DAObjFuncTotalPressureRatio::calcObjFunc(), DAObjFuncTotalTemperatureRatio::calcObjFunc(), DATurbulenceModel::divDevRhoReff(), DALaplacianFoam::solvePrimal(), and DAScalarTransportFoam::solvePrimal().
DT
dimensionedScalar& DT = DTPtr_()
Definition at line 6 of file createRefsLaplacian.H.
Referenced by DAResidualLaplacianFoam::calcResiduals(), DAResidualScalarTransportFoam::calcResiduals(), DAResidualLaplacianFoam::DAResidualLaplacianFoam(), DAResidualScalarTransportFoam::DAResidualScalarTransportFoam(), DALaplacianFoam::solvePrimal(), and DAScalarTransportFoam::solvePrimal().