DAFoam: dafoam/src/include/createAdjointCompressible.H File Reference
createAdjointCompressible.H File Reference
Functions
daOptionPtr_ reset (new DAOption(mesh, pyOptions_))
DARegDbFluidThermo regDbThermo (mesh, thermo)
DARegDbTurbulenceModelCompressible regDbTurbulence (mesh, turbulencePtr_())
daTurbulenceModelPtr_ reset (DATurbulenceModel::New(turbModelName, mesh, daOptionPtr_()))
daModelPtr_ reset (new DAModel(mesh, daOptionPtr_()))
daStateInfoPtr_ reset (DAStateInfo::New(solverName, mesh, daOptionPtr_(), daModelPtr_()))
daIndexPtr_ reset (new DAIndex(mesh, daOptionPtr_(), daModelPtr_()))
daIndexPtr_ printIndices ()
daFieldPtr_ reset (new DAField(mesh, daOptionPtr_(), daModelPtr_(), daIndexPtr_()))
daResidualPtr_ reset (DAResidual::New(solverName, mesh, daOptionPtr_(), daModelPtr_(), daIndexPtr_()))
Variables
word turbModelName = daOptionPtr_->getOption<word>("turbulenceModel")
word solverName = daOptionPtr_->getOption<word>("solverName")
stateInfo_ = daStateInfoPtr_->getStateInfo()
Function Documentation
daOptionPtr_ reset (new DAOptionmesh, pyOptions_)
DARegDbFluidThermo regDbThermo (mesh , thermo)
DARegDbTurbulenceModelCompressible regDbTurbulence (mesh , turbulencePtr_())
daTurbulenceModelPtr_ reset (DATurbulenceModel:: NewturbModelName, mesh, daOptionPtr_())
daModelPtr_ reset (new DAModelmesh, daOptionPtr_())
daStateInfoPtr_ reset (DAStateInfo:: NewsolverName, mesh, daOptionPtr_(), daModelPtr_())
daIndexPtr_ reset (new DAIndexmesh, daOptionPtr_(), daModelPtr_())
daIndexPtr_ printIndices ()
daFieldPtr_ reset (new DAFieldmesh, daOptionPtr_(), daModelPtr_(), daIndexPtr_())
daResidualPtr_ reset (DAResidual:: NewsolverName, mesh, daOptionPtr_(), daModelPtr_(), daIndexPtr_())
Variable Documentation
word turbModelName = daOptionPtr_->getOption<word>("turbulenceModel")
Definition at line 10 of file createAdjointCompressible.H.
word solverName = daOptionPtr_->getOption<word>("solverName")
Definition at line 15 of file createAdjointCompressible.H.
Referenced by DAField::DAField(), DAJacCon::DAJacCon(), DAPartDeriv::DAPartDeriv(), ColoringCompressible::run(), and ColoringIncompressible::run().
stateInfo_ = daStateInfoPtr_->getStateInfo()
Definition at line 17 of file createAdjointCompressible.H.