DAFoam: dafoam/src/adjoint/DASolver/DAPisoFoam/createRefsPiso.H File Reference
createRefsPiso.H File Reference
Functions
runTime setTime (0.0, 0)
this initializeObjFuncHistFilePtr ("objFuncHist")
this setDAObjFuncList ()
Variables
Time & runTime = runTimePtr_()
fvMesh & mesh = meshPtr_()
pisoControl & piso = pisoPtr_()
volScalarField & p = pPtr_()
volVectorField & U = UPtr_()
surfaceScalarField & phi = phiPtr_()
singlePhaseTransportModel & laminarTransport = laminarTransportPtr_()
scalar & cumulativeContErr = cumulativeContErr_
label & pRefCell = pRefCell_
scalar & pRefValue = pRefValue_
volVectorField & fvSource = fvSourcePtr_()
Function Documentation
setTime()
runTime setTime (0. 0, 0)
initializeObjFuncHistFilePtr()
this initializeObjFuncHistFilePtr ("objFuncHist")
setDAObjFuncList()
this setDAObjFuncList ()
Variable Documentation
runTime
Time& runTime = runTimePtr_()
Definition at line 1 of file createRefsPiso.H.
Referenced by DATurbulenceModel::getPrt(), DARhoSimpleCFoam::initSolver(), DASolidDisplacementFoam::initSolver(), DATurboFoam::initSolver(), DASimpleTFoam::initSolver(), DASimpleFoam::initSolver(), DARhoSimpleFoam::initSolver(), DAPisoFoam::initSolver(), DASolver::loop(), DARhoSimpleCFoam::solvePrimal(), DASolidDisplacementFoam::solvePrimal(), DATurboFoam::solvePrimal(), DASimpleTFoam::solvePrimal(), DASimpleFoam::solvePrimal(), DARhoSimpleFoam::solvePrimal(), DAPisoFoam::solvePrimal(), and DASolver::~DASolver().
mesh
fvMesh& mesh = meshPtr_()
Definition at line 4 of file createRefsPiso.H.
Referenced by DAIndex::DAIndex(), DAkEpsilon::DAkEpsilon(), DAkOmega::DAkOmega(), DAkOmegaSST::DAkOmegaSST(), DAkOmegaSSTLM::DAkOmegaSSTLM(), DAObjFuncWallHeatFlux::DAObjFuncWallHeatFlux(), DAResidualSimpleTFoam::DAResidualSimpleTFoam(), DAResidualSolidDisplacementFoam::DAResidualSolidDisplacementFoam(), DASpalartAllmaras::DASpalartAllmaras(), DASpalartAllmarasFv3::DASpalartAllmarasFv3(), DASpalartAllmarasFv3Beta::DASpalartAllmarasFv3Beta(), DATurbulenceModel::DATurbulenceModel(), if(), DARhoSimpleCFoam::initSolver(), DASolidDisplacementFoam::initSolver(), DATurboFoam::initSolver(), DASimpleTFoam::initSolver(), DASimpleFoam::initSolver(), DARhoSimpleFoam::initSolver(), DAPisoFoam::initSolver(), Foam::mergeAndWrite(), DARadiationModel::New(), DAStateInfo::New(), DAResidual::New(), DAFvSource::New(), DAObjFunc::New(), DAPartDeriv::New(), DATurbulenceModel::New(), DAJacCon::New(), DAField::pointVec2OFMesh(), ColoringSolid::run(), ColoringCompressible::run(), ColoringIncompressible::run(), DASolver::setDAObjFuncList(), DARhoSimpleCFoam::solvePrimal(), DASolidDisplacementFoam::solvePrimal(), DATurboFoam::solvePrimal(), DASimpleTFoam::solvePrimal(), DASimpleFoam::solvePrimal(), DARhoSimpleFoam::solvePrimal(), DAPisoFoam::solvePrimal(), and while().
piso
pisoControl& piso = pisoPtr_()
Definition at line 5 of file createRefsPiso.H.
Referenced by DAPisoFoam::solvePrimal(), and while().
p
volScalarField& p = pPtr_()
Definition at line 6 of file createRefsPiso.H.
Referenced by DAObjFuncMoment::calcObjFunc(), DAObjFuncTotalPressure::calcObjFunc(), DAObjFuncTotalPressureRatio::calcObjFunc(), DAObjFuncForce::calcObjFunc(), Foam::checkCoupledPoints(), if(), multiFreqScalarFvPatchField::multiFreqScalarFvPatchField(), multiFreqVectorFvPatchField::multiFreqVectorFvPatchField(), DARhoSimpleCFoam::solvePrimal(), DATurboFoam::solvePrimal(), DASimpleTFoam::solvePrimal(), DASimpleFoam::solvePrimal(), DARhoSimpleFoam::solvePrimal(), multiFreqScalarFvPatchField::updateCoeffs(), multiFreqVectorFvPatchField::updateCoeffs(), and while().
U
volVectorField& U = UPtr_()
Definition at line 7 of file createRefsPiso.H.
Referenced by DASolver::calcdFdAOAAD(), DASolver::calcdRdAOATPsiAD(), DAObjFuncTotalPressure::calcObjFunc(), DAObjFuncMassFlowRate::calcObjFunc(), DAObjFuncTotalPressureRatio::calcObjFunc(), DAObjFuncTotalTemperatureRatio::calcObjFunc(), DAField::checkSpecialBCs(), DAJacCon::checkSpecialBCs(), DAkOmegaSST::correctNut(), DAkOmegaSSTLM::correctNut(), if(), DASolver::setRotingWallVelocity(), DAField::specialBCTreatment(), DAObjFuncForce::updateForceDir(), DASolver::writeAssociatedFields(), and DATurbulenceModel::~DATurbulenceModel().
phi
surfaceScalarField& phi = phiPtr_()
Definition at line 8 of file createRefsPiso.H.
Referenced by if(), and while().
laminarTransport
singlePhaseTransportModel& laminarTransport = laminarTransportPtr_()
Definition at line 9 of file createRefsPiso.H.
Referenced by DASimpleTFoam::solvePrimal(), DASimpleFoam::solvePrimal(), and DAPisoFoam::solvePrimal().
cumulativeContErr
scalar& cumulativeContErr = cumulativeContErr_
Definition at line 10 of file createRefsPiso.H.
pRefCell
label& pRefCell = pRefCell_
Definition at line 11 of file createRefsPiso.H.
Referenced by DAResidualPisoFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), and while().
pRefValue
scalar& pRefValue = pRefValue_
Definition at line 12 of file createRefsPiso.H.
Referenced by DAResidualPisoFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), and while().
fvSource
volVectorField& fvSource = fvSourcePtr_()
Definition at line 13 of file createRefsPiso.H.
Referenced by DASolver::calcdFdACTAD(), DASolver::calcdRdActTPsiAD(), DAPartDerivdFdACTD::calcPartDerivMat(), DAPartDerivdRdACTD::calcPartDerivMat(), if(), DAPisoFoam::initSolver(), DASolver::syncDAOptionToActuatorDVs(), DAFvSource::~DAFvSource(), DAFvSourceActuatorDisk::~DAFvSourceActuatorDisk(), DAFvSourceActuatorLine::~DAFvSourceActuatorLine(), DAFvSourceActuatorPoint::~DAFvSourceActuatorPoint(), and DAFvSourceUniformPressureGradient::~DAFvSourceUniformPressureGradient().