DAFoam: dafoam/src/adjoint/DASolver/DARhoSimpleCFoam/EEqnRhoSimpleC.H File Reference
EEqnRhoSimpleC.H File Reference
Functions
fvScalarMatrix EEqn (fvm::div(phi, he)+(he.name()=="e" ? fvc::div(phi, volScalarField("Ekp", 0.5 *magSqr(U)+p/rho)) :fvc::div(phi, volScalarField("K", 0.5 *magSqr(U)))) - fvm::laplacian(turbulencePtr_->alphaEff(), he))
EEqn relax ()
this primalResidualControl< scalar > (solverE, printToScreen, printInterval, "he")
thermo correct ()
Variables
SolverPerformance< scalar > solverE = EEqn.solve()
Function Documentation
EEqn()
fvScalarMatrix EEqn (fvm::div(phi, he)+(he.name()=="e" ? fvc::div(phi, volScalarField("Ekp", 0.5 *magSqr(U)+p/rho)) :fvc::div(phi, volScalarField("K", 0.5 *magSqr(U)))) - fvm::laplacian(turbulencePtr_->alphaEff(), he))
Referenced by DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), and DAResidualRhoSimpleFoam::calcResiduals().
relax()
EEqn relax ()
primalResidualControl< scalar >()
this primalResidualControl< scalar > (solverE , printToScreen , printInterval , "he")
Referenced by if(), DAHeatTransferFoam::solvePrimal(), DALaplacianFoam::solvePrimal(), DAScalarTransportFoam::solvePrimal(), and while().
correct()
thermo correct ()
Variable Documentation
solverE
SolverPerformance<scalar> solverE = EEqn.solve()
Definition at line 15 of file EEqnRhoSimpleC.H.