DAFoam: Foam Namespace Reference
Foam Namespace Reference
Namespaces
patchDistMethods
RASModels
Classes
class ColoringCompressible
class ColoringIncompressible
class ColoringSolid
class DACheckMesh
class DAColoring
class DADummyTurbulenceModel
class DAField
class DAFvSource
class DAFvSourceActuatorDisk
class DAFvSourceActuatorLine
class DAFvSourceActuatorPoint
class DAFvSourceUniformPressureGradient
class DAIndex
class DAJacCon
class DAJacCondFdW
class DAJacCondRdW
class DAJacConDummy
class DAkEpsilon
class DAkOmega
class DAkOmegaFieldInversion
class DAkOmegaFieldInversionk
class DAkOmegaFieldInversionOmega
class DAkOmegaSST
class DAkOmegaSSTFieldInversion
class DAkOmegaSSTLM
class DALaplacianFoam
class DALinearEqn
class DAModel
class DAMotion
class DAMotionDummy
class DAMotionTranslation
class DAMotionTranslationCoupled
class DAObjFunc
class DAObjFuncCenterOfPressure
class DAObjFuncFieldInversion
class DAObjFuncForce
class DAObjFuncMass
class DAObjFuncMassFlowRate
class DAObjFuncMeshQualityKS
class DAObjFuncMoment
class DAObjFuncTotalPressure
class DAObjFuncTotalPressureRatio
class DAObjFuncTotalTemperatureRatio
class DAObjFuncVariableVolSum
class DAObjFuncVonMisesStressKS
class DAObjFuncWallHeatFlux
class DAOption
class DAP1
class DAPartDeriv
class DAPartDerivdFdACTD
class DAPartDerivdFdAOA
class DAPartDerivdFdBC
class DAPartDerivdFdFFD
class DAPartDerivdFdW
class DAPartDerivdRdACTD
class DAPartDerivdRdACTL
class DAPartDerivdRdACTP
class DAPartDerivdRdAOA
class DAPartDerivdRdBC
class DAPartDerivdRdFFD
class DAPartDerivdRdW
class DAPimpleDyMFoam
class DAPimpleFoam
class DAPisoFoam
class DARadiationModel
class DARegDbFluidThermo
class DARegDbNearWallDist
class DARegDbSinglePhaseTransportModel
class DARegDbTurbulenceModelCompressible
class DARegDbTurbulenceModelIncompressible
class DAResidual
class DAResidualDummy
class DAResidualLaplacianFoam
class DAResidualPimpleFoam
class DAResidualPisoFoam
class DAResidualRhoSimpleCFoam
class DAResidualRhoSimpleFoam
class DAResidualScalarTransportFoam
class DAResidualSimpleFoam
class DAResidualSimpleTFoam
class DAResidualSolidDisplacementFoam
class DAResidualTurboFoam
class DARhoSimpleCFoam
class DARhoSimpleFoam
class DAScalarTransportFoam
class DASimpleFoam
class DASimpleTFoam
class DASolidDisplacementFoam
class DASolver
class DASolvers
class DASpalartAllmaras
class DASpalartAllmarasFv3
class DASpalartAllmarasFv3FieldInversion
class DAStateInfo
class DAStateInfoLaplacianFoam
class DAStateInfoPimpleFoam
class DAStateInfoPisoFoam
class DAStateInfoRhoSimpleCFoam
class DAStateInfoRhoSimpleFoam
class DAStateInfoScalarTransportFoam
class DAStateInfoSimpleFoam
class DAStateInfoSimpleTFoam
class DAStateInfoSolidDisplacementFoam
class DAStateInfoTurboFoam
class DATurboFoam
class DATurbulenceModel
class DAUtility
class IOMRFZoneListDF
class MRFZoneDF
class MRFZoneListDF
class multiFreqScalarFvPatchField
class multiFreqVectorFvPatchField
class nutUSpaldingWallFunctionFvPatchScalarFieldDF
class pimpleControlDF
class tractionDisplacementFvPatchVectorField
class transformPositionList
Typedefs
typedef ThermalDiffusivity< CompressibleTurbulenceModel< fluidThermo > > fluidThermoCompressibleTurbulenceModel
typedef RASModel< EddyDiffusivity< fluidThermoCompressibleTurbulenceModel > > RASfluidThermoCompressibleTurbulenceModel
typedef IncompressibleTurbulenceModel< transportModel > transportModelIncompressibleTurbulenceModel
typedef RASModel< transportModelIncompressibleTurbulenceModel > RAStransportModelIncompressibleTurbulenceModel
typedef LESModel< transportModelIncompressibleTurbulenceModel > LEStransportModelIncompressibleTurbulenceModel
typedef LESModel< EddyDiffusivity< fluidThermoCompressibleTurbulenceModel > > LESfluidThermoCompressibleTurbulenceModel
Functions
makePatchTypeField (fvPatchScalarField, multiFreqScalarFvPatchField)
makePatchTypeField (fvPatchVectorField, multiFreqVectorFvPatchField)
makePatchTypeField (fvPatchScalarField, nutUSpaldingWallFunctionFvPatchScalarFieldDF)
makePatchTypeField (fvPatchVectorField, tractionDisplacementFvPatchVectorField)
label findOppositeWedge (const polyMesh &, const wedgePolyPatch &)
bool checkWedges (const polyMesh &, const bool report, const Vector< label > &, labelHashSet *)
Check wedge orientation.
bool checkCoupledPoints (const polyMesh &, const bool report, labelHashSet *)
Check 0th vertex on coupled faces.
label checkGeometry (const polyMesh &mesh, const autoPtr< surfaceWriter > &surfWriter, const autoPtr< writer< scalar >> &setWriter, const label maxIncorrectlyOrientedFaces)
check mesh quality
void mergeAndWrite (const polyMesh &mesh, const surfaceWriter &writer, const word &name, const indirectPrimitivePatch &setPatch, const fileName &outputDir)
void mergeAndWrite (const surfaceWriter &, const faceSet &)
void mergeAndWrite (const surfaceWriter &, const cellSet &)
void mergeAndWrite (const writer< scalar > &, const pointSet &)
defineTypeNameAndDebug (DAFvSource, 0)
defineRunTimeSelectionTable (DAFvSource, dictionary)
defineTypeNameAndDebug (DAFvSourceActuatorDisk, 0)
addToRunTimeSelectionTable (DAFvSource, DAFvSourceActuatorDisk, dictionary)
defineTypeNameAndDebug (DAFvSourceActuatorLine, 0)
addToRunTimeSelectionTable (DAFvSource, DAFvSourceActuatorLine, dictionary)
defineTypeNameAndDebug (DAFvSourceActuatorPoint, 0)
addToRunTimeSelectionTable (DAFvSource, DAFvSourceActuatorPoint, dictionary)
defineTypeNameAndDebug (DAFvSourceUniformPressureGradient, 0)
addToRunTimeSelectionTable (DAFvSource, DAFvSourceUniformPressureGradient, dictionary)
defineTypeNameAndDebug (DAJacCon, 0)
defineRunTimeSelectionTable (DAJacCon, dictionary)
defineTypeNameAndDebug (DAJacCondFdW, 0)
addToRunTimeSelectionTable (DAJacCon, DAJacCondFdW, dictionary)
defineTypeNameAndDebug (DAJacCondRdW, 0)
addToRunTimeSelectionTable (DAJacCon, DAJacCondRdW, dictionary)
defineTypeNameAndDebug (DAJacConDummy, 0)
addToRunTimeSelectionTable (DAJacCon, DAJacConDummy, dictionary)
defineTypeNameAndDebug (DAP1, 0)
addToRunTimeSelectionTable (DARadiationModel, DAP1, dictionary)
defineTypeNameAndDebug (DARadiationModel, 0)
defineRunTimeSelectionTable (DARadiationModel, dictionary)
defineTypeNameAndDebug (DADummyTurbulenceModel, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DADummyTurbulenceModel, dictionary)
defineTypeNameAndDebug (DAkEpsilon, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DAkEpsilon, dictionary)
defineTypeNameAndDebug (DAkOmega, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DAkOmega, dictionary)
defineTypeNameAndDebug (DAkOmegaFieldInversion, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DAkOmegaFieldInversion, dictionary)
defineTypeNameAndDebug (DAkOmegaFieldInversionk, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DAkOmegaFieldInversionk, dictionary)
defineTypeNameAndDebug (DAkOmegaFieldInversionOmega, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DAkOmegaFieldInversionOmega, dictionary)
defineTypeNameAndDebug (DAkOmegaSST, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DAkOmegaSST, dictionary)
defineTypeNameAndDebug (DAkOmegaSSTFieldInversion, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DAkOmegaSSTFieldInversion, dictionary)
defineTypeNameAndDebug (DAkOmegaSSTLM, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DAkOmegaSSTLM, dictionary)
defineTypeNameAndDebug (DASpalartAllmaras, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DASpalartAllmaras, dictionary)
defineTypeNameAndDebug (DASpalartAllmarasFv3, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DASpalartAllmarasFv3, dictionary)
defineTypeNameAndDebug (DASpalartAllmarasFv3FieldInversion, 0)
addToRunTimeSelectionTable (DATurbulenceModel, DASpalartAllmarasFv3FieldInversion, dictionary)
defineTypeNameAndDebug (DATurbulenceModel, 0)
defineRunTimeSelectionTable (DATurbulenceModel, dictionary)
defineTypeNameAndDebug (DAMotion, 0)
defineRunTimeSelectionTable (DAMotion, dictionary)
defineTypeNameAndDebug (DAMotionDummy, 0)
addToRunTimeSelectionTable (DAMotion, DAMotionDummy, dictionary)
defineTypeNameAndDebug (DAMotionTranslation, 0)
addToRunTimeSelectionTable (DAMotion, DAMotionTranslation, dictionary)
defineTypeNameAndDebug (DAMotionTranslationCoupled, 0)
addToRunTimeSelectionTable (DAMotion, DAMotionTranslationCoupled, dictionary)
defineTypeNameAndDebug (DAObjFunc, 0)
defineRunTimeSelectionTable (DAObjFunc, dictionary)
defineTypeNameAndDebug (DAObjFuncCenterOfPressure, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncCenterOfPressure, dictionary)
defineTypeNameAndDebug (DAObjFuncFieldInversion, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncFieldInversion, dictionary)
defineTypeNameAndDebug (DAObjFuncForce, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncForce, dictionary)
defineTypeNameAndDebug (DAObjFuncMass, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncMass, dictionary)
defineTypeNameAndDebug (DAObjFuncMassFlowRate, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncMassFlowRate, dictionary)
defineTypeNameAndDebug (DAObjFuncMeshQualityKS, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncMeshQualityKS, dictionary)
defineTypeNameAndDebug (DAObjFuncMoment, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncMoment, dictionary)
defineTypeNameAndDebug (DAObjFuncTotalPressure, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncTotalPressure, dictionary)
defineTypeNameAndDebug (DAObjFuncTotalPressureRatio, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncTotalPressureRatio, dictionary)
defineTypeNameAndDebug (DAObjFuncTotalTemperatureRatio, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncTotalTemperatureRatio, dictionary)
defineTypeNameAndDebug (DAObjFuncVariableVolSum, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncVariableVolSum, dictionary)
defineTypeNameAndDebug (DAObjFuncVonMisesStressKS, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncVonMisesStressKS, dictionary)
defineTypeNameAndDebug (DAObjFuncWallHeatFlux, 0)
addToRunTimeSelectionTable (DAObjFunc, DAObjFuncWallHeatFlux, dictionary)
defineTypeNameAndDebug (DAPartDeriv, 0)
defineRunTimeSelectionTable (DAPartDeriv, dictionary)
defineTypeNameAndDebug (DAPartDerivdFdACTD, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdFdACTD, dictionary)
defineTypeNameAndDebug (DAPartDerivdFdAOA, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdFdAOA, dictionary)
defineTypeNameAndDebug (DAPartDerivdFdBC, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdFdBC, dictionary)
defineTypeNameAndDebug (DAPartDerivdFdFFD, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdFdFFD, dictionary)
defineTypeNameAndDebug (DAPartDerivdFdW, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdFdW, dictionary)
defineTypeNameAndDebug (DAPartDerivdRdACTD, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdRdACTD, dictionary)
defineTypeNameAndDebug (DAPartDerivdRdACTL, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdRdACTL, dictionary)
defineTypeNameAndDebug (DAPartDerivdRdACTP, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdRdACTP, dictionary)
defineTypeNameAndDebug (DAPartDerivdRdAOA, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdRdAOA, dictionary)
defineTypeNameAndDebug (DAPartDerivdRdBC, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdRdBC, dictionary)
defineTypeNameAndDebug (DAPartDerivdRdFFD, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdRdFFD, dictionary)
defineTypeNameAndDebug (DAPartDerivdRdW, 0)
addToRunTimeSelectionTable (DAPartDeriv, DAPartDerivdRdW, dictionary)
defineTypeNameAndDebug (DAResidual, 0)
defineRunTimeSelectionTable (DAResidual, dictionary)
defineTypeNameAndDebug (DAResidualDummy, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualDummy, dictionary)
defineTypeNameAndDebug (DAResidualLaplacianFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualLaplacianFoam, dictionary)
defineTypeNameAndDebug (DAResidualPimpleFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualPimpleFoam, dictionary)
defineTypeNameAndDebug (DAResidualPisoFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualPisoFoam, dictionary)
defineTypeNameAndDebug (DAResidualRhoSimpleCFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualRhoSimpleCFoam, dictionary)
defineTypeNameAndDebug (DAResidualRhoSimpleFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualRhoSimpleFoam, dictionary)
defineTypeNameAndDebug (DAResidualScalarTransportFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualScalarTransportFoam, dictionary)
defineTypeNameAndDebug (DAResidualSimpleFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualSimpleFoam, dictionary)
defineTypeNameAndDebug (DAResidualSimpleTFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualSimpleTFoam, dictionary)
defineTypeNameAndDebug (DAResidualSolidDisplacementFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualSolidDisplacementFoam, dictionary)
defineTypeNameAndDebug (DAResidualTurboFoam, 0)
addToRunTimeSelectionTable (DAResidual, DAResidualTurboFoam, dictionary)
defineTypeNameAndDebug (DALaplacianFoam, 0)
addToRunTimeSelectionTable (DASolver, DALaplacianFoam, dictionary)
defineTypeNameAndDebug (DAPimpleDyMFoam, 0)
addToRunTimeSelectionTable (DASolver, DAPimpleDyMFoam, dictionary)
defineTypeNameAndDebug (DAPimpleFoam, 0)
addToRunTimeSelectionTable (DASolver, DAPimpleFoam, dictionary)
defineTypeNameAndDebug (DAPisoFoam, 0)
addToRunTimeSelectionTable (DASolver, DAPisoFoam, dictionary)
defineTypeNameAndDebug (DARhoSimpleCFoam, 0)
addToRunTimeSelectionTable (DASolver, DARhoSimpleCFoam, dictionary)
defineTypeNameAndDebug (DARhoSimpleFoam, 0)
addToRunTimeSelectionTable (DASolver, DARhoSimpleFoam, dictionary)
defineTypeNameAndDebug (DAScalarTransportFoam, 0)
addToRunTimeSelectionTable (DASolver, DAScalarTransportFoam, dictionary)
defineTypeNameAndDebug (DASimpleFoam, 0)
addToRunTimeSelectionTable (DASolver, DASimpleFoam, dictionary)
defineTypeNameAndDebug (DASimpleTFoam, 0)
addToRunTimeSelectionTable (DASolver, DASimpleTFoam, dictionary)
defineTypeNameAndDebug (DASolidDisplacementFoam, 0)
addToRunTimeSelectionTable (DASolver, DASolidDisplacementFoam, dictionary)
defineTypeNameAndDebug (DASolver, 0)
defineRunTimeSelectionTable (DASolver, dictionary)
defineTypeNameAndDebug (DATurboFoam, 0)
addToRunTimeSelectionTable (DASolver, DATurboFoam, dictionary)
defineTypeNameAndDebug (DAStateInfo, 0)
defineRunTimeSelectionTable (DAStateInfo, dictionary)
defineTypeNameAndDebug (DAStateInfoLaplacianFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoLaplacianFoam, dictionary)
defineTypeNameAndDebug (DAStateInfoPimpleFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoPimpleFoam, dictionary)
defineTypeNameAndDebug (DAStateInfoPisoFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoPisoFoam, dictionary)
defineTypeNameAndDebug (DAStateInfoRhoSimpleCFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoRhoSimpleCFoam, dictionary)
defineTypeNameAndDebug (DAStateInfoRhoSimpleFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoRhoSimpleFoam, dictionary)
defineTypeNameAndDebug (DAStateInfoScalarTransportFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoScalarTransportFoam, dictionary)
defineTypeNameAndDebug (DAStateInfoSimpleFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoSimpleFoam, dictionary)
defineTypeNameAndDebug (DAStateInfoSimpleTFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoSimpleTFoam, dictionary)
defineTypeNameAndDebug (DAStateInfoSolidDisplacementFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoSolidDisplacementFoam, dictionary)
defineTypeNameAndDebug (DAStateInfoTurboFoam, 0)
addToRunTimeSelectionTable (DAStateInfo, DAStateInfoTurboFoam, dictionary)
defineTypeNameAndDebug (MRFZoneDF, 0)
Ostream & operator<< (Ostream &os, const MRFZoneListDF &models)
defineTypeNameAndDebug (pimpleControlDF, 0)
Typedef Documentation
fluidThermoCompressibleTurbulenceModel
typedef ThermalDiffusivity< CompressibleTurbulenceModel< fluidThermo > > fluidThermoCompressibleTurbulenceModel
Definition at line 37 of file makeDummyTurbulenceModelCompressible.C.
RASfluidThermoCompressibleTurbulenceModel
typedef RASModel< EddyDiffusivity< fluidThermoCompressibleTurbulenceModel > > RASfluidThermoCompressibleTurbulenceModel
Definition at line 37 of file makeDummyTurbulenceModelCompressible.C.
transportModelIncompressibleTurbulenceModel
typedef IncompressibleTurbulenceModel< transportModel > transportModelIncompressibleTurbulenceModel
Definition at line 29 of file makeDummyTurbulenceModelIncompressible.C.
RAStransportModelIncompressibleTurbulenceModel
typedef RASModel< transportModelIncompressibleTurbulenceModel > RAStransportModelIncompressibleTurbulenceModel
Definition at line 29 of file makeDummyTurbulenceModelIncompressible.C.
LEStransportModelIncompressibleTurbulenceModel
typedef LESModel< transportModelIncompressibleTurbulenceModel > LEStransportModelIncompressibleTurbulenceModel
Definition at line 29 of file makeDummyTurbulenceModelIncompressible.C.
LESfluidThermoCompressibleTurbulenceModel
typedef LESModel< EddyDiffusivity< fluidThermoCompressibleTurbulenceModel > > LESfluidThermoCompressibleTurbulenceModel
Definition at line 62 of file makekOmegaFieldInversionCompressible.C.
Function Documentation
makePatchTypeField() [1/4]
Foam::makePatchTypeField (fvPatchScalarField , multiFreqScalarFvPatchField)
makePatchTypeField() [2/4]
Foam::makePatchTypeField (fvPatchVectorField , multiFreqVectorFvPatchField)
makePatchTypeField() [3/4]
Foam::makePatchTypeField (fvPatchScalarField , nutUSpaldingWallFunctionFvPatchScalarFieldDF)
makePatchTypeField() [4/4]
Foam::makePatchTypeField (fvPatchVectorField , tractionDisplacementFvPatchVectorField)
findOppositeWedge()
label Foam::findOppositeWedge (const polyMesh & , const wedgePolyPatch &)
checkWedges()
bool Foam::checkWedges (const polyMesh & , const bool report, const Vector< label > & , labelHashSet *)
Check wedge orientation.
checkCoupledPoints()
bool checkCoupledPoints (const polyMesh & mesh, const bool report, labelHashSet * setPtr)
Check 0th vertex on coupled faces.
Definition at line 96 of file checkGeometry.C.
References mesh, p, and p0().
Referenced by checkGeometry().
checkGeometry()
Foam::label checkGeometry (const polyMesh & mesh, const autoPtr< surfaceWriter > & surfWriter, const autoPtr< writer< scalar >> & setWriter, const label maxIncorrectlyOrientedFaces)
check mesh quality
Definition at line 233 of file checkGeometry.C.
References checkCoupledPoints(), mergeAndWrite(), and mesh.
Referenced by DACheckMesh::run().
mergeAndWrite() [1/4]
void mergeAndWrite (const polyMesh & mesh, const surfaceWriter & writer, const word & name, const indirectPrimitivePatch & setPatch, const fileName & outputDir)
Definition at line 52 of file checkTools.C.
References mesh.
Referenced by checkGeometry(), and mergeAndWrite().
mergeAndWrite() [2/4]
void mergeAndWrite (const surfaceWriter & writer, const faceSet & set)
Definition at line 103 of file checkTools.C.
References mergeAndWrite(), and mesh.
mergeAndWrite() [3/4]
void mergeAndWrite (const surfaceWriter & writer, const cellSet & set)
Definition at line 123 of file checkTools.C.
References mergeAndWrite(), and mesh.
mergeAndWrite() [4/4]
void Foam::mergeAndWrite (const writer< scalar > & , const pointSet &)
defineTypeNameAndDebug() [1/92]
Foam::defineTypeNameAndDebug (DAFvSource , 0)
defineRunTimeSelectionTable() [1/10]
Foam::defineRunTimeSelectionTable (DAFvSource , dictionary)
defineTypeNameAndDebug() [2/92]
Foam::defineTypeNameAndDebug (DAFvSourceActuatorDisk , 0)
addToRunTimeSelectionTable() [1/80]
Foam::addToRunTimeSelectionTable (DAFvSource , DAFvSourceActuatorDisk , dictionary)
defineTypeNameAndDebug() [3/92]
Foam::defineTypeNameAndDebug (DAFvSourceActuatorLine , 0)
addToRunTimeSelectionTable() [2/80]
Foam::addToRunTimeSelectionTable (DAFvSource , DAFvSourceActuatorLine , dictionary)
defineTypeNameAndDebug() [4/92]
Foam::defineTypeNameAndDebug (DAFvSourceActuatorPoint , 0)
addToRunTimeSelectionTable() [3/80]
Foam::addToRunTimeSelectionTable (DAFvSource , DAFvSourceActuatorPoint , dictionary)
defineTypeNameAndDebug() [5/92]
Foam::defineTypeNameAndDebug (DAFvSourceUniformPressureGradient , 0)
addToRunTimeSelectionTable() [4/80]
Foam::addToRunTimeSelectionTable (DAFvSource , DAFvSourceUniformPressureGradient , dictionary)
defineTypeNameAndDebug() [6/92]
Foam::defineTypeNameAndDebug (DAJacCon , 0)
defineRunTimeSelectionTable() [2/10]
Foam::defineRunTimeSelectionTable (DAJacCon , dictionary)
defineTypeNameAndDebug() [7/92]
Foam::defineTypeNameAndDebug (DAJacCondFdW , 0)
addToRunTimeSelectionTable() [5/80]
Foam::addToRunTimeSelectionTable (DAJacCon , DAJacCondFdW , dictionary)
defineTypeNameAndDebug() [8/92]
Foam::defineTypeNameAndDebug (DAJacCondRdW , 0)
addToRunTimeSelectionTable() [6/80]
Foam::addToRunTimeSelectionTable (DAJacCon , DAJacCondRdW , dictionary)
defineTypeNameAndDebug() [9/92]
Foam::defineTypeNameAndDebug (DAJacConDummy , 0)
addToRunTimeSelectionTable() [7/80]
Foam::addToRunTimeSelectionTable (DAJacCon , DAJacConDummy , dictionary)
defineTypeNameAndDebug() [10/92]
Foam::defineTypeNameAndDebug (DAP1 , 0)
addToRunTimeSelectionTable() [8/80]
Foam::addToRunTimeSelectionTable (DARadiationModel , DAP1 , dictionary)
defineTypeNameAndDebug() [11/92]
Foam::defineTypeNameAndDebug (DARadiationModel , 0)
defineRunTimeSelectionTable() [3/10]
Foam::defineRunTimeSelectionTable (DARadiationModel , dictionary)
defineTypeNameAndDebug() [12/92]
Foam::defineTypeNameAndDebug (DADummyTurbulenceModel , 0)
addToRunTimeSelectionTable() [9/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DADummyTurbulenceModel , dictionary)
defineTypeNameAndDebug() [13/92]
Foam::defineTypeNameAndDebug (DAkEpsilon , 0)
addToRunTimeSelectionTable() [10/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DAkEpsilon , dictionary)
defineTypeNameAndDebug() [14/92]
Foam::defineTypeNameAndDebug (DAkOmega , 0)
addToRunTimeSelectionTable() [11/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DAkOmega , dictionary)
defineTypeNameAndDebug() [15/92]
Foam::defineTypeNameAndDebug (DAkOmegaFieldInversion , 0)
addToRunTimeSelectionTable() [12/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DAkOmegaFieldInversion , dictionary)
defineTypeNameAndDebug() [16/92]
Foam::defineTypeNameAndDebug (DAkOmegaFieldInversionk , 0)
addToRunTimeSelectionTable() [13/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DAkOmegaFieldInversionk , dictionary)
defineTypeNameAndDebug() [17/92]
Foam::defineTypeNameAndDebug (DAkOmegaFieldInversionOmega , 0)
addToRunTimeSelectionTable() [14/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DAkOmegaFieldInversionOmega , dictionary)
defineTypeNameAndDebug() [18/92]
Foam::defineTypeNameAndDebug (DAkOmegaSST , 0)
addToRunTimeSelectionTable() [15/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DAkOmegaSST , dictionary)
defineTypeNameAndDebug() [19/92]
Foam::defineTypeNameAndDebug (DAkOmegaSSTFieldInversion , 0)
addToRunTimeSelectionTable() [16/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DAkOmegaSSTFieldInversion , dictionary)
defineTypeNameAndDebug() [20/92]
Foam::defineTypeNameAndDebug (DAkOmegaSSTLM , 0)
addToRunTimeSelectionTable() [17/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DAkOmegaSSTLM , dictionary)
defineTypeNameAndDebug() [21/92]
Foam::defineTypeNameAndDebug (DASpalartAllmaras , 0)
addToRunTimeSelectionTable() [18/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DASpalartAllmaras , dictionary)
defineTypeNameAndDebug() [22/92]
Foam::defineTypeNameAndDebug (DASpalartAllmarasFv3 , 0)
addToRunTimeSelectionTable() [19/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DASpalartAllmarasFv3 , dictionary)
defineTypeNameAndDebug() [23/92]
Foam::defineTypeNameAndDebug (DASpalartAllmarasFv3FieldInversion , 0)
addToRunTimeSelectionTable() [20/80]
Foam::addToRunTimeSelectionTable (DATurbulenceModel , DASpalartAllmarasFv3FieldInversion , dictionary)
defineTypeNameAndDebug() [24/92]
Foam::defineTypeNameAndDebug (DATurbulenceModel , 0)
defineRunTimeSelectionTable() [4/10]
Foam::defineRunTimeSelectionTable (DATurbulenceModel , dictionary)
defineTypeNameAndDebug() [25/92]
Foam::defineTypeNameAndDebug (DAMotion , 0)
defineRunTimeSelectionTable() [5/10]
Foam::defineRunTimeSelectionTable (DAMotion , dictionary)
defineTypeNameAndDebug() [26/92]
Foam::defineTypeNameAndDebug (DAMotionDummy , 0)
addToRunTimeSelectionTable() [21/80]
Foam::addToRunTimeSelectionTable (DAMotion , DAMotionDummy , dictionary)
defineTypeNameAndDebug() [27/92]
Foam::defineTypeNameAndDebug (DAMotionTranslation , 0)
addToRunTimeSelectionTable() [22/80]
Foam::addToRunTimeSelectionTable (DAMotion , DAMotionTranslation , dictionary)
defineTypeNameAndDebug() [28/92]
Foam::defineTypeNameAndDebug (DAMotionTranslationCoupled , 0)
addToRunTimeSelectionTable() [23/80]
Foam::addToRunTimeSelectionTable (DAMotion , DAMotionTranslationCoupled , dictionary)
defineTypeNameAndDebug() [29/92]
Foam::defineTypeNameAndDebug (DAObjFunc , 0)
defineRunTimeSelectionTable() [6/10]
Foam::defineRunTimeSelectionTable (DAObjFunc , dictionary)
defineTypeNameAndDebug() [30/92]
Foam::defineTypeNameAndDebug (DAObjFuncCenterOfPressure , 0)
addToRunTimeSelectionTable() [24/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncCenterOfPressure , dictionary)
defineTypeNameAndDebug() [31/92]
Foam::defineTypeNameAndDebug (DAObjFuncFieldInversion , 0)
addToRunTimeSelectionTable() [25/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncFieldInversion , dictionary)
defineTypeNameAndDebug() [32/92]
Foam::defineTypeNameAndDebug (DAObjFuncForce , 0)
addToRunTimeSelectionTable() [26/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncForce , dictionary)
defineTypeNameAndDebug() [33/92]
Foam::defineTypeNameAndDebug (DAObjFuncMass , 0)
addToRunTimeSelectionTable() [27/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncMass , dictionary)
defineTypeNameAndDebug() [34/92]
Foam::defineTypeNameAndDebug (DAObjFuncMassFlowRate , 0)
addToRunTimeSelectionTable() [28/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncMassFlowRate , dictionary)
defineTypeNameAndDebug() [35/92]
Foam::defineTypeNameAndDebug (DAObjFuncMeshQualityKS , 0)
addToRunTimeSelectionTable() [29/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncMeshQualityKS , dictionary)
defineTypeNameAndDebug() [36/92]
Foam::defineTypeNameAndDebug (DAObjFuncMoment , 0)
addToRunTimeSelectionTable() [30/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncMoment , dictionary)
defineTypeNameAndDebug() [37/92]
Foam::defineTypeNameAndDebug (DAObjFuncTotalPressure , 0)
addToRunTimeSelectionTable() [31/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncTotalPressure , dictionary)
defineTypeNameAndDebug() [38/92]
Foam::defineTypeNameAndDebug (DAObjFuncTotalPressureRatio , 0)
addToRunTimeSelectionTable() [32/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncTotalPressureRatio , dictionary)
defineTypeNameAndDebug() [39/92]
Foam::defineTypeNameAndDebug (DAObjFuncTotalTemperatureRatio , 0)
addToRunTimeSelectionTable() [33/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncTotalTemperatureRatio , dictionary)
defineTypeNameAndDebug() [40/92]
Foam::defineTypeNameAndDebug (DAObjFuncVariableVolSum , 0)
addToRunTimeSelectionTable() [34/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncVariableVolSum , dictionary)
defineTypeNameAndDebug() [41/92]
Foam::defineTypeNameAndDebug (DAObjFuncVonMisesStressKS , 0)
addToRunTimeSelectionTable() [35/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncVonMisesStressKS , dictionary)
defineTypeNameAndDebug() [42/92]
Foam::defineTypeNameAndDebug (DAObjFuncWallHeatFlux , 0)
addToRunTimeSelectionTable() [36/80]
Foam::addToRunTimeSelectionTable (DAObjFunc , DAObjFuncWallHeatFlux , dictionary)
defineTypeNameAndDebug() [43/92]
Foam::defineTypeNameAndDebug (DAPartDeriv , 0)
defineRunTimeSelectionTable() [7/10]
Foam::defineRunTimeSelectionTable (DAPartDeriv , dictionary)
defineTypeNameAndDebug() [44/92]
Foam::defineTypeNameAndDebug (DAPartDerivdFdACTD , 0)
addToRunTimeSelectionTable() [37/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdFdACTD , dictionary)
defineTypeNameAndDebug() [45/92]
Foam::defineTypeNameAndDebug (DAPartDerivdFdAOA , 0)
addToRunTimeSelectionTable() [38/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdFdAOA , dictionary)
defineTypeNameAndDebug() [46/92]
Foam::defineTypeNameAndDebug (DAPartDerivdFdBC , 0)
addToRunTimeSelectionTable() [39/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdFdBC , dictionary)
defineTypeNameAndDebug() [47/92]
Foam::defineTypeNameAndDebug (DAPartDerivdFdFFD , 0)
addToRunTimeSelectionTable() [40/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdFdFFD , dictionary)
defineTypeNameAndDebug() [48/92]
Foam::defineTypeNameAndDebug (DAPartDerivdFdW , 0)
addToRunTimeSelectionTable() [41/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdFdW , dictionary)
defineTypeNameAndDebug() [49/92]
Foam::defineTypeNameAndDebug (DAPartDerivdRdACTD , 0)
addToRunTimeSelectionTable() [42/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdRdACTD , dictionary)
defineTypeNameAndDebug() [50/92]
Foam::defineTypeNameAndDebug (DAPartDerivdRdACTL , 0)
addToRunTimeSelectionTable() [43/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdRdACTL , dictionary)
defineTypeNameAndDebug() [51/92]
Foam::defineTypeNameAndDebug (DAPartDerivdRdACTP , 0)
addToRunTimeSelectionTable() [44/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdRdACTP , dictionary)
defineTypeNameAndDebug() [52/92]
Foam::defineTypeNameAndDebug (DAPartDerivdRdAOA , 0)
addToRunTimeSelectionTable() [45/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdRdAOA , dictionary)
defineTypeNameAndDebug() [53/92]
Foam::defineTypeNameAndDebug (DAPartDerivdRdBC , 0)
addToRunTimeSelectionTable() [46/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdRdBC , dictionary)
defineTypeNameAndDebug() [54/92]
Foam::defineTypeNameAndDebug (DAPartDerivdRdFFD , 0)
addToRunTimeSelectionTable() [47/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdRdFFD , dictionary)
defineTypeNameAndDebug() [55/92]
Foam::defineTypeNameAndDebug (DAPartDerivdRdW , 0)
addToRunTimeSelectionTable() [48/80]
Foam::addToRunTimeSelectionTable (DAPartDeriv , DAPartDerivdRdW , dictionary)
defineTypeNameAndDebug() [56/92]
Foam::defineTypeNameAndDebug (DAResidual , 0)
defineRunTimeSelectionTable() [8/10]
Foam::defineRunTimeSelectionTable (DAResidual , dictionary)
defineTypeNameAndDebug() [57/92]
Foam::defineTypeNameAndDebug (DAResidualDummy , 0)
addToRunTimeSelectionTable() [49/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualDummy , dictionary)
defineTypeNameAndDebug() [58/92]
Foam::defineTypeNameAndDebug (DAResidualLaplacianFoam , 0)
addToRunTimeSelectionTable() [50/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualLaplacianFoam , dictionary)
defineTypeNameAndDebug() [59/92]
Foam::defineTypeNameAndDebug (DAResidualPimpleFoam , 0)
addToRunTimeSelectionTable() [51/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualPimpleFoam , dictionary)
defineTypeNameAndDebug() [60/92]
Foam::defineTypeNameAndDebug (DAResidualPisoFoam , 0)
addToRunTimeSelectionTable() [52/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualPisoFoam , dictionary)
defineTypeNameAndDebug() [61/92]
Foam::defineTypeNameAndDebug (DAResidualRhoSimpleCFoam , 0)
addToRunTimeSelectionTable() [53/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualRhoSimpleCFoam , dictionary)
defineTypeNameAndDebug() [62/92]
Foam::defineTypeNameAndDebug (DAResidualRhoSimpleFoam , 0)
addToRunTimeSelectionTable() [54/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualRhoSimpleFoam , dictionary)
defineTypeNameAndDebug() [63/92]
Foam::defineTypeNameAndDebug (DAResidualScalarTransportFoam , 0)
addToRunTimeSelectionTable() [55/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualScalarTransportFoam , dictionary)
defineTypeNameAndDebug() [64/92]
Foam::defineTypeNameAndDebug (DAResidualSimpleFoam , 0)
addToRunTimeSelectionTable() [56/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualSimpleFoam , dictionary)
defineTypeNameAndDebug() [65/92]
Foam::defineTypeNameAndDebug (DAResidualSimpleTFoam , 0)
addToRunTimeSelectionTable() [57/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualSimpleTFoam , dictionary)
defineTypeNameAndDebug() [66/92]
Foam::defineTypeNameAndDebug (DAResidualSolidDisplacementFoam , 0)
addToRunTimeSelectionTable() [58/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualSolidDisplacementFoam , dictionary)
defineTypeNameAndDebug() [67/92]
Foam::defineTypeNameAndDebug (DAResidualTurboFoam , 0)
addToRunTimeSelectionTable() [59/80]
Foam::addToRunTimeSelectionTable (DAResidual , DAResidualTurboFoam , dictionary)
defineTypeNameAndDebug() [68/92]
Foam::defineTypeNameAndDebug (DALaplacianFoam , 0)
addToRunTimeSelectionTable() [60/80]
Foam::addToRunTimeSelectionTable (DASolver , DALaplacianFoam , dictionary)
defineTypeNameAndDebug() [69/92]
Foam::defineTypeNameAndDebug (DAPimpleDyMFoam , 0)
addToRunTimeSelectionTable() [61/80]
Foam::addToRunTimeSelectionTable (DASolver , DAPimpleDyMFoam , dictionary)
defineTypeNameAndDebug() [70/92]
Foam::defineTypeNameAndDebug (DAPimpleFoam , 0)
addToRunTimeSelectionTable() [62/80]
Foam::addToRunTimeSelectionTable (DASolver , DAPimpleFoam , dictionary)
defineTypeNameAndDebug() [71/92]
Foam::defineTypeNameAndDebug (DAPisoFoam , 0)
addToRunTimeSelectionTable() [63/80]
Foam::addToRunTimeSelectionTable (DASolver , DAPisoFoam , dictionary)
defineTypeNameAndDebug() [72/92]
Foam::defineTypeNameAndDebug (DARhoSimpleCFoam , 0)
addToRunTimeSelectionTable() [64/80]
Foam::addToRunTimeSelectionTable (DASolver , DARhoSimpleCFoam , dictionary)
defineTypeNameAndDebug() [73/92]
Foam::defineTypeNameAndDebug (DARhoSimpleFoam , 0)
addToRunTimeSelectionTable() [65/80]
Foam::addToRunTimeSelectionTable (DASolver , DARhoSimpleFoam , dictionary)
defineTypeNameAndDebug() [74/92]
Foam::defineTypeNameAndDebug (DAScalarTransportFoam , 0)
addToRunTimeSelectionTable() [66/80]
Foam::addToRunTimeSelectionTable (DASolver , DAScalarTransportFoam , dictionary)
defineTypeNameAndDebug() [75/92]
Foam::defineTypeNameAndDebug (DASimpleFoam , 0)
addToRunTimeSelectionTable() [67/80]
Foam::addToRunTimeSelectionTable (DASolver , DASimpleFoam , dictionary)
defineTypeNameAndDebug() [76/92]
Foam::defineTypeNameAndDebug (DASimpleTFoam , 0)
addToRunTimeSelectionTable() [68/80]
Foam::addToRunTimeSelectionTable (DASolver , DASimpleTFoam , dictionary)
defineTypeNameAndDebug() [77/92]
Foam::defineTypeNameAndDebug (DASolidDisplacementFoam , 0)
addToRunTimeSelectionTable() [69/80]
Foam::addToRunTimeSelectionTable (DASolver , DASolidDisplacementFoam , dictionary)
defineTypeNameAndDebug() [78/92]
Foam::defineTypeNameAndDebug (DASolver , 0)
defineRunTimeSelectionTable() [9/10]
Foam::defineRunTimeSelectionTable (DASolver , dictionary)
defineTypeNameAndDebug() [79/92]
Foam::defineTypeNameAndDebug (DATurboFoam , 0)
addToRunTimeSelectionTable() [70/80]
Foam::addToRunTimeSelectionTable (DASolver , DATurboFoam , dictionary)
defineTypeNameAndDebug() [80/92]
Foam::defineTypeNameAndDebug (DAStateInfo , 0)
defineRunTimeSelectionTable() [10/10]
Foam::defineRunTimeSelectionTable (DAStateInfo , dictionary)
defineTypeNameAndDebug() [81/92]
Foam::defineTypeNameAndDebug (DAStateInfoLaplacianFoam , 0)
addToRunTimeSelectionTable() [71/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoLaplacianFoam , dictionary)
defineTypeNameAndDebug() [82/92]
Foam::defineTypeNameAndDebug (DAStateInfoPimpleFoam , 0)
addToRunTimeSelectionTable() [72/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoPimpleFoam , dictionary)
defineTypeNameAndDebug() [83/92]
Foam::defineTypeNameAndDebug (DAStateInfoPisoFoam , 0)
addToRunTimeSelectionTable() [73/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoPisoFoam , dictionary)
defineTypeNameAndDebug() [84/92]
Foam::defineTypeNameAndDebug (DAStateInfoRhoSimpleCFoam , 0)
addToRunTimeSelectionTable() [74/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoRhoSimpleCFoam , dictionary)
defineTypeNameAndDebug() [85/92]
Foam::defineTypeNameAndDebug (DAStateInfoRhoSimpleFoam , 0)
addToRunTimeSelectionTable() [75/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoRhoSimpleFoam , dictionary)
defineTypeNameAndDebug() [86/92]
Foam::defineTypeNameAndDebug (DAStateInfoScalarTransportFoam , 0)
addToRunTimeSelectionTable() [76/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoScalarTransportFoam , dictionary)
defineTypeNameAndDebug() [87/92]
Foam::defineTypeNameAndDebug (DAStateInfoSimpleFoam , 0)
addToRunTimeSelectionTable() [77/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoSimpleFoam , dictionary)
defineTypeNameAndDebug() [88/92]
Foam::defineTypeNameAndDebug (DAStateInfoSimpleTFoam , 0)
addToRunTimeSelectionTable() [78/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoSimpleTFoam , dictionary)
defineTypeNameAndDebug() [89/92]
Foam::defineTypeNameAndDebug (DAStateInfoSolidDisplacementFoam , 0)
addToRunTimeSelectionTable() [79/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoSolidDisplacementFoam , dictionary)
defineTypeNameAndDebug() [90/92]
Foam::defineTypeNameAndDebug (DAStateInfoTurboFoam , 0)
addToRunTimeSelectionTable() [80/80]
Foam::addToRunTimeSelectionTable (DAStateInfo , DAStateInfoTurboFoam , dictionary)
defineTypeNameAndDebug() [91/92]
Foam::defineTypeNameAndDebug (MRFZoneDF , 0)
operator<<()
Foam::Ostream & operator<< (Ostream & os, const MRFZoneListDF & models)
Definition at line 244 of file MRFZoneListDF.C.
References MRFZoneListDF::writeData().
defineTypeNameAndDebug() [92/92]
Foam::defineTypeNameAndDebug (pimpleControlDF , 0)