DAFoam: dafoam.optFuncs Namespace Reference
dafoam.optFuncs Namespace Reference
Classes
class Info
Functions
def calcObjFuncValues (xDV)
def calcObjFuncValuesMP (xDV)
def calcObjFuncValuesHybridAdjoint (xDV)
def calcObjFuncSens (xDV, funcs)
def calcObjFuncSensMP (xDV, funcs)
def calcObjFuncSensHybridAdjoint (xDV, funcs)
def runPrimal (objFun=calcObjFuncValues)
def runAdjoint (objFun=calcObjFuncValues, sensFun=calcObjFuncSens, fileName=None)
def solveCL (CL_star, alphaName, liftName, objFun=calcObjFuncValues)
def verifySens (objFun=calcObjFuncValues, sensFun=calcObjFuncSens)
def calcFDSens (objFun=calcObjFuncValues, fileName=None)
Variables
precision
suppress
Detailed Description
    DAFoam  : Discrete Adjoint with OpenFOAM
    Version : v2
    Description:
    Common functions for DAFoam optimization setup.
Function Documentation
calcObjFuncValues()
def dafoam.optFuncs.calcObjFuncValues (xDV)
Update the design surface and run the primal solver to get objective function values.
Definition at line 26 of file optFuncs.py.
calcObjFuncValuesMP()
def dafoam.optFuncs.calcObjFuncValuesMP (xDV)
Update the design surface and run the primal solver to get objective function values.
This is the multipoint version of calcObjFuncValues
Definition at line 68 of file optFuncs.py.
calcObjFuncValuesHybridAdjoint()
def dafoam.optFuncs.calcObjFuncValuesHybridAdjoint (xDV)
Update the design surface and run the primal solver to get objective function values.
This is the hybrid adjoint version of calcObjFuncValues
Definition at line 139 of file optFuncs.py.
calcObjFuncSens()
def dafoam.optFuncs.calcObjFuncSens (xDV, funcs)
Run the adjoint solver and get objective function sensitivities.
Definition at line 183 of file optFuncs.py.
calcObjFuncSensMP()
def dafoam.optFuncs.calcObjFuncSensMP (xDV, funcs)
Run the adjoint solver and get objective function sensitivities.
This is the multipoint version of calcObjFuncSens
Definition at line 221 of file optFuncs.py.
calcObjFuncSensHybridAdjoint()
def dafoam.optFuncs.calcObjFuncSensHybridAdjoint (xDV, funcs)
Run the adjoint solver and get objective function sensitivities.
This is the hybrid adjoint version of calcObjFuncSens
Definition at line 289 of file optFuncs.py.
runPrimal()
def dafoam.optFuncs.runPrimal (objFun = calcObjFuncValues)
Just run the primal
Definition at line 355 of file optFuncs.py.
runAdjoint()
def dafoam.optFuncs.runAdjoint (objFun = calcObjFuncValues, sensFun = calcObjFuncSens, fileName = None)
Just run the primal and adjoint
Definition at line 365 of file optFuncs.py.
Referenced by dafoam.optFuncs.verifySens().
solveCL()
def dafoam.optFuncs.solveCL (CL_star, alphaName, liftName, objFun = calcObjFuncValues)
Definition at line 395 of file optFuncs.py.
verifySens()
def dafoam.optFuncs.verifySens (objFun = calcObjFuncValues, sensFun = calcObjFuncSens)
Verify the FFD sensitivity against finite-difference references
Definition at line 423 of file optFuncs.py.
References dafoam.optFuncs.calcFDSens(), and dafoam.optFuncs.runAdjoint().
calcFDSens()
def dafoam.optFuncs.calcFDSens (objFun = calcObjFuncValues, fileName = None)
Compute finite-difference sensitivity
Definition at line 432 of file optFuncs.py.
Referenced by dafoam.optFuncs.verifySens().
Variable Documentation
precision
precision
Definition at line 23 of file optFuncs.py.
suppress
suppress
Definition at line 23 of file optFuncs.py.