DAFoam: dafoam/src/adjoint/DASolver/DASimpleFoam/pEqnSimple.H File Reference
pEqnSimple.H File Reference
Functions
volVectorField HbyA ("HbyA", U)
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA))
adjustPhi (phiHbyA, U, p)
tmp< volScalarField > rAtU (rAU)
if (simple.consistent())
tUEqn clear ()
while (simple.correctNonOrthogonal())
if (nSolverIters%printInterval==0||nSolverIters==1)
p relax ()
U correctBoundaryConditions ()
Variables
HbyA = rAU * UEqn.H()
U = HbyA - rAtU() * fvc::grad(p)
Function Documentation
volVectorField HbyA ("HbyA" , U)
surfaceScalarField phiHbyA ("phiHbyA" , fvc:: fluxHbyA)
Referenced by if(), and while().
adjustPhi (phiHbyA , U , p)
Referenced by DAResidualSimpleFoam::calcResiduals(), and DAResidualRhoSimpleFoam::calcResiduals().
tmp<volScalarField> rAtU (rAU)
Referenced by if(), and while().
if (simple. consistent())
Definition at line 16 of file pEqnSimple.H.
References HbyA, mesh, p, phiHbyA(), rAtU(), rAU(), and UEqn.
tUEqn clear ()
while (simple. correctNonOrthogonal())
Definition at line 30 of file pEqnSimple.H.
References p, phi, phiHbyA(), pRefCell, pRefValue, primalResidualControl< scalar >(), rAtU(), and simple.
if (nSolverIters% printInterval = = 0 || nSolverIters == 1)
Definition at line 49 of file pEqnSimple.H.
p relax ()
U correctBoundaryConditions ()
Variable Documentation
HbyA = rAU * UEqn.H()
Definition at line 10 of file pEqnSimple.H.
Referenced by if().
U = HbyA - rAtU() * fvc::grad(p)
Definition at line 58 of file pEqnSimple.H.