DAFoam: dafoam/src/adjoint/DASolver/DAPisoFoam/pEqnPiso.H File Reference
pEqnPiso.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA))
adjustPhi (phiHbyA, U, p)
while (piso.correctNonOrthogonal())
if (printToScreen)
U correctBoundaryConditions ()
Variables
U = HbyA - rAU * fvc::grad(p)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
Referenced by DAResidualSimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), if(), and while().
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA))
Referenced by while().
adjustPhi()
adjustPhi (phiHbyA , U , p)
Referenced by DAResidualSimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), and DAResidualRhoSimpleFoam::calcResiduals().
while()
while (piso. correctNonOrthogonal())
Definition at line 8 of file pEqnPiso.H.
References mesh, p, phi, phiHbyA(), piso, pRefCell, pRefValue, primalResidualControl< scalar >(), and rAU().
if()
if (printToScreen)
Definition at line 29 of file pEqnPiso.H.
correctBoundaryConditions()
U correctBoundaryConditions ()
Variable Documentation
U
U = HbyA - rAU * fvc::grad(p)
Definition at line 34 of file pEqnPiso.H.