DAFoam: dafoam/src/adjoint/DASolver/DAPimpleFoam/pEqnPimple.H File Reference
pEqnPimple.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+fvc::interpolate(rAU) *fvc::ddtCorr(U, phi))
adjustPhi (phiHbyA, U, p)
tmp< volScalarField > rAtU (rAU)
if (pimple.consistent())
if (pimple.nCorrPISO()<=1)
while (pimple.correctNonOrthogonal())
if (printToScreen)
p relax ()
U correctBoundaryConditions ()
Variables
U = HbyA - rAtU() * fvc::grad(p)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), and if().
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
Referenced by if().
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+fvc::interpolate(rAU) *fvc::ddtCorr(U, phi))
Referenced by if(), and while().
adjustPhi()
adjustPhi (phiHbyA , U , p)
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), and DAResidualRhoSimpleFoam::calcResiduals().
rAtU()
tmp<volScalarField> rAtU (rAU)
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), if(), and while().
if() [1/3]
if (pimple. consistent())
Definition at line 12 of file pEqnPimple.H.
References HbyA(), mesh, p, phiHbyA(), rAtU(), rAU(), and UEqn.
if() [2/3]
if (pimple.nCorrPISO()<= 1)
Definition at line 20 of file pEqnPimple.H.
References tUEqn().
while()
while (pimple. correctNonOrthogonal())
Definition at line 26 of file pEqnPimple.H.
References mesh, p, phi, phiHbyA(), pimple, pRefCell, pRefValue, primalResidualControl< scalar >(), and rAtU().
if() [3/3]
if (printToScreen)
Definition at line 46 of file pEqnPimple.H.
References p.
relax()
rho relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
Variable Documentation
U
U = HbyA - rAtU() * fvc::grad(p)
Definition at line 54 of file pEqnPimple.H.