DAFoam: dafoam/src/adjoint/DASolver/DAPimpleDyMFoam/pEqnPimpleDyM.H File Reference
pEqnPimpleDyM.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA)+MRF.zeroFilter(fvc::interpolate(rAU) *fvc::ddtCorr(U, phi, Uf)))
MRF makeRelative (phiHbyA)
if (p.needReference())
tmp< volScalarField > rAtU (rAU)
if (pimple.consistent())
if (pimple.nCorrPISO()<=1)
constrainPressure (p, U, phiHbyA, rAtU(), MRF)
while (pimple.correctNonOrthogonal())
p relax ()
U correctBoundaryConditions ()
fvOptions correct (U)
Variables
U = HbyA - rAtU*fvc::grad(p)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), and if().
HbyA()
volVectorField HbyA (constrainHbyA(rAU *UEqn.H(), U, p))
Referenced by if().
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA)+MRF.zeroFilter(fvc::interpolate(rAU) *fvc::ddtCorr(U, phi, Uf)))
Referenced by if(), and while().
makeRelative()
MRF makeRelative (phiHbyA)
Referenced by if(), and DAPimpleDyMFoam::solvePrimal().
if() [1/3]
if (p. needReference())
Definition at line 12 of file pEqnPimpleDyM.H.
References adjustPhi(), makeRelative(), p, phiHbyA(), and U.
rAtU()
tmp<volScalarField> rAtU (rAU)
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), if(), and while().
if() [2/3]
if (pimple. consistent())
Definition at line 21 of file pEqnPimpleDyM.H.
References HbyA(), mesh, p, phiHbyA(), rAtU(), rAU(), and UEqn.
if() [3/3]
if (pimple.nCorrPISO()<= 1)
Definition at line 29 of file pEqnPimpleDyM.H.
References tUEqn().
constrainPressure()
constrainPressure (p , U , phiHbyA , rAtU() , MRF)
Referenced by DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), and DAResidualRhoSimpleFoam::calcResiduals().
while()
while (pimple. correctNonOrthogonal())
Definition at line 38 of file pEqnPimpleDyM.H.
References mesh, p, phi, phiHbyA(), pimple, pRefCell, pRefValue, and rAtU().
relax()
rho relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
correct()
fvOptions correct (U)
Variable Documentation
U
U = HbyA - rAtU*fvc::grad(p)
Definition at line 60 of file pEqnPimpleDyM.H.
Referenced by MRFZoneDF::addCoriolis(), DASolver::calcdRdAOATPsiAD(), DAObjFuncMassFlowRate::calcObjFunc(), DAObjFuncTotalPressure::calcObjFunc(), DAObjFuncTotalPressureRatio::calcObjFunc(), DAObjFuncTotalTemperatureRatio::calcObjFunc(), DAObjFuncFieldInversion::calcObjFunc(), DAField::checkSpecialBCs(), DAJacCon::checkSpecialBCs(), MRFZoneListDF::correctBoundaryVelocity(), MRFZoneDF::correctBoundaryVelocity(), DAkOmegaSST::correctNut(), DAkOmegaSSTFieldInversion::correctNut(), DAkOmegaSSTLM::correctNut(), MRFZoneListDF::DDt(), DATurbulenceModel::divDevReff(), DATurbulenceModel::divDevRhoReff(), DAMotion::getForce(), if(), MRFZoneListDF::makeRelative(), MRFZoneDF::makeRelative(), DAPimpleDyMFoam::solvePrimal(), DAField::specialBCTreatment(), DAObjFuncForce::updateForceDir(), and DASolver::writeAssociatedFields().