DAFoam: dafoam/src/adjoint/DASolver/DATurboFoam/pEqnTurbo.H File Reference
pEqnTurbo.H File Reference
Functions
if (!simple.transonic())
volScalarField p0 (p)
volScalarField AU (UEqn.A())
volScalarField AtU (AU - UEqn.H1())
volVectorField HbyA ("HbyA", U)
volScalarField rAU (1.0/UEqn.A())
tUEqn clear ()
if (simple.transonic())
MRF makeRelative (fvc::interpolate(rho), phiHbyA)
while (simple.correctNonOrthogonal())
if (printToScreen)
p relax ()
U correctBoundaryConditions ()
if (closedVolume)
Variables
rho = thermo.rho()
HbyA = UEqn.H() / AU
bool closedVolume = false
else
phiHbyA = fvc::interpolate(rho / AtU - rho / AU) * fvc::snGrad(p) * mesh.magSf()
U = HbyA - (fvc::grad(p0) * (1.0 / AU - 1.0 / AtU) + fvc::grad(p) / AtU)
Function Documentation
if() [1/4]
if (!simple. transonic())
Definition at line 5 of file pEqnTurbo.H.
References AtU(), AU(), HbyA, p, p0(), rho, U, and UEqn.
p0()
volScalarField p0 (p)
Referenced by Foam::checkCoupledPoints(), and if().
AU()
volScalarField AU (UEqn. A())
Referenced by DAResidualTurboFoam::calcResiduals(), and if().
AtU()
volScalarField AtU (AU - UEqn. H1())
Referenced by DAResidualTurboFoam::calcResiduals(), if(), and while().
HbyA()
volVectorField HbyA ("HbyA" , U)
rAU()
volScalarField rAU (1.0/UEqn. A())
Referenced by if().
clear()
tUEqn clear ()
if() [2/4]
if (simple. transonic())
Definition at line 22 of file pEqnTurbo.H.
References mesh, MRF, p, phi, phid(), pressureControl, primalResidualControl< scalar >(), psi, rAU(), rho, and simple.
makeRelative()
MRF makeRelative (fvc::interpolate(rho) , phiHbyA)
while()
while (simple. correctNonOrthogonal())
Definition at line 67 of file pEqnTurbo.H.
References AtU(), p, phi, phiHbyA, pressureControl, primalResidualControl< scalar >(), rho, and simple.
if() [3/4]
if (printToScreen)
Definition at line 90 of file pEqnTurbo.H.
References allOptions, and p.
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
if() [4/4]
if (closedVolume)
Definition at line 109 of file pEqnTurbo.H.
References allOptions, initialMass_, p, psi, rho, simple, and thermo.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqnTurbo.H.
Referenced by if(), and while().
HbyA
HbyA = UEqn.H() / AU
Definition at line 15 of file pEqnTurbo.H.
Referenced by if().
closedVolume
closedVolume = false
Definition at line 20 of file pEqnTurbo.H.
else
else
Initial value:
{
    surfaceScalarField phiHbyA(
        "phiHbyA",
        fvc::interpolate(rho * HbyA) & mesh.Sf())
Definition at line 57 of file pEqnTurbo.H.
phiHbyA
phiHbyA = fvc::interpolate(rho / AtU - rho / AU) * fvc::snGrad(p) * mesh.magSf()
Definition at line 65 of file pEqnTurbo.H.
Referenced by while().
U
U = HbyA - (fvc::grad(p0) * (1.0 / AU - 1.0 / AtU) + fvc::grad(p) / AtU)
Definition at line 101 of file pEqnTurbo.H.
Referenced by if().