DAFoam: dafoam/src/adjoint/DASolver/DARhoSimpleCFoam/pEqnRhoSimpleC.H File Reference
pEqnRhoSimpleC.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
volScalarField rAtU (1.0/(1.0/rAU - UEqn.H1()))
volVectorField HbyA ("HbyA", U)
tUEqn clear ()
surfaceScalarField phiHbyA ("phiHbyA", fvc::interpolate(rho) *fvc::flux(HbyA))
volScalarField rhorAtU ("rhorAtU", rho *rAtU)
surfaceScalarField phid ("phid",(fvc::interpolate(psi)/fvc::interpolate(rho)) *phiHbyA)
while (simple.correctNonOrthogonal())
if (printToScreen)
p relax ()
U correctBoundaryConditions ()
if (closedVolume)
if (pLimited||closedVolume)
Variables
rho = thermo.rho()
HbyA = rAU * UEqn.H()
bool closedVolume = false
phiHbyA
U = HbyA - rAtU * fvc::grad(p)
bool pLimited = pressureControl.limit(p)
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rAtU()
volScalarField rAtU (1.0/ 1.0/rAU - UEqn.H1())
HbyA()
volVectorField HbyA ("HbyA" , U)
clear()
tUEqn clear ()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::interpolate(rho) *fvc::flux(HbyA))
rhorAtU()
volScalarField rhorAtU ("rhorAtU" , rho * rAtU)
Referenced by DAResidualRhoSimpleCFoam::calcResiduals(), and while().
phid()
surfaceScalarField phid ("phid" , (fvc::interpolate(psi)/fvc::interpolate(rho)) * phiHbyA)
Referenced by DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), if(), and while().
while()
while (simple. correctNonOrthogonal())
Definition at line 33 of file pEqnRhoSimpleC.H.
References p, phi, phid(), phiHbyA, pressureControl, primalResidualControl< scalar >(), rhorAtU(), and simple.
if() [1/3]
if (printToScreen)
Definition at line 59 of file pEqnRhoSimpleC.H.
References allOptions, and p.
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
if() [2/3]
if (closedVolume)
Definition at line 79 of file pEqnRhoSimpleC.H.
References initialMass_, p, and psi.
if() [3/3]
if (pLimited|| closedVolume)
Definition at line 85 of file pEqnRhoSimpleC.H.
References allOptions, p, rho, and thermo.
Variable Documentation
rho
rho = thermo.rho()
Definition at line 1 of file pEqnRhoSimpleC.H.
Referenced by if().
HbyA
HbyA = rAU * UEqn.H()
Definition at line 12 of file pEqnRhoSimpleC.H.
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), and DAResidualRhoSimpleFoam::calcResiduals().
closedVolume
bool closedVolume = false
Definition at line 15 of file pEqnRhoSimpleC.H.
phiHbyA
phiHbyA
Initial value:
=
    fvc::interpolate(rho * (rAtU - rAU)) * fvc::snGrad(p) * mesh.magSf()
    - fvc::interpolate(psi * p) * phiHbyA / fvc::interpolate(rho)
Definition at line 27 of file pEqnRhoSimpleC.H.
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), and while().
U
U = HbyA - rAtU * fvc::grad(p)
Definition at line 70 of file pEqnRhoSimpleC.H.
pLimited
bool pLimited = pressureControl.limit(p)
Definition at line 75 of file pEqnRhoSimpleC.H.