DAFoam: dafoam/src/adjoint/DASolver/DARhoSimpleFoam/pEqnRhoSimple.H File Reference
pEqnRhoSimple.H File Reference
Functions
volScalarField rAU (1.0/UEqn.A())
surfaceScalarField rhorAUf ("rhorAUf", fvc::interpolate(rho *rAU))
volVectorField HbyA ("HbyA", U)
tUEqn clear ()
surfaceScalarField phiHbyA ("phiHbyA", fvc::interpolate(rho) *fvc::flux(HbyA))
while (simple.correctNonOrthogonal())
if (nSolverIters % printInterval==0||nSolverIters==1)
p relax ()
U correctBoundaryConditions ()
if (closedVolume)
if (pLimited||closedVolume)
Variables
HbyA = rAU * UEqn.H()
bool closedVolume = false
U = HbyA - rAU * fvc::grad(p)
bool pLimited = pressureControl.limit(p)
rho = thermo.rho()
Function Documentation
rAU()
volScalarField rAU (1.0/UEqn. A())
rhorAUf()
surfaceScalarField rhorAUf ("rhorAUf" , fvc::interpolate(rho *rAU))
Referenced by DAResidualRhoSimpleFoam::calcResiduals(), and while().
HbyA()
volVectorField HbyA ("HbyA" , U)
clear()
tUEqn clear ()
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::interpolate(rho) *fvc::flux(HbyA))
Referenced by while().
while()
while (simple. correctNonOrthogonal())
Definition at line 21 of file pEqnRhoSimple.H.
References p, phi, phiHbyA(), pressureControl, primalResidualControl< scalar >(), rhorAUf(), and simple.
if() [1/3]
if (nSolverIters % printInterval = = 0 || nSolverIters == 1)
Definition at line 43 of file pEqnRhoSimple.H.
References allOptions, and p.
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
if() [2/3]
if (closedVolume)
Definition at line 63 of file pEqnRhoSimple.H.
References initialMass_, p, and psi.
if() [3/3]
if (pLimited|| closedVolume)
Definition at line 69 of file pEqnRhoSimple.H.
References p.
Variable Documentation
HbyA
HbyA = rAU * UEqn.H()
Definition at line 10 of file pEqnRhoSimple.H.
closedVolume
closedVolume = false
Definition at line 13 of file pEqnRhoSimple.H.
U
U = HbyA - rAU * fvc::grad(p)
Definition at line 54 of file pEqnRhoSimple.H.
pLimited
bool pLimited = pressureControl.limit(p)
Definition at line 59 of file pEqnRhoSimple.H.
rho
rho = thermo.rho()
Definition at line 74 of file pEqnRhoSimple.H.