DAFoam: dafoam/src/adjoint/DASolver/DASimpleTFoam/pEqnSimpleT.H File Reference
pEqnSimpleT.H File Reference
Functions
volVectorField HbyA ("HbyA", U)
surfaceScalarField phiHbyA ("phiHbyA", fvc::flux(HbyA))
adjustPhi (phiHbyA, U, p)
tmp< volScalarField > rAtU (rAU)
if (simple.consistent())
tUEqn clear ()
while (simple.correctNonOrthogonal())
if (printToScreen)
p relax ()
U correctBoundaryConditions ()
Variables
HbyA = rAU * UEqn.H()
U = HbyA - rAtU() * fvc::grad(p)
Function Documentation
HbyA()
volVectorField HbyA ("HbyA" , U)
phiHbyA()
surfaceScalarField phiHbyA ("phiHbyA" , fvc::flux(HbyA))
Referenced by if(), and while().
adjustPhi()
adjustPhi (phiHbyA , U , p)
rAtU()
tmp<volScalarField> rAtU (rAU)
Referenced by if(), and while().
if() [1/2]
if (simple. consistent())
Definition at line 16 of file pEqnSimpleT.H.
References HbyA, mesh, p, phiHbyA(), rAtU(), rAU(), tUEqn(), and UEqn.
clear()
tUEqn clear ()
while()
while (simple. correctNonOrthogonal())
Definition at line 30 of file pEqnSimpleT.H.
References p, phi, phiHbyA(), pRefCell, pRefValue, primalResidualControl< scalar >(), rAtU(), and simple.
if() [2/2]
if (printToScreen)
Definition at line 49 of file pEqnSimpleT.H.
References p.
relax()
p relax ()
correctBoundaryConditions()
U correctBoundaryConditions ()
Variable Documentation
HbyA
HbyA = rAU * UEqn.H()
Definition at line 10 of file pEqnSimpleT.H.
Referenced by if().
U
U = HbyA - rAtU() * fvc::grad(p)
Definition at line 58 of file pEqnSimpleT.H.