DAFoam: dafoam/src/adjoint/DASolver/DASimpleFoam/pseudoEqns.H File Reference
pseudoEqns.H File Reference
Functions
if (daOptionPtr_->getSubDictOption< label >("adjEqnOption", "fpPCUpwind"))
volVectorField pseudoU ("pseudoU", U)
fvVectorMatrix pseudoUEqn (fvm::div(phi, pseudoU, divScheme) - fvm::laplacian(nuEff, pseudoU))
pseudoUEqn relax (relaxUEqn_)
swap (pseudoUEqn.upper(), pseudoUEqn.lower())
volScalarField rAU (1.0/pseudoUEqn.A())
volScalarField pseudoP ("pseudoP", p)
fvScalarMatrix pseudoPEqn (fvm::laplacian(rAU, pseudoP))
swap (pseudoPEqn.upper(), pseudoPEqn.lower())
daTurbulenceModelPtr_ constructPseudoNuTildaEqn ()
Variables
word divScheme = "div(phi,U)"
List< scalar > UDiag = pseudoUEqn.D()
volScalarField & pseudoNuTilda = const_cast<volScalarField&>(db.lookupObject<volScalarField>("pseudoNuTilda"))
Function Documentation
if()
if (daOptionPtr_->getSubDictOption< label > "adjEqnOption", "fpPCUpwind")
Definition at line 2 of file pseudoEqns.H.
References divScheme.
pseudoU()
volVectorField pseudoU ("pseudoU" , U)
Referenced by forAll(), and DASimpleFoam::runFPAdj().
pseudoUEqn()
fvVectorMatrix pseudoUEqn (fvm::div(phi, pseudoU, divScheme) - fvm::laplacian(nuEff, pseudoU))
Referenced by forAll(), and DASimpleFoam::runFPAdj().
relax()
pseudoUEqn relax (relaxUEqn_)
swap() [1/2]
swap (pseudoUEqn. upper(), pseudoUEqn. lower())
rAU()
volScalarField rAU (1.0/pseudoUEqn. A())
pseudoP()
volScalarField pseudoP ("pseudoP" , p)
Referenced by forAll(), and DASimpleFoam::runFPAdj().
pseudoPEqn()
fvScalarMatrix pseudoPEqn (fvm::laplacian(rAU, pseudoP))
Referenced by forAll().
swap() [2/2]
swap (pseudoPEqn. upper(), pseudoPEqn. lower())
constructPseudoNuTildaEqn()
daTurbulenceModelPtr_ constructPseudoNuTildaEqn ()
Variable Documentation
divScheme
word divScheme = "div(phi,U)"
Definition at line 1 of file pseudoEqns.H.
Referenced by DATurbulenceModel::divDevRhoReff(), and if().
UDiag
List<scalar> UDiag = pseudoUEqn.D()
Definition at line 18 of file pseudoEqns.H.
Referenced by DASimpleFoam::calcLduResiduals(), and DASimpleFoam::runFPAdj().
pseudoNuTilda
volScalarField& pseudoNuTilda = const_cast<volScalarField&>(db.lookupObject<volScalarField>("pseudoNuTilda"))
Definition at line 34 of file pseudoEqns.H.
Referenced by DASimpleFoam::runFPAdj().