DAFoam: dafoam/src/utilities/pyColoringSolid/createFields.H File Reference
createFields.H File Reference
Functions
volVectorField D (IOobject("D", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("D", dimensionSet(0, 1, 0, 0, 0, 0, 0), vector::zero), zeroGradientFvPatchField< vector >::typeName)
volScalarField mu (IOobject("solid:mu", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("solid:mu", dimensionSet(0, 1, 0, 0, 0, 0, 0), 0.0), zeroGradientFvPatchField< scalar >::typeName)
volScalarField rho (IOobject("solid:rho", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("solid:rho", dimensionSet(0, 1, 0, 0, 0, 0, 0), 0.0), zeroGradientFvPatchField< scalar >::typeName)
volScalarField nu (IOobject("solid:nu", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("solid:nu", dimensionSet(0, 1, 0, 0, 0, 0, 0), 0.0), zeroGradientFvPatchField< scalar >::typeName)
volScalarField lambda (IOobject("solid:lambda", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedScalar("solid:lambda", dimensionSet(0, 1, 0, 0, 0, 0, 0), 0.0), zeroGradientFvPatchField< scalar >::typeName)
volTensorField gradD (IOobject("gradD", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), fvc::grad(D))
volSymmTensorField sigmaD (IOobject("sigmaD", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mu *twoSymm(fvc::grad(D))+lambda *(I *tr(fvc::grad(D))))
volVectorField divSigmaExp (IOobject("divSigmaExp", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE), mesh, dimensionedVector("divSigmaExp", dimensionSet(0, 1, 0, 0, 0, 0, 0), vector::zero), zeroGradientFvPatchField< vector >::typeName)
Variables
fvMesh & mesh = meshPtr_()
Function Documentation
D()
volVectorField D (IOobject("D", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("D", dimensionSet(0, 1, 0, 0, 0, 0, 0), vector::zero) , zeroGradientFvPatchField< vector >::typeName)
mu()
volScalarField mu (IOobject("solid:mu", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar("solid:mu", dimensionSet(0, 1, 0, 0, 0, 0, 0), 0.0) , zeroGradientFvPatchField< scalar >::typeName)
rho()
volScalarField rho (IOobject("solid:rho", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar("solid:rho", dimensionSet(0, 1, 0, 0, 0, 0, 0), 0.0) , zeroGradientFvPatchField< scalar >::typeName)
nu()
volScalarField nu (IOobject("solid:nu", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar("solid:nu", dimensionSet(0, 1, 0, 0, 0, 0, 0), 0.0) , zeroGradientFvPatchField< scalar >::typeName)
Referenced by SpalartAllmarasFv3< BasicTurbulenceModel >::chi(), SpalartAllmarasFv3< BasicTurbulenceModel >::DnuTildaEff(), and tractionDisplacementFvPatchVectorField::updateCoeffs().
lambda()
volScalarField lambda (IOobject("solid:lambda", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedScalar("solid:lambda", dimensionSet(0, 1, 0, 0, 0, 0, 0), 0.0) , zeroGradientFvPatchField< scalar >::typeName)
gradD()
volTensorField gradD (IOobject("gradD", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , fvc::grad(D))
sigmaD()
volSymmTensorField sigmaD (IOobject("sigmaD", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mu * twoSymmfvc::grad(D))+lambda *(I *tr(fvc::grad(D)))
divSigmaExp()
volVectorField divSigmaExp (IOobject("divSigmaExp", mesh.time().timeName(), mesh, IOobject::NO_READ, IOobject::NO_WRITE) , mesh , dimensionedVector("divSigmaExp", dimensionSet(0, 1, 0, 0, 0, 0, 0), vector::zero) , zeroGradientFvPatchField< vector >::typeName)
Variable Documentation
mesh
fvMesh& mesh = meshPtr_()
Definition at line 3 of file createFields.H.