DAFoam: dafoam/src/utilities/coloring/pyColoringCompressible/createAdjoint.H File Reference
createAdjoint.H File Reference
Functions
DAOption daOption (mesh, pyOptions_)
DARegDbFluidThermo regDbThermo (mesh, thermo)
DARegDbTurbulenceModelCompressible regDbTurbulence (mesh, turbulence())
const word turbModelName (IOdictionary(IOobject("turbulenceProperties", mesh.time().constant(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE, false)) .subDict("RAS") .lookup("RASModel"))
autoPtr< DATurbulenceModel > daTurbulenceModel (DATurbulenceModel::New(turbModelName, mesh, daOption))
DAModel daModel (mesh, daOption)
DAIndex daIndex (mesh, daOption, daModel)
Variables
DAUtility daUtil
Function Documentation
daOption()
DAOption daOption (mesh , pyOptions_)
Referenced by DAField::DAField(), DAFvSourceActuatorLine::DAFvSourceActuatorLine(), DAFvSourceActuatorPoint::DAFvSourceActuatorPoint(), DAJacCon::DAJacCon(), DAkEpsilon::DAkEpsilon(), DAkOmega::DAkOmega(), DAkOmegaFieldInversionOmega::DAkOmegaFieldInversionOmega(), DAkOmegaSST::DAkOmegaSST(), DAkOmegaSSTFieldInversion::DAkOmegaSSTFieldInversion(), DAkOmegaSSTFIML::DAkOmegaSSTFIML(), DAkOmegaSSTLM::DAkOmegaSSTLM(), DAPartDeriv::DAPartDeriv(), DAResidualPimpleFoam::DAResidualPimpleFoam(), DAResidualPisoFoam::DAResidualPisoFoam(), DAResidualRhoSimpleFoam::DAResidualRhoSimpleFoam(), DAResidualSimpleFoam::DAResidualSimpleFoam(), DAResidualSimpleTFoam::DAResidualSimpleTFoam(), DASpalartAllmaras::DASpalartAllmaras(), DASpalartAllmarasFv3::DASpalartAllmarasFv3(), DASpalartAllmarasFv3FieldInversion::DASpalartAllmarasFv3FieldInversion(), DARadiationModel::New(), DAMotion::New(), DAStateInfo::New(), DAResidual::New(), DAFvSource::New(), DAObjFunc::New(), DAPartDeriv::New(), DATurbulenceModel::New(), DAJacCon::New(), ColoringSolid::run(), ColoringIncompressible::run(), and ColoringCompressible::run().
regDbThermo()
DARegDbFluidThermo regDbThermo (mesh , thermo)
regDbTurbulence()
DARegDbTurbulenceModelCompressible regDbTurbulence (mesh , turbulence())
turbModelName()
const word turbModelName (IOdictionary(IOobject("turbulenceProperties", mesh.time().constant(), mesh, IOobject::MUST_READ, IOobject::NO_WRITE, false)) .subDict("RAS") .lookup("RASModel"))
daTurbulenceModel()
autoPtr<DATurbulenceModel> daTurbulenceModel (DATurbulenceModel::New(turbModelName, mesh, daOption))
daModel()
DAModel daModel (mesh , daOption)
Referenced by DAField::DAField(), DAJacCon::DAJacCon(), DAObjFuncForce::DAObjFuncForce(), DAObjFuncMoment::DAObjFuncMoment(), DAObjFuncPower::DAObjFuncPower(), DAObjFuncWallHeatFlux::DAObjFuncWallHeatFlux(), DAPartDeriv::DAPartDeriv(), DAStateInfoPimpleFoam::DAStateInfoPimpleFoam(), DAStateInfoPisoFoam::DAStateInfoPisoFoam(), DAStateInfoRhoSimpleCFoam::DAStateInfoRhoSimpleCFoam(), DAStateInfoRhoSimpleFoam::DAStateInfoRhoSimpleFoam(), DAStateInfoSimpleFoam::DAStateInfoSimpleFoam(), DAStateInfoSimpleTFoam::DAStateInfoSimpleTFoam(), DAStateInfoTurboFoam::DAStateInfoTurboFoam(), DAResidual::masterFunction(), DAObjFunc::masterFunction(), DAStateInfo::New(), DAResidual::New(), DAFvSource::New(), DAObjFunc::New(), DAPartDeriv::New(), DAJacCon::New(), ColoringSolid::run(), ColoringCompressible::run(), and ColoringIncompressible::run().
daIndex()
DAIndex daIndex (mesh , daOption , daModel)
Referenced by DAObjFuncFieldInversion::DAObjFuncFieldInversion(), DAObjFuncVariableVolSum::DAObjFuncVariableVolSum(), DAResidual::New(), DAFvSource::New(), DAObjFunc::New(), DAPartDeriv::New(), DAJacCon::New(), ColoringSolid::run(), ColoringIncompressible::run(), and ColoringCompressible::run().
Variable Documentation
daUtil
DAUtility daUtil
Definition at line 3 of file createAdjoint.H.