DAFoam: dafoam/src/include/setRootCasePython.H File Reference
setRootCasePython.H File Reference
Functions
argsPtr_ reset (new Foam::argList(argc, argv, true, true, false))
if (!args.checkRootCase())
Variables
Foam::argList & args = argsPtr_()
Function Documentation
reset()
argsPtr_ reset (new Foam::argListargc, argv, true, true, false)
if()
if (!args. checkRootCase())
Definition at line 22 of file setRootCasePython.H.
Variable Documentation
args
Foam::argList& args = argsPtr_()
Definition at line 20 of file setRootCasePython.H.
Referenced by DARhoSimpleCFoam::initSolver(), DATurboFoam::initSolver(), DARhoSimpleFoam::initSolver(), and main().