DAFoam: dafoam/src/adjoint/DASolver/DASimpleFoam/solvePseudoPEqn.H File Reference
solvePseudoPEqn.H File Reference
Functions
pseudoPEqn source ()
pseudoPEqn setReference (0, 0.0)
forAll (pseudoP.boundaryField(), patchI)
forAll (pseudoP.primitiveFieldRef(), cellI)
pseudoPEqn solve (solverDictP_)
Function Documentation
source()
pseudoPEqn source ()
Referenced by DASolver::calcdFdACTAD(), and DASolver::calcdRdActTPsiAD().
setReference()
pseudoPEqn setReference (0 , 0. 0)
forAll() [1/2]
forAll (pseudoP. boundaryField(), patchI)
Definition at line 10 of file solvePseudoPEqn.H.
References pseudoP(), and pseudoPEqn().
Referenced by MRFZoneListDF::active(), DAJacCon::addBoundaryFaceConnections(), DAJacCon::addConMatCellFaces(), DAJacCon::addConMatNeighbourCells(), MRFZoneDF::addCoriolis(), DAJacCon::addStateConnections(), DASolver::assignFieldGradient2Vec(), DASolver::assignSeeds2ResidualGradient(), DASolver::assignStateGradient2Vec(), DASolver::assignVec2AcousticGradient(), DASolver::assignVec2ForceGradient(), DASolver::assignVec2ResidualGradient(), DAUtility::boundVar(), DASimpleFoam::calcAdjointResidual(), DAIndex::calcAdjStateID(), DAIndex::calcAdjStateID4GlobalAdjIdx(), DAkOmegaSSTFIML::calcBetaField(), DASolver::calcCouplingFaceCoords(), DASolver::calcdAcousticsdXvAD(), DASolver::calcdFdACT(), DASolver::calcdFdACTAD(), DASolver::calcdFdAOA(), DASolver::calcdFdBC(), DASolver::calcdFdBCAD(), DASolver::calcdFdFFD(), DASolver::calcdFdFieldAD(), DASolver::calcdFdW(), DASolver::calcdFdWAD(), DASolver::calcdFdXvAD(), DASolver::calcdForcedXvAD(), DASolver::calcdFvSourcedInputsTPsiAD(), DASolver::calcdRdAOATPsiAD(), DASolver::calcdRdBCTPsiAD(), DASolver::calcdRdXvTPsiAD(), DAFvSourceUniformPressureGradient::calcFvSource(), DAFvSourceActuatorPoint::calcFvSource(), DAFvSourceActuatorLine::calcFvSource(), DAFvSourceActuatorDisk::calcFvSource(), DASolver::calcFvSource(), DAFvSourceActuatorDisk::calcFvSourceCellIndices(), DASolver::calcFvSourceInternal(), DASimpleFoam::calcLduResiduals(), DASpalartAllmarasFv3::calcLduResidualTurb(), DAIndex::calcLocalIdxLists(), DAJacCon::calcNeiBFaceGlobalCompact(), nutUSpaldingWallFunctionFvPatchScalarFieldDF::calcNut(), DAObjFuncMass::calcObjFunc(), DAObjFuncVonMisesStressKS::calcObjFunc(), DAObjFuncMeshQualityKS::calcObjFunc(), DAObjFuncMoment::calcObjFunc(), DAObjFuncCenterOfPressure::calcObjFunc(), DAObjFuncMassFlowRate::calcObjFunc(), DAObjFuncPower::calcObjFunc(), DAObjFuncTotalPressure::calcObjFunc(), DAObjFuncPatchMean::calcObjFunc(), DAObjFuncVariableVolSum::calcObjFunc(), DAObjFuncFieldInversion::calcObjFunc(), DAObjFuncForce::calcObjFunc(), DAObjFuncTotalPressureRatio::calcObjFunc(), DAObjFuncTotalTemperatureRatio::calcObjFunc(), DAObjFuncWallHeatFlux::calcObjFunc(), DASolver::calcPrimalResidualStatistics(), DASolver::calcResidualVec(), DAIndex::calcStateLocalIndexOffset(), nutUSpaldingWallFunctionFvPatchScalarFieldDF::calcUTau(), Foam::checkCoupledPoints(), Foam::checkGeometry(), DAField::checkSpecialBCs(), DAJacCon::checkSpecialBCs(), DAJacCon::combineStateBndCon(), DAMotionTranslation::correct(), DAMotionTranslationCoupled::correct(), meshWaveFrozen::correct(), MRFZoneListDF::correctBoundaryVelocity(), MRFZoneDF::correctBoundaryVelocity(), DASpalartAllmaras::correctModelStates(), DAkEpsilon::correctModelStates(), DASpalartAllmarasFv3::correctModelStates(), DAkOmega::correctModelStates(), DASpalartAllmarasFv3FieldInversion::correctModelStates(), DAkOmegaFieldInversionOmega::correctModelStates(), DAkOmegaSST::correctModelStates(), DAkOmegaSSTFieldInversion::correctModelStates(), DAkOmegaSSTFIML::correctModelStates(), DAkOmegaSSTLM::correctModelStates(), DADummyTurbulenceModel::correctStateResidualModelCon(), DASpalartAllmaras::correctStateResidualModelCon(), DAkEpsilon::correctStateResidualModelCon(), DASpalartAllmarasFv3::correctStateResidualModelCon(), DAkOmega::correctStateResidualModelCon(), DASpalartAllmarasFv3FieldInversion::correctStateResidualModelCon(), DAkOmegaFieldInversionOmega::correctStateResidualModelCon(), DAkOmegaSST::correctStateResidualModelCon(), DAkOmegaSSTFieldInversion::correctStateResidualModelCon(), DAkOmegaSSTFIML::correctStateResidualModelCon(), DAkOmegaSSTLM::correctStateResidualModelCon(), DAkEpsilon::DAkEpsilon(), DAkOmega::DAkOmega(), DAkOmegaFieldInversionOmega::DAkOmegaFieldInversionOmega(), DAkOmegaSST::DAkOmegaSST(), DAkOmegaSSTFieldInversion::DAkOmegaSSTFieldInversion(), DAkOmegaSSTFIML::DAkOmegaSSTFIML(), DAkOmegaSSTLM::DAkOmegaSSTLM(), DAObjFunc::DAObjFunc(), DAResidualSolidDisplacementFoam::DAResidualSolidDisplacementFoam(), MRFZoneListDF::DDt(), dummyTurbulenceModel< BasicTurbulenceModel >::dummyTurbulenceModel(), DAkOmegaSSTLM::Flength(), DASolver::getAcousticData(), DASolver::getAcousticDataInternal(), DASolver::getCouplingPatchList(), DAMotion::getForce(), DASolver::getForces(), DASolver::getForcesInternal(), DAIndex::getLocalAdjointStateIndex(), DAJacCon::getLocalCoupledBFaceIndex(), DASolver::getObjFuncValue(), MRFZoneListDF::getOmegaRef(), DASolver::getPatchInfo(), DASolver::getThermal(), DASpalartAllmarasFv3FieldInversion::getTurbProdTerm(), DALaplacianFoam::initSolver(), DAScalarTransportFoam::initSolver(), DAPisoFoam::initSolver(), DAPimpleFoam::initSolver(), DAUtility::isInList(), DASimpleFoam::L2norm(), DAField::list2OFField(), DAUtility::listDeleteVal(), DAUtility::listReplaceVal(), main(), MRFZoneListDF::makeRelative(), MRFZoneDF::makeRelative(), Foam::mergeAndWrite(), DASolver::normalizeGradientVec(), DAField::ofField2List(), DAField::ofField2StateVec(), DAField::ofMesh2PointVec(), DAField::ofResField2ResVec(), transformPositionList::operator()(), DAPartDeriv::perturbAOA(), DAPartDeriv::perturbBC(), DAField::point2OFMesh(), DAField::pointVec2OFMesh(), DASolver::printAllObjFuncs(), DAIndex::printMatChars(), DATurbulenceModel::printYPlus(), DASolver::reduceStateResConLevel(), DASolver::registerAcousticOutput4AD(), DASolver::registerFieldVariableInput4AD(), DASolver::registerForceOutput4AD(), DASolver::registerResidualOutput4AD(), DASolver::registerStateVariableInput4AD(), DAField::resetOFSeeds(), DAField::resVec2OFResField(), DAkOmegaSSTLM::ReThetac(), DAkOmegaSSTLM::ReThetat0(), DASpalartAllmarasFv3::rhsSolvePseudoNuTildaEqn(), ColoringSolid::run(), ColoringIncompressible::run(), ColoringCompressible::run(), DASimpleFoam::runFPAdj(), DAkEpsilon::saveEpsilonNearWall(), DAkOmega::saveOmegaNearWall(), DAkOmegaFieldInversionOmega::saveOmegaNearWall(), DAkOmegaSST::saveOmegaNearWall(), DAkOmegaSSTFieldInversion::saveOmegaNearWall(), DAkOmegaSSTFIML::saveOmegaNearWall(), DAkOmegaSSTLM::saveOmegaNearWall(), DASolver::saveTimeInstanceFieldHybrid(), DASolver::saveTimeInstanceFieldTimeAccurate(), DASolver::setDAObjFuncList(), DAkEpsilon::setEpsilonNearWall(), DAPartDeriv::setNormStatePerturbVec(), DAJacCondFdW::setObjFuncVec(), DAkOmega::setOmegaNearWall(), DAkOmegaFieldInversionOmega::setOmegaNearWall(), DAkOmegaSST::setOmegaNearWall(), DAkOmegaSSTFieldInversion::setOmegaNearWall(), DAkOmegaSSTFIML::setOmegaNearWall(), DAkOmegaSSTLM::setOmegaNearWall(), DAJacCon::setPIVVec(), DAField::setPrimalBoundaryConditions(), DASolver::setThermal(), DAJacCondRdW::setupdRdWCon(), DAJacCondFdW::setupJacCon(), DAJacCon::setupStateBoundaryCon(), DAField::state2OFField(), DAField::stateVec2OFField(), DAFvSource::syncDAOptionToActuatorDVs(), multiFreqScalarFvPatchField::updateCoeffs(), multiFreqVectorFvPatchField::updateCoeffs(), DASimpleFoam::vec2Fields(), and DAIndex::writeAdjointIndexing().
forAll() [2/2]
forAll (pseudoP. primitiveFieldRef(), cellI)
Definition at line 22 of file solvePseudoPEqn.H.
References pseudoP().
solve()
pseudoPEqn solve (solverDictP_)
Referenced by DASpalartAllmaras::calcResiduals(), DAkEpsilon::calcResiduals(), DASpalartAllmarasFv3::calcResiduals(), DAkOmega::calcResiduals(), DASpalartAllmarasFv3FieldInversion::calcResiduals(), DAkOmegaFieldInversionOmega::calcResiduals(), DAkOmegaSST::calcResiduals(), DAkOmegaSSTFieldInversion::calcResiduals(), DAkOmegaSSTFIML::calcResiduals(), DAkOmegaSSTLM::calcResiduals(), and if().