DAFoam: dafoam/src/adjoint/DASolver/DASimpleFoam/solvePseudoUEqn.H File Reference
solvePseudoUEqn.H File Reference
Functions
pseudoUEqn source ()
forAll (pseudoU.boundaryField(), patchI)
forAll (pseudoU.primitiveFieldRef(), cellI)
pseudoUEqn solve (solverDictU_)
Function Documentation
source()
pseudoUEqn source ()
forAll() [1/2]
forAll (pseudoU. boundaryField(), patchI)
Definition at line 6 of file solvePseudoUEqn.H.
References pseudoU(), and pseudoUEqn().
forAll() [2/2]
forAll (pseudoU. primitiveFieldRef(), cellI)
Definition at line 21 of file solvePseudoUEqn.H.
References pseudoU().
solve()
pseudoUEqn solve (solverDictU_)