DAFoam: dafoam/src/adjoint/DASolver/DASimpleTFoam/TEqnSimpleT.H File Reference
TEqnSimpleT.H File Reference
Functions
alphat correctBoundaryConditions ()
volScalarField alphaEff ("alphaEff", turbulencePtr_->nu()/Pr+alphat)
fvScalarMatrix TEqn (fvm::div(phi, T) - fvm::laplacian(alphaEff, T))
TEqn relax ()
this primalResidualControl< scalar > (solverT, printToScreen, printInterval, "T")
Variables
SolverPerformance< scalar > solverT = TEqn.solve()
Function Documentation
correctBoundaryConditions()
alphat correctBoundaryConditions ()
alphaEff()
volScalarField alphaEff ("alphaEff" , turbulencePtr_->nu()/Pr+ alphat)
Referenced by DAObjFuncWallHeatFlux::calcObjFunc(), DAResidualSimpleTFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), and DAResidualRhoSimpleFoam::calcResiduals().
TEqn()
fvScalarMatrix TEqn (fvm::div(phi, T) - fvm::laplacian(alphaEff, T))
Referenced by DAResidualSimpleTFoam::calcResiduals().
relax()
TEqn relax ()
primalResidualControl< scalar >()
this primalResidualControl< scalar > (solverT , printToScreen , printInterval , "T")
Variable Documentation
solverT
SolverPerformance<scalar> solverT = TEqn.solve()
Definition at line 16 of file TEqnSimpleT.H.