DAFoam: dafoam/src/adjoint/DASolver/DAPimpleDyMFoam/UEqnPimpleDyM.H File Reference
UEqnPimpleDyM.H File Reference
Functions
MRF correctBoundaryVelocity (U)
tmp< fvVectorMatrix > tUEqn (fvm::ddt(U)+fvm::div(phi, U)+MRF.DDt(U)+turbulence->divDevReff(U)==fvOptions(U))
UEqn relax ()
fvOptions constrain (UEqn)
if (pimple.momentumPredictor())
Variables
fvVectorMatrix & UEqn = tUEqn.ref()
Function Documentation
correctBoundaryVelocity()
MRF correctBoundaryVelocity (U)
tUEqn()
tmp<fvVectorMatrix> tUEqn (fvm::ddt(U)+fvm::div(phi, U)+MRF.DDt(U)+turbulence->divDevReff(U) = =fvOptions(U))
Referenced by DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), and if().
relax()
UEqn relax ()
constrain()
fvOptions constrain (UEqn)
if()
if (pimple. momentumPredictor())
Definition at line 19 of file UEqnPimpleDyM.H.
References p, U, and UEqn.
Variable Documentation
UEqn
fvVectorMatrix& UEqn = tUEqn.ref()
Definition at line 13 of file UEqnPimpleDyM.H.
Referenced by DAResidualPimpleFoam::calcResiduals(), DAResidualPisoFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), and if().