DAFoam: dafoam/src/adjoint/DASolver/DAPisoFoam/UEqnPiso.H File Reference
UEqnPiso.H File Reference
Functions
if (hasFvSource_)
fvVectorMatrix UEqn (fvm::ddt(U)+fvm::div(phi, U)+turbulencePtr_->divDevReff(U) - fvSource)
UEqn relax ()
if (piso.momentumPredictor())
Function Documentation
if() [1/2]
if (hasFvSource_)
Definition at line 3 of file UEqnPiso.H.
References fvSource, phi, U, and UEqn().
UEqn()
fvVectorMatrix UEqn (fvm::ddt(U)+fvm::div(phi, U)+turbulencePtr_->divDevReff(U) - fvSource)
Referenced by if().
relax()
rho relax ()
if() [2/2]
if (piso. momentumPredictor())
Definition at line 17 of file UEqnPiso.H.
References p, primalResidualControl< vector >(), solverU, and UEqn().