DAFoam: dafoam/src/adjoint/DASolver/DARhoSimpleCFoam/UEqnRhoSimpleC.H File Reference
UEqnRhoSimpleC.H File Reference
Functions
tmp< fvVectorMatrix > tUEqn (fvm::div(phi, U)+turbulencePtr_->divDevRhoReff(U))
UEqn relax ()
this primalResidualControl< vector > (solverU, printToScreen, printInterval, "U")
Variables
fvVectorMatrix & UEqn = tUEqn.ref()
SolverPerformance< vector > solverU = solve(UEqn == -fvc::grad(p))
Function Documentation
tUEqn()
tmp<fvVectorMatrix> tUEqn (fvm::div(phi, U)+turbulencePtr_->divDevRhoReff(U))
Referenced by DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), and if().
relax()
UEqn relax ()
primalResidualControl< vector >()
this primalResidualControl< vector > (solverU , printToScreen , printInterval , "U")
Referenced by if(), and DASolidDisplacementFoam::solvePrimal().
Variable Documentation
UEqn
fvVectorMatrix& UEqn = tUEqn.ref()
Definition at line 6 of file UEqnRhoSimpleC.H.
Referenced by DAResidualPisoFoam::calcResiduals(), DAResidualSimpleTFoam::calcResiduals(), DAResidualSimpleFoam::calcResiduals(), DAResidualRhoSimpleCFoam::calcResiduals(), DAResidualTurboFoam::calcResiduals(), DAResidualRhoSimpleFoam::calcResiduals(), and if().
solverU
SolverPerformance<vector> solverU = solve(UEqn == -fvc::grad(p))
Definition at line 12 of file UEqnRhoSimpleC.H.
Referenced by if(), and DASolidDisplacementFoam::solvePrimal().